import type { Question } from "./types";

export const BAHASA_INDONESIA_1_DRILL_QUESTIONS: Question[] = [
  {
    id: "bahasa-indonesia-1-01",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Dalam laporan kegiatan terdapat kalimat:\n\n“Para peserta-peserta pelatihan diwajibkan untuk mengikuti seluruh rangkaian kegiatan yang telah direncanakan sebelumnya.”\n\nPerbaikan yang paling efektif adalah ...",
    choices: [
      { id: "a", label: "Peserta pelatihan diwajibkan mengikuti seluruh rangkaian kegiatan yang telah direncanakan.", score: 5 },
      { id: "b", label: "Para peserta pelatihan diwajibkan untuk mengikuti seluruh rangkaian kegiatan yang telah direncanakan sebelumnya.", score: 0 },
      { id: "c", label: "Para peserta-peserta pelatihan diwajibkan mengikuti seluruh rangkaian kegiatan yang telah direncanakan.", score: 0 },
      { id: "d", label: "Peserta-peserta pelatihan diwajibkan untuk mengikuti seluruh rangkaian kegiatan yang telah direncanakan sebelumnya.", score: 0 },
      { id: "e", label: "Para peserta pelatihan diwajibkan untuk dapat mengikuti seluruh rangkaian kegiatan yang sebelumnya telah direncanakan.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan A tepat karena kalimat tersebut menghilangkan bentuk jamak ganda pada para peserta-peserta, menghilangkan kata untuk yang tidak diperlukan, serta menghilangkan kata sebelumnya yang maknanya sudah tercakup dalam telah direncanakan. Pilihan B kurang tepat karena masih terdapat kata para dan konstruksi diwajibkan untuk. Pilihan C masih menunjukkan penanda jamak ganda. Pilihan D masih menggunakan peserta-peserta dan kata untuk. Pilihan E kurang hemat karena penggunaan untuk dapat dan sebelumnya.",
  },
  {
    id: "bahasa-indonesia-1-02",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Bacalah wacana berikut!\n\nPemerintah daerah mulai menerapkan sistem antrean digital pada sejumlah unit pelayanan administrasi. Masyarakat dapat mengambil nomor antrean melalui aplikasi sebelum datang ke lokasi pelayanan. Kebijakan tersebut pada awalnya menimbulkan sejumlah kendala karena sebagian masyarakat belum terbiasa menggunakan aplikasi. Untuk mengatasi persoalan tersebut, petugas menyediakan loket bantuan dan memberikan panduan singkat mengenai cara penggunaan sistem. Setelah beberapa minggu, waktu tunggu masyarakat mulai berkurang dan distribusi kedatangan menjadi lebih teratur. Meskipun demikian, pemerintah daerah tetap melakukan evaluasi karena tidak semua kelompok masyarakat memiliki tingkat kemampuan digital yang sama. Evaluasi tersebut digunakan untuk menentukan bentuk pendampingan yang diperlukan agar sistem antrean digital tidak justru menciptakan hambatan bagi kelompok tertentu.\n\nIde pokok paragraf tersebut adalah ...",
    choices: [
      { id: "a", label: "Masyarakat mengalami kesulitan menggunakan aplikasi antrean digital karena belum terbiasa dengan teknologi pelayanan.", score: 0 },
      { id: "b", label: "Sistem antrean digital mampu mengurangi waktu tunggu dan membuat kedatangan masyarakat lebih teratur.", score: 0 },
      { id: "c", label: "Penerapan antrean digital perlu disertai evaluasi dan pendampingan agar meningkatkan kualitas pelayanan tanpa menciptakan hambatan baru.", score: 5 },
      { id: "d", label: "Pemerintah daerah menyediakan loket bantuan untuk membantu masyarakat menggunakan sistem antrean digital.", score: 0 },
      { id: "e", label: "Perbedaan kemampuan digital masyarakat menjadi alasan utama pemerintah daerah mengevaluasi sistem antrean.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan C tepat karena mencakup keseluruhan gagasan paragraf, mulai dari penerapan sistem digital, kendala pengguna, pendampingan, hasil awal, hingga evaluasi agar kebijakan tetap inklusif dan tidak menimbulkan hambatan baru.",
  },
  {
    id: "bahasa-indonesia-1-03",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Perhatikan kalimat dalam laporan resmi berikut.\n\n“Berdasarkan hasil analisa, ditemukan beberapa faktor yang mempengaruhi keterlambatan pelayanan administrasi.”\n\nPerbaikan kata yang tepat sesuai kaidah bahasa Indonesia adalah ...",
    choices: [
      { id: "a", label: "Berdasarkan hasil analisis, ditemukan beberapa faktor yang memengaruhi keterlambatan pelayanan administrasi.", score: 5 },
      { id: "b", label: "Berdasarkan hasil analisa, ditemukan beberapa faktor yang mempengaruhi keterlambatan pelayanan administrasi.", score: 0 },
      { id: "c", label: "Berdasarkan hasil analisis, ditemukan beberapa faktor yang mempengaruhi keterlambatan pelayanan administrasi.", score: 0 },
      { id: "d", label: "Berdasarkan hasil analisa, ditemukan beberapa faktor yang memengaruhi keterlambatan pelayanan administrasi.", score: 0 },
      { id: "e", label: "Berdasarkan hasil analisa, ditemukan beberapa faktor yang mempengaruhkan keterlambatan pelayanan administrasi.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan A tepat karena bentuk baku yang digunakan dalam bahasa Indonesia adalah analisis dan memengaruhi. Kata analisis merupakan bentuk serapan baku, sedangkan memengaruhi merupakan bentuk berimbuhan me- yang tepat dari kata dasar pengaruh (huruf p luluh).",
  },
  {
    id: "bahasa-indonesia-1-04",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Perhatikan kutipan surat dinas berikut:\n\n“Dalam rangka memperingati hari ulang tahun kemerdekaan Republik Indonesia, pemerintah kabupaten akan menyelenggarakan kegiatan pelayanan administrasi terpadu.”\n\nJika dilakukan penyuntingan berdasarkan kaidah huruf kapital, perbaikan yang paling tepat adalah ...",
    choices: [
      { id: "a", label: "Dalam rangka memperingati Hari Ulang Tahun Kemerdekaan Republik Indonesia, Pemerintah Kabupaten akan menyelenggarakan kegiatan pelayanan administrasi terpadu.", score: 5 },
      { id: "b", label: "Dalam rangka memperingati hari ulang tahun Kemerdekaan Republik Indonesia, Pemerintah Kabupaten akan menyelenggarakan kegiatan pelayanan administrasi terpadu.", score: 0 },
      { id: "c", label: "Dalam rangka memperingati Hari Ulang Tahun Kemerdekaan Republik Indonesia, pemerintah kabupaten akan menyelenggarakan kegiatan pelayanan administrasi terpadu.", score: 0 },
      { id: "d", label: "Dalam rangka memperingati hari ulang tahun kemerdekaan Republik Indonesia, Pemerintah Kabupaten akan menyelenggarakan kegiatan Pelayanan Administrasi Terpadu.", score: 0 },
      { id: "e", label: "Dalam rangka memperingati Hari Ulang Tahun kemerdekaan Republik Indonesia, pemerintah Kabupaten akan menyelenggarakan kegiatan pelayanan Administrasi Terpadu.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan A tepat karena Hari Ulang Tahun Kemerdekaan Republik Indonesia digunakan sebagai nama peristiwa/peringatan resmi sehingga unsur namanya menggunakan huruf kapital. Pemerintah Kabupaten juga menggunakan huruf kapital karena merujuk pada nama badan/institusi pemerintah tertentu dalam konteks surat dinas.",
  },
  {
    id: "bahasa-indonesia-1-05",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Perhatikan kalimat berikut:\n\n“Dalam rangka meningkatkan kualitas pelayanan kepada masyarakat, oleh instansi tersebut telah dilakukan penyederhanaan prosedur administrasi.”\n\nPerbaikan yang paling padu adalah ...",
    choices: [
      { id: "a", label: "Dalam rangka meningkatkan kualitas pelayanan kepada masyarakat, instansi tersebut telah menyederhanakan prosedur administrasi.", score: 5 },
      { id: "b", label: "Dalam rangka meningkatkan kualitas pelayanan kepada masyarakat, oleh instansi tersebut prosedur administrasi telah disederhanakan.", score: 0 },
      { id: "c", label: "Dalam rangka meningkatkan kualitas pelayanan kepada masyarakat, telah dilakukan oleh instansi tersebut penyederhanaan prosedur administrasi.", score: 0 },
      { id: "d", label: "Dalam rangka meningkatkan kualitas pelayanan kepada masyarakat, penyederhanaan prosedur administrasi telah dilakukan oleh instansi tersebut.", score: 0 },
      { id: "e", label: "Dalam rangka peningkatan kualitas pelayanan kepada masyarakat, maka oleh instansi tersebut telah dilakukan penyederhanaan prosedur administrasi.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan A tepat karena subjek instansi tersebut langsung diikuti predikat aktif telah menyederhanakan, sehingga hubungan antarkomponen kalimat lebih padu dan mudah dipahami. Pilihan B, C, D strukturnya pasif dan berbelit, sedangkan pilihan E menambahkan kata maka yang tidak perlu.",
  },
  {
    id: "bahasa-indonesia-1-06",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Bacalah wacana berikut!\n\nSebuah unit kerja menemukan bahwa banyak surat yang harus dikembalikan kepada pengirim karena alamat tujuan tidak lengkap. Setelah ditelusuri, kesalahan tersebut tidak hanya berasal dari pegawai yang membuat surat, tetapi juga dari format data penerima yang berbeda-beda antarunit. Beberapa unit menggunakan nama lengkap beserta jabatan, sedangkan unit lainnya hanya mencantumkan nama tanpa informasi tambahan. Untuk mengurangi kesalahan, sekretariat menetapkan format penulisan alamat yang sama dan menyediakan daftar data pejabat yang diperbarui secara berkala. Dalam evaluasi berikutnya, jumlah surat yang dikembalikan berkurang cukup banyak. Perubahan tersebut menunjukkan bahwa penyelesaian masalah administrasi tidak selalu cukup dilakukan dengan mengingatkan individu yang melakukan kesalahan, tetapi dapat memerlukan perbaikan sistem kerja.\n\nKesimpulan yang paling tepat berdasarkan wacana adalah ...",
    choices: [
      { id: "a", label: "Daftar data pejabat merupakan unsur terpenting dalam penyelesaian seluruh kesalahan administrasi surat.", score: 0 },
      { id: "b", label: "Kesalahan administrasi dapat dikurangi dengan memperbaiki sistem dan standar kerja, bukan hanya dengan mengingatkan individu.", score: 5 },
      { id: "c", label: "Penyeragaman format surat dapat menghilangkan seluruh kesalahan administrasi dalam organisasi.", score: 0 },
      { id: "d", label: "Pegawai merupakan penyebab utama kesalahan penulisan alamat dalam surat dinas antarunit.", score: 0 },
      { id: "e", label: "Kesalahan surat dinas terutama terjadi karena pegawai tidak memahami cara menuliskan alamat penerima.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan B tepat karena merupakan kesimpulan yang sesuai dengan keseluruhan isi wacana dan tidak melampaui bukti yang tersedia: penyelesaian masalah administrasi lebih efektif melalui standardisasi dan perbaikan sistem kerja daripada hanya menegur individu.",
  },
  {
    id: "bahasa-indonesia-1-07",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Dalam surat dinas terdapat kalimat:\n\n“Peserta diminta mengisi daftar hadir dan membawa fotocopy kartu identitas sebelum mengikuti kegiatan.”\n\nKata yang perlu diperbaiki agar sesuai dengan bentuk baku adalah ...",
    choices: [
      { id: "a", label: "peserta menjadi pesertah", score: 0 },
      { id: "b", label: "daftar menjadi daftaran", score: 0 },
      { id: "c", label: "fotocopy menjadi fotokopi", score: 5 },
      { id: "d", label: "identitas menjadi identitaz", score: 0 },
      { id: "e", label: "kegiatan menjadi kegiatann", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan C tepat karena bentuk baku serapan yang digunakan dalam bahasa Indonesia adalah fotokopi (bukan fotocopy). Pilihan lainnya merupakan bentuk kata yang salah.",
  },
  {
    id: "bahasa-indonesia-1-08",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Perhatikan kalimat berikut:\n\n“Petugas diharapkan dapat mempertanggung jawabkan seluruh penggunaan anggaran secara transparan.”\n\nBentuk penulisan yang sesuai kaidah adalah ...",
    choices: [
      { id: "a", label: "Petugas diharapkan dapat mempertanggungjawabkan seluruh penggunaan anggaran secara transparan.", score: 5 },
      { id: "b", label: "Petugas diharapkan dapat mempertanggung jawabkan seluruh penggunaan anggaran secara transparan.", score: 0 },
      { id: "c", label: "Petugas diharapkan dapat mempertanggung-jawabkan seluruh penggunaan anggaran secara transparan.", score: 0 },
      { id: "d", label: "Petugas diharapkan dapat mempertanggung jawab-kan seluruh penggunaan anggaran secara transparan.", score: 0 },
      { id: "e", label: "Petugas diharapkan dapat mempertanggungjawab-kan seluruh penggunaan anggaran secara transparan.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan A tepat karena bentuk mempertanggungjawabkan merupakan kata berimbuhan yang dibentuk dari gabungan kata tanggung jawab yang mendapat awalan dan akhiran sekaligus (konfiks me-...-kan), sehingga harus ditulis serangkai tanpa spasi atau tanda hubung.",
  },
  {
    id: "bahasa-indonesia-1-09",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Perhatikan kalimat berikut:\n\n“Berdasarkan hasil evaluasi menunjukkan bahwa terdapat peningkatan kualitas pelayanan setelah prosedur baru diterapkan.”\n\nPerbaikan yang paling tepat adalah ...",
    choices: [
      { id: "a", label: "Berdasarkan hasil evaluasi menunjukkan bahwa kualitas pelayanan meningkat setelah prosedur baru diterapkan.", score: 0 },
      { id: "b", label: "Hasil evaluasi menunjukkan bahwa terdapat peningkatan kualitas pelayanan setelah prosedur baru diterapkan.", score: 5 },
      { id: "c", label: "Berdasarkan hasil evaluasi terdapat menunjukkan bahwa kualitas pelayanan meningkat setelah prosedur baru diterapkan.", score: 0 },
      { id: "d", label: "Berdasarkan hasil evaluasi adalah menunjukkan bahwa terdapat peningkatan kualitas pelayanan setelah prosedur baru diterapkan.", score: 0 },
      { id: "e", label: "Berdasarkan hasil evaluasi yang menunjukkan bahwa terdapat peningkatan kualitas pelayanan setelah prosedur baru diterapkan.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan B tepat karena hasil evaluasi langsung berfungsi sebagai subjek dan menunjukkan sebagai predikat sehingga struktur kalimat menjadi lengkap dan efektif. Jika diawali kata berdasarkan, bagian tersebut menjadi keterangan dan kalimat kehilangan subjek.",
  },
  {
    id: "bahasa-indonesia-1-10",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Perhatikan kalimat berikut:\n\n“Untuk menjamin kwalitas pelayanan, setiap unit kerja harus melakukan evaluasi secara berkala.”\n\nPerbaikan kata yang tepat adalah ...",
    choices: [
      { id: "a", label: "kwalitas menjadi kualitas", score: 5 },
      { id: "b", label: "kwalitas menjadi kwantitas", score: 0 },
      { id: "c", label: "pelayanan menjadi pelayanaan", score: 0 },
      { id: "d", label: "evaluasi menjadi evaluase", score: 0 },
      { id: "e", label: "berkala menjadi berkalla", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan A tepat karena bentuk baku dalam bahasa Indonesia adalah kualitas, bukan kwalitas. Kuantitas memiliki arti berbeda (jumlah, bukan mutu).",
  },
];

export const BAHASA_INDONESIA_2_DRILL_QUESTIONS: Question[] = [
  {
    id: "bahasa-indonesia-2-01",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Perhatikan kalimat berikut:\n\n“Pimpinan memberikan ijin kepada pegawai untuk mengikuti kegiatan tersebut setelah memperoleh rekomendasi dari atasannya.”\n\nBentuk baku yang tepat untuk menggantikan kata ijin adalah ...",
    choices: [
      { id: "a", label: "izin", score: 5 },
      { id: "b", label: "idzin", score: 0 },
      { id: "c", label: "ijinan", score: 0 },
      { id: "d", label: "izinan", score: 0 },
      { id: "e", label: "perijinan", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan A tepat karena bentuk baku dalam bahasa Indonesia adalah izin. Bentuk turunan yang baku terkait perbuatan memberi izin adalah perizinan (bukan perijinan).",
  },
  {
    id: "bahasa-indonesia-2-02",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Bacalah wacana berikut!\n\nTransparansi dalam pelayanan publik tidak cukup diwujudkan dengan menyediakan informasi sebanyak mungkin kepada masyarakat. Informasi yang diberikan harus mudah ditemukan, menggunakan bahasa yang dapat dipahami, dan menjelaskan prosedur secara lengkap. Informasi mengenai biaya, waktu penyelesaian, persyaratan, serta mekanisme pengaduan juga perlu diperbarui ketika terjadi perubahan kebijakan. Jika informasi yang tersedia tidak sesuai dengan praktik pelayanan di lapangan, masyarakat justru dapat mengalami kebingungan. Oleh karena itu, pengelolaan informasi harus menjadi bagian dari proses pelayanan, bukan sekadar kegiatan administratif untuk memenuhi kewajiban penyampaian informasi.\n\nKalimat utama paragraf tersebut adalah ...",
    choices: [
      { id: "a", label: "Informasi mengenai biaya dan waktu penyelesaian harus selalu diperbarui.", score: 0 },
      { id: "b", label: "Transparansi dalam pelayanan publik tidak cukup diwujudkan dengan menyediakan informasi sebanyak mungkin kepada masyarakat.", score: 5 },
      { id: "c", label: "Pengelolaan informasi harus dilakukan untuk memenuhi kewajiban administrasi pelayanan publik.", score: 0 },
      { id: "d", label: "Informasi yang tidak sesuai dengan praktik pelayanan dapat menyebabkan masyarakat mengalami kebingungan.", score: 0 },
      { id: "e", label: "Informasi pelayanan harus menggunakan bahasa yang mudah dipahami oleh masyarakat.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan B tepat karena kalimat pertama merupakan kalimat utama (paragraf deduktif) yang memperkenalkan gagasan utama yang kemudian dijelaskan dan dirinci oleh seluruh kalimat berikutnya.",
  },
  {
    id: "bahasa-indonesia-2-03",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Kalimat berikut terdapat dalam surat pemberitahuan:\n\n“Diharapkan kepada seluruh pegawai agar supaya dapat hadir tepat waktu sesuai dengan jadwal yang telah ditentukan.”\n\nKalimat yang paling efektif adalah ...",
    choices: [
      { id: "a", label: "Diharapkan seluruh pegawai dapat hadir tepat waktu sesuai dengan jadwal yang telah ditentukan.", score: 5 },
      { id: "b", label: "Diharapkan kepada seluruh pegawai agar dapat hadir tepat waktu sesuai dengan jadwal yang telah ditentukan.", score: 0 },
      { id: "c", label: "Diharapkan kepada seluruh pegawai agar supaya hadir tepat waktu sesuai dengan jadwal yang telah ditentukan.", score: 0 },
      { id: "d", label: "Diharapkan seluruh pegawai agar supaya dapat hadir tepat waktu sesuai jadwal yang telah ditentukan.", score: 0 },
      { id: "e", label: "Diharapkan kepada seluruh pegawai untuk dapat hadir tepat waktu sesuai dengan jadwal yang telah ditentukan.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan A tepat karena menghindari penggunaan kata berlebih seperti diharapkan kepada, agar supaya, dan untuk dapat. Struktur kalimat menjadi jelas dan hemat.",
  },
  {
    id: "bahasa-indonesia-2-04",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Perhatikan kalimat berikut:\n\n“Pegawai yang bertugas di lapangan harus menyerahkan laporan ke pada koordinator setelah kegiatan selesai.”\n\nPerbaikan yang paling tepat adalah ...",
    choices: [
      { id: "a", label: "Pegawai yang bertugas dilapangan harus menyerahkan laporan kepada koordinator setelah kegiatan selesai.", score: 0 },
      { id: "b", label: "Pegawai yang bertugas di lapangan harus menyerahkan laporan kepada koordinator setelah kegiatan selesai.", score: 5 },
      { id: "c", label: "Pegawai yang bertugas di lapangan harus menyerahkan laporan ke pada koordinator setelah kegiatan selesai.", score: 0 },
      { id: "d", label: "Pegawai yang bertugas dilapangan harus menyerahkan laporan ke pada koordinator setelah kegiatan selesai.", score: 0 },
      { id: "e", label: "Pegawai yang bertugas di-lapangan harus menyerahkan laporan kepada koordinator setelah kegiatan selesai.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan B tepat karena di lapangan menunjukkan tempat sehingga kata depan di ditulis terpisah. Sementara itu, kepada merupakan satu kata majemuk yang ditulis serangkai.",
  },
  {
    id: "bahasa-indonesia-2-05",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Bacalah wacana berikut!\n\nPenggunaan kecerdasan buatan dalam pekerjaan administrasi mulai membantu pegawai menyelesaikan tugas yang bersifat rutin, seperti mengelompokkan dokumen dan menyusun ringkasan informasi. Meskipun demikian, hasil yang dihasilkan teknologi tersebut tetap memerlukan pemeriksaan manusia. Kesalahan dalam membaca konteks, memahami istilah tertentu, atau menarik hubungan antarinformasi dapat menghasilkan keluaran yang kurang tepat. Oleh karena itu, pemanfaatan teknologi sebaiknya tidak dipahami sebagai pengganti seluruh proses kerja pegawai. Pegawai tetap membutuhkan kemampuan untuk memeriksa, mengoreksi, dan mengambil keputusan berdasarkan informasi yang tersedia. Dengan pendekatan tersebut, teknologi dapat digunakan sebagai alat pendukung untuk meningkatkan efisiensi sekaligus mempertahankan akurasi pekerjaan.\n\nIde pokok wacana tersebut adalah ...",
    choices: [
      { id: "a", label: "Kesalahan teknologi dapat terjadi ketika sistem tidak memahami konteks dan istilah tertentu.", score: 0 },
      { id: "b", label: "Teknologi administrasi dapat meningkatkan efisiensi pekerjaan apabila digunakan oleh pegawai.", score: 0 },
      { id: "c", label: "Pegawai membutuhkan kemampuan untuk mengoreksi hasil yang diberikan oleh teknologi.", score: 0 },
      { id: "d", label: "Pemanfaatan kecerdasan buatan dalam pekerjaan administrasi perlu disertai pemeriksaan dan pengambilan keputusan oleh manusia.", score: 5 },
      { id: "e", label: "Kecerdasan buatan dapat membantu pegawai mengelompokkan dokumen dan membuat ringkasan informasi.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan D tepat karena mencakup inti pesan wacana: pemanfaatan kecerdasan buatan sebagai alat bantu administrasi harus tetap disertai verifikasi, pengawasan, dan pengambilan keputusan akhir oleh manusia.",
  },
  {
    id: "bahasa-indonesia-2-06",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Perhatikan kalimat berikut:\n\n“Hasil rapat akan disampaikan kepada seluruh pegawai untuk memperoleh respon terhadap perubahan prosedur pelayanan.”\n\nJika digunakan dalam dokumen resmi, bentuk kata yang paling tepat adalah ...",
    choices: [
      { id: "a", label: "respon", score: 0 },
      { id: "b", label: "respons", score: 5 },
      { id: "c", label: "response", score: 0 },
      { id: "d", label: "merespon", score: 0 },
      { id: "e", label: "responsi", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan B tepat karena bentuk serapan baku dalam bahasa Indonesia adalah respons (tetap berakhiran -s). Bentuk kata kerja berimbuhannya adalah merespons.",
  },
  {
    id: "bahasa-indonesia-2-07",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Manakah kalimat yang memiliki struktur subjek dan predikat yang paling sepadan?",
    choices: [
      { id: "a", label: "Pelaksanaan program tersebut memerlukan koordinasi yang baik antarsatuan kerja.", score: 5 },
      { id: "b", label: "Dalam pelaksanaan program tersebut memerlukan koordinasi yang baik antarsatuan kerja.", score: 0 },
      { id: "c", label: "Pelaksanaan program tersebut adalah memerlukan koordinasi yang baik antarsatuan kerja.", score: 0 },
      { id: "d", label: "Untuk pelaksanaan program tersebut memerlukan adanya koordinasi yang baik antarsatuan kerja.", score: 0 },
      { id: "e", label: "Adanya pelaksanaan program tersebut memerlukan untuk koordinasi yang baik antarsatuan kerja.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan A tepat karena pelaksanaan program tersebut berfungsi sebagai subjek dan memerlukan sebagai predikat. Hubungan subjek-predikat jelas dan sepadan. Pilihan B dan D tidak memiliki subjek jelas akibat penggunaan preposisi dalam/untuk di awal kalimat.",
  },
  {
    id: "bahasa-indonesia-2-08",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Perhatikan penggunaan gabungan kata berikut:\n\n“Setiap pegawai harus memiliki tanggung jawab dalam melaksanakan tugas dan menjaga kerja sama antarunit.”\n\nJika kalimat tersebut digunakan dalam dokumen resmi, penulisan yang tepat adalah ...",
    choices: [
      { id: "a", label: "Setiap pegawai harus memiliki tanggungjawab dalam melaksanakan tugas dan menjaga kerjasama antarunit.", score: 0 },
      { id: "b", label: "Setiap pegawai harus memiliki tanggung jawab dalam melaksanakan tugas dan menjaga kerja sama antarunit.", score: 5 },
      { id: "c", label: "Setiap pegawai harus memiliki tanggung-jawab dalam melaksanakan tugas dan menjaga kerja-sama antarunit.", score: 0 },
      { id: "d", label: "Setiap pegawai harus memiliki tanggung jawab dalam melaksanakan tugas dan menjaga kerjasama antar unit.", score: 0 },
      { id: "e", label: "Setiap pegawai harus memiliki tanggungjawab dalam melaksanakan tugas dan menjaga kerja sama antar unit.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan B tepat karena gabungan kata tanpa afiks ganda ditulis terpisah: tanggung jawab dan kerja sama. Sementara itu, antarunit ditulis serangkai karena antar- merupakan bentuk terikat.",
  },
  {
    id: "bahasa-indonesia-2-09",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Bacalah wacana berikut!\n\nSebuah pemerintah daerah membuka kanal pengaduan melalui berbagai media, mulai dari aplikasi hingga layanan pesan singkat. Jumlah pengaduan yang masuk kemudian meningkat secara signifikan. Pada awalnya, peningkatan tersebut dianggap sebagai tanda bahwa kualitas pelayanan mengalami penurunan. Setelah dilakukan analisis, ternyata sebagian besar peningkatan berasal dari masyarakat yang sebelumnya tidak memiliki saluran untuk menyampaikan keluhan. Selain itu, waktu penyelesaian pengaduan justru menjadi lebih singkat karena laporan dapat diteruskan secara langsung kepada unit yang berwenang. Data tersebut menunjukkan bahwa jumlah pengaduan tidak dapat digunakan secara tunggal untuk menilai kualitas pelayanan. Interpretasi harus mempertimbangkan akses masyarakat terhadap kanal pengaduan dan bagaimana laporan tersebut ditindaklanjuti.\n\nKesimpulan yang paling tepat adalah ...",
    choices: [
      { id: "a", label: "Jumlah pengaduan tidak dapat digunakan sama sekali sebagai salah satu informasi dalam menilai kualitas pelayanan.", score: 0 },
      { id: "b", label: "Kanal pengaduan digital merupakan penyebab utama peningkatan jumlah pengaduan masyarakat.", score: 0 },
      { id: "c", label: "Meningkatnya jumlah pengaduan tidak selalu menunjukkan memburuknya pelayanan karena harus dilihat bersama akses dan tindak lanjut pengaduan.", score: 5 },
      { id: "d", label: "Pelayanan pemerintah dapat dinilai baik apabila seluruh pengaduan dapat diselesaikan dalam waktu singkat.", score: 0 },
      { id: "e", label: "Meningkatnya jumlah pengaduan menunjukkan bahwa masyarakat semakin tidak puas terhadap pelayanan pemerintah.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan C tepat karena merangkum wacana secara berimbang: lonjakan jumlah aduan dapat mencerminkan kemudahan akses masyarakat, bukan semata-mata penurunan kinerja pelayanan.",
  },
  {
    id: "bahasa-indonesia-2-10",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Perhatikan kalimat berikut:\n\n“Dokumen hasil pemeriksaan akan di kirim dari kantor pusat ke kantor cabang setelah mendapat persetujuan pimpinan.”\n\nPenyuntingan yang paling tepat adalah ...",
    choices: [
      { id: "a", label: "Dokumen hasil pemeriksaan akan dikirim dari kantor pusat ke kantor cabang setelah mendapat persetujuan pimpinan.", score: 5 },
      { id: "b", label: "Dokumen hasil pemeriksaan akan di kirim dari kantor pusat kekantor cabang setelah mendapat persetujuan pimpinan.", score: 0 },
      { id: "c", label: "Dokumen hasil pemeriksaan akan dikirim dari kantor pusat kekantor cabang setelah mendapat persetujuan pimpinan.", score: 0 },
      { id: "d", label: "Dokumen hasil pemeriksaan akan di-kirim dari kantor pusat ke-kantor cabang setelah mendapat persetujuan pimpinan.", score: 0 },
      { id: "e", label: "Dokumen hasil pemeriksaan akan dikirim dari kantor pusat ke-kantor cabang setelah mendapat persetujuan pimpinan.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan A tepat karena awalan di- pada kata kerja pasif dikirim ditulis serangkai, sedangkan kata depan ke yang menunjukkan tujuan tempat ditulis terpisah (ke kantor cabang).",
  },
];

export const BAHASA_INDONESIA_3_DRILL_QUESTIONS: Question[] = [
  {
    id: "bahasa-indonesia-3-01",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Bacalah paragraf berikut!\n\nDalam pengelolaan arsip, kecepatan menemukan dokumen bukan satu-satunya ukuran keberhasilan. Arsip juga harus disimpan dengan sistem klasifikasi yang konsisten agar mudah ditelusuri ketika dibutuhkan. Selain itu, dokumen yang mengandung informasi penting perlu memiliki pengaturan akses yang jelas. Pemindahan arsip ke media digital pun harus memperhatikan keamanan, keutuhan, dan kemampuan untuk memulihkan data jika terjadi kerusakan. Dengan demikian, pengelolaan arsip membutuhkan keseimbangan antara kemudahan akses, keamanan informasi, dan keberlanjutan penyimpanan.\n\nKalimat utama paragraf tersebut adalah ...",
    choices: [
      { id: "a", label: "Digitalisasi arsip harus memperhatikan keamanan dan kemampuan pemulihan data.", score: 0 },
      { id: "b", label: "Dalam pengelolaan arsip, kecepatan menemukan dokumen bukan satu-satunya ukuran keberhasilan.", score: 5 },
      { id: "c", label: "Pengelolaan arsip membutuhkan keseimbangan antara kemudahan akses, keamanan informasi, dan keberlanjutan penyimpanan.", score: 0 },
      { id: "d", label: "Arsip harus disimpan dengan sistem klasifikasi yang konsisten agar mudah ditelusuri.", score: 0 },
      { id: "e", label: "Dokumen penting membutuhkan pengaturan akses yang jelas dalam sistem kearsipan.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan B tepat karena kalimat pertama merupakan ide utama yang membuka pembahasan, yang kemudian dielaborasi oleh aspek-aspek lain pengelolaan arsip (klasifikasi, akses, dan digitalisasi). Kalimat C adalah simpulan, bukan kalimat utama pembuka.",
  },
  {
    id: "bahasa-indonesia-3-02",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Perhatikan kalimat berikut dalam laporan:\n\n“Pimpinan meminta pegawai baru melaporkan dokumen tersebut kepada petugas yang membawa map merah.”\n\nKalimat tersebut dapat menimbulkan tafsir ganda. Perbaikan yang paling cermat jika yang membawa map merah adalah petugas adalah ...",
    choices: [
      { id: "a", label: "Pimpinan meminta pegawai baru melaporkan dokumen tersebut kepada petugas pembawa map merah.", score: 0 },
      { id: "b", label: "Pimpinan meminta pegawai baru melaporkan dokumen tersebut kepada petugas yang membawa map berwarna merah.", score: 5 },
      { id: "c", label: "Pimpinan meminta pegawai baru melaporkan dokumen tersebut kepada petugas, yang membawa map merah.", score: 0 },
      { id: "d", label: "Pimpinan meminta pegawai baru melaporkan dokumen tersebut kepada petugas dengan map merah.", score: 0 },
      { id: "e", label: "Pimpinan meminta pegawai baru melaporkan dokumen tersebut kepada petugas yang mapnya berwarna merah.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan B paling tepat karena klausanya secara cermat memperjelas bahwa ciri membawa map berwarna merah melekat pada petugas sehingga menghilangkan kerancuan penafsiran.",
  },
  {
    id: "bahasa-indonesia-3-03",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Perhatikan kalimat berikut:\n\n“Instansi tersebut melakukan koordinasi secara intensif agar pelaksanaan program dapat berjalan efektif dan efisien.”\n\nKata yang digunakan dalam kalimat tersebut sudah baku, kecuali jika ditambahkan bentuk berikut. Manakah pasangan kata yang tidak baku?",
    choices: [
      { id: "a", label: "efektif – efisien", score: 0 },
      { id: "b", label: "koordinasi – intensif", score: 0 },
      { id: "c", label: "analisa – resiko", score: 5 },
      { id: "d", label: "program – pelaksanaan", score: 0 },
      { id: "e", label: "administrasi – evaluasi", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan C tepat karena pasangan analisa – resiko keduanya merupakan bentuk kata tidak baku. Bentuk baku yang benar menurut KBBI adalah analisis dan risiko.",
  },
  {
    id: "bahasa-indonesia-3-04",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Dalam laporan resmi ditemukan kalimat:\n\n“Tim melakukan evaluasi terhadap sistem online yang digunakan dalam pelayanan publik.”\n\nJika istilah asing tersebut belum diserap ke dalam bahasa Indonesia, penulisan yang paling tepat adalah ...",
    choices: [
      { id: "a", label: "Tim melakukan evaluasi terhadap sistem online yang digunakan dalam pelayanan publik.", score: 0 },
      { id: "b", label: "Tim melakukan evaluasi terhadap sistem *online* yang digunakan dalam pelayanan publik.", score: 5 },
      { id: "c", label: "Tim melakukan evaluasi terhadap sistem “online” yang digunakan dalam pelayanan publik.", score: 0 },
      { id: "d", label: "Tim melakukan evaluasi terhadap sistem **online** yang digunakan dalam pelayanan publik.", score: 0 },
      { id: "e", label: "Tim melakukan evaluasi terhadap sistem Online yang digunakan dalam pelayanan publik.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan B tepat karena kata atau istilah asing yang digunakan dalam kalimat bahasa Indonesia dan belum memiliki bentuk serapan baku harus dicetak miring (*online*).",
  },
  {
    id: "bahasa-indonesia-3-05",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Bacalah wacana berikut!\n\nBanyak organisasi berusaha meningkatkan produktivitas dengan menambah jumlah rapat koordinasi. Namun, peningkatan frekuensi rapat tidak selalu menghasilkan koordinasi yang lebih baik. Rapat yang tidak memiliki agenda jelas sering menghasilkan pembahasan yang melebar dan keputusan yang sulit ditindaklanjuti. Sebaliknya, rapat yang didukung data, memiliki tujuan spesifik, dan menghasilkan pembagian tugas yang jelas dapat membantu pekerjaan berjalan lebih terarah. Oleh karena itu, kualitas rapat lebih penting daripada sekadar banyaknya rapat yang diselenggarakan. Organisasi perlu memastikan setiap rapat memiliki tujuan, peserta yang relevan, bahan pembahasan, serta tindak lanjut yang dapat dipantau.\n\nIde pokok paragraf tersebut adalah ...",
    choices: [
      { id: "a", label: "Rapat koordinasi harus menghasilkan pembagian tugas yang jelas agar pekerjaan dapat berjalan.", score: 0 },
      { id: "b", label: "Data dan agenda merupakan unsur yang harus selalu tersedia sebelum rapat koordinasi diselenggarakan.", score: 0 },
      { id: "c", label: "Efektivitas rapat koordinasi lebih ditentukan oleh kualitas perencanaan dan tindak lanjut daripada frekuensinya.", score: 5 },
      { id: "d", label: "Organisasi perlu mengurangi jumlah rapat agar produktivitas pegawai meningkat.", score: 0 },
      { id: "e", label: "Rapat yang tidak memiliki agenda dapat menyebabkan pembahasan menjadi terlalu luas.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan C tepat karena merangkum gagasan inti paragraf: bahwa keberhasilan dan efektivitas rapat koordinasi bergantung pada mutu persiapan, agenda, dan tindak lanjut, bukan banyaknya pertemuan.",
  },
  {
    id: "bahasa-indonesia-3-06",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Perhatikan kalimat berikut:\n\n“Program tersebut bertujuan meningkatkan kompetensi pegawai, memperbaiki kualitas pelayanan, dan agar terciptanya budaya kerja yang profesional.”\n\nPerbaikan yang paling tepat adalah ...",
    choices: [
      { id: "a", label: "Program tersebut bertujuan meningkatkan kompetensi pegawai, memperbaiki kualitas pelayanan, dan menciptakan budaya kerja yang profesional.", score: 5 },
      { id: "b", label: "Program tersebut bertujuan meningkatkan kompetensi pegawai, memperbaiki kualitas pelayanan, dan agar terciptanya budaya kerja yang profesional.", score: 0 },
      { id: "c", label: "Program tersebut bertujuan untuk meningkatkan kompetensi pegawai, memperbaiki kualitas pelayanan, dan agar menciptakan budaya kerja yang profesional.", score: 0 },
      { id: "d", label: "Program tersebut bertujuan meningkatkan kompetensi pegawai, perbaikan kualitas pelayanan, dan menciptakan budaya kerja yang profesional.", score: 0 },
      { id: "e", label: "Program tersebut bertujuan peningkatan kompetensi pegawai, memperbaiki kualitas pelayanan, dan penciptaan budaya kerja yang profesional.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan A tepat karena rincian tujuan disusun secara paralel menggunakan bentuk verba aktif me- yang setara: meningkatkan, memperbaiki, dan menciptakan. Pilihan lainnya mencampurkan bentuk klausa atau nomina.",
  },
  {
    id: "bahasa-indonesia-3-07",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Dalam sebuah laporan terdapat kalimat:\n\n“Menurut Kepala Bagian Kepegawaian, seluruh pegawai akan mengikuti pelatihan pada bulan depan.”\n\nApabila kepala bagian kepegawaian bukan nama jabatan yang diikuti nama orang dan digunakan sebagai penyebutan umum, penulisan yang paling tepat adalah ...",
    choices: [
      { id: "a", label: "Menurut Kepala Bagian Kepegawaian, seluruh pegawai akan mengikuti pelatihan pada bulan depan.", score: 0 },
      { id: "b", label: "Menurut kepala bagian kepegawaian, seluruh pegawai akan mengikuti pelatihan pada bulan depan.", score: 5 },
      { id: "c", label: "Menurut Kepala bagian kepegawaian, seluruh Pegawai akan mengikuti pelatihan pada bulan depan.", score: 0 },
      { id: "d", label: "Menurut kepala Bagian Kepegawaian, seluruh pegawai akan mengikuti pelatihan pada Bulan depan.", score: 0 },
      { id: "e", label: "Menurut Kepala Bagian kepegawaian, seluruh Pegawai akan mengikuti pelatihan pada bulan Depan.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan B tepat karena nama jabatan yang digunakan sebagai penyebutan umum tanpa diikuti nama orang atau instansi spesifik ditulis dengan huruf nonkapital (kepala bagian kepegawaian).",
  },
  {
    id: "bahasa-indonesia-3-08",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Dalam sebuah laporan ditemukan kalimat:\n\n“Pemerintah perlu mengkaji efektifitas kebijakan tersebut sebelum melakukan implementasi lebih lanjut.”\n\nPerbaikan kata yang paling tepat adalah ...",
    choices: [
      { id: "a", label: "efektivitas dan implementasi", score: 5 },
      { id: "b", label: "efektifitas dan implementasi", score: 0 },
      { id: "c", label: "efektivitas dan implemantasi", score: 0 },
      { id: "d", label: "efektifitas dan implemantasi", score: 0 },
      { id: "e", label: "efektifitas dan implementasion", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan A tepat karena bentuk baku serapannya adalah efektivitas (dengan -ivitas, bukan -ifitas) dan implementasi.",
  },
  {
    id: "bahasa-indonesia-3-09",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Bacalah paragraf berikut!\n\nKesalahan dalam membaca data dapat memengaruhi keputusan yang diambil oleh sebuah organisasi. Angka yang meningkat, misalnya, tidak selalu menunjukkan bahwa suatu kondisi membaik karena peningkatan tersebut dapat terjadi akibat perubahan cara pengukuran. Demikian pula, penurunan angka tidak selalu berarti masalah telah terselesaikan apabila indikator yang digunakan tidak menggambarkan kondisi secara keseluruhan. Oleh sebab itu, data perlu dibaca dengan memperhatikan definisi indikator, periode pengukuran, sumber data, dan konteks yang melatarbelakanginya. Kemampuan memahami konteks tersebut menjadi penting agar keputusan tidak hanya didasarkan pada angka yang terlihat secara permukaan.\n\nKalimat utama paragraf tersebut adalah ...",
    choices: [
      { id: "a", label: "Data perlu dibaca dengan memperhatikan definisi indikator, periode, sumber, dan konteks.", score: 0 },
      { id: "b", label: "Kemampuan memahami konteks diperlukan agar keputusan tidak hanya didasarkan pada angka.", score: 0 },
      { id: "c", label: "Penurunan angka tidak selalu berarti masalah telah terselesaikan.", score: 0 },
      { id: "d", label: "Kesalahan dalam membaca data dapat memengaruhi keputusan yang diambil oleh sebuah organisasi.", score: 5 },
      { id: "e", label: "Angka yang meningkat tidak selalu menunjukkan bahwa suatu kondisi membaik.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan D tepat karena kalimat pertama merupakan pernyataan umum (kalimat topik deduktif) yang menjadi fokus pembahasan mengenai risiko kesalahan interpretasi data terhadap keputusan organisasi.",
  },
  {
    id: "bahasa-indonesia-3-10",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Perhatikan kalimat berikut:\n\n“Petugas memeriksa dokumen peserta yang belum lengkap di ruang pelayanan.”\n\nKalimat tersebut dapat menimbulkan pertanyaan mengenai unsur yang belum lengkap. Perbaikan paling cermat jika yang belum lengkap adalah dokumen peserta adalah ...",
    choices: [
      { id: "a", label: "Di ruang pelayanan, petugas memeriksa dokumen peserta yang belum lengkap.", score: 0 },
      { id: "b", label: "Petugas di ruang pelayanan memeriksa dokumen peserta yang belum lengkap.", score: 0 },
      { id: "c", label: "Petugas memeriksa dokumen peserta yang kelengkapannya belum terpenuhi di ruang pelayanan.", score: 5 },
      { id: "d", label: "Petugas memeriksa dokumen peserta di ruang pelayanan yang belum lengkap.", score: 0 },
      { id: "e", label: "Petugas memeriksa dokumen peserta, yang belum lengkap, di ruang pelayanan.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan C tepat karena perbaikan yang kelengkapannya belum terpenuhi secara spesifik menerangkan dokumen sehingga tidak menimbulkan tafsir ganda apakah peserta atau dokumennya yang belum lengkap.",
  },
];

export const BAHASA_INDONESIA_4_DRILL_QUESTIONS: Question[] = [
  {
    id: "bahasa-indonesia-4-01",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Perhatikan kalimat berikut:\n\n“Setelah selesai mengikuti pelatihan, peserta kembali ke dalam ruang untuk mengikuti sesi evaluasi.”\n\nSeorang peserta mengusulkan agar ke dalam ditulis kedalam. Berdasarkan kaidah bahasa Indonesia, tanggapan yang tepat adalah ...",
    choices: [
      { id: "a", label: "Usulan tersebut benar karena ke dalam menunjukkan tempat sehingga harus ditulis serangkai.", score: 0 },
      { id: "b", label: "Usulan tersebut benar karena semua kata yang menunjukkan arah harus digabungkan dengan kata setelahnya.", score: 0 },
      { id: "c", label: "Usulan tersebut tidak tepat karena ke berfungsi sebagai kata depan dan harus ditulis terpisah dari dalam.", score: 5 },
      { id: "d", label: "Usulan tersebut tidak tepat karena kata dalam harus diganti dengan kata ruang agar penulisannya benar.", score: 0 },
      { id: "e", label: "Usulan tersebut tidak tepat karena ke dalam seharusnya menggunakan tanda hubung sebagai penanda arah.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan C tepat karena ke dalam terdiri atas kata depan ke dan kata arah dalam sehingga penulisannya harus dipisah (ke dalam).",
  },
  {
    id: "bahasa-indonesia-4-02",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Perhatikan pasangan kata berikut:\n1. risiko — resiko\n2. praktik — praktek\n3. objek — obyek\n4. sistem — sistim\n5. izin — ijin\n\nPasangan yang menunjukkan kata baku diikuti kata tidak baku secara tepat adalah ...",
    choices: [
      { id: "a", label: "risiko — resiko", score: 5 },
      { id: "b", label: "resiko — risiko", score: 0 },
      { id: "c", label: "praktik — praktek", score: 0 },
      { id: "d", label: "objek — obyek", score: 0 },
      { id: "e", label: "izin — ijin", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan A tepat karena urutannya sesuai dengan permintaan soal: kata baku (risiko) diikuti kata tidak baku (resiko).",
  },
  {
    id: "bahasa-indonesia-4-03",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Bacalah wacana berikut!\n\nSebuah sekolah mengembangkan program pengelolaan sampah dengan meminta setiap kelas memilah sampah organik dan anorganik. Pada tahap awal, program berjalan baik karena guru secara rutin mengingatkan siswa. Setelah beberapa bulan, kepatuhan mulai menurun ketika pengawasan dikurangi. Sekolah kemudian mengubah pendekatan dengan melibatkan siswa dalam menentukan aturan, membuat jadwal pengelolaan, dan mencatat hasil pemilahan setiap minggu. Setelah siswa memiliki peran yang lebih besar, kebiasaan memilah sampah mulai bertahan meskipun pengawasan guru tidak dilakukan secara terus-menerus. Pengalaman tersebut menunjukkan bahwa keberlanjutan suatu program tidak hanya bergantung pada pengawasan, tetapi juga pada keterlibatan pihak yang menjalankannya.\n\nKesimpulan yang paling tepat adalah ...",
    choices: [
      { id: "a", label: "Program pengelolaan sampah tidak dapat berjalan tanpa pengawasan guru secara rutin.", score: 0 },
      { id: "b", label: "Pelibatan siswa dalam program lebih efektif karena menghilangkan kebutuhan terhadap aturan sekolah.", score: 0 },
      { id: "c", label: "Pengawasan guru merupakan faktor utama yang menentukan keberhasilan program pengelolaan sampah di sekolah.", score: 0 },
      { id: "d", label: "Siswa akan menjalankan program pengelolaan sampah apabila sekolah memberikan aturan yang lebih ketat.", score: 0 },
      { id: "e", label: "Program dapat lebih berkelanjutan ketika pihak yang menjalankannya dilibatkan dalam proses pengelolaan, bukan hanya diawasi.", score: 5 },
    ],
    explanation: "Pembahasan: Pilihan E tepat karena berhasil menyimpulkan gagasan teks secara utuh: rasa kepemilikan dan keterlibatan aktif pihak pelaksana menjamin keberlanjutan program daripada sekadar pengawasan searah.",
  },
  {
    id: "bahasa-indonesia-4-04",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Perhatikan kalimat berikut:\n\n“Untuk dapat meningkatkan kualitas pelayanan, maka setiap pegawai harus mampu untuk memahami prosedur pelayanan yang berlaku.”\n\nKalimat yang paling efektif adalah ...",
    choices: [
      { id: "a", label: "Untuk meningkatkan kualitas pelayanan, setiap pegawai harus memahami prosedur yang berlaku.", score: 5 },
      { id: "b", label: "Untuk dapat meningkatkan kualitas pelayanan, maka setiap pegawai harus mampu memahami prosedur pelayanan yang berlaku.", score: 0 },
      { id: "c", label: "Dalam rangka untuk meningkatkan kualitas pelayanan, setiap pegawai harus mampu untuk memahami prosedur yang berlaku.", score: 0 },
      { id: "d", label: "Untuk meningkatkan kualitas pelayanan, maka setiap pegawai harus mampu untuk memahami prosedur pelayanan yang berlaku.", score: 0 },
      { id: "e", label: "Dalam rangka meningkatkan kualitas pelayanan, maka setiap pegawai harus mampu untuk memahami prosedur pelayanan yang berlaku.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan A tepat karena meniadakan kata-kata berlebih seperti dapat, maka, dan mampu untuk, serta menghindari pengulangan kata pelayanan.",
  },
  {
    id: "bahasa-indonesia-4-05",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Perhatikan beberapa bentuk penulisan berikut:\n1. kerja sama\n2. sumber daya\n3. tanda tangan\n4. mata pelajaran\n5. kerja-sama\n6. sumberdaya\n\nBentuk yang tepat terdapat pada ...",
    choices: [
      { id: "a", label: "1, 2, 3, dan 4", score: 5 },
      { id: "b", label: "1, 3, 5, dan 6", score: 0 },
      { id: "c", label: "2, 4, 5, dan 6", score: 0 },
      { id: "d", label: "1, 2, 5, dan 6", score: 0 },
      { id: "e", label: "2, 3, 4, dan 6", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan A tepat karena gabungan kata kerja sama, sumber daya, tanda tangan, dan mata pelajaran merupakan frasa kata majemuk yang belum bersenyawa utuh sehingga wajib ditulis terpisah.",
  },
  {
    id: "bahasa-indonesia-4-06",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Perhatikan kalimat berikut:\n\n“Panitia menghimbau kepada seluruh peserta agar hadir tiga puluh menit sebelum kegiatan dimulai.”\n\nPerbaikan yang paling tepat adalah ...",
    choices: [
      { id: "a", label: "Panitia mengimbau seluruh peserta agar hadir tiga puluh menit sebelum kegiatan dimulai.", score: 5 },
      { id: "b", label: "Panitia menghimbau seluruh peserta agar hadir tiga puluh menit sebelum kegiatan dimulai.", score: 0 },
      { id: "c", label: "Panitia mengimbau kepada seluruh peserta untuk agar hadir tiga puluh menit sebelum kegiatan dimulai.", score: 0 },
      { id: "d", label: "Panitia menghimbau kepada seluruh peserta untuk dapat agar hadir sebelum kegiatan dimulai.", score: 0 },
      { id: "e", label: "Panitia mengimbau kepada seluruh peserta agar supaya hadir tiga puluh menit sebelum kegiatan dimulai.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan A tepat karena bentuk dasar baku adalah imbau (bukan himbau) sehingga bentukan yang benar adalah mengimbau. Selain itu, verba mengimbau langsung diikuti objek peserta tanpa preposisi kepada.",
  },
  {
    id: "bahasa-indonesia-4-07",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Bacalah wacana berikut!\n\nDalam pelayanan administrasi, masyarakat sering menilai kualitas layanan berdasarkan lamanya proses yang mereka alami. Namun, kecepatan tidak selalu menjadi satu-satunya ukuran. Pelayanan yang cepat tetapi menghasilkan dokumen yang salah dapat menimbulkan masalah baru bagi masyarakat. Sebaliknya, pemeriksaan yang terlalu lama juga dapat menghambat kebutuhan masyarakat apabila sebenarnya dapat dilakukan dengan prosedur yang lebih sederhana. Karena itu, unit pelayanan perlu mencari keseimbangan antara kecepatan, ketepatan, dan kepastian proses. Penggunaan daftar pemeriksaan, penyederhanaan tahapan yang tidak diperlukan, serta pemanfaatan teknologi dapat membantu mencapai keseimbangan tersebut. Dengan pendekatan ini, peningkatan kualitas pelayanan tidak hanya diukur dari seberapa cepat proses selesai, tetapi juga dari seberapa tepat hasil yang diterima masyarakat.\n\nPernyataan yang paling tepat sebagai kesimpulan wacana adalah ...",
    choices: [
      { id: "a", label: "Penggunaan teknologi merupakan cara paling penting untuk mempercepat seluruh proses pelayanan administrasi.", score: 0 },
      { id: "b", label: "Kualitas pelayanan perlu dinilai secara menyeluruh dengan mempertimbangkan kecepatan, ketepatan, dan kepastian hasil, bukan hanya lamanya proses.", score: 5 },
      { id: "c", label: "Pemeriksaan dokumen sebaiknya dikurangi agar masyarakat memperoleh pelayanan dalam waktu yang sesingkat mungkin.", score: 0 },
      { id: "d", label: "Lamanya proses pelayanan merupakan indikator utama yang dapat digunakan untuk menentukan kualitas suatu unit pelayanan.", score: 0 },
      { id: "e", label: "Pelayanan yang cepat merupakan faktor utama yang menentukan kepuasan masyarakat dalam pelayanan administrasi.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan B tepat karena menyimpulkan keseluruhan argumentasi wacana: bahwa mutu layanan harus dinilai secara holistik mencakup kecepatan, akurasi, dan kepastian hukum hasil pelayanan.",
  },
  {
    id: "bahasa-indonesia-4-08",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Bacalah kalimat berikut:\n\n“Dalam rapat tersebut membahas mengenai evaluasi program pelayanan yang telah dilaksanakan oleh masing-masing unit kerja, serta menyusun rencana tindak lanjut untuk ke depannya.”\n\nJika kalimat tersebut akan dimasukkan ke dalam laporan hasil rapat, perbaikan paling tepat adalah ...",
    choices: [
      { id: "a", label: "Rapat tersebut membahas evaluasi program pelayanan yang telah dilaksanakan oleh masing-masing unit kerja serta menyusun rencana tindak lanjut.", score: 5 },
      { id: "b", label: "Dalam rapat tersebut membahas mengenai evaluasi program pelayanan yang telah dilaksanakan oleh masing-masing unit kerja serta menyusun rencana tindak lanjut untuk ke depannya.", score: 0 },
      { id: "c", label: "Dalam rapat tersebut dibahas mengenai evaluasi program pelayanan yang telah dilaksanakan oleh masing-masing unit kerja, serta menyusun rencana tindak lanjut untuk ke depannya.", score: 0 },
      { id: "d", label: "Rapat tersebut membahas mengenai evaluasi program pelayanan yang telah dilaksanakan oleh masing-masing unit kerja dan penyusunan rencana tindak lanjut untuk ke depannya.", score: 0 },
      { id: "e", label: "Dalam rapat tersebut telah membahas evaluasi program pelayanan yang telah dilaksanakan oleh masing-masing unit kerja dan menyusun rencana tindak lanjut untuk ke depannya.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan A tepat karena subjek rapat tersebut jelas, menghilangkan kata mengenai setelah verba transitif membahas, dan menghilangkan frasa mubazir untuk ke depannya.",
  },
  {
    id: "bahasa-indonesia-4-09",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Bacalah kalimat berikut:\n\n“Dalam rangka meningkatkan profesionalisme aparatur, pimpinan menghimbau seluruh pegawai untuk mengutamakan kwalitas pelayanan dan memberikan respon yang cepat terhadap pengaduan masyarakat.”\n\nJika seluruh kata tidak baku diperbaiki, bentuk kalimat yang paling tepat adalah ...",
    choices: [
      { id: "a", label: "Dalam rangka meningkatkan profesionalisme aparatur, pimpinan mengimbau seluruh pegawai untuk mengutamakan kualitas pelayanan dan memberikan respons yang cepat terhadap pengaduan masyarakat.", score: 5 },
      { id: "b", label: "Dalam rangka meningkatkan profesionalisme aparatur, pimpinan menghimbau seluruh pegawai untuk mengutamakan kualitas pelayanan dan memberikan respon yang cepat terhadap pengaduan masyarakat.", score: 0 },
      { id: "c", label: "Dalam rangka meningkatkan profesionalisme aparatur, pimpinan mengimbau seluruh pegawai untuk mengutamakan kwalitas pelayanan dan memberikan respons yang cepat terhadap pengaduan masyarakat.", score: 0 },
      { id: "d", label: "Dalam rangka meningkatkan profesionalisme aparatur, pimpinan mengimbau kepada seluruh pegawai untuk mengutamakan kualitas pelayanan dan memberikan respon yang cepat terhadap pengaduan masyarakat.", score: 0 },
      { id: "e", label: "Dalam rangka meningkatkan profesionalisme aparatur, pimpinan menghimbau kepada seluruh pegawai untuk mengutamakan kwalitas pelayanan dan memberikan response yang cepat terhadap pengaduan masyarakat.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan A tepat karena memperbaiki ketiga kata tidak baku menjadi bentuk baku yang sesuai kaidah: mengimbau (bukan menghimbau), kualitas (bukan kwalitas), dan respons (bukan respon/response).",
  },
  {
    id: "bahasa-indonesia-4-10",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Perhatikan kutipan berikut:\n\n“Berdasarkan laporan yang diterima dari unit pelayanan, beberapa dokumen masih di simpan di ruang arsip sedangkan dokumen lainnya telah di kirim ke kantor pusat.”\n\nJika seluruh kesalahan ejaan diperbaiki tanpa mengubah makna kalimat, bentuk yang paling tepat adalah ...",
    choices: [
      { id: "a", label: "Berdasarkan laporan yang diterima dari unit pelayanan, beberapa dokumen masih disimpan di ruang arsip, sedangkan dokumen lainnya telah dikirim ke kantor pusat.", score: 5 },
      { id: "b", label: "Berdasarkan laporan yang diterima dari unit pelayanan, beberapa dokumen masih di simpan diruang arsip, sedangkan dokumen lainnya telah di kirim kekantor pusat.", score: 0 },
      { id: "c", label: "Berdasarkan laporan yang diterima dari unit pelayanan, beberapa dokumen masih disimpan diruang arsip sedangkan dokumen lainnya telah dikirim kekantor pusat.", score: 0 },
      { id: "d", label: "Berdasarkan laporan yang diterima dari unit pelayanan, beberapa dokumen masih di-simpan di ruang arsip sedangkan dokumen lainnya telah di-kirim ke kantor pusat.", score: 0 },
      { id: "e", label: "Berdasarkan laporan yang diterima dari unit pelayanan, beberapa dokumen masih disimpan di ruang arsip sedangkan dokumen lainnya telah di kirim ke kantor pusat.", score: 0 },
    ],
    explanation: "Pembahasan: Pilihan A tepat karena awalan di- pada kata kerja pasif ditulis serangkai (disimpan, dikirim), kata depan di dan ke ditulis terpisah (di ruang arsip, ke kantor pusat), serta diberi tanda koma sebelum konjungsi pertentangan sedangkan.",
  },
];

export const BAHASA_INDONESIA_DRILL_QUESTIONS: Question[] = [
  ...BAHASA_INDONESIA_1_DRILL_QUESTIONS,
  ...BAHASA_INDONESIA_2_DRILL_QUESTIONS,
  ...BAHASA_INDONESIA_3_DRILL_QUESTIONS,
  ...BAHASA_INDONESIA_4_DRILL_QUESTIONS,
];
