import type { Question } from "./types";

export const MINI_TWK_QUESTIONS: Question[] = [
  {
    id: "mini-twk-01",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "(1) Festival musik tradisional di sejumlah daerah mulai dikemas dalam bentuk pertunjukan kolaboratif agar lebih mudah diterima oleh generasi muda. (2) Para seniman memadukan instrumen tradisional dengan tata panggung modern tanpa menghilangkan karakter utama dari musik yang dimainkan. (3) Meski mendapat respons positif, sebagian pengamat menilai bahwa perubahan tersebut perlu dilakukan secara hati-hati: agar unsur tradisi tidak sekadar dijadikan pelengkap pertunjukan. (4) Penyelenggara kemudian melibatkan budayawan dalam proses penyusunan konsep agar unsur artistik dan nilai budaya dapat berjalan beriringan. (5) Upaya tersebut diharapkan membuat seni tradisional tetap relevan tanpa kehilangan identitas yang menjadi ciri khasnya.\n\nPenggunaan tanda baca yang salah terdapat pada kalimat nomor...",
    choices: [
      { id: "a", label: "(1)", score: 0 },
      { id: "b", label: "(2)", score: 0 },
      { id: "c", label: "(3)", score: 5 },
      { id: "d", label: "(4)", score: 0 },
      { id: "e", label: "(5)", score: 0 },
    ],
    explanation: "Penggunaan tanda baca titik dua (:) pada kalimat (3) tidak tepat. Berdasarkan pedoman PUEBI/EYD, tanda titik dua dipakai pada akhir suatu pernyataan lengkap yang diikuti pemerincian atau penjelasan. Pada kalimat (3), klausa 'agar unsur tradisi tidak sekadar dijadikan pelengkap pertunjukan' merupakan anak kalimat keterangan tujuan, bukan perincian, sehingga tidak memerlukan tanda titik dua.",
  },
  {
    id: "mini-twk-02",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "Manakah kalimat di bawah ini yang merupakan kalimat tidak efektif?",
    choices: [
      { id: "a", label: "Para atlet menjalani latihan tambahan untuk meningkatkan kemampuan mereka menghadapi pertandingan final.", score: 0 },
      { id: "b", label: "Setelah bertanding hampir dua jam, para pemain mulai mengalami penurunan kondisi fisik.", score: 0 },
      { id: "c", label: "Setelah menyelesaikan pertandingan, hasil pertandingan tersebut kemudian dianalisis oleh pelatih untuk menentukan strategi berikutnya.", score: 5 },
      { id: "d", label: "Pelatih meminta seluruh pemain menjaga konsentrasi hingga pertandingan berakhir.", score: 0 },
      { id: "e", label: "Keberhasilan tim tersebut tidak terlepas dari kerja sama antarpemain yang telah dibangun sejak awal musim.", score: 0 },
    ],
    explanation: "Kalimat pada opsi C tidak efektif karena memiliki subjek gantung (dangling modifier). Frasa 'Setelah menyelesaikan pertandingan' memiliki subjek logis manusia (pemain/pelatih), tetapi induk kalimatnya bersubjek 'hasil pertandingan tersebut', sehingga subjek anak kalimat dan induk kalimat menjadi tidak berpadu secara gramatikal.",
  },
  {
    id: "mini-twk-03",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "(1) Pemandangan dari kawasan pegunungan itu tampak eksotis setelah hujan turun sepanjang malam. (2) Pengelola menyediakan sejumlah fasilitas untuk meningkatkan kenyamanan pengunjung selama berada di kawasan wisata. (3) Beberapa wisatawan justru terlihat acuh terhadap larangan membuang sampah sembarangan yang telah dipasang di sejumlah lokasi. (4) Petugas kemudian memberikan teguran secara persuasif agar wisatawan bersedia mematuhi ketentuan yang berlaku. (5) Pengelola berharap kesadaran pengunjung dapat membantu menjaga kelestarian kawasan wisata tersebut.\n\nPenggunaan kata yang salah pada paragraf di atas adalah...",
    choices: [
      { id: "a", label: "Eksotis (kalimat 1)", score: 0 },
      { id: "b", label: "Kenyamanan (kalimat 2)", score: 0 },
      { id: "c", label: "Acuh (kalimat 3)", score: 5 },
      { id: "d", label: "Persuasif (kalimat 4)", score: 0 },
      { id: "e", label: "Kelestarian (kalimat 5)", score: 0 },
    ],
    explanation: "Menurut KBBI, kata 'acuh' berarti 'peduli; mengindahkan'. Kalimat (3) menghendaki maksud 'tidak peduli' terhadap larangan membuang sampah, sehingga penggunaan kata yang tepat seharusnya adalah 'tidak acuh' atau 'acuh tak acuh'.",
  },
  {
    id: "mini-twk-04",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "(1) Tren memasak makanan rumahan kembali meningkat setelah banyak masyarakat mulai memperhatikan asal bahan dan kandungan makanan yang dikonsumsi. (2) Media sosial turut mempercepat tren tersebut dengan menyediakan berbagai resep yang mudah diikuti oleh pemula. (3) Di sisi lain, kemudahan memperoleh resep tidak selalu diikuti pemahaman mengenai teknik pengolahan bahan yang tepat. (4) Kesalahan dalam mengolah bahan tertentu dapat memengaruhi rasa, tekstur, bahkan kandungan gizi makanan. (5) Oleh karena itu, peningkatan minat memasak di rumah perlu diiringi pemahaman dasar mengenai pemilihan dan pengolahan bahan makanan.\n\nKesimpulan yang paling tepat untuk paragraf tersebut adalah...",
    choices: [
      { id: "a", label: "Media sosial menjadi faktor utama yang menyebabkan masyarakat kembali tertarik memasak makanan rumahan.", score: 0 },
      { id: "b", label: "Meningkatnya minat memasak di rumah perlu disertai pengetahuan mengenai bahan dan teknik pengolahannya.", score: 5 },
      { id: "c", label: "Kesalahan dalam mengolah bahan makanan dapat mengurangi kandungan gizi makanan yang dikonsumsi masyarakat.", score: 0 },
      { id: "d", label: "Resep yang tersedia di media sosial memudahkan masyarakat mempelajari teknik memasak secara mandiri.", score: 0 },
      { id: "e", label: "Perhatian terhadap asal bahan makanan menjadi alasan utama masyarakat memilih memasak sendiri di rumah.", score: 0 },
    ],
    explanation: "Kesimpulan paragraf dirumuskan pada kalimat penutup (5) yang diawali konjungsi antarkalimat penegas 'Oleh karena itu...', yaitu peningkatan minat memasak di rumah perlu diiringi dengan pemahaman dan pengetahuan mengenai pemilihan bahan serta teknik pengolahannya.",
  },
  {
    id: "mini-twk-05",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "(1) Kehadiran pasar malam tidak hanya memberikan hiburan bagi masyarakat, tetapi juga membuka peluang ekonomi bagi pedagang kecil. (2) Berbagai jenis makanan, permainan, dan kerajinan lokal ditawarkan kepada pengunjung yang datang dari berbagai wilayah. (3) Aktivitas perdagangan tersebut membuat kawasan sekitar menjadi lebih ramai pada malam hari. (4) Di samping memberikan manfaat ekonomi, kegiatan tersebut juga menjadi ruang pertemuan masyarakat dari latar belakang yang berbeda. (5) Dengan demikian, pasar malam memiliki fungsi yang lebih luas daripada sekadar tempat hiburan karena turut menggerakkan aktivitas ekonomi dan interaksi sosial.\n\nKalimat utama paragraf di atas ditandai dengan nomor...",
    choices: [
      { id: "a", label: "(1)", score: 5 },
      { id: "b", label: "(2)", score: 0 },
      { id: "c", label: "(3)", score: 0 },
      { id: "d", label: "(4)", score: 0 },
      { id: "e", label: "(5)", score: 0 },
    ],
    explanation: "Kalimat utama paragraf deduktif ini berada pada kalimat (1), yang memuat pernyataan inti bahwa kehadiran pasar malam memberi hiburan sekaligus membuka peluang ekonomi bagi pedagang kecil, yang kemudian dijabarkan secara rinci oleh kalimat-kalimat pengembang berikutnya.",
  },
  {
    id: "mini-twk-06",
    category: "TWK",
    topic: "Bahasa Indonesia",
    prompt: "(1) Kehadiran media komunitas di sejumlah daerah memberikan ruang bagi masyarakat untuk menyampaikan informasi mengenai kegiatan dan persoalan di lingkungan mereka. (2) Informasi yang disebarkan umumnya berasal dari laporan warga sehingga topik yang dibahas lebih dekat dengan kebutuhan masyarakat setempat. (3) Namun, kedekatan tersebut juga dapat menjadi persoalan apabila informasi yang diterima tidak melalui proses verifikasi yang memadai. (4) Kesalahan informasi dapat menimbulkan kesalahpahaman, terutama ketika suatu berita disebarkan kembali melalui berbagai platform digital. (5) Oleh karena itu, keberadaan media komunitas perlu diiringi penerapan proses verifikasi agar kedekatan informasi dengan masyarakat tetap berjalan tanpa mengabaikan akurasi berita.\n\nGagasan utama paragraf di atas adalah...",
    choices: [
      { id: "a", label: "Media komunitas menjadi sarana masyarakat untuk menyampaikan informasi mengenai persoalan di lingkungan sekitar.", score: 0 },
      { id: "b", label: "Informasi dari warga membuat media komunitas memiliki topik yang lebih dekat dengan kebutuhan masyarakat setempat.", score: 0 },
      { id: "c", label: "Penyebaran informasi melalui berbagai platform digital dapat memperbesar dampak kesalahan berita.", score: 0 },
      { id: "d", label: "Proses verifikasi diperlukan agar informasi media komunitas tetap akurat meskipun berasal dari laporan masyarakat.", score: 5 },
      { id: "e", label: "Kedekatan media komunitas dengan masyarakat dapat menjadi persoalan apabila informasi yang disampaikan tidak diverifikasi.", score: 0 },
    ],
    explanation: "Gagasan utama paragraf berpusat pada penegasan kalimat (5): pentingnya penerapan proses verifikasi agar informasi yang disampaikan oleh media komunitas tetap terjaga akurasinya meskipun bersumber langsung dari laporan warga.",
  },
  {
    id: "mini-twk-07",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Sebuah kebijakan negara mengutamakan kepentingan kelompok tertentu meskipun berdampak pada ketidakadilan bagi masyarakat lainnya. Jika dinilai berdasarkan kedudukan Pancasila dalam konstitusi, kebijakan tersebut bertentangan dengan...",
    choices: [
      { id: "a", label: "Pancasila sebagai dasar negara yang menjadi landasan penyelenggaraan kehidupan bernegara.", score: 0 },
      { id: "b", label: "Pancasila sebagai pandangan hidup yang menjadi pedoman perilaku masyarakat dalam kehidupan sehari-hari.", score: 0 },
      { id: "c", label: "Pancasila sebagai sumber nilai yang memberikan arah bagi pembentukan kebijakan negara.", score: 0 },
      { id: "d", label: "Pancasila dalam Pembukaan UUD 1945 sebagai dasar negara yang menjadi landasan penyelenggaraan negara.", score: 5 },
      { id: "e", label: "Pancasila sebagai identitas nasional yang mencerminkan karakter dan kepribadian bangsa Indonesia.", score: 0 },
    ],
    explanation: "Kedudukan yuridis-konstitusional Pancasila ditegaskan dalam Pembukaan UUD 1945 Alinea IV sebagai dasar negara yang menjadi landasan penyelenggaraan negara. Kebijakan publik yang diskriminatif dan tidak adil bertentangan langsung dengan kedudukan Pancasila dalam Pembukaan UUD 1945.",
  },
  {
    id: "mini-twk-08",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Sebuah pemerintah daerah mengembangkan kebijakan ekonomi berdasarkan potensi wilayahnya, tetapi tetap menyesuaikannya dengan arah pembangunan nasional. Pendekatan tersebut paling tepat mencerminkan...",
    choices: [
      { id: "a", label: "Mengoptimalkan potensi daerah untuk meningkatkan kesejahteraan masyarakat setempat.", score: 0 },
      { id: "b", label: "Memberikan kewenangan kepada daerah dalam menentukan prioritas pembangunan sesuai kebutuhannya.", score: 0 },
      { id: "c", label: "Mengembangkan keunggulan daerah dengan tetap mendukung kepentingan pembangunan nasional.", score: 5 },
      { id: "d", label: "Mendorong kemandirian daerah melalui pemanfaatan sumber daya sesuai karakteristik wilayah.", score: 0 },
      { id: "e", label: "Mewujudkan pemerataan pembangunan dengan memberikan ruang bagi setiap daerah untuk mengembangkan potensinya.", score: 0 },
    ],
    explanation: "Prinsip hubungan pusat dan daerah dalam kerangka NKRI menuntut adanya sinergi: pemerintah daerah mengembangkan potensi keunggulan lokalnya namun tetap selaras dan menopang prioritas pembangunan nasional secara menyeluruh.",
  },
  {
    id: "mini-twk-09",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam suatu wilayah, masyarakat memiliki tradisi yang berbeda dalam menyelesaikan persoalan sosial. Pemerintah memberi ruang bagi perbedaan tersebut selama tetap sesuai dengan aturan yang berlaku bersama. Sikap tersebut paling tepat menunjukkan bahwa...",
    choices: [
      { id: "a", label: "Menyesuaikan kebijakan dengan karakter masyarakat agar kehidupan sosial berjalan efektif.", score: 0 },
      { id: "b", label: "Mengakui keberagaman masyarakat tanpa mengabaikan aturan yang menjadi kepentingan bersama.", score: 5 },
      { id: "c", label: "Memberikan kewenangan kepada setiap kelompok untuk mempertahankan tata kehidupan masing-masing.", score: 0 },
      { id: "d", label: "Mengembangkan kebudayaan masyarakat melalui kebebasan menentukan penyelesaian persoalan sosial.", score: 0 },
      { id: "e", label: "Membangun persatuan dengan memberikan kesempatan kepada setiap kelompok menjalankan kebiasaannya.", score: 0 },
    ],
    explanation: "Memberi ruang bagi kearifan lokal/tradisi dengan syarat tetap tunduk pada hukum positif mencerminkan hakikat Bhinneka Tunggal Ika: mengakui dan menghormati kemajemukan kultural warga tanpa mengesampingkan tertib aturan yang menjadi kesepakatan bersama.",
  },
  {
    id: "mini-twk-10",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Pemerintah harus menentukan penerima bantuan dari beberapa kelompok masyarakat dengan tingkat kebutuhan yang berbeda. Agar bantuan diberikan secara adil, prioritas ditentukan berdasarkan kondisi masing-masing penerima. Kebijakan tersebut mencerminkan...",
    choices: [
      { id: "a", label: "Pemenuhan kebutuhan masyarakat berdasarkan kondisi sosial dan ekonomi penerima.", score: 0 },
      { id: "b", label: "Pemerataan kesejahteraan melalui pemberian bantuan kepada seluruh kelompok masyarakat.", score: 0 },
      { id: "c", label: "Penerapan keadilan dengan menyesuaikan bantuan berdasarkan tingkat kebutuhan penerima.", score: 5 },
      { id: "d", label: "Kepedulian sosial melalui keberpihakan kepada kelompok yang memiliki keterbatasan ekonomi.", score: 0 },
      { id: "e", label: "Pemenuhan hak masyarakat melalui distribusi bantuan secara proporsional.", score: 0 },
    ],
    explanation: "Keadilan substantif dalam Sila ke-5 Pancasila tidak selalu berarti membagi dalam porsi yang sama rata, melainkan menerapkan keadilan proporsional dengan mengalokasikan bantuan sesuai derajat urgensi dan kebutuhan masing-masing kelompok penerima.",
  },
  {
    id: "mini-twk-11",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Sebuah perguruan tinggi memberi ruang kepada mahasiswa untuk menyampaikan kritik terhadap kebijakan kampus. Namun, kritik tersebut tidak boleh mengancam atau merugikan hak mahasiswa lain. Penerapan tersebut menunjukkan bahwa...",
    choices: [
      { id: "a", label: "Kebebasan berpendapat perlu diarahkan untuk menjaga ketertiban dalam lingkungan pendidikan.", score: 0 },
      { id: "b", label: "Pelaksanaan hak individu harus mempertimbangkan kepentingan lembaga dan masyarakat.", score: 0 },
      { id: "c", label: "Penyampaian pendapat dapat dilakukan selama tidak menimbulkan gangguan terhadap pihak lain.", score: 0 },
      { id: "d", label: "Hak menyampaikan pendapat tetap dijamin dengan kewajiban menghormati hak orang lain.", score: 5 },
      { id: "e", label: "Kebebasan berpendapat dapat dilaksanakan sepanjang mengikuti mekanisme yang ditetapkan lembaga.", score: 0 },
    ],
    explanation: "Berdasarkan Pasal 28J ayat (1) UUD 1945, setiap orang berhak menggunakan hak dan kebebasannya, namun secara bersamaan wajib menghormati hak asasi orang lain serta menjaga ketertiban dan ketenteraman bersama.",
  },
  {
    id: "mini-twk-12",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Pasal 32 ayat (1) UUD 1945 menyatakan bahwa negara memajukan kebudayaan nasional Indonesia di tengah peradaban dunia dengan menjamin kebebasan masyarakat dalam memelihara dan mengembangkan nilai-nilai budayanya. Pemerintah daerah kemudian menyusun program budaya yang melibatkan tradisi lokal sekaligus memperkenalkannya melalui forum internasional. Kebijakan tersebut paling tepat dipahami sebagai...",
    choices: [
      { id: "a", label: "Upaya melestarikan kebudayaan daerah agar tetap dikenal oleh generasi berikutnya.", score: 0 },
      { id: "b", label: "Pengembangan kebudayaan lokal dengan memanfaatkan kesempatan untuk memperkenalkannya kepada masyarakat dunia.", score: 0 },
      { id: "c", label: "Pelaksanaan kewajiban negara memajukan kebudayaan nasional dengan tetap memberikan ruang bagi masyarakat mengembangkan budayanya.", score: 5 },
      { id: "d", label: "Pemanfaatan kebudayaan daerah sebagai bagian dari strategi memperkuat daya saing Indonesia dalam pergaulan internasional.", score: 0 },
      { id: "e", label: "Penguatan identitas nasional melalui pengembangan berbagai kebudayaan daerah yang memiliki nilai historis.", score: 0 },
    ],
    explanation: "Amanat Pasal 32 ayat (1) UUD 1945 menegaskan tanggung jawab negara memajukan kebudayaan nasional di kancah peradaban dunia dengan senantiasa memberikan ruang kebebasan bagi masyarakat dalam melestarikan dan mengembangkan nilai budaya lokalnya.",
  },
  {
    id: "mini-twk-13",
    category: "TWK",
    topic: "Bela Negara",
    prompt: "Pemerintah meningkatkan kewaspadaan terhadap ancaman siber yang dapat mengganggu keamanan informasi nasional. Sebagai ASN, tindakan yang paling mencerminkan kemampuan awal Bela Negara adalah...",
    choices: [
      { id: "a", label: "Memperbarui pengetahuan keamanan digital agar mampu mengenali risiko dalam pelaksanaan tugas sehari-hari.", score: 5 },
      { id: "b", label: "Menjaga kerahasiaan informasi kedinasan agar tidak dimanfaatkan pihak yang berkepentingan.", score: 0 },
      { id: "c", label: "Mengikuti prosedur keamanan informasi agar pelaksanaan tugas tetap berlangsung sesuai ketentuan.", score: 0 },
      { id: "d", label: "Mengingatkan rekan kerja mengenai pentingnya menjaga keamanan data selama menggunakan perangkat kedinasan.", score: 0 },
      { id: "e", label: "Melaporkan aktivitas mencurigakan agar potensi gangguan terhadap sistem dapat segera ditindaklanjuti.", score: 0 },
    ],
    explanation: "Kemampuan awal bela negara secara psikis/intelektual berakar pada peningkatan kecakapan, wawasan, dan literasi diri agar mampu mengidentifikasi serta memitigasi risiko keamanan digital sejak dini dalam pelaksanaan tugas kedinasan.",
  },
  {
    id: "mini-twk-14",
    category: "TWK",
    topic: "Bela Negara",
    prompt: "Penggunaan bahasa asing di media sosial semakin dominan hingga sebagian anak muda jarang menggunakan Bahasa Indonesia secara baik. Sikap yang paling mencerminkan cinta tanah air dalam menghadapi kondisi tersebut adalah...",
    choices: [
      { id: "a", label: "Membiasakan penggunaan Bahasa Indonesia dalam komunikasi digital tanpa mengabaikan perkembangan bahasa global.", score: 0 },
      { id: "b", label: "Mengembangkan konten berbahasa Indonesia agar identitas nasional tetap relevan di ruang digital.", score: 0 },
      { id: "c", label: "Mengutamakan Bahasa Indonesia dalam komunikasi publik sambil menghargai penggunaan bahasa asing secara proporsional.", score: 0 },
      { id: "d", label: "Mendorong generasi muda menggunakan Bahasa Indonesia sebagai bagian dari penguatan identitas nasional.", score: 5 },
      { id: "e", label: "Memanfaatkan Bahasa Indonesia dalam berbagai platform digital untuk memperluas apresiasi terhadap budaya nasional.", score: 0 },
    ],
    explanation: "Salah satu indikator utama nilai Cinta Tanah Air adalah menjaga kehormatan lambang dan jati diri bangsa dengan mengajak serta mendorong generasi muda bangga berbahasa Indonesia sebagai perekat identitas nasional.",
  },
  {
    id: "mini-twk-15",
    category: "TWK",
    topic: "Bela Negara",
    prompt: "Pemerintah membuka ruang partisipasi publik dalam proses pembentukan peraturan agar kebijakan lebih sesuai kebutuhan masyarakat. Sebagai warga negara yang memiliki kesadaran berbangsa dan bernegara, tindakan yang paling tepat adalah...",
    choices: [
      { id: "a", label: "Mempelajari rancangan regulasi sebelum menyampaikan pandangan melalui saluran partisipasi yang tersedia.", score: 0 },
      { id: "b", label: "Mengikuti pembahasan regulasi dengan memperhatikan kepentingan masyarakat yang terdampak oleh kebijakan tersebut.", score: 0 },
      { id: "c", label: "Menyampaikan pendapat berdasarkan kepentingan masyarakat melalui mekanisme partisipasi yang telah disediakan pemerintah.", score: 0 },
      { id: "d", label: "Mengawasi proses pembentukan regulasi agar kepentingan masyarakat tetap dipertimbangkan dalam pengambilan keputusan.", score: 0 },
      { id: "e", label: "Menghimpun aspirasi masyarakat terdampak sebagai bahan masukan dalam proses pembentukan regulasi pemerintah.", score: 5 },
    ],
    explanation: "Kesadaran berbangsa dan bernegara yang aktif tercermin dari inisiatif mengorganisir dan menghimpun aspirasi warga yang terdampak langsung, sehingga pertimbangan dalam pembentukan regulasi benar-benar merepresentasikan kepentingan umum yang berkeadilan.",
  },
  {
    id: "mini-twk-16",
    category: "TWK",
    topic: "Bela Negara",
    prompt: "Seorang ASN yang bertugas pada unit pelayanan mengetahui bahwa sistem pelayanan mengalami gangguan sehingga antrean masyarakat meningkat. Beberapa rekan memilih menunggu sistem kembali normal karena menganggap gangguan tersebut merupakan tanggung jawab bagian teknis. Sebagai bentuk kesadaran bela negara dalam menjalankan profesinya, sikap yang paling tepat adalah ....",
    choices: [
      { id: "a", label: "Tetap menjalankan tugas yang masih dapat dilakukan sambil menunggu bagian teknis menyelesaikan gangguan pada sistem.", score: 0 },
      { id: "b", label: "Berkoordinasi dengan bagian terkait agar gangguan segera ditangani sehingga pelayanan dapat kembali berjalan secara normal.", score: 0 },
      { id: "c", label: "Melaporkan kondisi kepada atasan sekaligus membantu mengatur masyarakat agar antrean tetap tertib selama sistem mengalami gangguan.", score: 0 },
      { id: "d", label: "Mengupayakan pelayanan sementara sesuai prosedur dan kewenangan agar kebutuhan masyarakat tetap terlayani selama sistem diperbaiki.", score: 5 },
      { id: "e", label: "Membantu bagian yang mengalami kendala agar proses pelayanan dapat segera dilanjutkan tanpa mengabaikan pembagian tugas yang berlaku.", score: 0 },
    ],
    explanation: "Wujud nilai rela berkorban untuk bangsa dan negara dalam profesi ASN adalah komitmen tinggi mengutamakan kepuasan masyarakat, yaitu mengupayakan mekanisme pelayanan sementara sesuai SOP agar kebutuhan warga tetap terlayani dengan baik.",
  },
  {
    id: "mini-twk-17",
    category: "TWK",
    topic: "Bela Negara",
    prompt: "Dalam pelaksanaan tugas, seorang ASN tidak hanya dituntut menyelesaikan pekerjaan, tetapi juga menjaga kepercayaan masyarakat. Ia menemukan beberapa proses kerja di unitnya belum berjalan secara optimal. Sebagai bagian dari aparatur negara, ia perlu memastikan pekerjaannya tetap memberikan manfaat bagi kepentingan publik. Sikap yang paling tepat dilakukan adalah...",
    choices: [
      { id: "a", label: "Menjalankan tugas sesuai SOP sambil memastikan setiap tahapan pekerjaan terlaksana secara tertib.", score: 0 },
      { id: "b", label: "Memperbaiki proses kerja yang kurang optimal agar pelaksanaan tugas semakin mendukung kebutuhan masyarakat.", score: 0 },
      { id: "c", label: "Meningkatkan kompetensi pribadi agar mampu memberikan kinerja terbaik dalam menjalankan tanggung jawab kedinasan.", score: 0 },
      { id: "d", label: "Mengutamakan kepentingan masyarakat dengan memastikan hasil pekerjaan memberikan manfaat pelayanan secara berkelanjutan.", score: 5 },
      { id: "e", label: "Menyesuaikan pelaksanaan tugas dengan kondisi unit agar pekerjaan tetap berjalan efektif dan terkoordinasi.", score: 0 },
    ],
    explanation: "Pengabdian aparatur sipil negara berlandaskan nilai bela negara menuntut orientasi mutlak pada kepentingan publik, yakni memastikan setiap keluaran (*output*) pekerjaan berdampak positif dan memberikan manfaat nyata bagi pelayanan masyarakat secara berkelanjutan.",
  },
  {
    id: "mini-twk-18",
    category: "TWK",
    topic: "Bela Negara",
    prompt: "Serangan siber terhadap sistem digital pemerintah menunjukkan bahwa ruang digital juga menjadi bagian penting dari kepentingan nasional. Ketergantungan terhadap teknologi dan layanan keamanan dari luar negeri dapat meningkatkan kerentanan ketika terjadi gangguan global. Sebagai ASN, Raka menyadari bahwa penguatan kapasitas digital dalam negeri membutuhkan kontribusi dari berbagai pihak. Sikap yang paling tepat dilakukan Raka adalah...",
    choices: [
      { id: "a", label: "Meningkatkan kualitas keamanan digital agar pelaksanaan tugas terlindungi dari berbagai gangguan siber.", score: 0 },
      { id: "b", label: "Menggunakan teknologi secara bijaksana agar keamanan informasi tetap terjaga selama menjalankan tugas kedinasan.", score: 0 },
      { id: "c", label: "Mendukung pemanfaatan teknologi dalam negeri yang andal untuk memperkuat kemandirian digital nasional.", score: 5 },
      { id: "d", label: "Menjaga kerahasiaan informasi kedinasan agar kepentingan masyarakat terlindungi dari penyalahgunaan data.", score: 0 },
      { id: "e", label: "Meningkatkan kewaspadaan terhadap ancaman digital agar kelancaran pelayanan kepada masyarakat tetap terjaga.", score: 0 },
    ],
    explanation: "Sikap patriotik dan bela negara yang strategis menghadapi ancaman ketergantungan teknologi asing adalah aktif mendukung kemandirian digital nasional melalui adopsi dan pengembangan teknologi karya anak bangsa.",
  },
  {
    id: "mini-twk-19",
    category: "TWK",
    topic: "Integritas",
    prompt: "Safira kembali bekerja setelah mengambil cuti beberapa hari. Seorang senior menegurnya di hadapan rekan kerja karena menganggap pekerjaan yang tertunda selama cuti merupakan tanggung jawab Safira. Padahal, pekerjaan tersebut telah dialihkan kepada pegawai lain sesuai pembagian tugas. Sikap Safira yang paling tepat adalah...",
    choices: [
      { id: "a", label: "Menjelaskan kondisi pekerjaan kepada senior agar penyelesaian tugas tetap dapat dipertanggungjawabkan.", score: 0 },
      { id: "b", label: "Menyampaikan klarifikasi kepada senior secara tegas meskipun berisiko menimbulkan ketegangan dalam hubungan kerja.", score: 5 },
      { id: "c", label: "Memastikan pembagian tugas ditinjau berdasarkan ketentuan agar setiap pegawai memperoleh tanggung jawab secara proporsional.", score: 0 },
      { id: "d", label: "Menunjukkan kembali pembagian pekerjaan yang berlaku agar pelaksanaan tugas tetap berjalan sesuai ketentuan.", score: 0 },
      { id: "e", label: "Menjaga komunikasi dengan senior agar perbedaan pemahaman tidak berkembang menjadi persoalan hubungan kerja.", score: 0 },
    ],
    explanation: "Nilai integritas menuntut keberanian bersikap jujur dan berpegang pada kebenaran faktual secara lugas dan profesional, meskipun berisiko menghadapi ketegangan relasional dalam hubungan kerja.",
  },
  {
    id: "mini-twk-20",
    category: "TWK",
    topic: "Integritas",
    prompt: "Setelah kembali dari perjalanan dinas, Fajar belum melakukan presensi karena langsung diminta atasannya mengantarkan oleh-oleh ke ruang kerja. Waktu presensi masih tersedia, tetapi Fajar khawatir dianggap tidak menghargai permintaan atasannya jika menunda. Sikap Fajar yang paling tepat adalah...",
    choices: [
      { id: "a", label: "Mengantarkan oleh-oleh terlebih dahulu agar permintaan atasan dapat segera diselesaikan.", score: 0 },
      { id: "b", label: "Menyampaikan kepada atasan bahwa presensi perlu diselesaikan sebelum menjalankan permintaan tersebut.", score: 5 },
      { id: "c", label: "Memastikan tugas pengantaran selesai dengan baik agar kepercayaan atasan tetap terjaga.", score: 0 },
      { id: "d", label: "Meminta rekan membantu mengantarkan oleh-oleh agar seluruh kepentingan dapat segera diselesaikan.", score: 0 },
      { id: "e", label: "Mengutamakan penyelesaian pekerjaan kantor agar waktu kerja dapat dimanfaatkan secara optimal.", score: 0 },
    ],
    explanation: "Integritas disiplin kerja menuntut kepatuhan pada aturan administrasi kedinasan (presensi resmi) di atas urusan pribadi/informal, yang disampaikan secara santun namun jelas kepada atasan.",
  },
  {
    id: "mini-twk-21",
    category: "TWK",
    topic: "Integritas",
    prompt: "Nanda dipercaya mengelola dana kegiatan organisasi. Menjelang acara, ia menyadari terdapat sisa anggaran yang cukup besar karena beberapa kebutuhan dapat diperoleh dengan harga lebih rendah. Beberapa anggota mengusulkan agar sisa dana tersebut digunakan untuk membeli fasilitas tambahan yang tidak direncanakan. Sikap Nanda yang paling tepat adalah...",
    choices: [
      { id: "a", label: "Menyimpan sisa dana untuk mengantisipasi kebutuhan tambahan yang mungkin muncul selama kegiatan.", score: 0 },
      { id: "b", label: "Menggunakan sisa dana untuk meningkatkan kualitas kegiatan selama manfaatnya dirasakan peserta.", score: 0 },
      { id: "c", label: "Mengembalikan sisa dana sesuai mekanisme agar penggunaannya tetap dapat dipertanggungjawabkan.", score: 5 },
      { id: "d", label: "Membahas penggunaan sisa dana bersama anggota agar keputusan mencerminkan kepentingan organisasi.", score: 0 },
      { id: "e", label: "Memanfaatkan sisa dana secara terbatas untuk memenuhi kebutuhan pendukung yang masih relevan.", score: 0 },
    ],
    explanation: "Akuntabilitas keuangan dan kejujuran menuntut kepatuhan pada Rencana Anggaran Biaya (RAB). Setiap kelebihan atau sisa anggaran wajib dilaporkan dan dikembalikan melalui mekanisme pertanggungjawaban resmi, tidak dialihkan secara sepihak.",
  },
  {
    id: "mini-twk-22",
    category: "TWK",
    topic: "Integritas",
    prompt: "Bima mendapat fasilitas perjalanan dari panitia untuk menghadiri kegiatan di luar kota. Panitia memberikan beberapa pilihan akomodasi dengan tingkat fasilitas berbeda, dan seluruh biaya ditanggung penyelenggara. Sikap Bima yang paling tepat adalah...",
    choices: [
      { id: "a", label: "Memilih akomodasi yang mendukung kebutuhan tugas agar pelaksanaan kegiatan tetap berjalan optimal.", score: 0 },
      { id: "b", label: "Memilih akomodasi berdasarkan kebutuhan perjalanan tanpa mempertimbangkan fasilitas yang berlebihan.", score: 5 },
      { id: "c", label: "Memilih akomodasi dengan fasilitas terbaik agar kesempatan yang diberikan dapat dimanfaatkan secara maksimal.", score: 0 },
      { id: "d", label: "Memilih akomodasi yang direkomendasikan panitia untuk memastikan seluruh kebutuhan kegiatan terpenuhi.", score: 0 },
      { id: "e", label: "Memilih akomodasi yang nyaman agar kondisi fisik tetap mendukung pelaksanaan tugas secara optimal.", score: 0 },
    ],
    explanation: "Integritas kesederhanaan dan tanggung jawab atas anggaran menuntut aparatur memilih fasilitas yang proporsional sesuai kebutuhan perjalanan dinas tanpa mencari fasilitas berlebihan atau kemewahan yang tidak perlu.",
  },
  {
    id: "mini-twk-23",
    category: "TWK",
    topic: "Integritas",
    prompt: "Sebagai guru, Nisa diminta menggunakan aplikasi pembelajaran baru yang belum pernah digunakan dalam kegiatan mengajar. Ia memiliki beberapa hari sebelum aplikasi tersebut wajib digunakan di kelas. Sikap Nisa yang paling tepat adalah...",
    choices: [
      { id: "a", label: "Mempelajari panduan penggunaan aplikasi agar pelaksanaan pembelajaran berjalan sesuai ketentuan.", score: 0 },
      { id: "b", label: "Berlatih menggunakan aplikasi secara berkala agar penerapannya semakin lancar di kelas.", score: 0 },
      { id: "c", label: "Berdiskusi dengan rekan berpengalaman untuk memperoleh gambaran mengenai penggunaan aplikasi tersebut.", score: 0 },
      { id: "d", label: "Mencoba segala rupa fitur aplikasi sambil menentukan cara penggunaannya dalam pembelajaran.", score: 5 },
      { id: "e", label: "Menyusun tahapan persiapan agar penggunaan aplikasi dapat diterapkan sesuai kebutuhan pembelajaran.", score: 0 },
    ],
    explanation: "Profesionalisme dan integritas dedikasi kerja ditunjukkan dengan inisiatif langsung mencoba dan mengeksplorasi seluruh fitur aplikasi guna menemukan cara integrasi paling tepat dan efektif bagi pembelajaran siswa.",
  },
  {
    id: "mini-twk-24",
    category: "TWK",
    topic: "Integritas",
    prompt: "Dafa merupakan siswa SD yang ingin meningkatkan prestasi belajarnya. Orang tuanya belum mampu menyediakan les tambahan, sementara beberapa materi pelajaran cukup sulit baginya. Sikap Dafa yang paling tepat adalah...",
    choices: [
      { id: "a", label: "Menyusun waktu belajar secara teratur agar seluruh kewajiban sekolah dapat terselesaikan.", score: 0 },
      { id: "b", label: "Mempelajari materi sendiri melalui buku sekolah sebelum meminta bantuan kepada orang lain.", score: 0 },
      { id: "c", label: "Terus berlatih memahami materi dengan memanfaatkan berbagai sumber belajar yang tersedia.", score: 5 },
      { id: "d", label: "Menyelesaikan seluruh tugas sekolah dengan sungguh-sungguh meskipun memiliki keterbatasan fasilitas belajar.", score: 0 },
      { id: "e", label: "Membantu teman memahami pelajaran yang dikuasainya agar kegiatan belajar menjadi lebih bermanfaat.", score: 0 },
    ],
    explanation: "Kemandirian, kerja keras, dan keuletan belajar tampak dari sikap tidak mudah menyerah oleh keterbatasan biaya, melainkan secara aktif memaksimalkan ragam sumber belajar terbuka untuk menguasai materi pelajaran.",
  },
  {
    id: "mini-twk-25",
    category: "TWK",
    topic: "Nasionalisme",
    prompt: "Sejumlah pejabat terbukti menyalahgunakan anggaran publik untuk kepentingan pribadi, sementara masyarakat masih menghadapi keterbatasan dalam memperoleh layanan dasar. Fenomena tersebut kemudian memunculkan anggapan bahwa sumber daya negara lebih banyak dimanfaatkan oleh kelompok tertentu. Kondisi tersebut paling berpotensi memengaruhi kehidupan kebangsaan melalui...",
    choices: [
      { id: "a", label: "Meningkatnya tuntutan dan keinginan masyarakat terhadap transparansi dalam pengelolaan sumber daya publik.", score: 0 },
      { id: "b", label: "Melemahnya keyakinan masyarakat terhadap efektivitas kebijakan dalam memenuhi kebutuhan publik.", score: 0 },
      { id: "c", label: "Berkembangnya sikap kritis masyarakat terhadap penyelenggaraan pemerintahan dan pengelolaan anggaran.", score: 0 },
      { id: "d", label: "Berkurangnya kesadaran bahwa sumber daya negara merupakan kepentingan bersama seluruh masyarakat.", score: 5 },
      { id: "e", label: "Meningkatnya kecenderungan masyarakat mempertanyakan manfaat pembangunan yang dirasakan lingkungan sekitarnya.", score: 0 },
    ],
    explanation: "Dampak paling merusak dari ketidakadilan pengelolaan sumber daya negara terhadap nasionalisme adalah erosi rasa memiliki bersama (*sense of belonging*), yang berakibat pada memudarnya kesadaran bahwa kekayaan negara adalah amanah demi kepentingan seluruh rakyat.",
  },
  {
    id: "mini-twk-26",
    category: "TWK",
    topic: "Nasionalisme",
    prompt: "Sebuah pemerintah daerah menyusun kebijakan pelestarian budaya dengan melibatkan berbagai komunitas etnis yang hidup di wilayah tersebut. Dalam pembahasannya, muncul usulan agar anggaran terbesar diberikan kepada budaya kelompok yang dianggap paling merepresentasikan identitas daerah. Kebijakan yang paling mencerminkan karakter Indonesia adalah...",
    choices: [
      { id: "a", label: "Menempatkan seluruh kebudayaan daerah sebagai bagian dari identitas nasional yang perlu dikembangkan secara proporsional.", score: 0 },
      { id: "b", label: "Memprioritaskan kebudayaan mayoritas sebagai representasi utama identitas daerah dalam pembangunan kebudayaan.", score: 0 },
      { id: "c", label: "Memberikan dukungan berdasarkan kontribusi setiap kebudayaan terhadap perkembangan masyarakat daerah secara berkelanjutan.", score: 0 },
      { id: "d", label: "Menyesuaikan pelestarian kebudayaan dengan karakteristik masyarakat agar identitas daerah tetap berkembang secara dinamis.", score: 0 },
      { id: "e", label: "Mengembangkan seluruh kebudayaan daerah melalui pendekatan inklusif tanpa menempatkan budaya tertentu sebagai representasi tunggal.", score: 5 },
    ],
    explanation: "Karakter bangsa Indonesia berpijak pada kebinekaan yang inklusif dan setara. Kebijakan kebudayaan harus merangkul seluruh komunitas adat/etnis tanpa hegemoni yang menjadikan satu kebudayaan tertentu sebagai representasi tunggal.",
  },
  {
    id: "mini-twk-27",
    category: "TWK",
    topic: "Nasionalisme",
    prompt: "Harga bahan bakar dalam negeri belum stabil akibat perubahan kondisi energi global. Pemerintah kemudian mempertimbangkan berbagai kebijakan agar gejolak harga tidak semakin membebani masyarakat sekaligus menjaga keberlanjutan perekonomian nasional. Pertimbangan yang paling mencerminkan kepentingan kebangsaan dalam kondisi tersebut adalah...",
    choices: [
      { id: "a", label: "Menjaga keterjangkauan harga energi dengan tetap mempertimbangkan kemampuan fiskal negara secara berkelanjutan.", score: 5 },
      { id: "b", label: "Mengendalikan harga energi agar daya beli masyarakat tetap terjaga dalam kondisi perekonomian nasional.", score: 0 },
      { id: "c", label: "Menyesuaikan kebijakan energi dengan perkembangan global agar stabilitas perekonomian nasional tetap terpelihara.", score: 0 },
      { id: "d", label: "Mengutamakan kepentingan masyarakat dengan menjaga stabilitas energi melalui kebijakan yang terukur dan berkelanjutan.", score: 0 },
      { id: "e", label: "Memperkuat ketahanan energi nasional agar kebutuhan masyarakat tidak terlalu bergantung pada dinamika eksternal.", score: 0 },
    ],
    explanation: "Kepentingan nasional dalam perekonomian menuntut keseimbangan antara melindungi daya beli masyarakat (keterjangkauan harga) dengan kehati-hatian menjaga ketahanan fiskal negara agar perekonomian dapat bertahan secara mandiri dalam jangka panjang.",
  },
  {
    id: "mini-twk-28",
    category: "TWK",
    topic: "Nasionalisme",
    prompt: "Nilai tukar rupiah mengalami tekanan akibat ketidakpastian ekonomi global dan perubahan arus modal internasional. Pemerintah mempertimbangkan kebijakan fiskal untuk menjaga stabilitas perekonomian tanpa mengurangi kemampuan negara membiayai kebutuhan masyarakat. Kebijakan yang paling mencerminkan orientasi kepentingan nasional adalah...",
    choices: [
      { id: "a", label: "Menyesuaikan belanja negara dengan dinamika ekonomi global agar stabilitas fiskal tetap terjaga demi pembangunan bangsa.", score: 0 },
      { id: "b", label: "Memprioritaskan pengendalian defisit keuangan agar kepercayaan pasar terhadap perekonomian nasional tetap terpelihara.", score: 0 },
      { id: "c", label: "Mengarahkan kebijakan fiskal untuk memperkuat ketahanan ekonomi nasional menghadapi tekanan eksternal.", score: 5 },
      { id: "d", label: "Meningkatkan belanja pemerintah agar aktivitas ekonomi domestik tetap tumbuh selama rupiah melemah.", score: 0 },
      { id: "e", label: "Mengurangi ketergantungan terhadap pembiayaan eksternal melalui penguatan penerimaan negara secara bertahap.", score: 0 },
    ],
    explanation: "Orientasi kepentingan nasional dalam menghadapi guncangan moneter global adalah mengarahkan instrumen fiskal demi memperkokoh ketahanan ekonomi domestik dan melindungi stabilitas kehidupan rakyat dari imbas eksternal.",
  },
  {
    id: "mini-twk-29",
    category: "TWK",
    topic: "Nasionalisme",
    prompt: "Perhatikan sikap berikut!\n\n1. Pemerintah memperkuat sektor strategis nasional agar keputusan pembangunan tidak mudah dipengaruhi kepentingan pihak luar.\n2. Pelaku usaha meningkatkan kualitas produk dalam negeri agar mampu berkompetisi di pasar internasional.\n3. Masyarakat mendorong kebijakan nasional yang memberikan ruang lebih besar bagi kerja sama ekonomi dengan negara lain.\n4. Pemerintah mengarahkan pembangunan berdasarkan kebutuhan nasional meskipun terdapat tekanan dari kepentingan eksternal.\n5. Generasi muda meningkatkan pemahaman mengenai perkembangan global agar mampu menyesuaikan diri dengan perubahan internasional.\n\nSikap yang paling mencerminkan nilai perjuangan Bung Karno dalam membangun nasionalisme terdapat pada nomor...",
    choices: [
      { id: "a", label: "1 dan 2", score: 0 },
      { id: "b", label: "2 dan 5", score: 0 },
      { id: "c", label: "1 dan 4", score: 5 },
      { id: "d", label: "3 dan 5", score: 0 },
      { id: "e", label: "2 dan 4", score: 0 },
    ],
    explanation: "Nasionalisme Bung Karno berakar pada konsep Trisakti, yaitu Berdaulat dalam bidang politik dan Berdikari dalam bidang ekonomi. Nilai ini tecermin langsung pada nomor (1) penguatan sektor strategis agar terbebas dari intervensi luar, dan nomor (4) pembangunan berorientasi kebutuhan nasional tanpa tunduk pada tekanan eksternal.",
  },
  {
    id: "mini-twk-30",
    category: "TWK",
    topic: "Nasionalisme",
    prompt: "Perhatikan sikap berikut!\n\n1. Pemerintah memperluas akses pembiayaan bagi usaha kecil agar masyarakat dapat mengembangkan kegiatan ekonominya secara mandiri.\n2. Pelaku usaha meningkatkan produktivitas agar mampu memperoleh keuntungan sebesar-besarnya dalam persaingan pasar terbuka.\n3. Masyarakat membentuk badan usaha bersama untuk mengelola kegiatan ekonomi berdasarkan prinsip kebersamaan.\n4. Pemerintah memberikan insentif kepada perusahaan besar agar pertumbuhan ekonomi nasional berlangsung lebih cepat.\n5. Pelaku usaha memperluas investasi asing untuk mempercepat penguasaan teknologi dan peningkatan kapasitas produksi.\n\nSikap yang paling mencerminkan pemikiran ekonomi Mohammad Hatta terdapat pada nomor...",
    choices: [
      { id: "a", label: "1 dan 2", score: 0 },
      { id: "b", label: "2 dan 4", score: 0 },
      { id: "c", label: "3 dan 5", score: 0 },
      { id: "d", label: "1 dan 3", score: 5 },
      { id: "e", label: "4 dan 5", score: 0 },
    ],
    explanation: "Pemikiran ekonomi kerakyatan Bung Hatta menekankan demokrasi ekonomi berasaskan kekeluargaan (koperasi, nomor 3) serta pemerataan kesempatan usaha mandiri bagi rakyat kecil demi mencegah eksploitasi kapitalistik (nomor 1).",
  },
];
