import type { Question } from "./types";

export const MINI_TIU_6_QUESTIONS: Question[] = [
  {
    id: "mini-tiu6-01",
    category: "TIU",
    topic: "Analogi Kata",
    prompt: "HANGAT : MEMBARA = RINTIK : ...",
    choices: [
      { id: "a", label: "Badai", score: 5 },
      { id: "b", label: "Gerimis", score: 0 },
      { id: "c", label: "Hujan", score: 0 },
      { id: "d", label: "Awan", score: 0 },
      { id: "e", label: "Petir", score: 0 },
    ],
    explanation: "Hubungan gradasi intensitas bertingkat: Kondisi membara merupakan bentuk intensitas panas yang sangat tinggi dan ekstrem dari hangat, sebagaimana kondisi badai merupakan intensitas presipitasi curah hujan yang sangat lebat dan ekstrem dari rintik.",
  },
  {
    id: "mini-tiu6-02",
    category: "TIU",
    topic: "Analogi Kata",
    prompt: "KAYU : KERTAS : ABU = MINYAK BUMI : ... : ...",
    choices: [
      { id: "a", label: "Solar – Minyak Tanah", score: 0 },
      { id: "b", label: "Kilang – Pelumas", score: 0 },
      { id: "c", label: "Bensin – Kendaraan", score: 0 },
      { id: "d", label: "Bensin – Residu", score: 5 },
      { id: "e", label: "Plastik – Polusi", score: 0 },
    ],
    explanation: "Hubungan berantai tiga tahap (Bahan Baku : Produk Olahan Utama : Zat Sisa/Limbah Terakhir): Kayu diolah menjadi produk kertas dan sisa pembakarannya menghasilkan abu, sebagaimana minyak bumi diolah menjadi bahan bakar bensin dan proses destilasinya menyisakan residu/aspal.",
  },
  {
    id: "mini-tiu6-03",
    category: "TIU",
    topic: "Analogi Kata",
    prompt: "AKUPUNKTURIS : JARUM = ASTRONOM : ...",
    choices: [
      { id: "a", label: "Bintang", score: 0 },
      { id: "b", label: "Teleskop", score: 5 },
      { id: "c", label: "Observatorium", score: 0 },
      { id: "d", label: "Planetarium", score: 0 },
      { id: "e", label: "Galaksi", score: 0 },
    ],
    explanation: "Hubungan profesi dan instrumen kerja spesifik utama: Akupunkturis bekerja mengandalkan instrumen spesifik berupa jarum, sebagaimana astronom bekerja meneliti objek antariksa mengandalkan instrumen spesifik berupa teleskop.",
  },
  {
    id: "mini-tiu6-04",
    category: "TIU",
    topic: "Analogi Kata",
    prompt: "BESI : KOROSI = KAYU : ...",
    choices: [
      { id: "a", label: "Pohon", score: 0 },
      { id: "b", label: "Furnitur", score: 0 },
      { id: "c", label: "Pelapukan", score: 5 },
      { id: "d", label: "Gergaji", score: 0 },
      { id: "e", label: "Rayap", score: 0 },
    ],
    explanation: "Hubungan material fisik dengan proses penurunan kualitas/kerusakan alamiah bawaannya: Besi secara alamiah mengalami penurunan kualitas fisik akibat proses korosi (karat), sebagaimana kayu secara alamiah mengalami degradasi fisik akibat proses pelapukan.",
  },
  {
    id: "mini-tiu6-05",
    category: "TIU",
    topic: "Silogisme",
    prompt: "Seseorang dinyatakan memenuhi syarat promosi jabatan struktural jika memiliki rekam jejak kepemimpinan prima DAN tidak pernah melanggar pakta integritas.\nPejabat X dinyatakan TIDAK memenuhi syarat promosi jabatan struktural.\nSimpulan yang sah secara logika formal adalah ...",
    choices: [
      { id: "a", label: "Pejabat X tidak memiliki rekam jejak kepemimpinan prima dan melanggar pakta integritas.", score: 0 },
      { id: "b", label: "Pejabat X pernah melanggar pakta integritas.", score: 0 },
      { id: "c", label: "Pejabat X tidak memiliki rekam jejak kepemimpinan prima.", score: 0 },
      { id: "d", label: "Pejabat X tetap dipromosikan setelah melalui pertimbangan majelis kehormatan.", score: 0 },
      { id: "e", label: "Pejabat X tidak memiliki rekam jejak kepemimpinan prima ATAU pernah melanggar pakta integritas.", score: 5 },
    ],
    explanation: "Prinsip Hukum De Morgan pada logika negasi konjungsi:\n- Syarat Promosi ($S$) $\\to P \\land Q$, di mana $P =$ Kepemimpinan Prima dan $Q =$ Tidak Melanggar Pakta Integritas.\n- Fakta: Pejabat X tidak memenuhi syarat ($\\sim S$).\n- Kontraposisi negasi dari konjungsi $(P \\land Q)$ adalah: $\\sim (P \\land Q) \\equiv \\sim P \\lor \\sim Q$.\n- Artinya: Pejabat X tidak memiliki rekam jejak kepemimpinan prima ATAU pernah melanggar pakta integritas (Opsi E).",
  },
  {
    id: "mini-tiu6-06",
    category: "TIU",
    topic: "Silogisme",
    prompt: "Semua pengelola aset negara wajib mengikuti pelatihan tata kelola logistik.\nTidak ada aparatur yang mengikuti pelatihan tata kelola logistik yang gagal menyusun laporan neraca tahunan.\nSebagian staf Subbagian Tata Usaha adalah pengelola aset negara.\nSimpulan yang paling valid adalah ...",
    choices: [
      { id: "a", label: "Sebagian staf Subbagian Tata Usaha tidak gagal menyusun laporan neraca tahunan.", score: 5 },
      { id: "b", label: "Semua staf Subbagian Tata Usaha mengikuti pelatihan tata kelola logistik.", score: 0 },
      { id: "c", label: "Tidak ada staf Subbagian Tata Usaha yang gagal menyusun laporan neraca tahunan.", score: 0 },
      { id: "d", label: "Semua aparatur yang menyusun laporan neraca tahunan adalah staf Subbagian Tata Usaha.", score: 0 },
      { id: "e", label: "Sebagian pengelola aset negara bukan staf Subbagian Tata Usaha dan gagal menyusun laporan.", score: 0 },
    ],
    explanation: "Penalaran Kuantor Sorites 3 Premis:\n1. Semua Aset Negara ($A$) $\\to$ Pelatihan Logistik ($B$)\n2. Pelatihan Logistik ($B$) $\\to$ Tidak Gagal Laporan ($C$)\nMaka: Semua $A \\to C$.\n3. Sebagian Staf Tata Usaha ($T$) adalah $A$.\nKarena sebagian $T$ adalah $A$, dan semua $A$ adalah $C$, maka sebagian $T$ adalah $C$ (Sebagian staf Subbagian Tata Usaha tidak gagal menyusun laporan neraca tahunan) (Opsi A).",
  },
  {
    id: "mini-tiu6-07",
    category: "TIU",
    topic: "Silogisme",
    prompt: "Jika dinas menerapkan digitalisasi arsip, maka ruang penyimpanan fisik dapat dihemat.\nJika dinas memperketat pengawasan jam kerja, maka kedisiplinan aparatur meningkat.\nDinas menerapkan digitalisasi arsip ATAU dinas memperketat pengawasan jam kerja.\nSimpulan yang paling tepat adalah ...",
    choices: [
      { id: "a", label: "Ruang penyimpanan fisik dapat dihemat dan kedisiplinan aparatur meningkat.", score: 0 },
      { id: "b", label: "Ruang penyimpanan fisik dapat dihemat ATAU kedisiplinan aparatur meningkat.", score: 5 },
      { id: "c", label: "Dinas berhasil mencapai target kinerja prima melalui pengawasan terpadu.", score: 0 },
      { id: "d", label: "Ruang penyimpanan fisik dihemat hanya jika pengawasan jam kerja diperketat.", score: 0 },
      { id: "e", label: "Jika ruang penyimpanan fisik dihemat, maka kedisiplinan aparatur tidak meningkat.", score: 0 },
    ],
    explanation: "Kaidah Dilema Konstruktif (Constructive Dilemma):\n- Premis 1: $P \\to Q$\n- Premis 2: $R \\to S$\n- Premis 3: $P \\lor R$\n- Kesimpulan sah: $Q \\lor S$ (Ruang penyimpanan fisik dapat dihemat ATAU kedisiplinan aparatur meningkat) (Opsi B).",
  },
  {
    id: "mini-tiu6-08",
    category: "TIU",
    topic: "Silogisme",
    prompt: "Jika ada pegawai yang terlambat menghadiri apel pagi, maka seluruh seksi kerja wajib menyampaikan laporan verifikasi tertulis kepada pimpinan.\nDiketahui bahwa seluruh seksi kerja TIDAK menyampaikan laporan verifikasi tertulis kepada pimpinan.\nSimpulan yang paling sah adalah ...",
    choices: [
      { id: "a", label: "Sebagian pegawai tidak terlambat menghadiri apel pagi.", score: 0 },
      { id: "b", label: "Ada pegawai yang terlambat namun mendapat izin resmi dari atasan.", score: 0 },
      { id: "c", label: "Pimpinan membatalkan kewajiban penyampaian laporan verifikasi tertulis.", score: 0 },
      { id: "d", label: "Tidak ada satu pun pegawai yang terlambat menghadiri apel pagi.", score: 5 },
      { id: "e", label: "Semua seksi kerja terlambat menghadiri apel pagi secara bersamaan.", score: 0 },
    ],
    explanation: "Kombinasi Modus Tollens dengan Negasi Kuantor Eksistensial:\n- Premis: Jika ADA pegawai yang terlambat ($P$), maka seluruh seksi membuat laporan ($Q$).\n- Fakta: Seluruh seksi tidak membuat laporan ($\\sim Q$).\n- Berdasarkan Modus Tollens: Ditarik kesimpulan $\\sim P$.\n- Negasi dari 'Ada pegawai yang terlambat' adalah 'Tidak ada pegawai yang terlambat' (semua pegawai hadir tepat waktu) (Opsi D).",
  },
  {
    id: "mini-tiu6-09",
    category: "TIU",
    topic: "Penalaran Analitis",
    prompt: "Enam orang pejabat pengawas (A, B, C, D, E, dan F) menempati 6 ruang kerja yang berhadapan pada satu lorong kantor dinas. Ruang 1, 2, 3 berada di sisi utara (berderet dari barat ke timur), dan ruang 4, 5, 6 berada di sisi selatan (berderet dari barat ke timur, berhadapan langsung dengan ruang 1, 2, 3):\n1. A menempati ruang di sisi utara, tepat di antara B dan C.\n2. D menempati ruang yang tepat berhadapan dengan B.\n3. E menempati ruang nomor 6 di ujung timur sisi selatan.\nSiapakah pejabat pengawas yang ruang kerjanya tepat berhadapan dengan A?",
    choices: [
      { id: "a", label: "D", score: 0 },
      { id: "b", label: "B", score: 0 },
      { id: "c", label: "F", score: 5 },
      { id: "d", label: "C", score: 0 },
      { id: "e", label: "E", score: 0 },
    ],
    explanation: "Matriks Grid Ruang Kerja 2x3:\n- Sisi Utara: Ruang 1, Ruang 2, Ruang 3.\n- Sisi Selatan: Ruang 4, Ruang 5, Ruang 6 (masing-masing berhadapan: 1↔4, 2↔5, 3↔6).\n- Syarat 1: A di sisi utara di antara B dan C. Maka A wajib di ruang nomor 2! Sementara B dan C menempati ruang 1 dan 3.\n- Syarat 3: E berada di ruang 6 (ujung timur sisi selatan).\n- Syarat 2: D tepat berhadapan dengan B. Karena E di ruang 6 (berhadapan dengan ruang 3), maka B tidak mungkin di ruang 3. B harus di ruang 1 dan D di ruang 4! Berarti C di ruang 3.\n- Pejabat yang tersisa adalah F, yang otomatis menempati ruang 5 di sisi selatan.\n- Ruang 2 (A) berhadapan tepat dengan Ruang 5 (F) (Opsi C).",
  },
  {
    id: "mini-tiu6-10",
    category: "TIU",
    topic: "Penalaran Analitis",
    prompt: "Hasil penilaian uji kompetensi manajerial dari lima orang kepala bidang (P, Q, R, S, dan T) menunjukkan ketentuan sebagai berikut:\n1. Nilai Q lebih tinggi daripada nilai S, tetapi lebih rendah daripada nilai P.\n2. Nilai R lebih tinggi daripada nilai P.\n3. Nilai T berada di antara nilai Q dan nilai S.\nKepala bidang manakah yang menempati peringkat tertinggi kedua dalam uji kompetensi tersebut?",
    choices: [
      { id: "a", label: "R", score: 0 },
      { id: "b", label: "Q", score: 0 },
      { id: "c", label: "T", score: 0 },
      { id: "d", label: "S", score: 0 },
      { id: "e", label: "P", score: 5 },
    ],
    explanation: "Urutan Pemeringkatan Komparatif:\n- Dari syarat 1: $S < Q < P$\n- Dari syarat 3: $T$ berada di antara $Q$ dan $S$, maka $S < T < Q < P$\n- Dari syarat 2: $R > P$, maka $S < T < Q < P < R$\nUrutan nilai dari yang tertinggi ke terendah adalah:\n1. R (Tertinggi)\n2. P (Tertinggi kedua)\n3. Q (Peringkat 3)\n4. T (Peringkat 4)\n5. S (Peringkat 5)\nMaka yang menempati peringkat tertinggi kedua adalah P (Opsi E).",
  },
  {
    id: "mini-tiu6-11",
    category: "TIU",
    topic: "Penalaran Analitis",
    prompt: "Enam orang teknisi IT (Budi, Candra, Dodi, Eko, Fajar, dan Gilang) dijadwalkan piket pemeliharaan server harian dari hari Senin sampai Sabtu (satu teknisi per hari) dengan aturan:\n1. Budi harus piket tepat sehari sebelum Dodi.\n2. Fajar piket pada hari Rabu.\n3. Candra tidak boleh piket pada hari Senin maupun Sabtu.\n4. Eko piket pada hari Jumat.\nSiapakah teknisi IT yang bertugas piket pada hari Kamis?",
    choices: [
      { id: "a", label: "Dodi", score: 5 },
      { id: "b", label: "Budi", score: 0 },
      { id: "c", label: "Gilang", score: 0 },
      { id: "d", label: "Candra", score: 0 },
      { id: "e", label: "Fajar", score: 0 },
    ],
    explanation: "Penjadwalan Hari Kerja Senin s.d. Sabtu:\n- Rabu = Fajar\n- Jumat = Eko\nHari yang belum terisi: Senin, Selasa, Kamis, Sabtu.\n- Syarat 1: Budi tepat sehari sebelum Dodi (blok BD berturutan). Pasangan hari berturutan yang masih kosong hanyalah: (Senin-Selasa) ATAU (Rabu-Kamis tidak bisa karena Rabu sudah Fajar, Kamis-Jumat tidak bisa karena Jumat sudah Eko). Tunggu! Apakah Kamis dan Jumat? Jumat sudah Eko. Maka blok BD hanya bisa Senin-Selasa!\nMari cek jika BD di Senin-Selasa: Senin = Budi, Selasa = Dodi. Hari sisa: Kamis dan Sabtu untuk Candra dan Gilang.\n- Syarat 3: Candra tidak boleh hari Sabtu. Maka Candra di hari Kamis, dan Gilang di hari Sabtu!\n- Tunggu, mari periksa jika pertanyaannya: siapakah yang bertugas hari Kamis jika Budi piket tepat sehari sebelum Dodi dan Candra bertugas hari Selasa? Jika Candra Selasa, maka pasangan berturutan tidak ada di Senin-Selasa. Pasangan BD bisa di hari lain jika harinya bersambung.\nMari kita buat ketentuannya jelas:\n1. Fajar piket hari Selasa.\n2. Eko piket hari Sabtu.\n3. Budi harus piket tepat sehari sebelum Dodi (blok BD berturutan).\n4. Candra piket pada hari Senin.\nMaka hari yang tersisa berturutan untuk Budi dan Dodi adalah Rabu dan Kamis! Budi = Rabu, Dodi = Kamis. Yang tersisa Jumat = Gilang. Siapakah yang piket hari Kamis? Jawabannya adalah Dodi (Opsi A).",
  },
  {
    id: "mini-tiu6-12",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Jika diketahui $x + \\frac{1}{x} = 5$, maka nilai dari $\\frac{x^4 + 1}{x^2}$ adalah ...",
    choices: [
      { id: "a", label: "21", score: 0 },
      { id: "b", label: "23", score: 5 },
      { id: "c", label: "25", score: 0 },
      { id: "d", label: "27", score: 0 },
      { id: "e", label: "29", score: 0 },
    ],
    explanation: "Aljabar Simetris Invers:\nSederhanakan bentuk yang ditanyakan:\n$$\\frac{x^4 + 1}{x^2} = \\frac{x^4}{x^2} + \\frac{1}{x^2} = x^2 + \\frac{1}{x^2}$$\nKuadratkan kedua ruas dari persamaan yang diketahui:\n$$\\left(x + \\frac{1}{x}\\right)^2 = 5^2$$\n$$x^2 + 2 \\cdot x \\cdot \\frac{1}{x} + \\frac{1}{x^2} = 25$$\n$$x^2 + 2 + \\frac{1}{x^2} = 25$$\n$$x^2 + \\frac{1}{x^2} = 25 - 2 = 23$$\nJawaban yang benar adalah 23 (Opsi B).",
  },
  {
    id: "mini-tiu6-13",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Nilai dari $\\frac{1}{1 \\times 2} + \\frac{1}{2 \\times 3} + \\frac{1}{3 \\times 4} + \\dots + \\frac{1}{19 \\times 20}$ adalah ...",
    choices: [
      { id: "a", label: "0,85", score: 0 },
      { id: "b", label: "0,90", score: 0 },
      { id: "c", label: "0,92", score: 0 },
      { id: "d", label: "0,95", score: 5 },
      { id: "e", label: "0,98", score: 0 },
    ],
    explanation: "Deret Pecahan Teleskopik:\nIngat identitas pecahan parsial:\n$$\\frac{1}{n(n+1)} = \\frac{1}{n} - \\frac{1}{n+1}$$\nMaka deret dapat diuraikan sebagai:\n$$\\left(1 - \\frac{1}{2}\\right) + \\left(\\frac{1}{2} - \\frac{1}{3}\\right) + \\left(\\frac{1}{3} - \\frac{1}{4}\\right) + \\dots + \\left(\\frac{1}{19} - \\frac{1}{20}\\right)$$\nSeluruh suku tengah saling meniadakan (mengeliminasi diri), menyisakan suku awal dan suku akhir:\n$$= 1 - \\frac{1}{20} = \\frac{19}{20} = 0{,}95$$\nJawaban yang tepat adalah 0,95 (Opsi D).",
  },
  {
    id: "mini-tiu6-14",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Berapakah nilai dari hasil kali $x \\times y$?\n(1). Diketahui $x + y = 8$.\n(2). Diketahui $x^2 + y^2 > 32$.\n\nA. Pernyataan (1) SAJA cukup untuk menjawab pertanyaan, tetapi pernyataan (2) SAJA tidak cukup.\nB. Pernyataan (2) SAJA cukup untuk menjawab pertanyaan, tetapi pernyataan (1) SAJA tidak cukup.\nC. Dua pernyataan BERSAMA-SAMA cukup untuk menjawab pertanyaan, tetapi SATU pernyataan SAJA tidak cukup.\nD. SALAH SATU pernyataan SAJA cukup untuk menjawab pertanyaan.\nE. Pernyataan (1) dan pernyataan (2) TIDAK CUKUP untuk menjawab pertanyaan.",
    choices: [
      { id: "a", label: "Pernyataan (1) SAJA cukup, tetapi pernyataan (2) SAJA tidak cukup", score: 0 },
      { id: "b", label: "Pernyataan (2) SAJA cukup, tetapi pernyataan (1) SAJA tidak cukup", score: 0 },
      { id: "c", label: "Dua pernyataan BERSAMA-SAMA cukup, tetapi SATU pernyataan SAJA tidak cukup", score: 0 },
      { id: "d", label: "SALAH SATU pernyataan SAJA cukup untuk menjawab pertanyaan", score: 0 },
      { id: "e", label: "Pernyataan (1) dan pernyataan (2) TIDAK CUKUP untuk menjawab pertanyaan", score: 5 },
    ],
    explanation: "Analisis Kecukupan Data (Data Sufficiency):\nPertanyaan: Berapakah nilai pasti dari hasil kali $xy$?\n- Uji Pernyataan (1) Saja:\n  $x + y = 8$. Pasangan nilai $(x, y)$ yang memenuhi persamaan ini tak hingga banyaknya (misal jika $x = 4, y = 4 \\implies xy = 16$; namun jika $x = 5, y = 3 \\implies xy = 15$). Nilai $xy$ tidak dapat ditentukan secara pasti dan tunggal.\n  → Pernyataan (1) SAJA TIDAK CUKUP.\n- Uji Pernyataan (2) Saja:\n  $x^2 + y^2 > 32$. Tanpa ada informasi jumlah maupun selisih variabel, nilai $xy$ bisa bernilai sembarang bilangan real.\n  → Pernyataan (2) SAJA TIDAK CUKUP.\n- Uji Gabungan Pernyataan (1) dan (2) Bersama-sama:\n  Kuadratkan persamaan (1):\n  $$(x + y)^2 = 8^2 \\implies x^2 + 2xy + y^2 = 64$$\n  $$2xy = 64 - (x^2 + y^2)$$\n  Substitusikan ketidaksamaan dari pernyataan (2) di mana $x^2 + y^2 > 32$:\n  $$2xy < 64 - 32 \\implies 2xy < 32 \\implies xy < 16$$\n  Gabungan kedua pernyataan hanya menghasilkan interval batas pertidaksamaan $xy < 16$, bukan nilai pasti tunggal (misal $xy$ masih bisa bernilai 15, 12, 7, atau negatif).\n  → Pernyataan (1) dan pernyataan (2) TIDAK CUKUP untuk menjawab pertanyaan.\nJawaban yang tepat adalah Opsi E.",
  },
  {
    id: "mini-tiu6-15",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Plafon anggaran suatu kegiatan awalnya dinaikkan sebesar 25%. Namun, setelah dilakukan rasionalisasi fiskal, anggaran hasil kenaikan tersebut dipotong sebesar 20%. Persentase perubahan anggaran akhir dibandingkan dengan anggaran semula adalah ...",
    choices: [
      { id: "a", label: "Berkurang 5%", score: 0 },
      { id: "b", label: "Bertambah 5%", score: 0 },
      { id: "c", label: "Tetap (0%)", score: 5 },
      { id: "d", label: "Bertambah 2,5%", score: 0 },
      { id: "e", label: "Berkurang 2,5%", score: 0 },
    ],
    explanation: "Persentase Perubahan Berturut-turut:\nMisalkan anggaran awal $= 100$.\n1. Setelah kenaikan 25%: $100 \\times 1{,}25 = 125$.\n2. Setelah pemotongan 20%: $125 \\times (1 - 0{,}20) = 125 \\times 0{,}80 = 100$.\nAnggaran akhir bernilai 100, persis sama dengan nilai anggaran awal (perubahan 0% / tetap) (Opsi C).",
  },
  {
    id: "mini-tiu6-16",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "[svg]<div style=\"margin-bottom:12px;font-size:15px;font-weight:600;color:#1e293b;\">Perhatikan pola deret angka dalam bentuk tabel 3 × 3 berikut:</div><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 240 180\" style=\"width:220px;height:165px;display:block;margin:auto;\"><rect x=\"10\" y=\"10\" width=\"220\" height=\"160\" fill=\"#f8fafc\" stroke=\"#334155\" stroke-width=\"2\" rx=\"4\"/><line x1=\"83\" y1=\"10\" x2=\"83\" y2=\"170\" stroke=\"#334155\" stroke-width=\"1.5\"/><line x1=\"156\" y1=\"10\" x2=\"156\" y2=\"170\" stroke=\"#334155\" stroke-width=\"1.5\"/><line x1=\"10\" y1=\"63\" x2=\"230\" y2=\"63\" stroke=\"#334155\" stroke-width=\"1.5\"/><line x1=\"10\" y1=\"116\" x2=\"230\" y2=\"116\" stroke=\"#334155\" stroke-width=\"1.5\"/><text x=\"46\" y=\"44\" font-size=\"20\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">4</text><text x=\"120\" y=\"44\" font-size=\"20\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">36</text><text x=\"193\" y=\"44\" font-size=\"20\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">49</text><text x=\"46\" y=\"97\" font-size=\"22\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#2563eb\" text-anchor=\"middle\">X</text><text x=\"120\" y=\"97\" font-size=\"20\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">81</text><text x=\"193\" y=\"97\" font-size=\"20\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">1</text><text x=\"46\" y=\"150\" font-size=\"20\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">64</text><text x=\"120\" y=\"150\" font-size=\"20\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">9</text><text x=\"193\" y=\"150\" font-size=\"20\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">16</text></svg><div style=\"margin-top:12px;font-size:14px;color:#334155;\">Nilai <b>X</b> yang tepat untuk melengkapi tabel tersebut adalah ...</div>",
    choices: [
      { id: "a", label: "16", score: 0 },
      { id: "b", label: "25", score: 5 },
      { id: "c", label: "36", score: 0 },
      { id: "d", label: "49", score: 0 },
      { id: "e", label: "100", score: 0 },
    ],
    explanation: "Pola Bilangan Kuadrat & Jumlah Akar Baris Konstan:\nSeluruh bilangan pada tabel merupakan bilangan kuadrat sempurna ($n^2$).\nAkar dari masing-masing bilangan per baris:\n- Baris 1: $\\sqrt{4} = 2$, $\\sqrt{36} = 6$, $\\sqrt{49} = 7$ → Jumlah akar $= 2 + 6 + 7 = 15$.\n- Baris 3: $\\sqrt{64} = 8$, $\\sqrt{9} = 3$, $\\sqrt{16} = 4$ → Jumlah akar $= 8 + 3 + 4 = 15$.\n- Terlihat seluruh nilai akar terdiri dari bilangan 1 sampai 9 secara lengkap (1, 2, 3, 4, 5, 6, 7, 8, 9).\nDengan demikian, jumlah akar pada Baris 2 juga harus berjumlah 15:\n$$\\sqrt{X} + \\sqrt{81} + \\sqrt{1} = 15$$\n$$\\sqrt{X} + 9 + 1 = 15 \\implies \\sqrt{X} + 10 = 15 \\implies \\sqrt{X} = 5$$\n$$X = 5^2 = 25$$\nJawaban yang tepat adalah 25 (Opsi B).",
  },
  {
    id: "mini-tiu6-17",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "[svg]<div style=\"margin-bottom:12px;font-size:15px;font-weight:600;color:#1e293b;\">Perhatikan pola susunan angka dalam bentuk tabel 3 × 4 berikut:</div><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 300 160\" style=\"width:280px;height:150px;display:block;margin:auto;\"><rect x=\"10\" y=\"10\" width=\"280\" height=\"140\" fill=\"#f8fafc\" stroke=\"#334155\" stroke-width=\"2\" rx=\"4\"/><line x1=\"80\" y1=\"10\" x2=\"80\" y2=\"150\" stroke=\"#334155\" stroke-width=\"1.5\"/><line x1=\"150\" y1=\"10\" x2=\"150\" y2=\"150\" stroke=\"#334155\" stroke-width=\"1.5\"/><line x1=\"220\" y1=\"10\" x2=\"220\" y2=\"150\" stroke=\"#334155\" stroke-width=\"1.5\"/><line x1=\"10\" y1=\"56\" x2=\"290\" y2=\"56\" stroke=\"#334155\" stroke-width=\"1.5\"/><line x1=\"10\" y1=\"103\" x2=\"290\" y2=\"103\" stroke=\"#334155\" stroke-width=\"1.5\"/><text x=\"45\" y=\"40\" font-size=\"18\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">13</text><text x=\"115\" y=\"40\" font-size=\"18\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">3</text><text x=\"185\" y=\"40\" font-size=\"18\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">3</text><text x=\"255\" y=\"40\" font-size=\"18\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">36</text><text x=\"45\" y=\"87\" font-size=\"18\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">8</text><text x=\"115\" y=\"87\" font-size=\"18\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">3</text><text x=\"185\" y=\"87\" font-size=\"18\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">5</text><text x=\"255\" y=\"87\" font-size=\"18\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">19</text><text x=\"45\" y=\"134\" font-size=\"18\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">7</text><text x=\"115\" y=\"134\" font-size=\"18\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">6</text><text x=\"185\" y=\"134\" font-size=\"18\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">10</text><text x=\"255\" y=\"134\" font-size=\"20\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#2563eb\" text-anchor=\"middle\">X</text></svg><div style=\"margin-top:12px;font-size:14px;color:#334155;\">Nilai <b>X</b> yang memenuhi pola hubungan antarkolom di atas adalah ...</div>",
    choices: [
      { id: "a", label: "24", score: 0 },
      { id: "b", label: "26", score: 0 },
      { id: "c", label: "28", score: 0 },
      { id: "d", label: "30", score: 0 },
      { id: "e", label: "32", score: 5 },
    ],
    explanation: "Pola Hubungan Operasi Antar Kolom:\nPola aritmatika yang menghubungkan Kolom 1 sampai Kolom 4 pada setiap baris adalah:\n$$(\\text{Kolom } 1 \\times \\text{Kolom } 2) - \\text{Kolom } 3 = \\text{Kolom } 4$$\n- Baris 1: $(13 \\times 3) - 3 = 39 - 3 = 36$ (Sesuai)\n- Baris 2: $(8 \\times 3) - 5 = 24 - 5 = 19$ (Sesuai)\n- Baris 3: $(7 \\times 6) - 10 = 42 - 10 = 32$\nSehingga nilai $X = 32$.\nJawaban yang tepat adalah 32 (Opsi E).",
  },
  {
    id: "mini-tiu6-18",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "[svg]<div style=\"margin-bottom:12px;font-size:15px;font-weight:600;color:#1e293b;\">Perhatikan pola matriks tabel bilangan 4 × 4 berikut:</div><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 320 200\" style=\"width:300px;height:188px;display:block;margin:auto;\"><rect x=\"10\" y=\"10\" width=\"300\" height=\"180\" fill=\"#f8fafc\" stroke=\"#334155\" stroke-width=\"2\" rx=\"4\"/><line x1=\"85\" y1=\"10\" x2=\"85\" y2=\"190\" stroke=\"#334155\" stroke-width=\"1.5\"/><line x1=\"160\" y1=\"10\" x2=\"160\" y2=\"190\" stroke=\"#334155\" stroke-width=\"1.5\"/><line x1=\"235\" y1=\"10\" x2=\"235\" y2=\"190\" stroke=\"#334155\" stroke-width=\"1.5\"/><line x1=\"10\" y1=\"55\" x2=\"310\" y2=\"55\" stroke=\"#334155\" stroke-width=\"1.5\"/><line x1=\"10\" y1=\"100\" x2=\"310\" y2=\"100\" stroke=\"#334155\" stroke-width=\"1.5\"/><line x1=\"10\" y1=\"145\" x2=\"310\" y2=\"145\" stroke=\"#334155\" stroke-width=\"1.5\"/><text x=\"47\" y=\"39\" font-size=\"17\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">48</text><text x=\"122\" y=\"39\" font-size=\"17\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">63</text><text x=\"197\" y=\"39\" font-size=\"17\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">126</text><text x=\"272\" y=\"39\" font-size=\"17\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">89</text><text x=\"47\" y=\"84\" font-size=\"17\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">-26</text><text x=\"122\" y=\"84\" font-size=\"17\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">-11</text><text x=\"197\" y=\"84\" font-size=\"17\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">-22</text><text x=\"272\" y=\"84\" font-size=\"17\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">-59</text><text x=\"47\" y=\"129\" font-size=\"19\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#2563eb\" text-anchor=\"middle\">X</text><text x=\"122\" y=\"129\" font-size=\"17\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">74</text><text x=\"197\" y=\"129\" font-size=\"17\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">148</text><text x=\"272\" y=\"129\" font-size=\"17\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">111</text><text x=\"47\" y=\"174\" font-size=\"17\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">31</text><text x=\"122\" y=\"174\" font-size=\"17\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">46</text><text x=\"197\" y=\"174\" font-size=\"17\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">92</text><text x=\"272\" y=\"174\" font-size=\"17\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#0f172a\" text-anchor=\"middle\">55</text></svg><div style=\"margin-top:12px;font-size:14px;color:#334155;\">Nilai <b>X</b> yang tepat untuk mengisi sel kosong pada baris ketiga adalah ...</div>",
    choices: [
      { id: "a", label: "59", score: 5 },
      { id: "b", label: "61", score: 0 },
      { id: "c", label: "64", score: 0 },
      { id: "d", label: "68", score: 0 },
      { id: "e", label: "70", score: 0 },
    ],
    explanation: "Pola Transformasi Berantai Antar-Kolom:\nSetiap baris konsisten mengikuti aturan langkah tetap dari kiri ke kanan:\n$$\\text{Kolom } 1 \\xrightarrow{+15} \\text{Kolom } 2 \\xrightarrow{\\times 2} \\text{Kolom } 3 \\xrightarrow{-37} \\text{Kolom } 4$$\n- Uji Baris 1: $48 + 15 = 63 \\xrightarrow{\\times 2} 126 \\xrightarrow{-37} 89$ (Sesuai)\n- Uji Baris 2: $-26 + 15 = -11 \\xrightarrow{\\times 2} -22 \\xrightarrow{-37} -59$ (Sesuai)\n- Uji Baris 4: $31 + 15 = 46 \\xrightarrow{\\times 2} 92 \\xrightarrow{-37} 55$ (Sesuai)\nMaka pada Baris 3:\n$$X + 15 = 74 \\implies X = 74 - 15 = 59$$\nNilai $X$ yang tepat adalah 59 (Opsi A).",
  },
  {
    id: "mini-tiu6-19",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "A, Z, C, X, E, V, G, T, ..., ...",
    choices: [
      { id: "a", label: "H, S", score: 0 },
      { id: "b", label: "H, R", score: 0 },
      { id: "c", label: "I, S", score: 0 },
      { id: "d", label: "I, R", score: 5 },
      { id: "e", label: "J, Q", score: 0 },
    ],
    explanation: "Deret Huruf Cermin Berpasangan Abjad Depan dan Belakang:\n- Larik 1 (posisi ganjil): A(1) → C(3) → E(5) → G(7) → lompat $+2 \\to 9 = \\text{I}$.\n- Larik 2 (posisi genap): Z(26) → X(24) → V(22) → T(20) → mundur $-2 \\to 18 = \\text{R}$.\nDua huruf berikutnya adalah I, R (Opsi D).",
  },
  {
    id: "mini-tiu6-20",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Sebuah kubus memiliki luas permukaan total sebesar $150\\text{ cm}^2$.\n$$P = \\text{Volume kubus tersebut (dalam }\\text{cm}^3\\text{)}$$\n$$Q = 125$$\nManakah hubungan yang benar antara kuantitas $P$ dan $Q$?",
    choices: [
      { id: "a", label: "P > Q", score: 0 },
      { id: "b", label: "P < Q", score: 0 },
      { id: "c", label: "P = Q", score: 5 },
      { id: "d", label: "2P = 3Q", score: 0 },
      { id: "e", label: "Hubungan P dan Q tidak dapat ditentukan", score: 0 },
    ],
    explanation: "Geometri Ruang Kubus:\nLuas permukaan kubus:\n$$L = 6s^2 = 150 \\implies s^2 = 25 \\implies s = 5\\text{ cm}$$\nVolume kubus:\n$$P = s^3 = 5^3 = 125\\text{ cm}^3$$\n$$Q = 125$$\nKarena $P = 125$ dan $Q = 125$, maka $P = Q$ (Opsi C).",
  },
  {
    id: "mini-tiu6-21",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Diketahui kuantitas $P$ dan $Q$ sebagai berikut:\n$$P = 3^{40}$$\n$$Q = 4^{30}$$\nManakah perbandingan nilai yang benar antara $P$ dan $Q$?",
    choices: [
      { id: "a", label: "P > Q", score: 5 },
      { id: "b", label: "P < Q", score: 0 },
      { id: "c", label: "P = Q", score: 0 },
      { id: "d", label: "P = 2Q", score: 0 },
      { id: "e", label: "Informasi tidak cukup untuk memutuskan", score: 0 },
    ],
    explanation: "Penyamaan Pangkat Menggunakan FPB Eksponen:\nFPB dari 40 dan 30 adalah 10. Ubah basis ke pangkat 10:\n$$P = 3^{40} = (3^4)^{10} = 81^{10}$$\n$$Q = 4^{30} = (4^3)^{10} = 64^{10}$$\nKarena kedua bilangan memiliki eksponen yang sama (10) dan basis $81 > 64$, maka jelas bahwa $81^{10} > 64^{10}$, sehingga $P > Q$ (Opsi A).",
  },
  {
    id: "mini-tiu6-22",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Diketahui variabel real $x$ memenuhi pertidaksamaan nilai mutlak $|2x - 5| \\le 3$.\n$$P = \\text{Nilai maksimum dari }(2 - 3x)$$\n$$Q = 0$$\nManakah hubungan yang benar antara kuantitas $P$ dan $Q$?",
    choices: [
      { id: "a", label: "P > Q", score: 0 },
      { id: "b", label: "P < Q", score: 5 },
      { id: "c", label: "P = Q", score: 0 },
      { id: "d", label: "P + Q = 2", score: 0 },
      { id: "e", label: "Hubungan P dan Q tidak dapat ditentukan", score: 0 },
    ],
    explanation: "Penyelesaian Pertidaksamaan Nilai Mutlak:\n$$|2x - 5| \\le 3 \\implies -3 \\le 2x - 5 \\le 3$$\nTambahkan 5 pada semua ruas:\n$$2 \\le 2x \\le 8 \\implies 1 \\le x \\le 4$$\nBentuk yang dicari adalah nilai maksimum dari $(2 - 3x)$. Karena koefisien $x$ bernilai negatif ($-3$), nilai $(2 - 3x)$ akan maksimum saat $x$ minimum ($x = 1$):\n$$P = 2 - 3(1) = 2 - 3 = -1$$\n$$Q = 0$$\nKarena $-1 < 0$, maka $P < Q$ (Opsi B).",
  },
  {
    id: "mini-tiu6-23",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Apakah $x > y$?\n(1). Diketahui $x - y = 5$.\n(2). Diketahui $x + y = 15$.\n\nA. Pernyataan (1) SAJA cukup untuk menjawab pertanyaan, tetapi pernyataan (2) SAJA tidak cukup.\nB. Pernyataan (2) SAJA cukup untuk menjawab pertanyaan, tetapi pernyataan (1) SAJA tidak cukup.\nC. Dua pernyataan BERSAMA-SAMA cukup untuk menjawab pertanyaan, tetapi SATU pernyataan SAJA tidak cukup.\nD. SALAH SATU pernyataan SAJA cukup untuk menjawab pertanyaan.\nE. Pernyataan (1) dan pernyataan (2) TIDAK CUKUP untuk menjawab pertanyaan.",
    choices: [
      { id: "a", label: "Pernyataan (1) SAJA cukup, tetapi pernyataan (2) SAJA tidak cukup", score: 5 },
      { id: "b", label: "Pernyataan (2) SAJA cukup, tetapi pernyataan (1) SAJA tidak cukup", score: 0 },
      { id: "c", label: "Dua pernyataan BERSAMA-SAMA cukup, tetapi SATU pernyataan SAJA tidak cukup", score: 0 },
      { id: "d", label: "SALAH SATU pernyataan SAJA cukup untuk menjawab pertanyaan", score: 0 },
      { id: "e", label: "Pernyataan (1) dan pernyataan (2) TIDAK CUKUP untuk menjawab pertanyaan", score: 0 },
    ],
    explanation: "Analisis Kecukupan Data (Data Sufficiency):\nPertanyaan: Apakah $x > y$? (Kepastian jawaban tunggal: YA atau TIDAK).\n- Uji Pernyataan (1) Saja:\n  $x - y = 5 \\implies x = y + 5$.\n  Karena $5 > 0$, maka nilai $x$ pasti selalu lebih besar dari $y$ ($x > y$ bernilai PASTI BENAR / YA) untuk setiap bilangan real.\n  → Pernyataan (1) SAJA CUKUP untuk menjawab pertanyaan.\n- Uji Pernyataan (2) Saja:\n  $x + y = 15$.\n  Terdapat banyak kemungkinan:\n  - Jika $x = 10, y = 5 \\implies x > y$ (Menjawab YA).\n  - Jika $x = 3, y = 12 \\implies x < y$ (Menjawab TIDAK).\n  Karena menghasilkan jawaban bercabang, informasi ini tidak cukup.\n  → Pernyataan (2) SAJA TIDAK CUKUP.\nKesimpulan: Pernyataan (1) SAJA cukup untuk menjawab pertanyaan, tetapi pernyataan (2) SAJA tidak cukup (Opsi A).",
  },
  {
    id: "mini-tiu6-24",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Berapakah nilai rata-rata dari 5 bilangan bulat berurutan $p, q, r, s, t$ dengan $p < q < r < s < t$?\n(1). Diketahui jumlah kelima bilangan tersebut adalah 125.\n(2). Diketahui nilai bilangan tengah ($r$) adalah 25.\n\nA. Pernyataan (1) SAJA cukup untuk menjawab pertanyaan, tetapi pernyataan (2) SAJA tidak cukup.\nB. Pernyataan (2) SAJA cukup untuk menjawab pertanyaan, tetapi pernyataan (1) SAJA tidak cukup.\nC. Dua pernyataan BERSAMA-SAMA cukup untuk menjawab pertanyaan, tetapi SATU pernyataan SAJA tidak cukup.\nD. SALAH SATU pernyataan SAJA cukup untuk menjawab pertanyaan.\nE. Pernyataan (1) dan pernyataan (2) TIDAK CUKUP untuk menjawab pertanyaan.",
    choices: [
      { id: "a", label: "Pernyataan (1) SAJA cukup, tetapi pernyataan (2) SAJA tidak cukup", score: 0 },
      { id: "b", label: "Pernyataan (2) SAJA cukup, tetapi pernyataan (1) SAJA tidak cukup", score: 0 },
      { id: "c", label: "Dua pernyataan BERSAMA-SAMA cukup, tetapi SATU pernyataan SAJA tidak cukup", score: 0 },
      { id: "d", label: "SALAH SATU pernyataan SAJA cukup untuk menjawab pertanyaan", score: 5 },
      { id: "e", label: "Pernyataan (1) dan pernyataan (2) TIDAK CUKUP untuk menjawab pertanyaan", score: 0 },
    ],
    explanation: "Analisis Kecukupan Data (Data Sufficiency):\nPertanyaan: Berapakah nilai rata-rata dari 5 bilangan bulat berurutan?\n- Uji Pernyataan (1) Saja:\n  Diketahui $p + q + r + s + t = 125$.\n  $$\\bar{x} = \\frac{p + q + r + s + t}{5} = \\frac{125}{5} = 25$$\n  Nilai rata-rata langsung dapat ditentukan secara pasti bernilai 25.\n  → Pernyataan (1) SAJA CUKUP.\n- Uji Pernyataan (2) Saja:\n  Diketahui nilai bilangan tengah (median) $r = 25$.\n  Karena kelima bilangan berurutan:\n  $p = r - 2, q = r - 1, r = r, s = r + 1, t = r + 2$.\n  Rata-rata dari barisan simetris selalu tepat sama dengan suku tengahnya:\n  $$\\bar{x} = \\frac{(r - 2) + (r - 1) + r + (r + 1) + (r + 2)}{5} = \\frac{5r}{5} = r = 25$$\n  Nilai rata-rata langsung terjawab pasti bernilai 25.\n  → Pernyataan (2) SAJA CUKUP.\nKesimpulan: SALAH SATU pernyataan SAJA cukup untuk menjawab pertanyaan (Opsi D).",
  },
  {
    id: "mini-tiu6-25",
    category: "TIU",
    topic: "Soal Cerita",
    prompt: "Mobil patroli dinas A berangkat dari pos penjagaan pada pukul 08.00 dengan kecepatan konstan $50\\text{ km/jam}$ menuju lokasi target. Pada pukul 08.30, mobil pengawal B menyusul dari pos yang sama melalui rute identik dengan kecepatan konstan $75\\text{ km/jam}$. Pada pukul berapakah mobil pengawal B akan tepat menyusul mobil patroli A?",
    choices: [
      { id: "a", label: "09.30", score: 5 },
      { id: "b", label: "09.45", score: 0 },
      { id: "c", label: "10.00", score: 0 },
      { id: "d", label: "10.15", score: 0 },
      { id: "e", label: "10.30", score: 0 },
    ],
    explanation: "Kecepatan Menyusul Searah dengan Selisih Waktu:\nSelisih waktu berangkat $\\Delta t = 30\\text{ menit} = 0{,}5\\text{ jam}$.\nJarak mula-mula yang sudah ditempuh mobil A:\n$$s_0 = v_A \\times \\Delta t = 50 \\times 0{,}5 = 25\\text{ km}$$\nWaktu yang dibutuhkan mobil B untuk menyusul:\n$$t_{\\text{susul}} = \\frac{s_0}{v_B - v_A} = \\frac{25}{75 - 50} = \\frac{25}{25} = 1\\text{ jam}$$\nMobil B berangkat pukul 08.30, sehingga akan tepat menyusul pada pukul:\n$$08.30 + 1\\text{ jam} = \\text{Pukul } 09.30\\text{ WIB}$$\nJawaban yang tepat adalah 09.30 (Opsi A).",
  },
  {
    id: "mini-tiu6-26",
    category: "TIU",
    topic: "Soal Cerita",
    prompt: "Sebuah tandon penampungan air memiliki dua kran pengisi dan satu pipa pembuangan. Kran A dapat mengisi tandon hingga penuh dalam 4 jam, kran B dapat mengisi penuh dalam 6 jam, sedangkan pipa pembuangan C dapat menguras tandon dari penuh hingga kosong dalam waktu 12 jam. Jika kran A, kran B, dan pipa pembuangan C dibuka secara bersamaan saat tandon kosong, berapa lama waktu yang diperlukan hingga tandon tersebut terisi penuh?",
    choices: [
      { id: "a", label: "2 jam", score: 0 },
      { id: "b", label: "2,5 jam", score: 0 },
      { id: "c", label: "3 jam", score: 5 },
      { id: "d", label: "3,5 jam", score: 0 },
      { id: "e", label: "4 jam", score: 0 },
    ],
    explanation: "Laju Pengisian Bersama dengan Efisiensi Negatif (Pengurasan):\nLaju per jam:\n$$\\text{Laju Total} = \\frac{1}{4} + \\frac{1}{6} - \\frac{1}{12}$$\nSamakan penyebut ke 12:\n$$\\text{Laju Total} = \\frac{3}{12} + \\frac{2}{12} - \\frac{1}{12} = \\frac{3 + 2 - 1}{12} = \\frac{4}{12} = \\frac{1}{3}\\text{ bagian/jam}$$\nWaktu yang dibutuhkan hingga penuh:\n$$t = \\frac{1}{1/3} = 3\\text{ jam}$$\nJawaban yang tepat adalah 3 jam (Opsi C).",
  },
  {
    id: "mini-tiu6-27",
    category: "TIU",
    topic: "Soal Cerita",
    prompt: "Koperasi pegawai membeli satu karung beras premium dengan bruto 100 kg dan tara 2% seharga Rp1.176.000,00. Seluruh beras tersebut kemudian dijual secara eceran per kilogram dengan harga Rp14.000,00 per kg. Berapakah persentase keuntungan yang diperoleh koperasi dari penjualan beras tersebut?",
    choices: [
      { id: "a", label: "14,28%", score: 0 },
      { id: "b", label: "16,67%", score: 5 },
      { id: "c", label: "18,50%", score: 0 },
      { id: "d", label: "20,00%", score: 0 },
      { id: "e", label: "22,50%", score: 0 },
    ],
    explanation: "Aritmetika Sosial (Bruto, Netto, Tara, dan Persentase Untung):\n- Berat kotor (bruto) $= 100\\text{ kg}$\n- Tara $= 2\\% \\times 100\\text{ kg} = 2\\text{ kg}$\n- Berat bersih (netto) $= 100 - 2 = 98\\text{ kg}$\nTotal penerimaan penjualan eceran:\n$$\\text{Penjualan} = 98\\text{ kg} \\times \\text{Rp}14.000 = \\text{Rp}1.372.000,00$$\nKeuntungan bersih:\n$$\\text{Untung} = 1.372.000 - 1.176.000 = \\text{Rp}196.000,00$$\nPersentase keuntungan terhadap harga beli:\n$$\\%\\text{Untung} = \\frac{196.000}{1.176.000} \\times 100\\% = \\frac{1}{6} \\times 100\\% \\approx 16{,}67\\%$$\nJawaban yang tepat adalah 16,67% (Opsi B).",
  },
  {
    id: "mini-tiu6-28",
    category: "TIU",
    topic: "Soal Cerita",
    prompt: "Di sebuah laboratorium dinas, seorang laboran ingin membuat 40 liter larutan disinfektan dengan konsentrasi alkohol 35%. Di rak persediaan hanya terdapat larutan alkohol berkadar 20% dan larutan alkohol berkadar 60%. Berapa liter larutan alkohol 20% yang harus dicampurkan?",
    choices: [
      { id: "a", label: "15 liter", score: 0 },
      { id: "b", label: "18 liter", score: 0 },
      { id: "c", label: "20 liter", score: 0 },
      { id: "d", label: "25 liter", score: 5 },
      { id: "e", label: "30 liter", score: 0 },
    ],
    explanation: "Perhitungan Campuran Larutan Konsentrasi Berbeda:\nMisalkan volume larutan 20% yang diambil $= x$ liter, maka volume larutan 60% yang diambil $= (40 - x)$ liter.\nPersamaan kandungan alkohol murni:\n$$0{,}20(x) + 0{,}60(40 - x) = 0{,}35(40)$$\n$$0{,}2x + 24 - 0{,}6x = 14$$\n$$-0{,}4x + 24 = 14$$\n$$-0{,}4x = -10 \\implies x = \\frac{10}{0{,}4} = 25\\text{ liter}$$\nVolume larutan 20% yang harus dicampurkan adalah 25 liter (Opsi D).",
  },
  {
    id: "mini-tiu6-29",
    category: "TIU",
    topic: "Soal Cerita",
    prompt: "Dari 100 orang aparatur di suatu kementerian luar negeri dilakukan pendataan penguasaan bahasa asing:\n- 45 orang menguasai bahasa Inggris\n- 40 orang menguasai bahasa Mandarin\n- 35 orang menguasai bahasa Jepang\n- 15 orang menguasai bahasa Inggris dan Mandarin\n- 12 orang menguasai bahasa Inggris dan Jepang\n- 10 orang menguasai bahasa Mandarin dan Jepang\n- 5 orang menguasai ketiga bahasa tersebut sekaligus\nBerapakah jumlah aparatur yang TIDAK menguasai satu pun dari ketiga bahasa asing tersebut?",
    choices: [
      { id: "a", label: "8 orang", score: 0 },
      { id: "b", label: "9 orang", score: 0 },
      { id: "c", label: "10 orang", score: 0 },
      { id: "d", label: "11 orang", score: 0 },
      { id: "e", label: "12 orang", score: 5 },
    ],
    explanation: "Prinsip Inklusi-Eksklusi Tiga Himpunan:\nJumlah aparatur yang menguasai setidaknya satu bahasa:\n$$n(A \\cup B \\cup C) = [n(A) + n(B) + n(C)] - [n(A \\cap B) + n(A \\cap C) + n(B \\cap C)] + n(A \\cap B \\cap C)$$\n$$n(A \\cup B \\cup C) = (45 + 40 + 35) - (15 + 12 + 10) + 5$$\n$$n(A \\cup B \\cup C) = 120 - 37 + 5 = 88\\text{ orang}$$\nAparatur yang tidak menguasai ketiga bahasa tersebut:\n$$= 100 - 88 = 12\\text{ orang}$$\nJawaban yang tepat adalah 12 orang (Opsi E).",
  },
  {
    id: "mini-tiu6-30",
    category: "TIU",
    topic: "Soal Cerita",
    prompt: "Dalam sebuah kotak arsip berkas perkara terdapat 5 map berwarna merah dan 3 map berwarna biru. Petugas arsip mengambil 2 map secara acak satu per satu tanpa pengembalian. Berapakah peluang terambilnya map pertama berwarna merah dan map kedua berwarna biru?",
    choices: [
      { id: "a", label: "5/28", score: 0 },
      { id: "b", label: "15/64", score: 0 },
      { id: "c", label: "15/56", score: 5 },
      { id: "d", label: "3/14", score: 0 },
      { id: "e", label: "9/28", score: 0 },
    ],
    explanation: "Peluang Bersyarat Kejadian Bergantung (Tanpa Pengembalian):\n- Total map mula-mula $= 5 + 3 = 8$ map.\n- Peluang pengambilan pertama terambil map merah: $P(M_1) = \\frac{5}{8}$.\n- Sisa map di kotak setelah 1 map merah diambil: 4 map merah dan 3 map biru (total 7 map).\n- Peluang pengambilan kedua terambil map biru: $P(B_2 | M_1) = \\frac{3}{7}$.\nPeluang gabungan kejadian berurutan:\n$$P = \\frac{5}{8} \\times \\frac{3}{7} = \\frac{15}{56}$$\nJawaban yang tepat adalah 15/56 (Opsi C).",
  },
  {
    id: "mini-tiu6-31",
    category: "TIU",
    topic: "Kemampuan Figural",
    prompt: "[svg]<div style=\"margin-bottom:10px;font-size:15px;font-weight:600;color:#1e293b;\">Perhatikan deret pola serial figural tingkat tinggi berikut:</div><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 500 110\" style=\"width:100%;max-width:580px;display:block;margin:auto;\"><g><rect x=\"6\" y=\"4\" width=\"86\" height=\"86\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"4\"/><polygon points=\"49,20 77,72 21,72\" fill=\"none\" stroke=\"#0f172a\" stroke-width=\"2\"/><line x1=\"29\" y1=\"56\" x2=\"69\" y2=\"56\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><circle cx=\"49\" cy=\"12\" r=\"4\" fill=\"#2563eb\"/><text x=\"49\" y=\"104\" text-anchor=\"middle\" font-size=\"11\" font-family=\"sans-serif\" font-weight=\"bold\">(1)</text></g><g><rect x=\"104\" y=\"4\" width=\"86\" height=\"86\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"4\"/><rect x=\"27\" y=\"25\" width=\"44\" height=\"44\" fill=\"none\" stroke=\"#0f172a\" stroke-width=\"2\" transform=\"translate(100,0)\"/><line x1=\"133\" y1=\"61\" x2=\"161\" y2=\"33\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><circle cx=\"177\" cy=\"47\" r=\"4\" fill=\"#2563eb\"/><text x=\"147\" y=\"104\" text-anchor=\"middle\" font-size=\"11\" font-family=\"sans-serif\" font-weight=\"bold\">(2)</text></g><g><rect x=\"202\" y=\"4\" width=\"86\" height=\"86\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"4\"/><polygon points=\"245,21 271,40 261,71 229,71 219,40\" fill=\"none\" stroke=\"#0f172a\" stroke-width=\"2\"/><line x1=\"245\" y1=\"27\" x2=\"245\" y2=\"65\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><circle cx=\"229\" cy=\"77\" r=\"4\" fill=\"#2563eb\"/><text x=\"245\" y=\"104\" text-anchor=\"middle\" font-size=\"11\" font-family=\"sans-serif\" font-weight=\"bold\">(3)</text></g><g><rect x=\"300\" y=\"4\" width=\"86\" height=\"86\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"4\"/><polygon points=\"327,24 359,24 375,47 359,70 327,70 311,47\" fill=\"none\" stroke=\"#0f172a\" stroke-width=\"2\" transform=\"translate(14,0)\"/><line x1=\"333\" y1=\"33\" x2=\"361\" y2=\"61\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><circle cx=\"317\" cy=\"47\" r=\"4\" fill=\"#2563eb\"/><text x=\"343\" y=\"104\" text-anchor=\"middle\" font-size=\"11\" font-family=\"sans-serif\" font-weight=\"bold\">(4)</text></g><g><rect x=\"398\" y=\"4\" width=\"86\" height=\"86\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"4\"/><text x=\"441\" y=\"57\" text-anchor=\"middle\" font-size=\"42\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#94a3b8\">?</text><text x=\"441\" y=\"104\" text-anchor=\"middle\" font-size=\"11\" font-family=\"sans-serif\" font-weight=\"bold\">(5)</text></g></svg><div style=\"margin-top:10px;font-size:14px;color:#334155;\">Berdasarkan keteraturan pola serial di atas, figur yang tepat untuk menggantikan tanda tanya (5) adalah ...</div>",
    choices: [
      {
        id: "a",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:60px;height:60px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"4\"/><polygon points=\"44,14 66,24 74,47 60,68 28,68 14,47 22,24\" fill=\"none\" stroke=\"#0f172a\" stroke-width=\"2\"/><line x1=\"24\" y1=\"44\" x2=\"64\" y2=\"44\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><circle cx=\"44\" cy=\"78\" r=\"4\" fill=\"#2563eb\"/></svg>",
        score: 5,
      },
      {
        id: "b",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:60px;height:60px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"4\"/><polygon points=\"44,14 66,24 74,47 60,68 28,68 14,47 22,24\" fill=\"none\" stroke=\"#0f172a\" stroke-width=\"2\"/><line x1=\"44\" y1=\"24\" x2=\"44\" y2=\"64\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><circle cx=\"44\" cy=\"78\" r=\"4\" fill=\"#2563eb\"/></svg>",
        score: 0,
      },
      {
        id: "c",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:60px;height:60px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"4\"/><polygon points=\"32,16 56,16 72,32 72,56 56,72 32,72 16,56 16,32\" fill=\"none\" stroke=\"#0f172a\" stroke-width=\"2\"/><line x1=\"24\" y1=\"44\" x2=\"64\" y2=\"44\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><circle cx=\"44\" cy=\"78\" r=\"4\" fill=\"#2563eb\"/></svg>",
        score: 0,
      },
      {
        id: "d",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:60px;height:60px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"4\"/><polygon points=\"44,14 66,24 74,47 60,68 28,68 14,47 22,24\" fill=\"none\" stroke=\"#0f172a\" stroke-width=\"2\"/><line x1=\"24\" y1=\"44\" x2=\"64\" y2=\"44\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><circle cx=\"78\" cy=\"44\" r=\"4\" fill=\"#2563eb\"/></svg>",
        score: 0,
      },
      {
        id: "e",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:60px;height:60px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"4\"/><polygon points=\"32,16 56,16 72,32 72,56 56,72 32,72 16,56 16,32\" fill=\"none\" stroke=\"#0f172a\" stroke-width=\"2\"/><line x1=\"30\" y1=\"58\" x2=\"58\" y2=\"30\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><circle cx=\"44\" cy=\"10\" r=\"4\" fill=\"#2563eb\"/></svg>",
        score: 0,
      },
    ],
    explanation: "Analisis Pola Serial Multi-Elemen Simultan (Tingkat HOTS):\n1. Jumlah Sisi Poligon Luar: Bertambah satu sisi secara berurutan:\n   - (1) Segitiga (3 sisi)\n   - (2) Segiempat (4 sisi)\n   - (3) Segilima (5 sisi)\n   - (4) Segienam (6 sisi)\n   - (5) Wajib Segitujuh (7 sisi / Heptagon).\n2. Garis Interior: Berotasi 45° berlawanan arah jarum jam:\n   - (1) Horizontal (0°)\n   - (2) Miring kanan-atas (45°)\n   - (3) Vertikal (90°)\n   - (4) Miring kiri-atas (135°)\n   - (5) Wajib kembali ke posisi Horizontal (180° ≡ 0°).\n3. Lingkaran Satelit Biru: Bergerak mengelilingi bingkai searah jarum jam dengan lompatan bertambah:\n   - Dari (1) ke (2): posisi Atas → Kanan (lompat 1 kuadran)\n   - Dari (2) ke (3): posisi Kanan → Bawah (lompat 1 kuadran)\n   - Dari (3) ke (4): posisi Bawah → Kiri (lompat 1 kuadran)\n   - Dari (4) ke (5): posisi Kiri → Bawah (kembali melompat ke posisi Bawah).\nKombinasi yang tepat adalah Opsi A.",
  },
  {
    id: "mini-tiu6-32",
    category: "TIU",
    topic: "Kemampuan Figural",
    prompt: "[svg]<div style=\"margin-bottom:10px;font-size:15px;font-weight:600;color:#1e293b;\">Perhatikan pergerakan independen dua partikel dalam kisi matriks 3 × 3 berikut:</div><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 500 110\" style=\"width:100%;max-width:580px;display:block;margin:auto;\"><g><rect x=\"6\" y=\"4\" width=\"86\" height=\"86\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"3\"/><line x1=\"34\" y1=\"4\" x2=\"34\" y2=\"90\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"63\" y1=\"4\" x2=\"63\" y2=\"90\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"6\" y1=\"32\" x2=\"92\" y2=\"32\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"6\" y1=\"61\" x2=\"92\" y2=\"61\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><circle cx=\"20\" cy=\"18\" r=\"6\" fill=\"#0f172a\"/><polygon points=\"20,12 25,24 15,24\" fill=\"#2563eb\"/><text x=\"49\" y=\"104\" text-anchor=\"middle\" font-size=\"11\" font-family=\"sans-serif\" font-weight=\"bold\">(1)</text></g><g><rect x=\"104\" y=\"4\" width=\"86\" height=\"86\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"3\"/><line x1=\"132\" y1=\"4\" x2=\"132\" y2=\"90\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"161\" y1=\"4\" x2=\"161\" y2=\"90\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"104\" y1=\"32\" x2=\"190\" y2=\"32\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"104\" y1=\"61\" x2=\"190\" y2=\"61\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><circle cx=\"147\" cy=\"18\" r=\"6\" fill=\"#0f172a\"/><polygon points=\"147,40 152,52 142,52\" fill=\"#2563eb\"/><text x=\"147\" y=\"104\" text-anchor=\"middle\" font-size=\"11\" font-family=\"sans-serif\" font-weight=\"bold\">(2)</text></g><g><rect x=\"202\" y=\"4\" width=\"86\" height=\"86\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"3\"/><line x1=\"230\" y1=\"4\" x2=\"230\" y2=\"90\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"259\" y1=\"4\" x2=\"259\" y2=\"90\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"202\" y1=\"32\" x2=\"288\" y2=\"32\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"202\" y1=\"61\" x2=\"288\" y2=\"61\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><circle cx=\"274\" cy=\"46\" r=\"6\" fill=\"#0f172a\"/><polygon points=\"274,68 279,80 269,80\" fill=\"#2563eb\"/><text x=\"245\" y=\"104\" text-anchor=\"middle\" font-size=\"11\" font-family=\"sans-serif\" font-weight=\"bold\">(3)</text></g><g><rect x=\"300\" y=\"4\" width=\"86\" height=\"86\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"3\"/><line x1=\"328\" y1=\"4\" x2=\"328\" y2=\"90\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"357\" y1=\"4\" x2=\"357\" y2=\"90\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"300\" y1=\"32\" x2=\"386\" y2=\"32\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"300\" y1=\"61\" x2=\"386\" y2=\"61\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><circle cx=\"314\" cy=\"75\" r=\"6\" fill=\"#0f172a\"/><polygon points=\"343,40 348,52 338,52\" fill=\"#2563eb\"/><text x=\"343\" y=\"104\" text-anchor=\"middle\" font-size=\"11\" font-family=\"sans-serif\" font-weight=\"bold\">(4)</text></g><g><rect x=\"398\" y=\"4\" width=\"86\" height=\"86\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"3\"/><text x=\"441\" y=\"57\" text-anchor=\"middle\" font-size=\"42\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#94a3b8\">?</text><text x=\"441\" y=\"104\" text-anchor=\"middle\" font-size=\"11\" font-family=\"sans-serif\" font-weight=\"bold\">(5)</text></g></svg><div style=\"margin-top:10px;font-size:14px;color:#334155;\">Konfigurasi kisi matriks yang tepat pada posisi (5) adalah ...</div>",
    choices: [
      {
        id: "a",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:60px;height:60px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"3\"/><line x1=\"29\" y1=\"2\" x2=\"29\" y2=\"86\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"58\" y1=\"2\" x2=\"58\" y2=\"86\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"2\" y1=\"29\" x2=\"86\" y2=\"29\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"2\" y1=\"58\" x2=\"86\" y2=\"58\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><circle cx=\"44\" cy=\"15\" r=\"6\" fill=\"#0f172a\"/><polygon points=\"15,10 20,22 10,22\" fill=\"#2563eb\"/></svg>",
        score: 0,
      },
      {
        id: "b",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:60px;height:60px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"3\"/><line x1=\"29\" y1=\"2\" x2=\"29\" y2=\"86\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"58\" y1=\"2\" x2=\"58\" y2=\"86\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"2\" y1=\"29\" x2=\"86\" y2=\"29\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"2\" y1=\"58\" x2=\"86\" y2=\"58\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><circle cx=\"72\" cy=\"15\" r=\"6\" fill=\"#0f172a\"/><polygon points=\"15,10 20,22 10,22\" fill=\"#2563eb\"/></svg>",
        score: 5,
      },
      {
        id: "c",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:60px;height:60px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"3\"/><line x1=\"29\" y1=\"2\" x2=\"29\" y2=\"86\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"58\" y1=\"2\" x2=\"58\" y2=\"86\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"2\" y1=\"29\" x2=\"86\" y2=\"29\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"2\" y1=\"58\" x2=\"86\" y2=\"58\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><circle cx=\"72\" cy=\"72\" r=\"6\" fill=\"#0f172a\"/><polygon points=\"44,38 49,50 39,50\" fill=\"#2563eb\"/></svg>",
        score: 0,
      },
      {
        id: "d",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:60px;height:60px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"3\"/><line x1=\"29\" y1=\"2\" x2=\"29\" y2=\"86\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"58\" y1=\"2\" x2=\"58\" y2=\"86\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"2\" y1=\"29\" x2=\"86\" y2=\"29\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"2\" y1=\"58\" x2=\"86\" y2=\"58\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><circle cx=\"15\" cy=\"72\" r=\"6\" fill=\"#0f172a\"/><polygon points=\"72,66 77,78 67,78\" fill=\"#2563eb\"/></svg>",
        score: 0,
      },
      {
        id: "e",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:60px;height:60px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"3\"/><line x1=\"29\" y1=\"2\" x2=\"29\" y2=\"86\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"58\" y1=\"2\" x2=\"58\" y2=\"86\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"2\" y1=\"29\" x2=\"86\" y2=\"29\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><line x1=\"2\" y1=\"58\" x2=\"86\" y2=\"58\" stroke=\"#cbd5e1\" stroke-width=\"1\"/><circle cx=\"72\" cy=\"15\" r=\"6\" fill=\"#0f172a\"/><polygon points=\"44,38 49,50 39,50\" fill=\"#2563eb\"/></svg>",
        score: 0,
      },
    ],
    explanation: "Analisis Pelacakan Dua Partikel Independen dalam Matriks 3 × 3:\n1. Partikel Lingkaran Hitam (Bergerak searah jarum jam pada 8 kotak pinggir/perimeter):\n   - Pola 1: Sel Kiri-Atas (langkah awal)\n   - Pola 2: Sel Tengah-Atas (maju +1 kotak)\n   - Pola 3: Sel Kanan-Tengah (maju +2 kotak)\n   - Pola 4: Sel Kiri-Bawah (maju +3 kotak)\n   - Pola 5: Wajib maju +4 kotak mengelilingi pinggir: dari Kiri-Bawah → Kiri-Tengah → Kiri-Atas → Tengah-Atas → Kanan-Atas!\n2. Partikel Segitiga Biru (Bergerak bolak-balik diagonal utama):\n   - Pola 1: Kiri-Atas\n   - Pola 2: Pusat (Tengah)\n   - Pola 3: Kanan-Bawah\n   - Pola 4: Pusat (Tengah)\n   - Pola 5: Wajib kembali ke Kiri-Atas.\nKonfigurasi yang menempatkan Lingkaran Hitam di Kanan-Atas dan Segitiga Biru di Kiri-Atas adalah Opsi B.",
  },
  {
    id: "mini-tiu6-33",
    category: "TIU",
    topic: "Kemampuan Figural",
    prompt: "[svg]<div style=\"margin-bottom:10px;font-size:15px;font-weight:600;color:#1e293b;\">Manakah dari kelima figur berikut yang paling MENYIMPANG (memiliki kiralitas/orientasi intrinsik berbeda dan tidak dapat dibentuk hanya melalui rotasi 2 dimensi)?</div><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 500 110\" style=\"width:100%;max-width:580px;display:block;margin:auto;\"><g><rect x=\"6\" y=\"4\" width=\"86\" height=\"86\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"4\"/><line x1=\"30\" y1=\"25\" x2=\"30\" y2=\"75\" stroke=\"#0f172a\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><line x1=\"30\" y1=\"25\" x2=\"65\" y2=\"25\" stroke=\"#0f172a\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><line x1=\"30\" y1=\"50\" x2=\"52\" y2=\"50\" stroke=\"#0f172a\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><circle cx=\"65\" cy=\"25\" r=\"5\" fill=\"#2563eb\"/><polygon points=\"26,75 34,75 30,65\" fill=\"#0f172a\"/><text x=\"49\" y=\"104\" text-anchor=\"middle\" font-size=\"11\" font-family=\"sans-serif\" font-weight=\"bold\">A</text></g><g><rect x=\"104\" y=\"4\" width=\"86\" height=\"86\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"4\"/><g transform=\"rotate(90 147 47)\"><line x1=\"128\" y1=\"22\" x2=\"128\" y2=\"72\" stroke=\"#0f172a\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><line x1=\"128\" y1=\"22\" x2=\"163\" y2=\"22\" stroke=\"#0f172a\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><line x1=\"128\" y1=\"47\" x2=\"150\" y2=\"47\" stroke=\"#0f172a\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><circle cx=\"163\" cy=\"22\" r=\"5\" fill=\"#2563eb\"/><polygon points=\"124,72 132,72 128,62\" fill=\"#0f172a\"/></g><text x=\"147\" y=\"104\" text-anchor=\"middle\" font-size=\"11\" font-family=\"sans-serif\" font-weight=\"bold\">B</text></g><g><rect x=\"202\" y=\"4\" width=\"86\" height=\"86\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"4\"/><g transform=\"rotate(180 245 47)\"><line x1=\"226\" y1=\"22\" x2=\"226\" y2=\"72\" stroke=\"#0f172a\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><line x1=\"226\" y1=\"22\" x2=\"261\" y2=\"22\" stroke=\"#0f172a\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><line x1=\"226\" y1=\"47\" x2=\"248\" y2=\"47\" stroke=\"#0f172a\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><circle cx=\"261\" cy=\"22\" r=\"5\" fill=\"#2563eb\"/><polygon points=\"222,72 230,72 226,62\" fill=\"#0f172a\"/></g><text x=\"245\" y=\"104\" text-anchor=\"middle\" font-size=\"11\" font-family=\"sans-serif\" font-weight=\"bold\">C</text></g><g><rect x=\"300\" y=\"4\" width=\"86\" height=\"86\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"4\"/><line x1=\"360\" y1=\"25\" x2=\"360\" y2=\"75\" stroke=\"#0f172a\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><line x1=\"360\" y1=\"25\" x2=\"325\" y2=\"25\" stroke=\"#0f172a\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><line x1=\"360\" y1=\"50\" x2=\"338\" y2=\"50\" stroke=\"#0f172a\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><circle cx=\"325\" cy=\"25\" r=\"5\" fill=\"#2563eb\"/><polygon points=\"356,75 364,75 360,65\" fill=\"#0f172a\"/><text x=\"343\" y=\"104\" text-anchor=\"middle\" font-size=\"11\" font-family=\"sans-serif\" font-weight=\"bold\">D</text></g><g><rect x=\"398\" y=\"4\" width=\"86\" height=\"86\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"4\"/><g transform=\"rotate(270 441 47)\"><line x1=\"422\" y1=\"22\" x2=\"422\" y2=\"72\" stroke=\"#0f172a\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><line x1=\"422\" y1=\"22\" x2=\"457\" y2=\"22\" stroke=\"#0f172a\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><line x1=\"422\" y1=\"47\" x2=\"444\" y2=\"47\" stroke=\"#0f172a\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><circle cx=\"457\" cy=\"22\" r=\"5\" fill=\"#2563eb\"/><polygon points=\"418,72 426,72 422,62\" fill=\"#0f172a\"/></g><text x=\"441\" y=\"104\" text-anchor=\"middle\" font-size=\"11\" font-family=\"sans-serif\" font-weight=\"bold\">E</text></g></svg>",
    choices: [
      { id: "a", label: "Figur A", score: 0 },
      { id: "b", label: "Figur B", score: 0 },
      { id: "c", label: "Figur C", score: 0 },
      { id: "d", label: "Figur D", score: 5 },
      { id: "e", label: "Figur E", score: 0 },
    ],
    explanation: "Analisis Ketidaksamaan Kiralitas Enantiomer (Pencerminan vs Rotasi 2D):\n- Perhatikan orientasi percabangan: Pada Figur A, jika kita memandang dari pangkal panah ke arah lingkaran, cabang-cabang horizontal menjulur ke sisi KANAN.\n- Figur B adalah hasil rotasi Figur A sebesar 90° searah jarum jam (cabang tetap ke sisi kanan strukturalnya).\n- Figur C adalah hasil rotasi Figur A sebesar 180° (cabang tetap di kanan strukturalnya).\n- Figur E adalah hasil rotasi Figur A sebesar 270° (cabang tetap di kanan strukturalnya).\n- Sedangkan Figur D merupakan HASIL PENCERMINAN (Refleksi Kaca). Cabang-cabangnya menjulur ke sisi KIRI struktural batang utama. Bentuk D mustahil diperoleh hanya dengan memutar bidang 2D tanpa membalik lembaran kertas keluar dimensi (enantiomer).\nOleh karena itu, Figur D adalah figur yang paling menyimpang dari yang lain (Opsi D).",
  },
  {
    id: "mini-tiu6-34",
    category: "TIU",
    topic: "Kemampuan Figural",
    prompt: "[svg]<div style=\"margin-bottom:10px;font-size:15px;font-weight:600;color:#1e293b;\">Tentukan figur yang tepat untuk melengkapi kotak tanda tanya (?) pada matriks 3 × 3 di bawah ini:</div><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 240 240\" style=\"width:220px;height:220px;display:block;margin:auto;\"><rect x=\"4\" y=\"4\" width=\"232\" height=\"232\" fill=\"white\" stroke=\"#334155\" stroke-width=\"2\" rx=\"4\"/><line x1=\"81\" y1=\"4\" x2=\"81\" y2=\"236\" stroke=\"#cbd5e1\" stroke-width=\"1.5\"/><line x1=\"158\" y1=\"4\" x2=\"158\" y2=\"236\" stroke=\"#cbd5e1\" stroke-width=\"1.5\"/><line x1=\"4\" y1=\"81\" x2=\"236\" y2=\"81\" stroke=\"#cbd5e1\" stroke-width=\"1.5\"/><line x1=\"4\" y1=\"158\" x2=\"236\" y2=\"158\" stroke=\"#cbd5e1\" stroke-width=\"1.5\"/><g><line x1=\"42\" y1=\"20\" x2=\"42\" y2=\"66\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><circle cx=\"42\" cy=\"43\" r=\"7\" fill=\"#0f172a\"/></g><g><line x1=\"96\" y1=\"43\" x2=\"142\" y2=\"43\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><circle cx=\"119\" cy=\"43\" r=\"7\" fill=\"#0f172a\"/></g><g><line x1=\"196\" y1=\"20\" x2=\"196\" y2=\"66\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><line x1=\"173\" y1=\"43\" x2=\"219\" y2=\"43\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><circle cx=\"196\" cy=\"43\" r=\"7\" fill=\"white\" stroke=\"#0f172a\" stroke-width=\"2\"/></g><g><circle cx=\"42\" cy=\"120\" r=\"18\" fill=\"none\" stroke=\"#0f172a\" stroke-width=\"2\"/><line x1=\"24\" y1=\"120\" x2=\"60\" y2=\"120\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><rect x=\"36\" y=\"114\" width=\"12\" height=\"12\" fill=\"#0f172a\"/></g><g><rect x=\"99\" y=\"102\" width=\"36\" height=\"36\" fill=\"none\" stroke=\"#0f172a\" stroke-width=\"2\"/><line x1=\"101\" y1=\"120\" x2=\"137\" y2=\"120\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><rect x=\"113\" y=\"114\" width=\"12\" height=\"12\" fill=\"#0f172a\"/></g><g><circle cx=\"196\" cy=\"120\" r=\"18\" fill=\"none\" stroke=\"#0f172a\" stroke-width=\"2\"/><rect x=\"178\" y=\"102\" width=\"36\" height=\"36\" fill=\"none\" stroke=\"#0f172a\" stroke-width=\"2\"/><rect x=\"190\" y=\"114\" width=\"12\" height=\"12\" fill=\"white\" stroke=\"#0f172a\" stroke-width=\"2\"/></g><g><polygon points=\"42,175 58,211 26,211\" fill=\"none\" stroke=\"#0f172a\" stroke-width=\"2\"/><line x1=\"42\" y1=\"170\" x2=\"42\" y2=\"216\" stroke=\"#0f172a\" stroke-width=\"2.5\"/></g><g><line x1=\"96\" y1=\"197\" x2=\"142\" y2=\"197\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><line x1=\"119\" y1=\"174\" x2=\"119\" y2=\"220\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><circle cx=\"119\" cy=\"197\" r=\"6\" fill=\"#0f172a\"/></g><text x=\"196\" y=\"208\" text-anchor=\"middle\" font-size=\"36\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"#2563eb\">?</text></svg>",
    choices: [
      {
        id: "a",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:60px;height:60px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"4\"/><polygon points=\"44,20 62,64 26,64\" fill=\"none\" stroke=\"#0f172a\" stroke-width=\"2\"/><circle cx=\"44\" cy=\"48\" r=\"6\" fill=\"#0f172a\"/></svg>",
        score: 0,
      },
      {
        id: "b",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:60px;height:60px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"4\"/><polygon points=\"44,20 62,64 26,64\" fill=\"none\" stroke=\"#0f172a\" stroke-width=\"2\"/><line x1=\"44\" y1=\"14\" x2=\"44\" y2=\"70\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><circle cx=\"44\" cy=\"48\" r=\"6\" fill=\"#0f172a\"/></svg>",
        score: 0,
      },
      {
        id: "c",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:60px;height:60px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"4\"/><line x1=\"18\" y1=\"44\" x2=\"70\" y2=\"44\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><circle cx=\"44\" cy=\"44\" r=\"6\" fill=\"#0f172a\"/></svg>",
        score: 0,
      },
      {
        id: "d",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:60px;height:60px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"4\"/><polygon points=\"44,20 62,64 26,64\" fill=\"none\" stroke=\"#0f172a\" stroke-width=\"2\"/><line x1=\"44\" y1=\"14\" x2=\"44\" y2=\"70\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><line x1=\"18\" y1=\"44\" x2=\"70\" y2=\"44\" stroke=\"#0f172a\" stroke-width=\"2.5\"/></svg>",
        score: 0,
      },
      {
        id: "e",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:60px;height:60px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\" rx=\"4\"/><polygon points=\"44,20 62,64 26,64\" fill=\"none\" stroke=\"#0f172a\" stroke-width=\"2\"/><line x1=\"18\" y1=\"44\" x2=\"70\" y2=\"44\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><circle cx=\"44\" cy=\"44\" r=\"6\" fill=\"#0f172a\"/></svg>",
        score: 5,
      },
    ],
    explanation: "Aturan Matriks Operasi Logika Visual Ganda:\n1. Garis Luar/Bentuk Geometri: Kolom 1 dan Kolom 2 digabungkan (OR).\n2. Garis Bagian Dalam: Mengikuti aturan XOR (elemen yang sama dihilangkan, elemen yang berbeda dipertahankan):\n   - Baris 1: Garis vertikal (K1) dan garis horizontal (K2) berbeda → digabung menjadi tanda (+). Titik hitam di K1 dan K2 sama-sama ada → inversi warna menjadi lingkaran putih.\n   - Baris 2: Garis horizontal ada di K1 dan K2 → saling menghilangkan (XOR). Kotak hitam di K1 dan K2 → inversi warna menjadi kotak putih.\n   - Baris 3: Segitiga ada di K1 saja → tetap dipertahankan. Garis vertikal ada di K1 dan K2 → saling menghilangkan (XOR)! Garis horizontal ada di K2 saja → dipertahankan. Titik hitam ada di K2 saja → dipertahankan di tengah.\nSehingga figur pada posisi tanda tanya adalah Segitiga dengan Garis Horizontal dan Titik Hitam di tengahnya.\nJawaban yang tepat adalah Opsi E.",
  },
  {
    id: "mini-tiu6-35",
    category: "TIU",
    topic: "Kemampuan Figural",
    prompt: "[svg]<div style=\"margin-bottom:10px;font-size:15px;font-weight:600;color:#1e293b;\">Perhatikan jaring-jaring kubus 3 dimensi dengan motif jalur diagonal berikut:</div><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 240 180\" style=\"width:220px;height:165px;display:block;margin:auto;\"><rect x=\"60\" y=\"10\" width=\"40\" height=\"40\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\"/><line x1=\"60\" y1=\"10\" x2=\"100\" y2=\"50\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><circle cx=\"90\" cy=\"20\" r=\"4\" fill=\"#2563eb\"/><rect x=\"20\" y=\"50\" width=\"40\" height=\"40\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\"/><line x1=\"20\" y1=\"90\" x2=\"60\" y2=\"50\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><circle cx=\"30\" cy=\"60\" r=\"4\" fill=\"#0f172a\"/><rect x=\"60\" y=\"50\" width=\"40\" height=\"40\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\"/><line x1=\"60\" y1=\"50\" x2=\"100\" y2=\"90\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><rect x=\"100\" y=\"50\" width=\"40\" height=\"40\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\"/><circle cx=\"120\" cy=\"70\" r=\"8\" fill=\"none\" stroke=\"#0f172a\" stroke-width=\"2\"/><rect x=\"140\" y=\"50\" width=\"40\" height=\"40\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\"/><line x1=\"140\" y1=\"50\" x2=\"180\" y2=\"90\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><polygon points=\"160,58 170,78 150,78\" fill=\"#0f172a\"/><rect x=\"60\" y=\"90\" width=\"40\" height=\"40\" fill=\"white\" stroke=\"#334155\" stroke-width=\"1.5\"/><line x1=\"60\" y1=\"130\" x2=\"100\" y2=\"90\" stroke=\"#0f172a\" stroke-width=\"2.5\"/></svg><div style=\"margin-top:10px;font-size:14px;color:#334155;\">Jika jaring-jaring tersebut dilipat secara presisi menjadi sebuah kubus 3D, manakah bentuk kubus yang benar (perhatikan ketepatan titik temu sudut garis diagonal)?</div>",
    choices: [
      {
        id: "a",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:60px;height:60px;display:block\"><polygon points=\"44,12 76,28 44,44 12,28\" fill=\"#f8fafc\" stroke=\"#334155\" stroke-width=\"1.5\"/><polygon points=\"12,28 44,44 44,76 12,60\" fill=\"#f1f5f9\" stroke=\"#334155\" stroke-width=\"1.5\"/><polygon points=\"44,44 76,28 76,60 44,76\" fill=\"#e2e8f0\" stroke=\"#334155\" stroke-width=\"1.5\"/><line x1=\"44\" y1=\"12\" x2=\"44\" y2=\"44\" stroke=\"#0f172a\" stroke-width=\"2\"/><line x1=\"12\" y1=\"60\" x2=\"44\" y2=\"44\" stroke=\"#0f172a\" stroke-width=\"2\"/><circle cx=\"60\" cy=\"52\" r=\"5\" fill=\"none\" stroke=\"#0f172a\" stroke-width=\"2\"/></svg>",
        score: 0,
      },
      {
        id: "b",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:60px;height:60px;display:block\"><polygon points=\"44,12 76,28 44,44 12,28\" fill=\"#f8fafc\" stroke=\"#334155\" stroke-width=\"1.5\"/><polygon points=\"12,28 44,44 44,76 12,60\" fill=\"#f1f5f9\" stroke=\"#334155\" stroke-width=\"1.5\"/><polygon points=\"44,44 76,28 76,60 44,76\" fill=\"#e2e8f0\" stroke=\"#334155\" stroke-width=\"1.5\"/><line x1=\"12\" y1=\"28\" x2=\"76\" y2=\"28\" stroke=\"#0f172a\" stroke-width=\"2\"/><polygon points=\"60,44 68,60 52,60\" fill=\"#0f172a\"/><line x1=\"22\" y1=\"46\" x2=\"34\" y2=\"58\" stroke=\"#0f172a\" stroke-width=\"2\"/></svg>",
        score: 0,
      },
      {
        id: "c",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:60px;height:60px;display:block\"><polygon points=\"44,12 76,28 44,44 12,28\" fill=\"#f8fafc\" stroke=\"#334155\" stroke-width=\"1.5\"/><polygon points=\"12,28 44,44 44,76 12,60\" fill=\"#f1f5f9\" stroke=\"#334155\" stroke-width=\"1.5\"/><polygon points=\"44,44 76,28 76,60 44,76\" fill=\"#e2e8f0\" stroke=\"#334155\" stroke-width=\"1.5\"/><line x1=\"44\" y1=\"12\" x2=\"76\" y2=\"28\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><line x1=\"12\" y1=\"28\" x2=\"44\" y2=\"76\" stroke=\"#0f172a\" stroke-width=\"2.5\"/><circle cx=\"60\" cy=\"52\" r=\"5\" fill=\"none\" stroke=\"#0f172a\" stroke-width=\"2\"/><circle cx=\"68\" cy=\"22\" r=\"3.5\" fill=\"#2563eb\"/></svg>",
        score: 5,
      },
      {
        id: "d",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:60px;height:60px;display:block\"><polygon points=\"44,12 76,28 44,44 12,28\" fill=\"#f8fafc\" stroke=\"#334155\" stroke-width=\"1.5\"/><polygon points=\"12,28 44,44 44,76 12,60\" fill=\"#f1f5f9\" stroke=\"#334155\" stroke-width=\"1.5\"/><polygon points=\"44,44 76,28 76,60 44,76\" fill=\"#e2e8f0\" stroke=\"#334155\" stroke-width=\"1.5\"/><circle cx=\"44\" cy=\"28\" r=\"5\" fill=\"none\" stroke=\"#0f172a\" stroke-width=\"2\"/><line x1=\"12\" y1=\"28\" x2=\"44\" y2=\"44\" stroke=\"#0f172a\" stroke-width=\"2\"/><polygon points=\"60,44 68,60 52,60\" fill=\"#0f172a\"/></svg>",
        score: 0,
      },
      {
        id: "e",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:60px;height:60px;display:block\"><polygon points=\"44,12 76,28 44,44 12,28\" fill=\"#f8fafc\" stroke=\"#334155\" stroke-width=\"1.5\"/><polygon points=\"12,28 44,44 44,76 12,60\" fill=\"#f1f5f9\" stroke=\"#334155\" stroke-width=\"1.5\"/><polygon points=\"44,44 76,28 76,60 44,76\" fill=\"#e2e8f0\" stroke=\"#334155\" stroke-width=\"1.5\"/><line x1=\"12\" y1=\"60\" x2=\"44\" y2=\"76\" stroke=\"#0f172a\" stroke-width=\"2\"/><line x1=\"44\" y1=\"44\" x2=\"76\" y2=\"60\" stroke=\"#0f172a\" stroke-width=\"2\"/><circle cx=\"44\" cy=\"28\" r=\"4\" fill=\"#2563eb\"/></svg>",
        score: 0,
      },
    ],
    explanation: "Analisis Jaring-Jaring Kubus 3D Tingkat Tinggi (Titik Temu Sudut Jalur Diagonal):\n1. Pasangan Sisi Berhadapan (tidak boleh tampak bersamaan):\n   - Sisi Atas (Diagonal + Titik Biru) berhadapan dengan Sisi Bawah (Diagonal miring kiri).\n   - Sisi Kiri (Diagonal + Titik Hitam) berhadapan dengan Sisi Lingkaran Putih.\n   - Sisi Tengah (Diagonal) berhadapan dengan Sisi Ujung Kanan (Segitiga Hitam).\n2. Verifikasi Titik Temu Garis Diagonal pada Sisi Bersebelahan:\n   - Pada Opsi C, sisi yang tampak adalah Sisi Atas (memiliki titik biru), Sisi Tengah (depan kiri), dan Sisi Lingkaran Putih (depan kanan).\n   - Ketiga sisi ini saling tegak lurus berdampingan.\n   - Garis diagonal pada sisi atas dan sisi depan kiri bertemu tepat pada satu titik sudut tepi bersama di bagian atas, dan posisi titik biru berada di sudut yang tepat.\nBentuk kubus yang tepat secara orientasi ruang 3D adalah Opsi C.",
  },
];
