import type { Question } from "./types";

export const MINI_TKP_QUESTIONS: Question[] = [
  {
    id: "mini-tkp-01",
    category: "TKP",
    topic: "Profesionalisme",
    prompt: "Anda ditugaskan mengolah hasil survei kepuasan masyarakat yang akan digunakan dalam rapat evaluasi. Saat memeriksa data, Anda menemukan beberapa jawaban responden yang tidak lengkap. Jika data tersebut dikeluarkan, jumlah sampel akan berkurang dan hasil analisis berpotensi berubah. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Tetap memasukkan seluruh data agar jumlah responden tidak berkurang terlalu banyak.", score: 2 },
      { id: "b", label: "Menghapus seluruh data yang tidak lengkap agar hasil analisis lebih mudah diolah.", score: 1 },
      { id: "c", label: "Memeriksa kriteria kelayakan data lalu mengonsultasikan temuan yang berpengaruh terhadap hasil analisis.", score: 5 },
      { id: "d", label: "Menggunakan data yang tersedia terlebih dahulu dan menjelaskan kekurangannya saat rapat evaluasi.", score: 4 },
      { id: "e", label: "Meminta rekan yang mengumpulkan data menentukan data mana yang masih dapat digunakan.", score: 3 },
    ],
    explanation: "Tindakan paling profesional adalah memeriksa kriteria kelayakan data secara objektif dan mengonsultasikan temuan penting kepada atasan/tim sebelum mengambil keputusan yang dapat memengaruhi validitas hasil analisis.",
  },
  {
    id: "mini-tkp-02",
    category: "TKP",
    topic: "Profesionalisme",
    prompt: "Anda menjadi koordinator kegiatan pelayanan masyarakat. Sehari sebelum kegiatan berlangsung, salah satu anggota tim menginformasikan bahwa jumlah petugas yang hadir kemungkinan berkurang karena beberapa orang mendapat tugas lain. Sementara itu, jumlah peserta diperkirakan tetap tinggi. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Membagi ulang petugas yang tersedia berdasarkan bagian yang dianggap paling membutuhkan.", score: 4 },
      { id: "b", label: "Meminta seluruh anggota tetap hadir agar kegiatan dapat berjalan sesuai rencana awal.", score: 2 },
      { id: "c", label: "Menunggu kepastian jumlah petugas sebelum melakukan perubahan pembagian tugas.", score: 3 },
      { id: "d", label: "Menyesuaikan alur pelayanan dan membagi kembali tugas berdasarkan beban pekerjaan yang diperkirakan.", score: 5 },
      { id: "e", label: "Meminta peserta memahami kondisi apabila pelayanan nantinya berjalan lebih lambat.", score: 1 },
    ],
    explanation: "Sebagai koordinator yang profesional dan adaptif, langkah terbaik adalah proaktif menyesuaikan alur alur layanan serta mendistribusikan kembali tugas berdasarkan estimasi beban kerja riil agar pelayanan publik tetap berjalan optimal.",
  },
  {
    id: "mini-tkp-03",
    category: "TKP",
    topic: "Profesionalisme",
    prompt: "Anda diminta menyiapkan bahan presentasi pimpinan menggunakan beberapa dokumen dari unit lain. Salah satu dokumen memuat informasi internal yang belum dipublikasikan. Rekan Anda meminta seluruh dokumen dimasukkan ke dalam bahan presentasi agar pembahasan lebih lengkap. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Memasukkan seluruh informasi karena dokumen tersebut berasal dari unit resmi.", score: 2 },
      { id: "b", label: "Menggunakan informasi yang relevan dengan kebutuhan presentasi dan memastikan bagian yang bersifat terbatas hanya digunakan sesuai kewenangan.", score: 5 },
      { id: "c", label: "Menghapus seluruh informasi internal agar tidak ada risiko dalam penyusunan presentasi.", score: 3 },
      { id: "d", label: "Meminta rekan menentukan informasi mana yang dapat dimasukkan ke dalam presentasi.", score: 1 },
      { id: "e", label: "Menyampaikan kepada pimpinan bahwa terdapat informasi internal sebelum memasukkannya ke bahan presentasi.", score: 4 },
    ],
    explanation: "Sikap profesional menuntut kecermatan dalam memilah informasi yang relevan sekaligus menjunjung tinggi kepatuhan terhadap batasan kerahasiaan dan kewenangan penggunaan data internal.",
  },
  {
    id: "mini-tkp-04",
    category: "TKP",
    topic: "Profesionalisme",
    prompt: "Anda menjadi anggota tim pengadaan dan diminta membantu mengevaluasi beberapa dokumen penawaran. Salah satu perusahaan peserta merupakan perusahaan yang pernah bekerja sama dengan Anda dalam kegiatan sebelumnya. Anda mengetahui kualitas perusahaan tersebut cukup baik, tetapi proses penilaian tetap harus dilakukan secara objektif. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Tetap memberikan penilaian berdasarkan dokumen yang tersedia tanpa mempertimbangkan pengalaman pribadi.", score: 4 },
      { id: "b", label: "Menyampaikan kepada ketua tim mengenai hubungan kerja sebelumnya agar dapat dipertimbangkan dalam pembagian tugas.", score: 5 },
      { id: "c", label: "Tetap ikut menilai karena pengalaman Anda terhadap perusahaan tersebut dapat membantu proses evaluasi.", score: 2 },
      { id: "d", label: "Menghindari memberikan penilaian terhadap perusahaan tersebut dan meminta anggota lain menggantikannya.", score: 3 },
      { id: "e", label: "Memberikan penilaian seperti biasa, tetapi menjelaskan kepada anggota tim bahwa perusahaan tersebut pernah bekerja sama dengan Anda.", score: 1 },
    ],
    explanation: "Menyatakan potensi benturan kepentingan (conflict of interest) secara transparan kepada ketua tim merupakan wujud integritas dan profesionalisme tertinggi dalam tata kelola pengadaan barang dan jasa.",
  },
  {
    id: "mini-tkp-05",
    category: "TKP",
    topic: "Profesionalisme",
    prompt: "Dalam penyusunan laporan bulanan, Anda menemukan bahwa salah satu angka pada laporan bulan sebelumnya ternyata salah input. Kesalahan tersebut tidak memengaruhi kesimpulan utama, tetapi angka itu akan menjadi dasar perbandingan laporan bulan ini. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Menggunakan angka yang benar pada laporan bulan ini dan memberikan catatan bahwa terdapat perbedaan dengan data pada laporan sebelumnya.", score: 4 },
      { id: "b", label: "Memeriksa kembali sumber data, lalu menggunakan angka yang telah terverifikasi dan menyampaikan koreksi sesuai mekanisme yang berlaku.", score: 5 },
      { id: "c", label: "Mengonfirmasi kesalahan tersebut kepada pihak yang mengelola data sebelum menggunakan angka yang benar sebagai dasar perbandingan.", score: 3 },
      { id: "d", label: "Menyesuaikan angka pembanding pada laporan bulan ini berdasarkan sumber data asli agar analisis yang disajikan tetap akurat.", score: 2 },
      { id: "e", label: "Tetap menggunakan angka sebelumnya sebagai pembanding, tetapi mencantumkan angka yang benar dalam catatan agar konsistensi laporan tetap terjaga.", score: 1 },
    ],
    explanation: "Memverifikasi ulang sumber data asli dan melakukan koreksi secara formal melalui mekanisme pelaporan yang sah mencerminkan tanggung jawab, akurasi, dan profesionalisme kerja.",
  },
  {
    id: "mini-tkp-06",
    category: "TKP",
    topic: "Profesionalisme",
    prompt: "Anda baru ditempatkan pada unit yang memiliki pola kerja berbeda dengan unit sebelumnya. Seorang rekan menjelaskan bahwa beberapa pekerjaan biasa dilakukan dengan cara yang lebih praktis daripada prosedur tertulis karena dianggap lebih cepat. Anda belum mengetahui apakah cara tersebut diperbolehkan. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Mempelajari prosedur yang berlaku dan mengonfirmasi cara kerja tersebut kepada pihak yang berwenang sebelum menerapkannya.", score: 5 },
      { id: "b", label: "Mengikuti prosedur tertulis terlebih dahulu sambil mempelajari alasan unit menggunakan cara yang lebih praktis.", score: 4 },
      { id: "c", label: "Meminta rekan menjelaskan tahapan cara tersebut dan membandingkannya dengan prosedur sebelum menentukan cara kerja yang digunakan.", score: 3 },
      { id: "d", label: "Menggunakan prosedur tertulis sambil mengusulkan evaluasi terhadap cara yang lebih praktis apabila memang terbukti lebih efisien.", score: 2 },
      { id: "e", label: "Mengamati penerapan cara tersebut oleh rekan yang lebih berpengalaman sebelum mempertimbangkan penggunaannya pada pekerjaan sendiri.", score: 1 },
    ],
    explanation: "Pegawai profesional selalu mengutamakan kepatuhan terhadap SOP resmi serta memastikan keabsahan inovasi/cara kerja alternatif kepada atasan yang berwenang sebelum mengadopsinya.",
  },
  {
    id: "mini-tkp-07",
    category: "TKP",
    topic: "Profesionalisme",
    prompt: "Anda memiliki beberapa pekerjaan dengan tenggat berbeda. Seorang rekan meminta bantuan karena harus menghadiri kegiatan mendadak, sedangkan pekerjaannya dibutuhkan unit lain hari itu. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Membantu pekerjaan rekan terlebih dahulu karena akan digunakan unit lain pada hari yang sama.", score: 3 },
      { id: "b", label: "Memeriksa prioritas pekerjaan Anda dan rekan, lalu membantu bagian yang paling mendesak tanpa mengabaikan tenggat sendiri.", score: 5 },
      { id: "c", label: "Menyelesaikan pekerjaan Anda yang paling mendesak, kemudian membantu rekan sesuai waktu yang tersedia.", score: 4 },
      { id: "d", label: "Membantu bagian pekerjaan rekan yang belum selesai sambil menyesuaikan kembali urutan pekerjaan Anda.", score: 2 },
      { id: "e", label: "Membantu rekan mencari anggota lain yang memiliki waktu lebih longgar untuk menyelesaikan pekerjaannya.", score: 1 },
    ],
    explanation: "Menimbang matriks urgensi dan skala prioritas secara objektif memungkinkan kita membantu rekan kerja yang membutuhkan tanpa mengorbankan akuntabilitas tugas dan tenggat waktu pribadi.",
  },
  {
    id: "mini-tkp-08",
    category: "TKP",
    topic: "Profesionalisme",
    prompt: "Anda diminta menyiapkan presentasi pimpinan dari beberapa dokumen unit lain. Salah satunya memuat informasi internal yang belum dipublikasikan. Rekan meminta seluruh dokumen dimasukkan agar materi lengkap. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Menggunakan bagian yang tidak sensitif sambil memastikan status informasi lainnya kepada unit pemilik.", score: 5 },
      { id: "b", label: "Meminta konfirmasi unit pemilik sebelum menggunakan informasi internal tersebut dalam presentasi.", score: 4 },
      { id: "c", label: "Menyiapkan informasi tersebut sebagai bahan tambahan dan hanya menggunakannya jika diminta pimpinan.", score: 2 },
      { id: "d", label: "Merangkum informasi internal tanpa mencantumkan rincian yang dianggap sensitif.", score: 1 },
      { id: "e", label: "Menggunakan dokumen lain terlebih dahulu sambil menunggu kejelasan penggunaan informasi internal.", score: 3 },
    ],
    explanation: "Langkah ini menjaga efisiensi penyusunan presentasi dengan memanfaatkan informasi yang aman, sekaligus tetap tertib berkoordinasi dengan unit pemilik terkait legalitas informasi lainnya.",
  },
  {
    id: "mini-tkp-09",
    category: "TKP",
    topic: "Pelayanan Publik",
    prompt: "Anda bertugas di kantor kecamatan. Seorang warga mengurus dokumen keluarga, tetapi terdapat perbedaan data dengan dokumen lama. Ia khawatir harus kembali karena rumahnya cukup jauh. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Menjelaskan perbedaan data dan meminta warga melengkapinya terlebih dahulu agar proses tidak menimbulkan kesalahan.", score: 2 },
      { id: "b", label: "Memeriksa sumber perbedaan data dan membantu warga melakukan perbaikan yang dapat diselesaikan saat itu sesuai prosedur.", score: 5 },
      { id: "c", label: "Memeriksa kelengkapan berkas dan menjelaskan langkah perbaikan agar warga dapat menyiapkannya tanpa kesalahan.", score: 3 },
      { id: "d", label: "Mengonfirmasi data yang berbeda pada sistem dan mengarahkan warga pada prosedur koreksi yang paling memungkinkan diselesaikan hari itu.", score: 4 },
      { id: "e", label: "Membantu mencatat data yang perlu diperbaiki dan memberikan informasi lengkap agar warga tidak mengalami kendala saat pengajuan berikutnya.", score: 1 },
    ],
    explanation: "Orientasi pelayanan publik yang prima mengutamakan empati, ketelitian, dan inisiatif memberikan solusi cepat (one-day service) sesuai ketentuan tanpa merepotkan masyarakat.",
  },
  {
    id: "mini-tkp-10",
    category: "TKP",
    topic: "Pelayanan Publik",
    prompt: "Anda menjadi petugas pelayanan di perpustakaan daerah. Seorang lansia kesulitan mencari buku melalui katalog digital, sementara antrean pengguna mulai bertambah. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Menjelaskan cara menggunakan katalog secara singkat, lalu meminta lansia mencoba kembali secara mandiri.", score: 2 },
      { id: "b", label: "Membantu pencarian sampai buku ditemukan sambil meminta pengguna lain menunggu sebentar.", score: 3 },
      { id: "c", label: "Mendampingi pada bagian yang sulit, lalu memastikan lansia dapat melanjutkan pencarian sambil menjaga antrean tetap berjalan.", score: 5 },
      { id: "d", label: "Membantu menemukan informasi buku yang dicari, kemudian mengarahkan lansia ke lokasi buku agar pelayanan dapat dilanjutkan.", score: 4 },
      { id: "e", label: "Menunjukkan tahapan pencarian pada katalog dan mengarahkan lansia kepada petugas lain jika masih membutuhkan bantuan.", score: 1 },
    ],
    explanation: "Pelayanan inklusif terhadap kelompok rentan (lansia) dilakukan dengan mendampingi bagian tersulit, lalu memberdayakannya agar antrean pemustaka lain tetap terlayani secara proporsional.",
  },
  {
    id: "mini-tkp-11",
    category: "TKP",
    topic: "Pelayanan Publik",
    prompt: "Anda bertugas menerima berkas bantuan pendidikan. Seorang warga kekurangan satu lampiran yang masih diproses instansi lain, sedangkan batas pengumpulan tinggal satu hari. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Memeriksa berkas lainnya dan menjelaskan cara melengkapi lampiran agar pengajuan masih dapat dilakukan tepat waktu.", score: 3 },
      { id: "b", label: "Menerima berkas yang tersedia terlebih dahulu sambil meminta warga menyerahkan lampiran segera setelah diterbitkan.", score: 1 },
      { id: "c", label: "Menjelaskan persyaratan yang belum terpenuhi dan membantu mengecek alternatif dokumen yang diperbolehkan sesuai ketentuan.", score: 4 },
      { id: "d", label: "Mengarahkan warga menghubungi instansi penerbit untuk mempercepat lampiran dan kembali sebelum batas pengumpulan.", score: 2 },
      { id: "e", label: "Mengecek ketentuan terkait berkas yang masih diproses, lalu mengarahkan warga pada mekanisme yang sah agar pengajuan tidak terlambat.", score: 5 },
    ],
    explanation: "Aparatur pelayanan publik memberikan kepastian hukum dengan mengecek diskresi/mekanisme sah bagi berkas dalam proses agar hak masyarakat tidak gugur karena keterlambatan instansi lain.",
  },
  {
    id: "mini-tkp-12",
    category: "TKP",
    topic: "Pelayanan Publik",
    prompt: "Anda bertugas menerima berkas bantuan pendidikan. Seorang warga kekurangan satu lampiran yang masih diproses instansi lain. Batas pengumpulan tinggal satu hari. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Memeriksa berkas lain dan menjelaskan langkah yang perlu dilakukan agar lampiran dapat segera dilengkapi.", score: 3 },
      { id: "b", label: "Mengecek ketentuan terkait dokumen yang masih diproses dan membantu warga menggunakan mekanisme yang diperbolehkan.", score: 5 },
      { id: "c", label: "Menjelaskan kekurangan berkas dan membantu mencari dokumen pengganti yang dapat digunakan sesuai ketentuan.", score: 4 },
      { id: "d", label: "Mengarahkan warga meminta bukti bahwa dokumen sedang diproses untuk kemudian diperiksa kemungkinan penggunaannya.", score: 2 },
      { id: "e", label: "Membantu warga memastikan persyaratan lain sudah lengkap sambil menunggu lampiran tersebut diterbitkan.", score: 1 },
    ],
    explanation: "Petugas yang solutif proaktif memeriksa aturan terkait dokumen yang tertunda dan memandu warga melalui prosedur resmi yang diperkenankan agar tenggat waktu pengajuan terpenuhi.",
  },
  {
    id: "mini-tkp-13",
    category: "TKP",
    topic: "Pelayanan Publik",
    prompt: "Anda bertugas di pusat layanan masyarakat. Seorang warga menyampaikan kritik karena informasi jam pelayanan di media sosial berbeda dengan yang tertera di kantor. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Memeriksa informasi yang berlaku dan menjelaskan kondisi kepada warga.", score: 5 },
      { id: "b", label: "Mencatat kritik tersebut untuk disampaikan kepada pengelola media.", score: 4 },
      { id: "c", label: "Meminta warga mengikuti informasi terbaru melalui media sosial.", score: 1 },
      { id: "d", label: "Menghubungi pengelola media agar informasi yang berbeda segera diperbaiki.", score: 3 },
      { id: "e", label: "Menjelaskan bahwa jadwal dapat berubah sesuai kondisi pelayanan.", score: 2 },
    ],
    explanation: "Merespons kritik warga secara langsung dengan memverifikasi fakta dan memberikan penjelasan yang ramah dan akurat menunjukkan sikap tanggap dan bertanggung jawab.",
  },
  {
    id: "mini-tkp-14",
    category: "TKP",
    topic: "Pelayanan Publik",
    prompt: "Anda bertugas di loket administrasi kependudukan. Saat antrean padat, sistem mengalami gangguan sehingga pelayanan melambat. Beberapa warga mulai mengeluh dan meminta proses dipercepat. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Menjelaskan gangguan yang terjadi dan tetap melayani sesuai urutan sambil menggunakan prosedur alternatif yang tersedia.", score: 5 },
      { id: "b", label: "Menenangkan warga dan menyampaikan bahwa pelayanan akan dilanjutkan sesuai antrean setelah sistem kembali stabil.", score: 1 },
      { id: "c", label: "Menginformasikan kendala kepada warga dan memprioritaskan proses yang masih dapat diselesaikan selama sistem terganggu.", score: 4 },
      { id: "d", label: "Menjelaskan kondisi sistem dan memperkirakan waktu tunggu agar warga dapat menentukan apakah tetap menunggu atau kembali nanti.", score: 2 },
      { id: "e", label: "Tetap melayani sesuai antrean sambil meminta petugas terkait menangani gangguan agar proses segera kembali normal.", score: 3 },
    ],
    explanation: "Komunikasi transparan mengenai kendala teknis yang dibarengi tindakan nyata memanfaatkan prosedur cadangan (offline/manual) menjaga kelancaran dan kepercayaan publik.",
  },
  {
    id: "mini-tkp-15",
    category: "TKP",
    topic: "Pelayanan Publik",
    prompt: "Anda bertugas di kantor pajak daerah. Seorang warga mengeluhkan tagihan yang lebih besar dari tahun sebelumnya dan membawa bukti pembayaran lama. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Membandingkan bukti lama dengan tagihan terbaru dan menjelaskan faktor yang menyebabkan perbedaan berdasarkan data yang tersedia.", score: 4 },
      { id: "b", label: "Memeriksa rincian tagihan pada sistem dan menjelaskan perbedaannya, lalu mengarahkan koreksi jika ditemukan ketidaksesuaian.", score: 5 },
      { id: "c", label: "Menjelaskan dasar penghitungan tagihan terbaru dan meminta warga memeriksa kembali kesesuaiannya dengan bukti pembayaran lama.", score: 2 },
      { id: "d", label: "Memeriksa data pembayaran sebelumnya dan tagihan terbaru, lalu menjelaskan prosedur keberatan apabila warga masih merasa dirugikan.", score: 3 },
      { id: "e", label: "Membantu warga mengidentifikasi bagian tagihan yang berubah dan mengarahkan konfirmasi lebih lanjut kepada bagian terkait.", score: 1 },
    ],
    explanation: "Petugas yang kompeten memeriksa rincian sistem secara cermat, menguraikan perhitungannya secara terbuka, dan segera memandu mekanisme perbaikan bila ada kesalahan input/sistem.",
  },
  {
    id: "mini-tkp-16",
    category: "TKP",
    topic: "Pelayanan Publik",
    prompt: "Anda bertugas di kantor pelayanan dokumen perjalanan. Seorang warga datang menjelang jam tutup, tetapi satu dokumen persyaratan belum dibawa. Ia harus bepergian dalam beberapa hari. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Memeriksa berkas yang tersedia dan menjelaskan cara tercepat melengkapi kekurangan agar pengajuan dapat segera diproses.", score: 4 },
      { id: "b", label: "Menjelaskan dokumen yang kurang dan meminta warga kembali setelah seluruh persyaratan lengkap.", score: 1 },
      { id: "c", label: "Mengecek ketentuan yang berlaku dan membantu mencari mekanisme resmi yang memungkinkan pengajuan tetap dilakukan tepat waktu.", score: 5 },
      { id: "d", label: "Memeriksa kelengkapan lainnya dan memberi informasi mengenai waktu pelayanan agar warga dapat kembali secepatnya.", score: 2 },
      { id: "e", label: "Menjelaskan persyaratan dan membantu memastikan dokumen lain sudah sesuai agar tidak ada kekurangan saat pengajuan berikutnya.", score: 3 },
    ],
    explanation: "Pelayanan berorientasi solusi memadukan kepatuhan regulasi dengan inisiatif mencarikan jalur resmi (misal layanan percepatan/unggah susulan) bagi kebutuhan warga yang mendesak.",
  },
  {
    id: "mini-tkp-17",
    category: "TKP",
    topic: "Jejaring Kerja",
    prompt: "Anda ditugaskan menyusun laporan gabungan yang memerlukan data dari tiga instansi. Salah satu instansi lambat merespons sehingga menghambat penyelesaian laporan. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Menghubungi kembali PIC instansi tersebut dan menjelaskan urgensi data serta tenggat laporan agar dapat segera ditindaklanjuti.", score: 4 },
      { id: "b", label: "Meminta bantuan rekan yang mengenal pegawai di instansi tersebut agar permintaan data lebih cepat mendapat respons.", score: 1 },
      { id: "c", label: "Menindaklanjuti melalui jalur koordinasi resmi dan menawarkan klarifikasi jika terdapat kendala dalam penyediaan data.", score: 5 },
      { id: "d", label: "Mengolah data dari dua instansi terlebih dahulu sambil menunggu respons agar penyusunan laporan tetap berjalan.", score: 2 },
      { id: "e", label: "Menghubungi PIC untuk memastikan kendalanya, lalu menyepakati waktu penyampaian data yang realistis bagi kedua pihak.", score: 3 },
    ],
    explanation: "Menjalin kemitraan kerja efektif dilakukan melalui jalur formal yang beretika, disertai sikap kooperatif menawarkan bantuan penyelesaian kendala bersama.",
  },
  {
    id: "mini-tkp-18",
    category: "TKP",
    topic: "Jejaring Kerja",
    prompt: "Anda adalah anggota tim pelayanan terpadu kecamatan. Unit pertanahan meminta bantuan Anda menyampaikan perubahan jadwal kepada warga, tetapi informasi tersebut belum diterima secara resmi oleh tim Anda. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Meminta unit pertanahan memberikan informasi resminya, lalu menyampaikannya kepada koordinator tim untuk ditindaklanjuti.", score: 5 },
      { id: "b", label: "Mengonfirmasi informasi kepada unit pertanahan dan meneruskannya kepada koordinator sebagai bahan penyampaian kepada warga.", score: 4 },
      { id: "c", label: "Menyampaikan permintaan unit pertanahan kepada koordinator dan menunggu arahan sebelum membantu penyebaran informasi.", score: 3 },
      { id: "d", label: "Meminta unit pertanahan berkoordinasi langsung dengan koordinator agar perubahan jadwal dapat segera ditindaklanjuti.", score: 1 },
      { id: "e", label: "Mengonfirmasi kebenaran jadwal kepada unit pertanahan sambil memberi tahu koordinator bahwa terdapat perubahan informasi pelayanan.", score: 2 },
    ],
    explanation: "Kolaborasi antarunit kerja harus didukung kejelasan dokumen resmi agar penyebaran informasi publik memiliki legalitas kuat dan koordinasi internal tetap terjaga.",
  },
  {
    id: "mini-tkp-19",
    category: "TKP",
    topic: "Jejaring Kerja",
    prompt: "Anda menjadi staf yang membantu menyiapkan kerja sama dengan organisasi masyarakat untuk program bantuan sosial. Mitra mengusulkan perubahan skema yang berbeda dari rencana awal, tetapi berpotensi menguntungkan kedua pihak. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Membahas manfaat dan risikonya bersama mitra, lalu menyampaikan hasilnya kepada penanggung jawab untuk dipertimbangkan.", score: 5 },
      { id: "b", label: "Menerima usulan tersebut sebagai alternatif dan meminta mitra menyiapkan rincian agar dapat dibahas lebih lanjut.", score: 3 },
      { id: "c", label: "Mempelajari kesesuaian usulan dengan tujuan program, lalu menyampaikannya kepada penanggung jawab sebagai alternatif kerja sama.", score: 4 },
      { id: "d", label: "Mendiskusikan usulan dengan mitra untuk mencari titik temu yang tetap sesuai dengan kepentingan program.", score: 2 },
      { id: "e", label: "Menampung usulan mitra dan menyampaikannya kepada penanggung jawab tanpa memberikan penilaian agar keputusan tetap objektif.", score: 1 },
    ],
    explanation: "Kemitraan yang produktif terbangun saat kedua pihak mampu menganalisis manfaat dan risiko usulan inovatif secara transparan sebelum diserahkan kepada pengambil keputusan.",
  },
  {
    id: "mini-tkp-20",
    category: "TKP",
    topic: "Jejaring Kerja",
    prompt: "Anda adalah staf sekretariat dalam kegiatan kerja sama antarkabupaten. Salah satu perwakilan daerah mengeluhkan informasi teknis yang sering terlambat karena perubahan dari beberapa pihak. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Menjelaskan penyebab keterlambatan dan meminta setiap pihak lebih cepat menyampaikan perubahan informasi.", score: 1 },
      { id: "b", label: "Mencatat keluhan tersebut dan mengusulkan kepada koordinator agar alur penyampaian informasi antarperwakilan diperjelas.", score: 4 },
      { id: "c", label: "Mengklarifikasi kendala kepada perwakilan tersebut, lalu meneruskan masukannya kepada koordinator untuk perbaikan komunikasi.", score: 3 },
      { id: "d", label: "Mengusulkan kepada koordinator penggunaan satu jalur informasi terkonfirmasi agar perubahan dapat diterima semua pihak secara seragam.", score: 5 },
      { id: "e", label: "Menyampaikan perubahan informasi kepada perwakilan segera setelah Anda menerimanya agar keterlambatan tidak kembali terjadi.", score: 2 },
    ],
    explanation: "Menyediakan single source of truth (satu pintu informasi terverifikasi) merupakan solusi sistemik terbaik untuk mencegah miskomunikasi dalam jejaring kerja multisektoral.",
  },
  {
    id: "mini-tkp-21",
    category: "TKP",
    topic: "Jejaring Kerja",
    prompt: "Anda menjadi penghubung dinas dengan perusahaan swasta dalam program CSR bagi masyarakat kurang mampu. Perusahaan ingin mengubah sasaran penerima karena pertimbangan citra, sedangkan data dinas menunjukkan sasaran awal masih lebih membutuhkan bantuan. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Menjelaskan data sasaran kepada perusahaan dan mencari alternatif publikasi yang tetap mendukung citra tanpa mengubah penerima prioritas.", score: 5 },
      { id: "b", label: "Menyampaikan usulan perusahaan beserta data dinas kepada penanggung jawab program untuk menentukan tindak lanjut.", score: 3 },
      { id: "c", label: "Membahas kembali dasar penentuan sasaran dengan perusahaan, lalu menyampaikan hasil pembahasan kepada penanggung jawab program.", score: 4 },
      { id: "d", label: "Mengusulkan agar sasaran awal dipertahankan berdasarkan data sambil tetap membuka ruang pembahasan kepentingan perusahaan.", score: 2 },
      { id: "e", label: "Meminta perusahaan memberikan alasan perubahan secara tertulis agar dapat menjadi bahan evaluasi dinas.", score: 1 },
    ],
    explanation: "Diplomasi jejaring kerja yang matang mampu mengakomodasi kebutuhan branding mitra swasta tanpa mengorbankan akurasi data dan prioritas penerima manfaat program pemerintah.",
  },
  {
    id: "mini-tkp-22",
    category: "TKP",
    topic: "Jejaring Kerja",
    prompt: "Anda adalah staf pelaksana kegiatan pelatihan di sebuah instansi. Peserta dari instansi mitra menilai materi kurang sesuai dengan kebutuhan unitnya dan mengusulkan sesi tambahan, sedangkan waktu kegiatan terbatas. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Mencatat usulan peserta dan menyampaikannya kepada penanggung jawab sebagai bahan penyesuaian kegiatan.", score: 3 },
      { id: "b", label: "Menggali kebutuhan peserta lebih lanjut, lalu menyampaikan usulan sesi tambahan kepada penanggung jawab kegiatan.", score: 4 },
      { id: "c", label: "Menyarankan peserta menyampaikan kebutuhan unitnya melalui evaluasi kegiatan agar dapat dipertimbangkan pada pelatihan berikutnya.", score: 1 },
      { id: "d", label: "Mengidentifikasi kebutuhan utama peserta dan mengusulkan alternatif yang tidak mengganggu agenda kepada penanggung jawab.", score: 5 },
      { id: "e", label: "Menampung masukan peserta dan menawarkan materi pendukung yang tersedia sambil tetap mengikuti susunan kegiatan.", score: 2 },
    ],
    explanation: "Menemukan titik temu dengan merumuskan alternatif solusi cerdas (misal ringkasan/materi tambahan mandiri) menjaga kepuasan mitra tanpa merusak jadwal kegiatan bersama.",
  },
  {
    id: "mini-tkp-23",
    category: "TKP",
    topic: "Jejaring Kerja",
    prompt: "Anda merupakan kepala subbagian yang memimpin tim lintas unit dalam penyusunan laporan kinerja. Salah satu unit merasa kontribusinya kurang terlihat dan meminta bagiannya diperluas, sedangkan ruang laporan terbatas. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Meminta unit tersebut memilih capaian utama yang paling mewakili kontribusinya untuk dimasukkan dalam laporan.", score: 3 },
      { id: "b", label: "Meninjau kembali porsi setiap unit dan menyesuaikannya berdasarkan relevansi kontribusi terhadap capaian bersama.", score: 5 },
      { id: "c", label: "Membahas kebutuhan unit tersebut bersama perwakilannya dan mencari penyajian yang tetap proporsional bagi seluruh unit.", score: 4 },
      { id: "d", label: "Mempertahankan susunan laporan, tetapi menambahkan kontribusi unit tersebut pada bagian yang masih memungkinkan.", score: 1 },
      { id: "e", label: "Mengajak perwakilan unit menyepakati prioritas informasi agar kontribusinya terlihat tanpa mengurangi keseimbangan laporan.", score: 2 },
    ],
    explanation: "Pemimpin kolaboratif mengelola keberagaman tim dengan meninjau proporsi laporan berdasarkan signifikansi kontribusi strategis terhadap target organisasi bersama.",
  },
  {
    id: "mini-tkp-24",
    category: "TKP",
    topic: "Sosial Budaya",
    prompt: "Anda menjadi anggota tim pelayanan masyarakat. Pegawai baru dari daerah lain beberapa kali tidak dilibatkan dalam pembicaraan informal karena dianggap belum memahami kebiasaan tim. Ia pun mulai lebih banyak bekerja sendiri. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Mengajaknya lebih sering berdiskusi dan membantu memahami kebiasaan tim agar ia lebih mudah beradaptasi.", score: 4 },
      { id: "b", label: "Mendorong rekan lain melibatkannya dalam komunikasi tim sambil membantunya memahami kebiasaan kerja yang belum familiar.", score: 5 },
      { id: "c", label: "Mengajak pegawai tersebut berinteraksi dalam kegiatan bersama agar hubungan dengan anggota tim berkembang secara alami.", score: 3 },
      { id: "d", label: "Membantu menjelaskan kebiasaan tim kepadanya dan menyarankan agar ia lebih aktif memulai komunikasi dengan rekan lain.", score: 1 },
      { id: "e", label: "Melibatkannya dalam pembicaraan yang berkaitan dengan pekerjaan agar ia memiliki kesempatan membangun kedekatan dengan tim.", score: 2 },
    ],
    explanation: "Menciptakan lingkungan kerja multikultural yang inklusif dilakukan dengan menjembatani komunikasi dua arah: mengajak tim menerima rekan baru dan membantunya beradaptasi.",
  },
  {
    id: "mini-tkp-25",
    category: "TKP",
    topic: "Sosial Budaya",
    prompt: "Anda bertugas dalam tim yang akan melakukan kunjungan kerja ke daerah dengan kebiasaan masyarakat yang berbeda. Salah satu anggota menilai beberapa kebiasaan setempat kurang efisien untuk kegiatan. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Mengajak tim memahami kebiasaan setempat dan menyesuaikan pelaksanaan kegiatan selama tujuan kerja tetap tercapai.", score: 4 },
      { id: "b", label: "Mempelajari kebiasaan setempat terlebih dahulu dan menentukan bagian yang perlu diperhatikan selama kunjungan.", score: 3 },
      { id: "c", label: "Mengusulkan penyesuaian teknis yang tetap menghormati kebiasaan masyarakat tanpa menghambat tujuan kegiatan.", score: 5 },
      { id: "d", label: "Mengingatkan anggota tersebut agar menghormati kebiasaan setempat meskipun berbeda dengan cara kerja tim.", score: 1 },
      { id: "e", label: "Mendiskusikan kebiasaan tersebut dengan pihak setempat agar tim memahami cara berinteraksi yang tepat selama kegiatan.", score: 2 },
    ],
    explanation: "Kepekaan sosial budaya tercermin dari kompromi konstruktif yang menghargai kearifan lokal masyarakat tanpa menurunkan standar efektivitas tugas kedinasan.",
  },
  {
    id: "mini-tkp-26",
    category: "TKP",
    topic: "Sosial Budaya",
    prompt: "Dalam rapat unit, seorang pegawai senior cukup dominan sehingga pegawai yang lebih muda jarang menyampaikan pandangan. Anda bukan pimpinan rapat. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Mengajak pegawai yang belum berbicara menyampaikan pandangannya saat terdapat kesempatan dalam diskusi.", score: 4 },
      { id: "b", label: "Menyampaikan pandangan Anda sambil mengaitkannya dengan masukan pegawai lain agar diskusi menjadi lebih berimbang.", score: 3 },
      { id: "c", label: "Mengusulkan kepada pimpinan rapat agar anggota lain juga diberi kesempatan menyampaikan pandangan.", score: 5 },
      { id: "d", label: "Mendengarkan pembahasan dan berdiskusi dengan pegawai yang lebih muda setelah rapat untuk mengetahui pandangan mereka.", score: 1 },
      { id: "e", label: "Menanggapi pendapat pegawai senior secara sopan, lalu membuka ruang bagi rekan lain untuk menambahkan perspektif.", score: 2 },
    ],
    explanation: "Mengusulkan secara santun kepada pimpinan rapat untuk memfasilitasi partisipasi seluruh peserta merupakan etika birokrasi yang tepat untuk menciptakan iklim kerja demokratis dan setara.",
  },
  {
    id: "mini-tkp-27",
    category: "TKP",
    topic: "Sosial Budaya",
    prompt: "Anda menjadi koordinator kegiatan kantor yang melibatkan pegawai dari beberapa generasi. Pegawai muda ingin menggunakan metode digital, sedangkan sebagian pegawai senior merasa kesulitan. Perbedaan mulai memengaruhi pembagian tugas. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Membagi tugas sesuai kemampuan masing-masing sambil tetap memberi kesempatan untuk mempelajari metode kerja yang berbeda.", score: 3 },
      { id: "b", label: "Mengajak tim menyepakati cara kerja yang dapat digunakan bersama tanpa mengabaikan kebutuhan setiap kelompok.", score: 4 },
      { id: "c", label: "Menggunakan metode digital pada bagian yang sesuai dan memberikan pendampingan bagi anggota yang belum terbiasa.", score: 2 },
      { id: "d", label: "Memadukan metode kerja yang memungkinkan sambil mengatur pembagian tugas berdasarkan kebutuhan kegiatan dan kemampuan anggota.", score: 5 },
      { id: "e", label: "Meminta anggota yang lebih terbiasa dengan teknologi membantu pegawai senior agar metode digital dapat diterapkan secara bertahap.", score: 1 },
    ],
    explanation: "Harmonisasi antargenerasi (intergenerational synergy) tercapai melalui perpaduan metode kerja hybrid dan penempatan tugas berbasis kekuatan kompetensi masing-masing anggota.",
  },
  {
    id: "mini-tkp-28",
    category: "TKP",
    topic: "Sosial Budaya",
    prompt: "Anda bekerja di kantor pelayanan dengan masyarakat dari beragam latar budaya. Seorang rekan menilai warga dari kelompok tertentu lebih sulit diajak berkomunikasi berdasarkan pengalamannya. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Mengajak rekan memahami karakter komunikasi kelompok tersebut agar pendekatan pelayanan dapat disesuaikan sejak awal.", score: 1 },
      { id: "b", label: "Menyarankan rekan mencoba pendekatan komunikasi berbeda dan menilai respons setiap warga sebelum menentukan cara pelayanan.", score: 3 },
      { id: "c", label: "Mengajak rekan membahas pengalaman tersebut untuk mengenali hambatan komunikasi tanpa menjadikannya penilaian terhadap seluruh kelompok.", score: 4 },
      { id: "d", label: "Mengingatkan rekan agar tetap objektif sambil mempertimbangkan perbedaan budaya yang mungkin memengaruhi cara warga berkomunikasi.", score: 2 },
      { id: "e", label: "Mengajak rekan mengevaluasi cara komunikasinya dan menyesuaikan pendekatan berdasarkan kebutuhan warga yang sedang dilayani.", score: 5 },
    ],
    explanation: "Menghindari stereotipe budaya diawali dengan refleksi diri (self-evaluation) dan fleksibilitas beradaptasi dengan gaya komunikasi penerima layanan secara berkeadilan.",
  },
  {
    id: "mini-tkp-29",
    category: "TKP",
    topic: "Sosial Budaya",
    prompt: "Anda menjadi ketua panitia kegiatan warga. Dua kelompok mengusulkan bentuk kegiatan berbeda sesuai kebiasaan masing-masing. Waktu persiapan terbatas dan keputusan harus segera dibuat. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Memilih unsur utama dari kedua usulan agar masing-masing kelompok tetap terwakili dalam kegiatan.", score: 3 },
      { id: "b", label: "Meminta kedua kelompok menentukan bagian usulan yang paling penting, lalu menyusun kegiatan berdasarkan prioritas bersama.", score: 4 },
      { id: "c", label: "Membandingkan kedua usulan berdasarkan kebutuhan kegiatan dan memilih bentuk yang paling memungkinkan diterapkan.", score: 1 },
      { id: "d", label: "Mengajak perwakilan kedua kelompok menyepakati bentuk kegiatan yang dapat diterima bersama dalam waktu yang tersedia.", score: 5 },
      { id: "e", label: "Menentukan bentuk kegiatan yang mengakomodasi kepentingan utama kedua kelompok setelah mendengar alasan masing-masing.", score: 2 },
    ],
    explanation: "Musyawarah mufakat cepat dengan menghadirkan perwakilan inti menciptakan konsensus bersama dan meminimalkan gesekan sosial antarkelompok warga.",
  },
  {
    id: "mini-tkp-30",
    category: "TKP",
    topic: "Sosial Budaya",
    prompt: "Anda baru ditempatkan di unit kerja dengan kebiasaan koordinasi yang berbeda. Beberapa prosedur informal belum Anda pahami sehingga pernah terjadi salah komunikasi dengan rekan. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Mengikuti pola koordinasi rekan yang lebih lama sambil menyesuaikan cara komunikasi agar kesalahan serupa tidak terjadi.", score: 2 },
      { id: "b", label: "Mempelajari kebiasaan koordinasi tim dan mengklarifikasi bagian yang belum dipahami kepada rekan yang terkait.", score: 4 },
      { id: "c", label: "Meminta rekan menjelaskan kebiasaan koordinasi yang berlaku, lalu menerapkannya selama tidak bertentangan dengan prosedur resmi.", score: 3 },
      { id: "d", label: "Mengamati pola komunikasi tim terlebih dahulu dan mencatat kebiasaan yang perlu Anda sesuaikan dalam pekerjaan berikutnya.", score: 1 },
      { id: "e", label: "Mengevaluasi penyebab salah komunikasi dan aktif menyesuaikan cara koordinasi dengan kebiasaan tim tanpa mengabaikan prosedur resmi.", score: 5 },
    ],
    explanation: "Adaptasi budaya kerja yang sehat memerlukan introspeksi aktif atas akar masalah komunikasi dan kesediaan membaur dengan tim tanpa melanggar regulasi kedinasan.",
  },
  {
    id: "mini-tkp-31",
    category: "TKP",
    topic: "Teknologi Informasi dan Komunikasi",
    prompt: "Anda menggunakan chatbot internal untuk membantu layanan informasi pegawai. Chatbot memberikan jawaban yang berbeda dengan pedoman terbaru, dan beberapa pegawai sudah menerima informasi tersebut. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Mengklarifikasi jawaban kepada pegawai berdasarkan pedoman terbaru, lalu mencatat ketidaksesuaian chatbot untuk evaluasi sistem.", score: 4 },
      { id: "b", label: "Memastikan pedoman terbaru telah berlaku, kemudian meminta pengelola sistem menyesuaikan basis informasi chatbot.", score: 2 },
      { id: "c", label: "Memverifikasi pedoman, mengoreksi informasi yang terlanjur diterima, dan meneruskan ketidaksesuaian chatbot untuk diperbarui.", score: 5 },
      { id: "d", label: "Mengarahkan penggunaan pedoman terbaru untuk pertanyaan serupa sambil melaporkan jawaban chatbot yang perlu disesuaikan.", score: 3 },
      { id: "e", label: "Membatasi sementara chatbot pada topik tersebut, lalu meminta pengelola sistem memeriksa kesesuaiannya dengan pedoman terbaru.", score: 1 },
    ],
    explanation: "Tindakan komprehensif mengintegrasikan validasi pedoman, pemulihan dampak (koreksi pegawai yang menerima info keliru), dan pelaporan perbaikan knowledge base sistem AI/chatbot.",
  },
  {
    id: "mini-tkp-32",
    category: "TKP",
    topic: "Teknologi Informasi dan Komunikasi",
    prompt: "Anda bertugas sebagai staf keuangan yang menggunakan aplikasi pengajuan perjalanan dinas. Saat menginput data, Anda menemukan nominal biaya pada sistem berbeda dengan dokumen perjalanan yang telah disetujui. Batas pengajuan tinggal beberapa jam. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Menggunakan nominal pada dokumen persetujuan dan menyimpan bukti perbedaannya", score: 4 },
      { id: "b", label: "Menghubungi bagian terkait untuk memastikan nominal yang seharusnya digunakan", score: 5 },
      { id: "c", label: "Menginput nominal sistem terlebih dahulu agar pengajuan tidak melewati batas waktu", score: 1 },
      { id: "d", label: "Membandingkan kembali seluruh komponen biaya sebelum melakukan pengajuan", score: 3 },
      { id: "e", label: "Menunda pengajuan sampai terdapat penjelasan mengenai perbedaan nominal", score: 2 },
    ],
    explanation: "Konfirmasi langsung dan cepat kepada unit pengesah mencegah kesalahan akuntansi dan kepatuhan anggaran dalam pemanfaatan sistem informasi keuangan.",
  },
  {
    id: "mini-tkp-33",
    category: "TKP",
    topic: "Teknologi Informasi dan Komunikasi",
    prompt: "Anda menjadi admin media sosial instansi. Sebuah unggahan mendapat banyak komentar karena sebagian informasinya dianggap membingungkan. Pimpinan meminta komunikasi dengan masyarakat tetap berjalan baik. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Menanggapi komentar dengan penjelasan yang tersedia sambil mencatat bagian informasi yang perlu diperjelas.", score: 2 },
      { id: "b", label: "Memeriksa kembali isi unggahan dengan sumber resmi, lalu memberikan klarifikasi melalui kanal media sosial yang sama.", score: 4 },
      { id: "c", label: "Menjawab pertanyaan yang paling sering muncul dan menambahkan informasi penjelas pada unggahan agar mudah ditemukan.", score: 3 },
      { id: "d", label: "Memverifikasi bagian yang membingungkan, memperbarui informasi jika diperlukan, lalu memberikan klarifikasi kepada masyarakat.", score: 5 },
      { id: "e", label: "Menyusun penjelasan berdasarkan informasi yang tersedia dan meminta konfirmasi unit terkait sebelum mempublikasikannya.", score: 1 },
    ],
    explanation: "Manajemen komunikasi digital responsif dilakukan dengan membedah titik kerancuan konten, memperbarui infografik/teks secara faktual, dan merilis klarifikasi resmi kepada warganet.",
  },
  {
    id: "mini-tkp-34",
    category: "TKP",
    topic: "Teknologi Informasi dan Komunikasi",
    prompt: "Anda bekerja sebagai staf pengelola inventaris. Seluruh barang kantor mulai dicatat melalui aplikasi inventaris baru. Setelah beberapa hari, Anda menemukan beberapa nomor barang pada aplikasi berbeda dengan label fisik di ruangan. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Mencatat perbedaan tersebut dan memperbaruinya setelah seluruh barang diperiksa", score: 3 },
      { id: "b", label: "Memeriksa barang yang bermasalah dan mencocokkannya dengan dokumen inventaris", score: 5 },
      { id: "c", label: "Meminta rekan melakukan pengecekan agar proses pencocokan lebih cepat", score: 2 },
      { id: "d", label: "Menggunakan nomor pada label fisik sebagai dasar pembaruan data", score: 4 },
      { id: "e", label: "Melaporkan perbedaan nomor barang kepada pengelola sistem untuk ditindaklanjuti", score: 1 },
    ],
    explanation: "Rekonsiliasi data aset digital dengan fisik wajib merujuk pada dokumen legal/berita acara inventaris master sebelum melakukan penyesuaian sistem.",
  },
  {
    id: "mini-tkp-35",
    category: "TKP",
    topic: "Teknologi Informasi dan Komunikasi",
    prompt: "Anda bertugas sebagai petugas informasi di kantor pelayanan. Sistem penerjemah digital digunakan untuk membantu warga yang kurang memahami bahasa Indonesia. Suatu saat, terjemahan istilah administrasi terlihat kurang tepat. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Membandingkan hasil terjemahan dengan sumber resmi, lalu menjelaskan istilah tersebut kepada warga dengan bahasa yang lebih sederhana.", score: 4 },
      { id: "b", label: "Menggunakan hasil terjemahan sebagai panduan awal sambil memastikan kembali istilah penting sebelum informasi diberikan kepada warga.", score: 3 },
      { id: "c", label: "Memverifikasi istilah yang diragukan, memberikan penjelasan yang tepat, lalu melaporkan kekeliruan untuk perbaikan sistem penerjemah.", score: 5 },
      { id: "d", label: "Menggunakan fitur terjemahan alternatif untuk membandingkan hasil sebelum menentukan penjelasan yang paling sesuai kepada warga.", score: 2 },
      { id: "e", label: "Menjelaskan maksud istilah berdasarkan konteks pelayanan, kemudian mencatat hasil terjemahan yang kurang tepat sebagai bahan evaluasi.", score: 1 },
    ],
    explanation: "Menangani kekurangan teknologi secara langsung pada pengguna (human touch) sekaligus menyampaikan laporan bug/anomali linguistik demi penyempurnaan sistem jangka panjang.",
  },
  {
    id: "mini-tkp-36",
    category: "TKP",
    topic: "Teknologi Informasi dan Komunikasi",
    prompt: "Anda bertugas membuat laporan bulanan dengan menggunakan data dari beberapa file spreadsheet milik unit berbeda. Saat digabungkan, terdapat nama kategori yang ditulis dengan format berbeda sehingga hasil perhitungan otomatis menjadi tidak konsisten. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Menyamakan kategori yang memiliki makna sama sebelum melakukan perhitungan", score: 5 },
      { id: "b", label: "Memeriksa kembali sumber data sebelum menentukan format kategori yang digunakan", score: 4 },
      { id: "c", label: "Menggunakan fitur penyaringan dan pengelompokan untuk menemukan kategori yang berbeda", score: 3 },
      { id: "d", label: "Meminta masing-masing unit menggunakan format yang sama pada laporan berikutnya", score: 2 },
      { id: "e", label: "Menggabungkan data sesuai format yang paling sering digunakan", score: 1 },
    ],
    explanation: "Data cleaning dan standarisasi entitas nilai sebelum pengolahan formula merupakan praktik integritas data mendasar dalam pemrosesan spreadsheet.",
  },
  {
    id: "mini-tkp-37",
    category: "TKP",
    topic: "Teknologi Informasi dan Komunikasi",
    prompt: "Anda menerima file hasil pemindaian dokumen melalui penyimpanan bersama. Ukurannya sangat besar sehingga sulit dibuka dan memperlambat pekerjaan tim, padahal dokumen segera diperlukan untuk verifikasi. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Mengunduh file ke perangkat kerja dan membukanya dengan aplikasi yang lebih ringan agar verifikasi dapat segera dilakukan.", score: 2 },
      { id: "b", label: "Mengoptimalkan ukuran file dengan aplikasi yang tersedia sambil memastikan kualitas dokumen tetap memadai untuk verifikasi.", score: 4 },
      { id: "c", label: "Membuat salinan file berukuran lebih kecil untuk proses verifikasi dan mempertahankan file asli pada penyimpanan resmi.", score: 3 },
      { id: "d", label: "Meminta rekan mengunggah ulang dokumen dengan resolusi lebih rendah agar file lebih mudah digunakan oleh seluruh anggota tim.", score: 1 },
      { id: "e", label: "Mengompresi salinan file sesuai kebutuhan verifikasi, memeriksa keterbacaannya, lalu membagikan versi tersebut melalui penyimpanan bersama.", score: 5 },
    ],
    explanation: "Tindakan proaktif mengompresi salinan file, memvalidasi legibilitas teks dokumen, dan membagikannya kembali di shared storage mempercepat kolaborasi seluruh tim secara sistemik.",
  },
  {
    id: "mini-tkp-38",
    category: "TKP",
    topic: "Teknologi Informasi dan Komunikasi",
    prompt: "Anda menjadi koordinator kegiatan yang menggunakan formulir digital untuk pendaftaran. Sehari sebelum kegiatan, beberapa peserta mengisi nomor kontak tidak lengkap sehingga sulit dihubungi. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Menghubungi peserta melalui data kontak lain yang tersedia dan memperbarui nomor mereka pada data kegiatan.", score: 4 },
      { id: "b", label: "Memeriksa data yang tidak lengkap dan meminta peserta memperbaikinya melalui tautan formulir sebelum kegiatan dimulai.", score: 3 },
      { id: "c", label: "Menggunakan kanal digital lain yang tersedia untuk mengonfirmasi nomor kontak, lalu memperbarui data peserta yang telah terverifikasi.", score: 2 },
      { id: "d", label: "Memperbaiki pengaturan formulir agar nomor kontak wajib memenuhi format tertentu dan menghubungi peserta yang datanya belum lengkap.", score: 5 },
      { id: "e", label: "Mengumpulkan kembali nomor kontak peserta yang bermasalah dan mencatatnya pada daftar terpisah untuk kebutuhan kegiatan.", score: 1 },
    ],
    explanation: "Menerapkan validasi input data (field regex/format requirement) mencegah masalah berulang sekaligus segera menjemput bola menyelesaikan data peserta yang bermasalah.",
  },
  {
    id: "mini-tkp-39",
    category: "TKP",
    topic: "Anti Radikalisme",
    prompt: "Anda adalah ketua tim pelayanan di sebuah kantor pemerintah. Seorang anggota tim meminta agar jadwal pelayanan kelompok masyarakat tertentu dipisahkan karena menurutnya interaksi antarkelompok sering menimbulkan ketegangan. Belum ada kejadian yang menunjukkan adanya ancaman, tetapi beberapa petugas mulai mendukung usulan tersebut. Anda akan...",
    choices: [
      { id: "a", label: "Menolak usulan tersebut karena pelayanan harus diberikan secara setara.", score: 3 },
      { id: "b", label: "Membahas usulan tersebut bersama petugas untuk mengetahui alasan yang mendasarinya.", score: 2 },
      { id: "c", label: "Mengatur pola pelayanan yang sama bagi seluruh kelompok dengan memperhatikan kondisi lapangan.", score: 4 },
      { id: "d", label: "Meminta petugas menjaga komunikasi agar perbedaan latar belakang tidak memengaruhi pelayanan.", score: 1 },
      { id: "e", label: "Mengkaji kebutuhan pengaturan pelayanan berdasarkan perilaku konkret, bukan identitas kelompok.", score: 5 },
    ],
    explanation: "Prinsip non-diskriminasi dan netralitas aparatur melarang segregasi layanan berbasis identitas primordial; setiap penataan keamanan wajib didasarkan pada indikator perilaku faktual dan objektif.",
  },
  {
    id: "mini-tkp-40",
    category: "TKP",
    topic: "Anti Radikalisme",
    prompt: "Anda merupakan anggota tim pengadaan barang. Seorang calon penyedia mengkritik aturan pengadaan dan menganggap beberapa ketentuan tidak adil. Kritik disampaikan cukup keras, tetapi tanpa ancaman atau ajakan melanggar aturan. Sikap Anda adalah...",
    choices: [
      { id: "a", label: "Menanggapi kritik berdasarkan ketentuan yang berlaku dan tetap menilai penyedia secara objektif sesuai kriteria pengadaan.", score: 4 },
      { id: "b", label: "Mencatat substansi kritik sebagai masukan dan menyampaikan kepada ketua tim apabila terdapat bagian yang relevan untuk ditindaklanjuti.", score: 3 },
      { id: "c", label: "Mengingatkan penyedia agar menyampaikan keberatan melalui mekanisme yang tersedia agar pembahasan rapat tetap kondusif.", score: 2 },
      { id: "d", label: "Tetap fokus pada evaluasi penyedia dan tidak menjadikan kritik terhadap aturan sebagai dasar penilaian selama tidak terkait kriteria pengadaan.", score: 5 },
      { id: "e", label: "Mengusulkan kepada ketua tim agar kritik dipisahkan dari proses evaluasi dan diarahkan ke mekanisme keberatan yang sesuai.", score: 1 },
    ],
    explanation: "Aparatur berintegritas memisahkan kritik prosedural warga/penyedia dari penilaian teknis agar keputusan pengadaan tetap objektif, adil, dan bebas dari sentimen personal.",
  },
  {
    id: "mini-tkp-41",
    category: "TKP",
    topic: "Anti Radikalisme",
    prompt: "Anda adalah koordinator relawan dalam kegiatan kebencanaan. Saat berada di lokasi, beberapa relawan menolak bekerja dengan kelompok relawan lain karena pernah terjadi perselisihan dalam kegiatan sebelumnya. Kondisi tersebut mulai menghambat distribusi bantuan. Anda akan...",
    choices: [
      { id: "a", label: "Meminta kedua kelompok kembali fokus pada pembagian bantuan.", score: 2 },
      { id: "b", label: "Membagi wilayah kerja agar kedua kelompok tidak perlu banyak berinteraksi.", score: 1 },
      { id: "c", label: "Menyatukan perwakilan kedua kelompok untuk menentukan pembagian tugas.", score: 5 },
      { id: "d", label: "Mengingatkan bahwa konflik sebelumnya tidak boleh menghambat kepentingan masyarakat.", score: 3 },
      { id: "e", label: "Menetapkan pembagian tugas berdasarkan kemampuan masing-masing kelompok.", score: 4 },
    ],
    explanation: "Membangun rekonsiliasi dan kesatuan aksi dengan melibatkan perwakilan kedua kubu bermusyawarah menegaskan orientasi kemanusiaan di atas rivalitas antarkelompok.",
  },
  {
    id: "mini-tkp-42",
    category: "TKP",
    topic: "Anti Radikalisme",
    prompt: "Anda adalah pegawai baru di daerah dengan karakter masyarakat yang berbeda. Beberapa kebiasaan setempat terasa kurang lazim, dan rekan lain mulai menganggapnya sebagai tanda masyarakat sulit menerima perubahan. Anda akan...",
    choices: [
      { id: "a", label: "Mengajak rekan memahami alasan di balik kebiasaan tersebut sebelum menyimpulkan sikap masyarakat terhadap perubahan.", score: 3 },
      { id: "b", label: "Mempelajari kebiasaan setempat dan mengingatkan rekan agar tidak menilai keterbukaan masyarakat hanya dari perbedaan kebiasaan.", score: 4 },
      { id: "c", label: "Menjaga sikap terbuka terhadap kebiasaan tersebut sambil mengamati respons masyarakat terhadap perubahan dalam kegiatan berikutnya.", score: 2 },
      { id: "d", label: "Berdiskusi dengan masyarakat setempat untuk memahami kebiasaan mereka dan menjadikannya dasar dalam menyesuaikan pendekatan kerja.", score: 1 },
      { id: "e", label: "Mengajak rekan membedakan kebiasaan budaya dari sikap menolak perubahan serta membangun komunikasi langsung dengan masyarakat.", score: 5 },
    ],
    explanation: "Sikap moderat dan bijak membedakan ekspresi tradisi kultural dari penolakan inovasi, serta memecahkan kecurigaan sosial melalui dialog langsung yang terbuka dengan warga.",
  },
  {
    id: "mini-tkp-43",
    category: "TKP",
    topic: "Anti Radikalisme",
    prompt: "Anda merupakan ketua panitia pemilihan pengurus organisasi mahasiswa. Menjelang pemungutan suara, muncul usulan agar calon dari kelompok tertentu tidak diberi kesempatan menyampaikan visi karena dikhawatirkan akan membawa kepentingan kelompoknya. Tidak ada bukti bahwa calon tersebut pernah melakukan tindakan diskriminatif. Anda akan...",
    choices: [
      { id: "a", label: "Tetap memberi calon kesempatan yang sama dan menilai penyampaiannya berdasarkan isi visi serta aturan pemilihan.", score: 4 },
      { id: "b", label: "Meminta panitia tidak menggunakan latar kelompok sebagai dasar pembatasan selama calon memenuhi ketentuan yang berlaku.", score: 3 },
      { id: "c", label: "Memberikan kesempatan menyampaikan visi dengan pengawasan yang sama seperti calon lain untuk memastikan aturan tetap dipatuhi.", score: 2 },
      { id: "d", label: "Membahas kekhawatiran panitia terlebih dahulu, lalu memastikan keputusan terhadap calon didasarkan pada perilaku yang dapat dibuktikan.", score: 1 },
      { id: "e", label: "Menegaskan kesempatan yang setara bagi seluruh calon dan menerapkan ketentuan yang sama jika ditemukan materi diskriminatif.", score: 5 },
    ],
    explanation: "Menjamin hak kesetaraan konstitusional tanpa diskriminasi latar belakang kelompok, dibarengi penegakan sanksi tegas jika terjadi pelanggaran aturan secara nyata.",
  },
  {
    id: "mini-tkp-44",
    category: "TKP",
    topic: "Anti Radikalisme",
    prompt: "Anda adalah pengurus lingkungan yang bertugas membantu pelaksanaan kegiatan warga. Dalam sebuah pertemuan, muncul perbedaan pendapat mengenai penggunaan fasilitas umum. Sebagian warga mengusulkan kegiatan kelompoknya mendapat prioritas karena sudah lebih dahulu menggunakan fasilitas tersebut pada tahun sebelumnya. Kelompok lain merasa hal itu tidak adil. Anda akan...",
    choices: [
      { id: "a", label: "Meminta kedua pihak menyampaikan kebutuhan masing-masing.", score: 3 },
      { id: "b", label: "Menggunakan jadwal tahun sebelumnya sebagai dasar pembagian.", score: 1 },
      { id: "c", label: "Menyusun jadwal baru berdasarkan kebutuhan dan kesepakatan warga.", score: 4 },
      { id: "d", label: "Meminta tokoh masyarakat menentukan pihak yang mendapat prioritas.", score: 2 },
      { id: "e", label: "Mengajak perwakilan kedua pihak menyepakati kriteria penggunaan fasilitas.", score: 5 },
    ],
    explanation: "Fasilitas umum adalah milik bersama yang harus diakses secara adil; menyusun kriteria objektif yang disepakati kedua belah pihak mencegah dominasi atau monopoli oleh kelompok tertentu.",
  },
  {
    id: "mini-tkp-45",
    category: "TKP",
    topic: "Anti Radikalisme",
    prompt: "Anda adalah ketua tim pelaksana program sosial di sebuah kelurahan. Dalam evaluasi, ditemukan bahwa sebagian warga mulai enggan mengikuti kegiatan bersama karena muncul anggapan bahwa program tersebut lebih menguntungkan kelompok tertentu. Setelah diperiksa, pembagian bantuan ternyata telah mengikuti kriteria yang ditetapkan, tetapi informasi mengenai kriteria tersebut belum dipahami sebagian warga. Anda akan...",
    choices: [
      { id: "a", label: "Meminta petugas menjelaskan kembali kriteria kepada warga.", score: 3 },
      { id: "b", label: "Menampilkan data penerima agar warga dapat melihat dasar pembagian.", score: 2 },
      { id: "c", label: "Mengadakan pertemuan warga untuk menjelaskan mekanisme program.", score: 5 },
      { id: "d", label: "Membuka ruang pertanyaan dan menerima masukan mengenai pelaksanaan program.", score: 4 },
      { id: "e", label: "Menjelaskan kriteria, membuka ruang masukan, lalu memperbaiki komunikasi program bila diperlukan.", score: 1 },
    ],
    explanation: "Mengadakan forum rembuk warga tatap muka secara transparan meredam praduga kecemburuan sosial dan memperkuat kohesi serta integrasi sosial masyarakat.",
  },
];
