import type { Question } from "./types";

export const MINI_TIU_5_QUESTIONS: Question[] = [
  {
    id: "mini-tiu5-01",
    category: "TIU",
    topic: "Analogi Kata",
    prompt: "ISOLASI : KONTAMINASI = VAKSINASI : ...",
    choices: [
      { id: "a", label: "Infeksi", score: 5 },
      { id: "b", label: "Imunisasi", score: 0 },
      { id: "c", label: "Pasien", score: 0 },
      { id: "d", label: "Bakteri", score: 0 },
      { id: "e", label: "Pengobatan", score: 0 },
    ],
    explanation: "Hubungan preventif untuk mencegah dampak negatif: Tindakan isolasi dilakukan secara preventif untuk mencegah terjadinya kontaminasi, sebagaimana tindakan vaksinasi dilakukan secara preventif untuk mencegah terjadinya infeksi.",
  },
  {
    id: "mini-tiu5-02",
    category: "TIU",
    topic: "Analogi Kata",
    prompt: "ANOREKSIA : NAFSU MAKAN = INSOMNIA : ...",
    choices: [
      { id: "a", label: "Lelah", score: 0 },
      { id: "b", label: "Mimpi", score: 0 },
      { id: "c", label: "Tenaga", score: 0 },
      { id: "d", label: "Tidur", score: 5 },
      { id: "e", label: "Kesadaran", score: 0 },
    ],
    explanation: "Hubungan kondisi patologis berupa ketiadaan atau hilangnya fungsi normal: Anoreksia adalah gangguan yang ditandai dengan hilangnya nafsu makan, sebagaimana insomnia adalah gangguan yang ditandai dengan hilangnya atau ketiadaan kemampuan tidur.",
  },
  {
    id: "mini-tiu5-03",
    category: "TIU",
    topic: "Analogi Kata",
    prompt: "KODAM : TNI AD = POLDA : ...",
    choices: [
      { id: "a", label: "Kapolres", score: 0 },
      { id: "b", label: "POLRI", score: 5 },
      { id: "c", label: "Brimob", score: 0 },
      { id: "d", label: "Mabes", score: 0 },
      { id: "e", label: "Kejaksaan", score: 0 },
    ],
    explanation: "Hubungan komando kewilayahan struktural utama: Komando Daerah Militer (Kodam) merupakan komando pelaksana operasional kewilayahan di bawah naungan institusi TNI AD, sebagaimana Kepolisian Daerah (Polda) merupakan komando pelaksana kewilayahan di bawah naungan institusi Kepolisian Negara Republik Indonesia (POLRI).",
  },
  {
    id: "mini-tiu5-04",
    category: "TIU",
    topic: "Analogi Kata",
    prompt: "KOMPAS : ARAH = TONGKAT : ...",
    choices: [
      { id: "a", label: "Lansia", score: 0 },
      { id: "b", label: "Perjalanan", score: 0 },
      { id: "c", label: "Tumpuan", score: 5 },
      { id: "d", label: "Beban", score: 0 },
      { id: "e", label: "Penglihatan", score: 0 },
    ],
    explanation: "Hubungan instrumen bantu dan fungsi pokoknya: Kompas digunakan sebagai alat bantu untuk menentukan arah, sebagaimana tongkat digunakan sebagai alat bantu fisik untuk tumpuan penopang tubuh.",
  },
  {
    id: "mini-tiu5-05",
    category: "TIU",
    topic: "Silogisme",
    prompt: "Semua auditor inspektorat yang memeriksa keuangan daerah wajib memegang sertifikasi pemeriksa forensik.\nSebagian aparatur di Inspektorat Wilayah II tidak memegang sertifikasi pemeriksa forensik.\nSimpulan yang paling sah adalah ...",
    choices: [
      { id: "a", label: "Semua aparatur di Inspektorat Wilayah II bukan auditor keuangan daerah.", score: 0 },
      { id: "b", label: "Sebagian auditor inspektorat tidak memegang sertifikasi pemeriksa forensik.", score: 0 },
      { id: "c", label: "Aparatur yang memegang sertifikasi forensik bukan aparatur Inspektorat Wilayah II.", score: 0 },
      { id: "d", label: "Sebagian aparatur di Inspektorat Wilayah II memegang sertifikasi dan memeriksa keuangan daerah.", score: 0 },
      { id: "e", label: "Sebagian aparatur di Inspektorat Wilayah II tidak memeriksa keuangan daerah.", score: 5 },
    ],
    explanation: "Berdasarkan prinsip logika formal Modus Tollens pada kuantor partikular:\n- Premis Mayor: Memeriksa Keuangan Daerah ($P$) → Memegang Sertifikasi Forensik ($Q$).\n- Premis Minor: Sebagian aparatur Wilayah II ($R$) tidak memegang sertifikasi forensik (~$Q$).\n- Kesimpulan: Sebagian aparatur Wilayah II tidak memeriksa keuangan daerah (~$P$) (Opsi E).",
  },
  {
    id: "mini-tiu5-06",
    category: "TIU",
    topic: "Silogisme",
    prompt: "Jika target realisasi anggaran tercapai di atas 95%, maka seluruh unit kerja menerima penghargaan kinerja prima.\nJika seluruh unit kerja menerima penghargaan kinerja prima, maka pimpinan instansi memberikan insentif remunerasi tambahan.\nDiketahui bahwa pimpinan instansi tidak memberikan insentif remunerasi tambahan.\nSimpulan yang valid adalah ...",
    choices: [
      { id: "a", label: "Target realisasi anggaran tidak tercapai di atas 95%.", score: 5 },
      { id: "b", label: "Sebagian unit kerja tidak menerima penghargaan kinerja prima.", score: 0 },
      { id: "c", label: "Target realisasi anggaran tercapai di atas 95% namun insentif dibatalkan.", score: 0 },
      { id: "d", label: "Pimpinan instansi mengganti insentif remunerasi dengan bentuk penghargaan lain.", score: 0 },
      { id: "e", label: "Seluruh unit kerja tetap menerima penghargaan kinerja prima.", score: 0 },
    ],
    explanation: "Penarikan kesimpulan berantai (Silogisme Hipotetis dan Modus Tollens):\n1. $P \\to Q$ (Target $>95\\% \\to$ Penghargaan Prima)\n2. $Q \\to R$ (Penghargaan Prima $\\to$ Insentif Tambahan)\nGabungan: $P \\to R$\nFakta: $\\sim R$ (Tidak memberikan insentif tambahan).\nBerdasarkan Modus Tollens: Dari $P \\to R$ dan $\\sim R$, disimpulkan $\\sim P$ (Target realisasi anggaran tidak tercapai di atas 95%) (Opsi A).",
  },
  {
    id: "mini-tiu5-07",
    category: "TIU",
    topic: "Silogisme",
    prompt: "Semua analis kebijakan publik memiliki pemahaman mendalam tentang tata kelola pemerintahan.\nSebagian staf ahli komisi tidak memiliki pemahaman mendalam tentang tata kelola pemerintahan.\nSimpulan yang tepat adalah ...",
    choices: [
      { id: "a", label: "Semua staf ahli komisi bukan analis kebijakan publik.", score: 0 },
      { id: "b", label: "Sebagian staf ahli komisi bukan analis kebijakan publik.", score: 5 },
      { id: "c", label: "Sebagian analis kebijakan publik adalah staf ahli komisi.", score: 0 },
      { id: "d", label: "Tidak ada staf ahli komisi yang menjadi analis kebijakan publik.", score: 0 },
      { id: "e", label: "Semua staf ahli komisi memiliki pemahaman tentang tata kelola pemerintahan.", score: 0 },
    ],
    explanation: "Diagram Venn hubungan himpunan:\n- Himpunan Analis Kebijakan ($A$) termuat seutuhnya di dalam Himpunan Pemahaman Tata Kelola ($T$).\n- Ada anggota Staf Ahli Komisi ($S$) yang berada di luar $T$.\n- Karena anggota $S$ tersebut berada di luar $T$, maka otomatis anggota tersebut juga berada di luar $A$.\n- Kesimpulan: Sebagian staf ahli komisi bukan analis kebijakan publik (Opsi B).",
  },
  {
    id: "mini-tiu5-08",
    category: "TIU",
    topic: "Silogisme",
    prompt: "Setiap berkas pengadaan yang disetujui harus memenuhi kelengkapan verifikasi faktual atau mendapat dispensasi tertulis dari Pejabat Pembuat Komitmen (PPK).\nBerkas pengadaan proyek revitalisasi sistem dinyatakan disetujui, tetapi tidak mendapat dispensasi tertulis dari PPK.\nSimpulan yang paling tepat adalah ...",
    choices: [
      { id: "a", label: "Berkas pengadaan proyek tersebut ditolak oleh tim pemeriksa.", score: 0 },
      { id: "b", label: "Proyek revitalisasi sistem tetap berjalan tanpa kelengkapan berkas.", score: 0 },
      { id: "c", label: "Dispensasi tertulis PPK akan diterbitkan menyusul setelah verifikasi selesai.", score: 0 },
      { id: "d", label: "Berkas pengadaan proyek tersebut memenuhi kelengkapan verifikasi faktual.", score: 5 },
      { id: "e", label: "Berkas pengadaan proyek tersebut disetujui bersyarat oleh PPK.", score: 0 },
    ],
    explanation: "Silogisme Disjungtif:\n- Syarat kelulusan: Berkas memenuhi verifikasi faktual ($P$) ATAU mendapat dispensasi PPK ($Q$).\n- Fakta: Berkas disetujui, namun tidak mendapat dispensasi PPK (~$Q$).\n- Karena proposisi disjungsi bernilai benar dan $Q$ salah, maka $P$ wajib bernilai benar.\n- Simpulan: Berkas pengadaan proyek tersebut memenuhi kelengkapan verifikasi faktual (Opsi D).",
  },
  {
    id: "mini-tiu5-09",
    category: "TIU",
    topic: "Penalaran Analitis",
    prompt: "Enam orang pegawai (Farhan, Gina, Hendra, Indah, Jaka, dan Kania) dijadwalkan menyampaikan laporan kinerja triwulanan secara berurutan pada satu hari kerja (urutan 1 sampai 6) dengan ketentuan:\n1. Jaka tampil tepat setelah Hendra.\n2. Farhan harus tampil sebelum Kania, tetapi sesudah Gina.\n3. Indah tampil pada urutan pertama atau terakhir.\n4. Gina tidak boleh tampil pada urutan kedua.\nJika Hendra tampil pada urutan ketiga, maka siapakah yang tampil pada urutan pertama?",
    choices: [
      { id: "a", label: "Farhan", score: 0 },
      { id: "b", label: "Kania", score: 0 },
      { id: "c", label: "Gina", score: 5 },
      { id: "d", label: "Jaka", score: 0 },
      { id: "e", label: "Indah", score: 0 },
    ],
    explanation: "Analisis Urutan Posisi:\n- Hendra di urutan 3, maka Jaka (tepat setelah Hendra) wajib di urutan 4.\n- Indah berada di urutan 1 atau 6.\n- Jika Indah di urutan 1, slot tersisa untuk Gina, Farhan, Kania ($G < F < K$) adalah 2, 5, 6. Ini menempatkan Gina di urutan 2, yang melanggar syarat 4 (Gina tidak boleh urutan kedua). Maka Indah wajib di urutan 6!\n- Slot tersisa untuk Gina, Farhan, Kania adalah urutan 1, 2, dan 5.\n- Karena urutan tampil harus Gina lalu Farhan lalu Kania ($G < F < K$), maka: Gina = urutan 1, Farhan = urutan 2, Hendra = 3, Jaka = 4, Kania = 5, Indah = 6.\n- Orang yang tampil pada urutan pertama adalah Gina (Opsi C).",
  },
  {
    id: "mini-tiu5-10",
    category: "TIU",
    topic: "Penalaran Analitis",
    prompt: "Enam orang pejabat dinas (Ahmad, Badrun, Choirul, Darma, Erwin, dan Firman) duduk mengelilingi meja bundar dengan posisi 6 kursi bernomor urut 1 sampai 6 searah jarum jam:\n1. Ahmad duduk tepat berhadapan dengan Darma.\n2. Badrun duduk di sebelah kanan Ahmad.\n3. Erwin duduk tepat di sebelah kiri Darma.\n4. Choirul tidak duduk bersebelahan dengan Darma maupun Badrun.\nSiapakah yang duduk tepat berhadapan dengan Badrun?",
    choices: [
      { id: "a", label: "Ahmad", score: 0 },
      { id: "b", label: "Choirul", score: 0 },
      { id: "c", label: "Darma", score: 0 },
      { id: "d", label: "Firman", score: 0 },
      { id: "e", label: "Erwin", score: 5 },
    ],
    explanation: "Analisis Posisi Meja Bundar:\n- Misalkan Ahmad di kursi 1, maka Darma duduk berhadapan di kursi 4.\n- Menghadap pusat meja: sebelah kanan Ahmad adalah kursi 2 (ditempati Badrun).\n- Sebelah kiri Darma yang menghadap pusat meja adalah kursi 5 (ditempati Erwin).\n- Sisa kursi: kursi 3 dan kursi 6.\n- Choirul tidak boleh di kursi 3 karena bersebelahan dengan Badrun (kursi 2) dan Darma (kursi 4). Maka Choirul wajib di kursi 6, dan Firman di kursi 3.\n- Pejabat yang duduk berhadapan dengan kursi 2 (Badrun) adalah kursi 5 (Erwin) (Opsi E).",
  },
  {
    id: "mini-tiu5-11",
    category: "TIU",
    topic: "Penalaran Analitis",
    prompt: "Panitia seleksi harus memilih 4 orang dari 6 calon anggota tim penilai (P, Q, R, S, T, U) dengan ketentuan:\n1. Jika P dipilih, maka Q tidak boleh dipilih.\n2. R dan S harus dipilih bersama-sama atau tidak dipilih sama sekali.\n3. T hanya dapat dipilih jika U juga dipilih.\nJika dalam tim tersebut terpilih Q, maka susunan tim penilai yang memenuhi seluruh syarat adalah ...",
    choices: [
      { id: "a", label: "Q, R, S, U", score: 5 },
      { id: "b", label: "Q, R, S, T", score: 0 },
      { id: "c", label: "Q, P, T, U", score: 0 },
      { id: "d", label: "Q, S, T, U", score: 0 },
      { id: "e", label: "Q, R, T, U", score: 0 },
    ],
    explanation: "Deduksi Logika Pemilihan:\n- Tim beranggotakan 4 orang dan Q terpilih.\n- Syarat 1: P dan Q tidak boleh bersama. Karena Q terpilih, maka P tidak boleh dipilih. Calon tersisa: {R, S, T, U} untuk 3 kursi sisa.\n- Syarat 2: R dan S harus bersama-sama. Jika R dan S masuk, anggota menjadi {Q, R, S} (3 orang, sisa 1 kursi).\n- Syarat 3: T hanya bisa dipilih jika U juga dipilih (butuh 2 orang). Karena hanya tersisa 1 kursi, T tidak dapat dipilih sehingga kursi terakhir diisi oleh U.\n- Susunan lengkap tim: Q, R, S, U (Opsi A).",
  },
  {
    id: "mini-tiu5-12",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Nilai dari $\\frac{98^2 - 12^2}{86 \\times 22}$ adalah ...",
    choices: [
      { id: "a", label: "4", score: 0 },
      { id: "b", label: "5", score: 5 },
      { id: "c", label: "6", score: 0 },
      { id: "d", label: "7", score: 0 },
      { id: "e", label: "8", score: 0 },
    ],
    explanation: "Gunakan identitas aljabar selisih kuadrat $a^2 - b^2 = (a - b)(a + b)$:\n$98^2 - 12^2 = (98 - 12)(98 + 12) = 86 \\times 110$.\nMaka:\n$$\\frac{86 \\times 110}{86 \\times 22} = \\frac{110}{22} = 5$$\nJawaban yang tepat adalah 5 (Opsi B).",
  },
  {
    id: "mini-tiu5-13",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Nilai dari $37{,}5\\% \\times 640 + 62{,}5\\% \\times 320$ adalah ...",
    choices: [
      { id: "a", label: "380", score: 0 },
      { id: "b", label: "400", score: 0 },
      { id: "c", label: "420", score: 0 },
      { id: "d", label: "440", score: 5 },
      { id: "e", label: "460", score: 0 },
    ],
    explanation: "Konversi bentuk pecahan istimewa:\n- $37{,}5\\% = \\frac{3}{8}$\n- $62{,}5\\% = \\frac{5}{8}$\nHitung masing-masing suku:\n- $\\frac{3}{8} \\times 640 = 3 \\times 80 = 240$\n- $\\frac{5}{8} \\times 320 = 5 \\times 40 = 200$\nJumlahkan: $240 + 200 = 440$ (Opsi D).",
  },
  {
    id: "mini-tiu5-14",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Hasil perhitungan dari $\\frac{3}{7} \\div \\frac{9}{28} \\times \\frac{3}{4}$ adalah ...",
    choices: [
      { id: "a", label: "1", score: 5 },
      { id: "b", label: "\\frac{4}{3}", score: 0 },
      { id: "c", label: "\\frac{3}{2}", score: 0 },
      { id: "d", label: "2", score: 0 },
      { id: "e", label: "\\frac{9}{7}", score: 0 },
    ],
    explanation: "Operasi pecahan:\n$$\\frac{3}{7} \\times \\frac{28}{9} \\times \\frac{3}{4} = \\frac{3 \\times 28 \\times 3}{7 \\times 9 \\times 4} = \\frac{252}{252} = 1$$\nJawaban yang tepat adalah 1 (Opsi A).",
  },
  {
    id: "mini-tiu5-15",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Nilai dari $\\sqrt{0{,}0064} + (0{,}5)^3 - \\sqrt[3]{0{,}027}$ adalah ...",
    choices: [
      { id: "a", label: "-0,155", score: 0 },
      { id: "b", label: "-0,105", score: 0 },
      { id: "c", label: "-0,095", score: 5 },
      { id: "d", label: "0,085", score: 0 },
      { id: "e", label: "0,125", score: 0 },
    ],
    explanation: "Hitung nilai masing-masing suku:\n- $\\sqrt{0{,}0064} = 0{,}08$\n- $(0{,}5)^3 = 0{,}125$\n- $\\sqrt[3]{0{,}027} = 0{,}300$\nOperasikan: $0{,}08 + 0{,}125 - 0{,}300 = 0{,}205 - 0{,}300 = -0{,}095$ (Opsi C).",
  },
  {
    id: "mini-tiu5-16",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "$3, 6, 11, 18, 27, 38, \\dots, \\dots$",
    choices: [
      { id: "a", label: "48, 62", score: 0 },
      { id: "b", label: "49, 64", score: 0 },
      { id: "c", label: "50, 65", score: 0 },
      { id: "d", label: "51, 64", score: 0 },
      { id: "e", label: "51, 66", score: 5 },
    ],
    explanation: "Analisis selisih antar suku:\n$3 \\xrightarrow{+3} 6 \\xrightarrow{+5} 11 \\xrightarrow{+7} 18 \\xrightarrow{+9} 27 \\xrightarrow{+11} 38$\nSelisih merupakan bilangan ganjil yang bertambah $+2$.\n- Suku berikutnya: $38 + 13 = 51$\n- Suku selanjutnya: $51 + 15 = 66$\nMaka dua suku berikutnya adalah 51, 66 (Opsi E).",
  },
  {
    id: "mini-tiu5-17",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "$4, 9, 8, 13, 16, 17, 32, 21, \\dots, \\dots$",
    choices: [
      { id: "a", label: "48, 24", score: 0 },
      { id: "b", label: "64, 25", score: 5 },
      { id: "c", label: "64, 26", score: 0 },
      { id: "d", label: "56, 25", score: 0 },
      { id: "e", label: "56, 26", score: 0 },
    ],
    explanation: "Deret terbagi atas dua larik berselang-seling:\n- Larik 1 (posisi ganjil): $4, 8, 16, 32, \\dots$ (pola perkalian $\\times 2$). Suku berikutnya $= 32 \\times 2 = 64$.\n- Larik 2 (posisi genap): $9, 13, 17, 21, \\dots$ (pola penjumlahan $+4$). Suku berikutnya $= 21 + 4 = 25$.\nDua suku berikutnya adalah 64, 25 (Opsi B).",
  },
  {
    id: "mini-tiu5-18",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "$5, 10, 6, 12, 8, 16, 12, 24, \\dots, \\dots$",
    choices: [
      { id: "a", label: "20, 40", score: 5 },
      { id: "b", label: "18, 36", score: 0 },
      { id: "c", label: "20, 36", score: 0 },
      { id: "d", label: "22, 44", score: 0 },
      { id: "e", label: "18, 40", score: 0 },
    ],
    explanation: "Pola operasi berulang secara bergantian: $\\times 2$, lalu $-4$.\n- $5 \\times 2 = 10$\n- $10 - 4 = 6$\n- $6 \\times 2 = 12$\n- $12 - 4 = 8$\n- $8 \\times 2 = 16$\n- $16 - 4 = 12$\n- $12 \\times 2 = 24$\nLanjutan:\n- $24 - 4 = 20$\n- $20 \\times 2 = 40$\nDua suku berikutnya adalah 20, 40 (Opsi A).",
  },
  {
    id: "mini-tiu5-19",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "B, E, D, G, F, I, H, K, ..., ...",
    choices: [
      { id: "a", label: "I, M", score: 0 },
      { id: "b", label: "I, L", score: 0 },
      { id: "c", label: "J, N", score: 0 },
      { id: "d", label: "J, M", score: 5 },
      { id: "e", label: "K, N", score: 0 },
    ],
    explanation: "Ubah ke urutan alfabet numerik (A=1, B=2, dst.):\n2, 5, 4, 7, 6, 9, 8, 11, ...\nTerdiri dari dua deret lompat:\n- Deret ganjil: 2, 4, 6, 8, ... (pola $+2 \\to 10 = \\text{J}$)\n- Deret genap: 5, 7, 9, 11, ... (pola $+2 \\to 13 = \\text{M}$)\nDua huruf selanjutnya adalah J, M (Opsi D).",
  },
  {
    id: "mini-tiu5-20",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Jika $2x + 3y = 27$ dan $x - y = 1$, manakah hubungan yang benar antara kuantitas $P$ dan $Q$ berikut?\n$$P = x + y$$\n$$Q = 11$$",
    choices: [
      { id: "a", label: "P > Q", score: 0 },
      { id: "b", label: "P < Q", score: 0 },
      { id: "c", label: "P = Q", score: 5 },
      { id: "d", label: "2P = 3Q", score: 0 },
      { id: "e", label: "Hubungan P dan Q tidak dapat ditentukan", score: 0 },
    ],
    explanation: "Selesaikan sistem persamaan linear:\n$x - y = 1 \\implies x = y + 1$\nSubstitusikan ke persamaan pertama:\n$$2(y + 1) + 3y = 27 \\implies 5y + 2 = 27 \\implies 5y = 25 \\implies y = 5$$\n$$x = 5 + 1 = 6$$\nMaka:\n$P = x + y = 6 + 5 = 11$\n$Q = 11$\nSehingga $P = Q$ (Opsi C).",
  },
  {
    id: "mini-tiu5-21",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Diketahui $a > 0$ dan $b > 0$ dengan $a = 2b$.\n$$P = \\frac{a^2 + b^2}{(a + b)^2}$$\n$$Q = \\frac{1}{2}$$\nManakah hubungan yang benar antara kuantitas $P$ dan $Q$?",
    choices: [
      { id: "a", label: "P > Q", score: 5 },
      { id: "b", label: "P < Q", score: 0 },
      { id: "c", label: "P = Q", score: 0 },
      { id: "d", label: "P + Q = 1", score: 0 },
      { id: "e", label: "Informasi yang diberikan tidak cukup", score: 0 },
    ],
    explanation: "Substitusikan $a = 2b$ ke dalam rumus $P$:\n$$P = \\frac{(2b)^2 + b^2}{(2b + b)^2} = \\frac{4b^2 + b^2}{(3b)^2} = \\frac{5b^2}{9b^2} = \\frac{5}{9} \\approx 0{,}556$$\n$$Q = \\frac{1}{2} = 0{,}500$$\nKarena $\\frac{5}{9} > \\frac{1}{2}$, maka $P > Q$ (Opsi A).",
  },
  {
    id: "mini-tiu5-22",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Diketahui $x$ adalah bilangan bulat positif kelipatan 4 antara 15 dan 25.\n$P =$ rata-rata dari seluruh kemungkinan nilai $x$\n$Q = 22$\nManakah hubungan yang benar antara kuantitas $P$ dan $Q$?",
    choices: [
      { id: "a", label: "P > Q", score: 0 },
      { id: "b", label: "P < Q", score: 5 },
      { id: "c", label: "P = Q", score: 0 },
      { id: "d", label: "P = 2Q", score: 0 },
      { id: "e", label: "Hubungan P dan Q tidak dapat ditentukan", score: 0 },
    ],
    explanation: "Kelipatan 4 antara 15 dan 25 adalah: 16, 20, dan 24.\nRata-rata nilai $x$:\n$$P = \\frac{16 + 20 + 24}{3} = \\frac{60}{3} = 20$$\n$$Q = 22$$\nKarena $20 < 22$, maka $P < Q$ (Opsi B).",
  },
  {
    id: "mini-tiu5-23",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Diketahui $x^2 = 36$ dan $y^2 = 49$.\n$$P = x + y$$\n$$Q = 13$$\nManakah hubungan yang benar antara kuantitas $P$ dan $Q$?",
    choices: [
      { id: "a", label: "P > Q", score: 0 },
      { id: "b", label: "P < Q", score: 0 },
      { id: "c", label: "P = Q", score: 0 },
      { id: "d", label: "P >= Q", score: 0 },
      { id: "e", label: "Informasi yang diberikan tidak cukup untuk memutuskan hubungan P dan Q", score: 5 },
    ],
    explanation: "Selesaikan nilai $x$ dan $y$:\n$x^2 = 36 \\implies x = 6$ atau $x = -6$.\n$y^2 = 49 \\implies y = 7$ atau $y = -7$.\n- Jika $x = 6$ dan $y = 7$, maka $P = 6 + 7 = 13$ (berlaku $P = Q$).\n- Jika $x = -6$ dan $y = -7$, maka $P = -13$ (berlaku $P < Q$).\nKarena terdapat lebih dari satu kemungkinan hubungan, maka informasi tidak cukup untuk menentukan hubungan pasti (Opsi E).",
  },
  {
    id: "mini-tiu5-24",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Sebuah persegi panjang memiliki keliling 50 cm. Panjangnya 5 cm lebih dari lebarnya.\n$P =$ Luas persegi panjang tersebut ($\\text{cm}^2$)\n$Q = 100$\nManakah hubungan yang benar antara kuantitas $P$ dan $Q$?",
    choices: [
      { id: "a", label: "P > Q", score: 0 },
      { id: "b", label: "P < Q", score: 0 },
      { id: "c", label: "P = Q", score: 0 },
      { id: "d", label: "2P = 3Q", score: 5 },
      { id: "e", label: "Hubungan P dan Q tidak dapat ditentukan", score: 0 },
    ],
    explanation: "Hitung dimensi persegi panjang:\n$K = 2(p + l) = 50 \\implies p + l = 25$\nDiketahui $p = l + 5$, maka:\n$(l + 5) + l = 25 \\implies 2l = 20 \\implies l = 10\\text{ cm}$\n$p = 10 + 5 = 15\\text{ cm}$\nLuas $P = p \\times l = 15 \\times 10 = 150\\text{ cm}^2$.\n$Q = 100$.\nUji relasi matematis:\n$2P = 2 \\times 150 = 300$\n$3Q = 3 \\times 100 = 300$\nMaka berlaku hubungan $2P = 3Q$ (Opsi D).",
  },
  {
    id: "mini-tiu5-25",
    category: "TIU",
    topic: "Soal Cerita",
    prompt: "Kendaraan dinas A berangkat dari Kota P menuju Kota Q pada pukul 07.30 dengan kecepatan rata-rata $60\\text{ km/jam}$. Pada waktu yang sama, kendaraan dinas B berangkat dari Kota Q menuju Kota P melalui jalan yang sama dengan kecepatan rata-rata $80\\text{ km/jam}$. Jika jarak antara Kota P dan Kota Q adalah $210\\text{ km}$, pada pukul berapakah kedua kendaraan tersebut akan berpapasan?",
    choices: [
      { id: "a", label: "09.00", score: 5 },
      { id: "b", label: "09.15", score: 0 },
      { id: "c", label: "09.30", score: 0 },
      { id: "d", label: "09.45", score: 0 },
      { id: "e", label: "10.00", score: 0 },
    ],
    explanation: "Waktu tempuh hingga berpapasan:\n$$t = \\frac{\\text{Jarak Total}}{v_A + v_B} = \\frac{210}{60 + 80} = \\frac{210}{140} = 1{,}5\\text{ jam} = 1\\text{ jam } 30\\text{ menit}$$\nWaktu berpapasan $= 07.30 + 01.30 = \\text{Pukul } 09.00$ (Opsi A).",
  },
  {
    id: "mini-tiu5-26",
    category: "TIU",
    topic: "Soal Cerita",
    prompt: "Sebuah proyek digitalisasi arsip dapat diselesaikan oleh 12 orang staf dalam waktu 20 hari. Setelah berjalan selama 5 hari, pekerjaan dihentikan selama 3 hari karena pemeliharaan server. Jika proyek tersebut harus selesai tepat waktu sesuai jadwal semula, berapa orang staf tambahan yang harus ditugaskan?",
    choices: [
      { id: "a", label: "2 orang", score: 0 },
      { id: "b", label: "2,5 orang", score: 0 },
      { id: "c", label: "3 orang", score: 5 },
      { id: "d", label: "4 orang", score: 0 },
      { id: "e", label: "5 orang", score: 0 },
    ],
    explanation: "Perhitungan beban kerja berbanding terbalik:\n- Sisa hari kerja normal $= 20 - 5 = 15$ hari untuk 12 staf.\n- Total sisa beban $= 15 \\times 12 = 180$ staf-hari.\n- Sisa waktu nyata setelah libur 3 hari $= 15 - 3 = 12$ hari.\n- Total staf yang dibutuhkan $= \\frac{180}{12} = 15$ orang.\n- Staf tambahan yang dibutuhkan $= 15 - 12 = 3$ orang (Opsi C).",
  },
  {
    id: "mini-tiu5-27",
    category: "TIU",
    topic: "Soal Cerita",
    prompt: "Sebuah instansi pengadaan membeli perlengkapan kantor seharga $\\text{Rp}12.000.000,00$. Toko memberikan diskon ganda bertingkat yaitu sebesar $20\\%$ kemudian diberikan diskon tambahan lagi sebesar $10\\%$ dari harga setelah diskon pertama. Berapakah total harga akhir yang harus dibayarkan oleh instansi tersebut?",
    choices: [
      { id: "a", label: "Rp8.400.000,00", score: 0 },
      { id: "b", label: "Rp8.640.000,00", score: 5 },
      { id: "c", label: "Rp8.800.000,00", score: 0 },
      { id: "d", label: "Rp9.000.000,00", score: 0 },
      { id: "e", label: "Rp9.240.000,00", score: 0 },
    ],
    explanation: "Perhitungan diskon bertingkat bertahap:\n- Diskon pertama $20\\%$: Harga menjadi $80\\% \\times \\text{Rp}12.000.000 = \\text{Rp}9.600.000,00$.\n- Diskon kedua $10\\%$: Harga akhir menjadi $90\\% \\times \\text{Rp}9.600.000 = \\text{Rp}8.640.000,00$.\nTotal harga yang dibayarkan adalah $\\text{Rp}8.640.000,00$ (Opsi B).",
  },
  {
    id: "mini-tiu5-28",
    category: "TIU",
    topic: "Soal Cerita",
    prompt: "Nilai rata-rata tes potensi akademik dari sebuah kelompok yang terdiri atas 25 orang peserta wanita adalah 82, sedangkan nilai rata-rata dari 15 orang peserta pria adalah 74. Berapakah nilai rata-rata gabungan dari seluruh peserta seleksi tersebut?",
    choices: [
      { id: "a", label: "77,5", score: 0 },
      { id: "b", label: "78,0", score: 0 },
      { id: "c", label: "78,5", score: 0 },
      { id: "d", label: "79,0", score: 5 },
      { id: "e", label: "79,5", score: 0 },
    ],
    explanation: "Rumus rata-rata gabungan:\n$$\\bar{x}_{\\text{gab}} = \\frac{(n_1 \\times \\bar{x}_1) + (n_2 \\times \\bar{x}_2)}{n_1 + n_2}$$\n$$\\bar{x}_{\\text{gab}} = \\frac{(25 \\times 82) + (15 \\times 74)}{25 + 15} = \\frac{2.050 + 1.110}{40} = \\frac{3.160}{40} = 79{,}0$$\nNilai rata-rata gabungan adalah 79,0 (Opsi D).",
  },
  {
    id: "mini-tiu5-29",
    category: "TIU",
    topic: "Soal Cerita",
    prompt: "Dari 90 orang aparatur sipil di suatu badan kepegawaian, 52 orang memiliki sertifikasi analisis data, 44 orang memiliki sertifikasi manajemen risiko, dan 14 orang belum memiliki kedua sertifikasi tersebut. Berapakah jumlah aparatur yang memiliki kedua sertifikasi sekaligus?",
    choices: [
      { id: "a", label: "12 orang", score: 0 },
      { id: "b", label: "14 orang", score: 0 },
      { id: "c", label: "16 orang", score: 0 },
      { id: "d", label: "18 orang", score: 0 },
      { id: "e", label: "20 orang", score: 5 },
    ],
    explanation: "Diagram Venn hubungan himpunan:\n- Total aparatur $n(S) = 90$\n- Tidak memiliki keduanya $= 14$, maka aparatur yang memiliki setidaknya satu sertifikasi: $n(A \\cup B) = 90 - 14 = 76$\n- Berdasarkan prinsip inklusi-eksklusi:\n$$n(A \\cup B) = n(A) + n(B) - n(A \\cap B)$$\n$$76 = 52 + 44 - n(A \\cap B) \\implies 76 = 96 - n(A \\cap B)$$\n$$n(A \\cap B) = 96 - 76 = 20\\text{ orang}$$\nJumlah yang memiliki kedua sertifikasi adalah 20 orang (Opsi E).",
  },
  {
    id: "mini-tiu5-30",
    category: "TIU",
    topic: "Soal Cerita",
    prompt: "Dari suatu unit kerja yang beranggotakan 5 orang pria dan 4 orang wanita, akan dibentuk tim delegasi kerja yang beranggotakan 3 orang. Jika tim tersebut disyaratkan harus terdiri atas 2 orang pria dan 1 orang wanita, ada berapa banyak cara susunan pemilihan delegasi yang dapat dibentuk?",
    choices: [
      { id: "a", label: "30 cara", score: 0 },
      { id: "b", label: "35 cara", score: 0 },
      { id: "c", label: "40 cara", score: 5 },
      { id: "d", label: "45 cara", score: 0 },
      { id: "e", label: "50 cara", score: 0 },
    ],
    explanation: "Kombinatorika pemilihan tim:\n- Memilih 2 pria dari 5 pria:\n$$C(5, 2) = \\frac{5 \\times 4}{2 \\times 1} = 10$$\n- Memilih 1 wanita dari 4 wanita:\n$$C(4, 1) = 4$$\nBerdasarkan kaidah perkalian:\nTotal cara $= 10 \\times 4 = 40\\text{ cara}$ (Opsi C).",
  },
  {
    id: "mini-tiu5-31",
    category: "TIU",
    topic: "Kemampuan Figural",
    prompt: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 470 100\" style=\"width:100%;max-width:560px;display:block\"><rect x=\"6\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"45\" y1=\"43\" x2=\"45\" y2=\"15\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><polygon points=\"45,11 41,19 49,19\" fill=\"black\"/><circle cx=\"18\" cy=\"16\" r=\"5\" fill=\"black\"/><text x=\"45\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(1)</text><rect x=\"100\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"139\" y1=\"43\" x2=\"159\" y2=\"23\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><polygon points=\"162,20 154,23 159,29\" fill=\"black\"/><circle cx=\"112\" cy=\"70\" r=\"5\" fill=\"black\"/><text x=\"139\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(2)</text><rect x=\"194\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"233\" y1=\"43\" x2=\"261\" y2=\"43\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><polygon points=\"265,43 257,39 257,47\" fill=\"black\"/><circle cx=\"260\" cy=\"70\" r=\"5\" fill=\"black\"/><text x=\"233\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(3)</text><rect x=\"288\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"327\" y1=\"43\" x2=\"347\" y2=\"63\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><polygon points=\"350,66 348,58 342,63\" fill=\"black\"/><circle cx=\"354\" cy=\"16\" r=\"5\" fill=\"black\"/><text x=\"327\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(4)</text><rect x=\"382\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><text x=\"421\" y=\"52\" text-anchor=\"middle\" font-size=\"40\" font-family=\"sans-serif\" font-weight=\"bold\">?</text><text x=\"421\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(5)</text></svg>",
    choices: [
      {
        id: "a",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"44\" y1=\"44\" x2=\"44\" y2=\"72\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><polygon points=\"44,76 40,68 48,68\" fill=\"black\"/><circle cx=\"16\" cy=\"16\" r=\"5\" fill=\"black\"/></svg>",
        score: 5,
      },
      {
        id: "b",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"44\" y1=\"44\" x2=\"24\" y2=\"64\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><polygon points=\"21,67 29,65 24,59\" fill=\"black\"/><circle cx=\"72\" cy=\"72\" r=\"5\" fill=\"black\"/></svg>",
        score: 0,
      },
      {
        id: "c",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"44\" y1=\"44\" x2=\"44\" y2=\"72\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><polygon points=\"44,76 40,68 48,68\" fill=\"black\"/><circle cx=\"72\" cy=\"16\" r=\"5\" fill=\"black\"/></svg>",
        score: 0,
      },
      {
        id: "d",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"44\" y1=\"44\" x2=\"16\" y2=\"44\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><polygon points=\"12,44 20,40 20,48\" fill=\"black\"/><circle cx=\"16\" cy=\"72\" r=\"5\" fill=\"black\"/></svg>",
        score: 0,
      },
      {
        id: "e",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"44\" y1=\"44\" x2=\"24\" y2=\"24\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><polygon points=\"21,21 24,29 29,24\" fill=\"black\"/><circle cx=\"16\" cy=\"16\" r=\"5\" fill=\"black\"/></svg>",
        score: 0,
      },
    ],
    explanation: "Analisis Pola Serial Geometri:\n1. Jarum panah: Berputar sebesar $45^\\circ$ searah jarum jam secara konsisten:\n   - Pola 1: Atas ($0^\\circ$)\n   - Pola 2: Kanan-Atas ($45^\\circ$)\n   - Pola 3: Kanan ($90^\\circ$)\n   - Pola 4: Kanan-Bawah ($135^\\circ$)\n   - Pola 5: Wajib menghadap ke bawah lurus ($180^\\circ$).\n2. Lingkaran hitam kecil: Berpindah di empat sudut berlawanan arah jarum jam:\n   - Pola 1: Kiri-Atas\n   - Pola 2: Kiri-Bawah\n   - Pola 3: Kanan-Bawah\n   - Pola 4: Kanan-Atas\n   - Pola 5: Wajib kembali ke Kiri-Atas.\nKombinasi yang tepat adalah jarum menghadap ke bawah dan lingkaran di sudut kiri-atas (Opsi A).",
  },
  {
    id: "mini-tiu5-32",
    category: "TIU",
    topic: "Kemampuan Figural",
    prompt: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 470 100\" style=\"width:100%;max-width:560px;display:block\"><rect x=\"6\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"6\" y1=\"30\" x2=\"84\" y2=\"30\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"6\" y1=\"56\" x2=\"84\" y2=\"56\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"32\" y1=\"4\" x2=\"32\" y2=\"82\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"58\" y1=\"4\" x2=\"58\" y2=\"82\" stroke=\"#9ca3af\" stroke-width=\"1\"/><rect x=\"6\" y=\"4\" width=\"26\" height=\"26\" fill=\"black\"/><circle cx=\"71\" cy=\"69\" r=\"6\" fill=\"none\" stroke=\"black\" stroke-width=\"2\"/><text x=\"45\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(1)</text><rect x=\"100\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"100\" y1=\"30\" x2=\"178\" y2=\"30\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"100\" y1=\"56\" x2=\"178\" y2=\"56\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"126\" y1=\"4\" x2=\"126\" y2=\"82\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"152\" y1=\"4\" x2=\"152\" y2=\"82\" stroke=\"#9ca3af\" stroke-width=\"1\"/><rect x=\"126\" y=\"4\" width=\"26\" height=\"26\" fill=\"black\"/><circle cx=\"113\" cy=\"69\" r=\"6\" fill=\"none\" stroke=\"black\" stroke-width=\"2\"/><text x=\"139\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(2)</text><rect x=\"194\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"194\" y1=\"30\" x2=\"272\" y2=\"30\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"194\" y1=\"56\" x2=\"272\" y2=\"56\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"220\" y1=\"4\" x2=\"220\" y2=\"82\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"246\" y1=\"4\" x2=\"246\" y2=\"82\" stroke=\"#9ca3af\" stroke-width=\"1\"/><rect x=\"246\" y=\"4\" width=\"26\" height=\"26\" fill=\"black\"/><circle cx=\"207\" cy=\"43\" r=\"6\" fill=\"none\" stroke=\"black\" stroke-width=\"2\"/><text x=\"233\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(3)</text><rect x=\"288\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"288\" y1=\"30\" x2=\"366\" y2=\"30\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"288\" y1=\"56\" x2=\"366\" y2=\"56\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"314\" y1=\"4\" x2=\"314\" y2=\"82\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"340\" y1=\"4\" x2=\"340\" y2=\"82\" stroke=\"#9ca3af\" stroke-width=\"1\"/><rect x=\"340\" y=\"30\" width=\"26\" height=\"26\" fill=\"black\"/><circle cx=\"301\" cy=\"17\" r=\"6\" fill=\"none\" stroke=\"black\" stroke-width=\"2\"/><text x=\"327\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(4)</text><rect x=\"382\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><text x=\"421\" y=\"52\" text-anchor=\"middle\" font-size=\"40\" font-family=\"sans-serif\" font-weight=\"bold\">?</text><text x=\"421\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(5)</text></svg>",
    choices: [
      {
        id: "a",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"2\" y1=\"30\" x2=\"86\" y2=\"30\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"2\" y1=\"58\" x2=\"86\" y2=\"58\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"30\" y1=\"2\" x2=\"30\" y2=\"86\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"58\" y1=\"2\" x2=\"58\" y2=\"86\" stroke=\"#9ca3af\" stroke-width=\"1\"/><rect x=\"58\" y=\"58\" width=\"28\" height=\"28\" fill=\"black\"/><circle cx=\"16\" cy=\"16\" r=\"7\" fill=\"none\" stroke=\"black\" stroke-width=\"2\"/></svg>",
        score: 0,
      },
      {
        id: "b",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"2\" y1=\"30\" x2=\"86\" y2=\"30\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"2\" y1=\"58\" x2=\"86\" y2=\"58\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"30\" y1=\"2\" x2=\"30\" y2=\"86\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"58\" y1=\"2\" x2=\"58\" y2=\"86\" stroke=\"#9ca3af\" stroke-width=\"1\"/><rect x=\"58\" y=\"58\" width=\"28\" height=\"28\" fill=\"black\"/><circle cx=\"44\" cy=\"16\" r=\"7\" fill=\"none\" stroke=\"black\" stroke-width=\"2\"/></svg>",
        score: 5,
      },
      {
        id: "c",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"2\" y1=\"30\" x2=\"86\" y2=\"30\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"2\" y1=\"58\" x2=\"86\" y2=\"58\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"30\" y1=\"2\" x2=\"30\" y2=\"86\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"58\" y1=\"2\" x2=\"58\" y2=\"86\" stroke=\"#9ca3af\" stroke-width=\"1\"/><rect x=\"30\" y=\"58\" width=\"28\" height=\"28\" fill=\"black\"/><circle cx=\"72\" cy=\"16\" r=\"7\" fill=\"none\" stroke=\"black\" stroke-width=\"2\"/></svg>",
        score: 0,
      },
      {
        id: "d",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"2\" y1=\"30\" x2=\"86\" y2=\"30\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"2\" y1=\"58\" x2=\"86\" y2=\"58\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"30\" y1=\"2\" x2=\"30\" y2=\"86\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"58\" y1=\"2\" x2=\"58\" y2=\"86\" stroke=\"#9ca3af\" stroke-width=\"1\"/><rect x=\"2\" y=\"58\" width=\"28\" height=\"28\" fill=\"black\"/><circle cx=\"44\" cy=\"44\" r=\"7\" fill=\"none\" stroke=\"black\" stroke-width=\"2\"/></svg>",
        score: 0,
      },
      {
        id: "e",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"2\" y1=\"30\" x2=\"86\" y2=\"30\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"2\" y1=\"58\" x2=\"86\" y2=\"58\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"30\" y1=\"2\" x2=\"30\" y2=\"86\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"58\" y1=\"2\" x2=\"58\" y2=\"86\" stroke=\"#9ca3af\" stroke-width=\"1\"/><rect x=\"58\" y=\"30\" width=\"28\" height=\"28\" fill=\"black\"/><circle cx=\"44\" cy=\"16\" r=\"7\" fill=\"none\" stroke=\"black\" stroke-width=\"2\"/></svg>",
        score: 0,
      },
    ],
    explanation: "Analisis Kisi Perimeter 9 Sel:\n1. Kotak Hitam: Bergerak 1 langkah searah jarum jam mengelilingi 8 sel tepi luar:\n   - Pola 1: Baris 1 Kolom 1\n   - Pola 2: Baris 1 Kolom 2\n   - Pola 3: Baris 1 Kolom 3\n   - Pola 4: Baris 2 Kolom 3\n   - Pola 5: Wajib berada di Baris 3 Kolom 3 (sudut kanan-bawah).\n2. Lingkaran Putih (Garis tepi): Bergerak 1 langkah berlawanan arah jarum jam mengelilingi 8 sel tepi luar:\n   - Pola 1: Baris 3 Kolom 3\n   - Pola 2: Baris 3 Kolom 1\n   - Pola 3: Baris 2 Kolom 1\n   - Pola 4: Baris 1 Kolom 1\n   - Pola 5: Wajib berada di Baris 1 Kolom 2 (tengah-atas).\nKonfigurasi yang tepat adalah Opsi B.",
  },
  {
    id: "mini-tiu5-33",
    category: "TIU",
    topic: "Kemampuan Figural",
    prompt: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 470 100\" style=\"width:100%;max-width:560px;display:block\"><g><rect x=\"6\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><polygon points=\"45,18 73,68 17,68\" fill=\"none\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"45\" y1=\"18\" x2=\"45\" y2=\"68\" stroke=\"#9ca3af\" stroke-dasharray=\"2,2\" stroke-width=\"1\"/><circle cx=\"45\" cy=\"46\" r=\"4\" fill=\"black\"/><text x=\"45\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">A</text></g><g><rect x=\"100\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><rect x=\"117\" y=\"21\" width=\"44\" height=\"44\" fill=\"none\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"117\" y1=\"21\" x2=\"161\" y2=\"65\" stroke=\"#9ca3af\" stroke-dasharray=\"2,2\" stroke-width=\"1\"/><circle cx=\"139\" cy=\"43\" r=\"4\" fill=\"black\"/><text x=\"139\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">B</text></g><g><rect x=\"194\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><polygon points=\"233,18 259,37 249,68 217,68 207,37\" fill=\"none\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"233\" y1=\"18\" x2=\"233\" y2=\"68\" stroke=\"#9ca3af\" stroke-dasharray=\"2,2\" stroke-width=\"1\"/><circle cx=\"233\" cy=\"45\" r=\"4\" fill=\"black\"/><text x=\"233\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">C</text></g><g><rect x=\"288\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><polygon points=\"327,18 355,43 327,68 299,43\" fill=\"none\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"299\" y1=\"43\" x2=\"355\" y2=\"43\" stroke=\"#9ca3af\" stroke-dasharray=\"2,2\" stroke-width=\"1\"/><circle cx=\"340\" cy=\"30\" r=\"4\" fill=\"black\"/><text x=\"327\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">D</text></g><g><rect x=\"382\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><polygon points=\"407,20 435,20 449,43 435,66 407,66 393,43\" fill=\"none\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"393\" y1=\"43\" x2=\"449\" y2=\"43\" stroke=\"#9ca3af\" stroke-dasharray=\"2,2\" stroke-width=\"1\"/><circle cx=\"421\" cy=\"43\" r=\"4\" fill=\"black\"/><text x=\"421\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">E</text></g></svg>\nManakah figur yang memiliki karakteristik paling berbeda (menyimpang dari pola umum)?",
    choices: [
      { id: "a", label: "Figur A", score: 0 },
      { id: "b", label: "Figur B", score: 0 },
      { id: "c", label: "Figur C", score: 0 },
      { id: "d", label: "Figur D", score: 5 },
      { id: "e", label: "Figur E", score: 0 },
    ],
    explanation: "Analisis Ketidaksamaan Pola Figural:\n- Pola umum: Setiap figur memiliki garis putus-putus sebagai sumbu simetri lipat, dan sebuah titik hitam yang terletak TEPAT di atas garis sumbu simetri tersebut.\n  - Figur A (Segitiga): Titik hitam tepat berada di sumbu simetri vertikal.\n  - Figur B (Bujur sangkar): Titik hitam tepat berada di sumbu simetri diagonal.\n  - Figur C (Segi lima): Titik hitam tepat berada di sumbu simetri vertikal.\n  - Figur E (Segi enam): Titik hitam tepat berada di sumbu simetri horizontal.\n- Figur D menyimpang karena titik hitam terletak di luar garis sumbu simetri.\nMaka figur yang paling berbeda adalah Figur D (Opsi D).",
  },
  {
    id: "mini-tiu5-34",
    category: "TIU",
    topic: "Kemampuan Figural",
    prompt: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 200 200\" style=\"width:180px;height:180px;display:block;margin:auto\"><rect x=\"4\" y=\"4\" width=\"192\" height=\"192\" fill=\"white\" stroke=\"black\" stroke-width=\"2\"/><line x1=\"68\" y1=\"4\" x2=\"68\" y2=\"196\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"132\" y1=\"4\" x2=\"132\" y2=\"196\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"4\" y1=\"68\" x2=\"196\" y2=\"68\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"4\" y1=\"132\" x2=\"196\" y2=\"132\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"14\" y1=\"36\" x2=\"58\" y2=\"36\" stroke=\"black\" stroke-width=\"2\"/><line x1=\"100\" y1=\"14\" x2=\"100\" y2=\"58\" stroke=\"black\" stroke-width=\"2\"/><line x1=\"142\" y1=\"36\" x2=\"186\" y2=\"36\" stroke=\"black\" stroke-width=\"2\"/><line x1=\"164\" y1=\"14\" x2=\"164\" y2=\"58\" stroke=\"black\" stroke-width=\"2\"/><circle cx=\"36\" cy=\"100\" r=\"16\" fill=\"none\" stroke=\"black\" stroke-width=\"2\"/><line x1=\"100\" y1=\"84\" x2=\"100\" y2=\"116\" stroke=\"black\" stroke-width=\"2\"/><circle cx=\"164\" cy=\"100\" r=\"16\" fill=\"none\" stroke=\"black\" stroke-width=\"2\"/><line x1=\"164\" y1=\"84\" x2=\"164\" y2=\"116\" stroke=\"black\" stroke-width=\"2\"/><rect x=\"20\" y=\"148\" width=\"32\" height=\"32\" fill=\"none\" stroke=\"black\" stroke-width=\"2\"/><line x1=\"78\" y1=\"164\" x2=\"122\" y2=\"164\" stroke=\"black\" stroke-width=\"2\"/><text x=\"164\" y=\"173\" text-anchor=\"middle\" font-size=\"28\" font-family=\"sans-serif\" font-weight=\"bold\">?</text></svg>\nTentukan figur yang tepat untuk mengisi kotak bertanda tanya (?) pada matriks di atas!",
    choices: [
      {
        id: "a",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><rect x=\"28\" y=\"28\" width=\"32\" height=\"32\" fill=\"none\" stroke=\"black\" stroke-width=\"2\"/><line x1=\"44\" y1=\"18\" x2=\"44\" y2=\"70\" stroke=\"black\" stroke-width=\"2\"/></svg>",
        score: 0,
      },
      {
        id: "b",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><circle cx=\"44\" cy=\"44\" r=\"18\" fill=\"none\" stroke=\"black\" stroke-width=\"2\"/><line x1=\"18\" y1=\"44\" x2=\"70\" y2=\"44\" stroke=\"black\" stroke-width=\"2\"/></svg>",
        score: 0,
      },
      {
        id: "c",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"18\" y1=\"44\" x2=\"70\" y2=\"44\" stroke=\"black\" stroke-width=\"2\"/><line x1=\"44\" y1=\"18\" x2=\"44\" y2=\"70\" stroke=\"black\" stroke-width=\"2\"/></svg>",
        score: 0,
      },
      {
        id: "d",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><rect x=\"28\" y=\"28\" width=\"32\" height=\"32\" fill=\"black\" stroke=\"black\" stroke-width=\"2\"/></svg>",
        score: 0,
      },
      {
        id: "e",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><rect x=\"28\" y=\"28\" width=\"32\" height=\"32\" fill=\"none\" stroke=\"black\" stroke-width=\"2\"/><line x1=\"18\" y1=\"44\" x2=\"70\" y2=\"44\" stroke=\"black\" stroke-width=\"2\"/></svg>",
        score: 5,
      },
    ],
    explanation: "Operasi Logika Matriks Baris:\n- Baris 1: Garis horizontal (Kolom 1) digabung dengan garis vertikal (Kolom 2) menghasilkan tanda tambah (+) di Kolom 3.\n- Baris 2: Lingkaran (Kolom 1) digabung dengan garis vertikal (Kolom 2) menghasilkan lingkaran bergaris vertikal di Kolom 3.\n- Baris 3: Persegi (Kolom 1) digabung dengan garis horizontal (Kolom 2) menghasilkan persegi bergaris horizontal di Kolom 3.\nFigur yang tepat adalah Opsi E.",
  },
  {
    id: "mini-tiu5-35",
    category: "TIU",
    topic: "Kemampuan Figural",
    prompt: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 470 100\" style=\"width:100%;max-width:560px;display:block\"><g><rect x=\"6\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><polygon points=\"45,16 68,68 22,68\" fill=\"black\"/><circle cx=\"45\" cy=\"52\" r=\"7\" fill=\"white\"/><text x=\"45\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">A</text></g><text x=\"98\" y=\"48\" font-size=\"24\" font-family=\"sans-serif\" font-weight=\"bold\">:</text><g><rect x=\"116\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><polygon points=\"45,68 68,16 22,16\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\" transform=\"translate(110,0)\"/><circle cx=\"155\" cy=\"32\" r=\"7\" fill=\"black\"/><text x=\"155\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">B</text></g><text x=\"212\" y=\"48\" font-size=\"24\" font-family=\"sans-serif\" font-weight=\"bold\">=</text><g><rect x=\"236\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><rect x=\"253\" y=\"21\" width=\"44\" height=\"44\" fill=\"black\"/><polygon points=\"275,31 289,55 261,55\" fill=\"white\"/><text x=\"275\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">C</text></g><text x=\"328\" y=\"48\" font-size=\"24\" font-family=\"sans-serif\" font-weight=\"bold\">:</text><g><rect x=\"346\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><text x=\"385\" y=\"52\" text-anchor=\"middle\" font-size=\"40\" font-family=\"sans-serif\" font-weight=\"bold\">?</text><text x=\"385\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">D</text></g></svg>\nTentukan figur yang tepat untuk melengkapi analogi A : B = C : D di atas!",
    choices: [
      {
        id: "a",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><rect x=\"22\" y=\"22\" width=\"44\" height=\"44\" fill=\"black\"/><polygon points=\"44,32 58,56 30,56\" fill=\"white\" transform=\"rotate(180 44 44)\"/></svg>",
        score: 0,
      },
      {
        id: "b",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><rect x=\"22\" y=\"22\" width=\"44\" height=\"44\" fill=\"none\" stroke=\"black\" stroke-width=\"1.5\"/><polygon points=\"44,32 58,56 30,56\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/></svg>",
        score: 0,
      },
      {
        id: "c",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><rect x=\"22\" y=\"22\" width=\"44\" height=\"44\" fill=\"none\" stroke=\"black\" stroke-width=\"1.5\"/><polygon points=\"44,56 58,32 30,32\" fill=\"black\"/></svg>",
        score: 5,
      },
      {
        id: "d",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><rect x=\"22\" y=\"22\" width=\"44\" height=\"44\" fill=\"none\" stroke=\"black\" stroke-width=\"1.5\"/><polygon points=\"44,32 58,56 30,56\" fill=\"black\"/></svg>",
        score: 0,
      },
      {
        id: "e",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><rect x=\"22\" y=\"22\" width=\"44\" height=\"44\" fill=\"black\"/><polygon points=\"44,56 58,32 30,32\" fill=\"black\" stroke=\"white\" stroke-width=\"1\"/></svg>",
        score: 0,
      },
    ],
    explanation: "Aturan Transformasi Analogi Figural:\n1. Transformasi orientasi: Elemen utama dibalik secara vertikal ($180^\\circ$ inversi sumbu).\n2. Transformasi warna (inversi arsiran):\n   - Warna latar luar (hitam $\\to$ putih bergaris batas).\n   - Warna elemen dalam (putih $\\to$ hitam).\nMenerapkan transformasi yang sama pada Figur C (bujur sangkar hitam berisi segitiga putih mengarah ke atas):\n- Bujur sangkar luar berubah menjadi putih dengan garis batas hitam.\n- Segitiga di dalam dibalik mengarah ke bawah dan diisi warna hitam penuh.\nKonfigurasi yang tepat adalah Opsi C.",
  },
];
