import type { Question } from "./types";

export const MINI_TIU_7_QUESTIONS: Question[] = [
  {
    id: "mini-tiu7-01",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "VAKSINASI : KEKEBALAN = ASURANSI : ...",
    choices: [
      { id: "a", label: "Perlindungan", score: 5 },
      { id: "b", label: "Premi", score: 0 },
      { id: "c", label: "Klaim", score: 0 },
      { id: "d", label: "Polis", score: 0 },
      { id: "e", label: "Kompensasi", score: 0 },
    ],
    explanation: "Hubungan tindakan preventif terencana dan tujuannya: Vaksinasi dilakukan secara terencana untuk memperoleh kekebalan tubuh terhadap penyakit, sebagaimana asuransi diikuti secara terencana untuk memperoleh perlindungan terhadap risiko kerugian finansial. Jawaban yang tepat adalah Opsi A.",
  },
  {
    id: "mini-tiu7-02",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "HIGROMETER : KELEMBAPAN = BAROMETER : ...",
    choices: [
      { id: "a", label: "Ketinggian", score: 0 },
      { id: "b", label: "Suhu Udara", score: 0 },
      { id: "c", label: "Tekanan Udara", score: 5 },
      { id: "d", label: "Kecepatan Angin", score: 0 },
      { id: "e", label: "Curah Hujan", score: 0 },
    ],
    explanation: "Hubungan alat ukur dan besaran fisik yang diukur: Higrometer adalah instrumen untuk mengukur tingkat kelembapan udara, sedangkan barometer adalah instrumen khusus untuk mengukur tekanan udara atmosfer. Jawaban yang tepat adalah Opsi C.",
  },
  {
    id: "mini-tiu7-03",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "KAPOLRES : KABUPATEN = KAPOLDA : ...",
    choices: [
      { id: "a", label: "Kecamatan", score: 0 },
      { id: "b", label: "Kotamadya", score: 0 },
      { id: "c", label: "Karesidenan", score: 0 },
      { id: "d", label: "Provinsi", score: 5 },
      { id: "e", label: "Nasional", score: 0 },
    ],
    explanation: "Hubungan pimpinan komando kewilayahan dan tingkat wilayah yurisdiksinya: Kapolres memimpin kesatuan kepolisian resor di tingkat kabupaten/kota, sedangkan Kapolda memimpin kesatuan kepolisian daerah di tingkat provinsi. Jawaban yang tepat adalah Opsi D.",
  },
  {
    id: "mini-tiu7-04",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "... : PERSIDANGAN = WASIT : ...",
    choices: [
      { id: "a", label: "Pengacara – Kejuaraan", score: 0 },
      { id: "b", label: "Hakim – Pertandingan", score: 5 },
      { id: "c", label: "Jaksa – Lapangan", score: 0 },
      { id: "d", label: "Terdakwa – Penonton", score: 0 },
      { id: "e", label: "Panitera – Peluit", score: 0 },
    ],
    explanation: "Hubungan analogi ganda penegak aturan dan arena tugasnya: Hakim memimpin dan memutuskan perkara secara adil dalam jalannya persidangan, sebagaimana wasit memimpin dan menegakkan aturan main secara adil dalam jalannya pertandingan. Jawaban yang tepat adalah Opsi B.",
  },
  {
    id: "mini-tiu7-05",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "Semua pranata komputer ahli pertama menguasai arsitektur basis data. Sebagian staf biro perencanaan adalah pranata komputer ahli pertama. Tidak ada staf biro perencanaan yang berstatus pegawai lepas.\n\nSimpulan yang paling tepat adalah ...",
    choices: [
      { id: "a", label: "Sebagian staf biro perencanaan menguasai arsitektur basis data.", score: 5 },
      { id: "b", label: "Semua staf biro perencanaan menguasai arsitektur basis data.", score: 0 },
      { id: "c", label: "Semua orang yang menguasai arsitektur basis data adalah staf biro perencanaan.", score: 0 },
      { id: "d", label: "Sebagian orang yang menguasai arsitektur basis data berstatus pegawai lepas.", score: 0 },
      { id: "e", label: "Tidak ada pranata komputer ahli pertama yang bukan staf biro perencanaan.", score: 0 },
    ],
    explanation: "Analisis Silogisme Kategorik:\n- Premis 1: Pranata Komputer Ahli Pertama (P) → Menguasai Basis Data (B).\n- Premis 2: Sebagian Staf Biro Perencanaan (S) adalah Pranata Komputer Ahli Pertama (P).\nSimpulan langsung: Karena sebagian S adalah P, dan seluruh P adalah B, maka dipastikan sebagian staf biro perencanaan (S) menguasai arsitektur basis data (B). Jawaban yang tepat adalah Opsi A.",
  },
  {
    id: "mini-tiu7-06",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "Jika sebuah instansi menerapkan digitalisasi arsip, maka waktu pelayanan publik menjadi lebih cepat. Jika waktu pelayanan publik menjadi lebih cepat, maka indeks kepuasan masyarakat meningkat. Instansi B tidak mengalami peningkatan indeks kepuasan masyarakat.\n\nSimpulan yang sah adalah ...",
    choices: [
      { id: "a", label: "Instansi B tetap menerapkan digitalisasi arsip namun pelayanannya lambat.", score: 0 },
      { id: "b", label: "Instansi B tidak menerapkan digitalisasi arsip.", score: 5 },
      { id: "c", label: "Instansi B mempercepat pelayanan publik tanpa digitalisasi arsip.", score: 0 },
      { id: "d", label: "Digitalisasi arsip tidak memengaruhi indeks kepuasan masyarakat di Instansi B.", score: 0 },
      { id: "e", label: "Sebagian pelayanan di Instansi B telah dilakukan secara digital.", score: 0 },
    ],
    explanation: "Analisis Silogisme Hipotetis & Modus Tollens:\n- Premis 1: Digitalisasi Arsip ($D$) → Waktu Lebih Cepat ($W$).\n- Premis 2: Waktu Lebih Cepat ($W$) → Indeks Kepuasan Naik ($I$).\nSilogisme berantai menghasilkan: $D \\implies I$.\n- Fakta: Instansi B tidak mengalami peningkatan indeks kepuasan masyarakat ($\\sim I$).\nBerdasarkan aturan penarikan kesimpulan Modus Tollens:\n$$(D \\implies I) \\land \\sim I \\implies \\sim D$$\nMaka simpulan yang sah: Instansi B tidak menerapkan digitalisasi arsip. Jawaban yang tepat adalah Opsi B.",
  },
  {
    id: "mini-tiu7-07",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "Setiap pejabat fungsional perencana wajib lulus uji kompetensi keahlian atau memiliki portofolio proyek strategis minimal 3 kali. Jika pejabat memiliki portofolio proyek strategis minimal 3 kali, ia harus sudah bekerja di biro perencanaan lebih dari 4 tahun. Bagus adalah pejabat fungsional perencana yang baru bekerja di biro perencanaan selama 2 tahun.\n\nSimpulan yang sah adalah ...",
    choices: [
      { id: "a", label: "Bagus tidak dapat diangkat sebagai pejabat fungsional perencana.", score: 0 },
      { id: "b", label: "Bagus telah memiliki portofolio proyek strategis minimal 3 kali.", score: 0 },
      { id: "c", label: "Bagus dibebaskan dari kewajiban uji kompetensi keahlian.", score: 0 },
      { id: "d", label: "Bagus harus menunggu 2 tahun lagi untuk mengikuti uji kompetensi.", score: 0 },
      { id: "e", label: "Bagus wajib lulus uji kompetensi keahlian.", score: 5 },
    ],
    explanation: "Analisis Silogisme Disjungtif & Modus Tollens:\n- Aturan: Lulus Uji Kompetensi ($U$) $\\lor$ Portofolio Proyek $\\ge 3$ ($P$).\n- Implikasi: $P \\implies$ Masa Kerja $> 4$ tahun ($M$).\n- Fakta: Masa kerja Bagus baru 2 tahun (artinya $\\sim M$).\nMelalui Modus Tollens: $\\sim M \\implies \\sim P$ (Bagus dipastikan belum memiliki portofolio proyek minimal 3 kali).\nMelalui Silogisme Disjungtif: $(U \\lor P) \\land \\sim P \\implies U$.\nMaka Bagus wajib lulus uji kompetensi keahlian. Jawaban yang tepat adalah Opsi E.",
  },
  {
    id: "mini-tiu7-08",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "Semua kendaraan operasional dinas berbahan bakar ramah lingkungan. Sebagian kendaraan operasional dinas digunakan untuk inspeksi lapangan. Semua kendaraan yang digunakan untuk inspeksi lapangan dilengkapi perangkat navigasi GPS.\n\nSimpulan yang benar adalah ...",
    choices: [
      { id: "a", label: "Semua kendaraan berbahan bakar ramah lingkungan digunakan untuk inspeksi lapangan.", score: 0 },
      { id: "b", label: "Semua kendaraan yang dilengkapi GPS bukan merupakan kendaraan dinas.", score: 0 },
      { id: "c", label: "Sebagian kendaraan berbahan bakar ramah lingkungan dilengkapi perangkat navigasi GPS.", score: 5 },
      { id: "d", label: "Tidak ada kendaraan dinas yang dilengkapi GPS berbahan bakar ramah lingkungan.", score: 0 },
      { id: "e", label: "Kendaraan yang tidak digunakan untuk inspeksi lapangan pasti tidak ramah lingkungan.", score: 0 },
    ],
    explanation: "Analisis Logika Himpunan / Diagram Venn:\n- Seluruh himpunan Kendaraan Dinas ($D$) termasuk dalam himpunan Ramah Lingkungan ($R$).\n- Sebagian $D$ beririsan dengan Kendaraan Inspeksi ($I$).\n- Seluruh $I$ termasuk dalam himpunan Ber-GPS ($G$).\nKarena sebagian $D$ adalah $I$, dan setiap $I$ memiliki GPS ($G$), maka terdapat sebagian kendaraan dinas yang ber-GPS. Mengingat semua kendaraan dinas adalah ramah lingkungan ($R$), maka dipastikan sebagian kendaraan berbahan bakar ramah lingkungan dilengkapi perangkat navigasi GPS. Jawaban yang tepat adalah Opsi C.",
  },
  {
    id: "mini-tiu7-09",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "Tujuh orang peserta pelatihan kepemimpinan (Adit, Bima, Caca, Doni, Ega, Fandi, dan Galih) duduk berjajar di barisan depan aula pada kursi nomor 1 sampai 7 secara berurutan dari kiri ke kanan dengan ketentuan:\n1. Doni duduk di kursi nomor 4.\n2. Galih duduk di kursi nomor 7.\n3. Adit duduk tepat di sebelah kiri Caca (keduanya menempati dua kursi berdampingan secara berurutan).\n4. Bima duduk tepat di sebelah kanan Ega (keduanya menempati dua kursi berdampingan secara berurutan).\n5. Fandi duduk di sebelah kiri Doni, tetapi tidak boleh duduk di kursi nomor 1.\n\nBerdasarkan ketentuan tersebut, pegawai yang PASTI duduk di kursi nomor 3 adalah ...",
    choices: [
      { id: "a", label: "Adit", score: 0 },
      { id: "b", label: "Bima", score: 0 },
      { id: "c", label: "Caca", score: 0 },
      { id: "d", label: "Fandi", score: 5 },
      { id: "e", label: "Ega", score: 0 },
    ],
    explanation: "Penalaran Analitis Posisi Duduk Berjajar:\n- Kursi tersedia: 1, 2, 3, 4, 5, 6, 7.\n- Posisi pasti: Kursi 4 = Doni, Kursi 7 = Galih.\n- Kursi yang masih kosong: {1, 2, 3} di sebelah kiri Doni, serta {5, 6} di sebelah kanan Doni.\n- Terdapat dua pasangan orang yang wajib duduk berdampingan: blok (Adit, Caca) dan blok (Ega, Bima).\n- Kursi {5, 6} adalah satu blok 2 kursi berturutan, sehingga salah satu pasangan (AC atau EB) WAJIB menempati kursi {5, 6}.\n- Pasangan lainnya wajib menempati kursi di sebelah kiri Doni {1, 2, 3}.\n- Agar satu pasangan dapat duduk berdampingan di {1, 2, 3}, pasangan tersebut harus menempati kursi {1, 2} ATAU {2, 3}.\n- Fakta syarat 5: Fandi duduk di kiri Doni ({1, 2, 3}) namun BUKAN di kursi 1. Jika pasangan menempati {2, 3}, maka Fandi terpaksa di kursi 1 (melanggar syarat 5). Oleh karena itu, pasangan tersebut wajib menempati kursi {1, 2}, sehingga Fandi secara unik dan pasti duduk di kursi nomor 3. Jawaban yang tepat adalah Opsi D.",
  },
  {
    id: "mini-tiu7-10",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "Tujuh orang peserta pelatihan kepemimpinan (Adit, Bima, Caca, Doni, Ega, Fandi, dan Galih) duduk berjajar di barisan depan aula pada kursi nomor 1 sampai 7 secara berurutan dari kiri ke kanan dengan ketentuan:\n1. Doni duduk di kursi nomor 4.\n2. Galih duduk di kursi nomor 7.\n3. Adit duduk tepat di sebelah kiri Caca.\n4. Bima duduk tepat di sebelah kanan Ega.\n5. Fandi duduk di sebelah kiri Doni, tetapi tidak boleh duduk di kursi nomor 1.\n\nJika Adit duduk di kursi nomor 1, maka pernyataan berikut yang PASTI BENAR adalah ...",
    choices: [
      { id: "a", label: "Ega duduk di kursi nomor 5.", score: 5 },
      { id: "b", label: "Bima duduk di kursi nomor 5.", score: 0 },
      { id: "c", label: "Caca duduk di kursi nomor 3.", score: 0 },
      { id: "d", label: "Fandi duduk di kursi nomor 2.", score: 0 },
      { id: "e", label: "Ega duduk di kursi nomor 6.", score: 0 },
    ],
    explanation: "Analisis Berdasarkan Kondisi Tambahan:\n- Jika Adit di kursi 1, karena Adit tepat di sebelah kiri Caca, maka Caca pasti duduk di kursi nomor 2.\n- Berdasarkan analisis sebelumnya, Fandi duduk di kursi nomor 3.\n- Doni duduk di kursi nomor 4.\n- Dua kursi yang tersisa di sebelah kanan adalah nomor 5 dan 6. Pasangan kedua adalah (Ega, Bima), di mana Bima tepat di sebelah kanan Ega (urutan: Ega lalu Bima).\n- Maka Ega pasti duduk di kursi nomor 5 dan Bima duduk di kursi nomor 6.\n- Galih di kursi nomor 7.\nPernyataan yang pasti benar adalah Ega duduk di kursi nomor 5. Jawaban yang tepat adalah Opsi A.",
  },
  {
    id: "mini-tiu7-11",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "Tujuh orang peserta pelatihan kepemimpinan (Adit, Bima, Caca, Doni, Ega, Fandi, dan Galih) duduk berjajar di barisan depan aula pada kursi nomor 1 sampai 7 secara berurutan dari kiri ke kanan dengan ketentuan:\n1. Doni duduk di kursi nomor 4.\n2. Galih duduk di kursi nomor 7.\n3. Adit duduk tepat di sebelah kiri Caca.\n4. Bima duduk tepat di sebelah kanan Ega.\n5. Fandi duduk di sebelah kiri Doni, tetapi tidak boleh duduk di kursi nomor 1.\n\nJika Bima duduk di kursi nomor 2, maka susunan posisi duduk dari kursi nomor 1 sampai 7 secara berurutan adalah ...",
    choices: [
      { id: "a", label: "Adit, Caca, Fandi, Doni, Ega, Bima, Galih", score: 0 },
      { id: "b", label: "Ega, Bima, Fandi, Doni, Adit, Caca, Galih", score: 5 },
      { id: "c", label: "Bima, Ega, Fandi, Doni, Adit, Caca, Galih", score: 0 },
      { id: "d", label: "Ega, Bima, Adit, Doni, Caca, Fandi, Galih", score: 0 },
      { id: "e", label: "Fandi, Bima, Ega, Doni, Adit, Caca, Galih", score: 0 },
    ],
    explanation: "Analisis Urutan Lengkap:\n- Jika Bima di kursi nomor 2, karena Bima tepat di sebelah kanan Ega, maka Ega wajib di kursi nomor 1 (formasi: Ega = 1, Bima = 2).\n- Fandi duduk di kursi nomor 3.\n- Doni duduk di kursi nomor 4.\n- Pasangan (Adit, Caca) dengan Adit tepat di kiri Caca menempati kursi nomor 5 dan 6 (Adit = 5, Caca = 6).\n- Galih duduk di kursi nomor 7.\nMaka susunan lengkap kursi 1 s.d. 7 adalah: Ega, Bima, Fandi, Doni, Adit, Caca, Galih. Jawaban yang tepat adalah Opsi B.",
  },
  {
    id: "mini-tiu7-12",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Jika diketahui sistem persamaan linear dua variabel $3x + 2y = 23$ dan $y = x + 4$, maka nilai dari $x \\times y$ adalah ...",
    choices: [
      { id: "a", label: "15", score: 0 },
      { id: "b", label: "18", score: 0 },
      { id: "c", label: "21", score: 5 },
      { id: "d", label: "24", score: 0 },
      { id: "e", label: "28", score: 0 },
    ],
    explanation: "Penyelesaian Sistem Persamaan Linear Substitusi Dasar:\nSubstitusikan nilai $y = x + 4$ ke dalam persamaan pertama:\n$$3x + 2(x + 4) = 23$$\n$$3x + 2x + 8 = 23$$\n$$5x + 8 = 23 \\implies 5x = 15 \\implies x = 3$$\nSubstitusikan nilai $x = 3$ untuk mencari $y$:\n$$y = 3 + 4 = 7$$\nMaka nilai hasil kali $x \\times y$ adalah:\n$$x \\times y = 3 \\times 7 = 21$$\nJawaban yang tepat adalah 21 (Opsi C).",
  },
  {
    id: "mini-tiu7-13",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Nilai dari $\\frac{86^2 - 14^2}{72}$ adalah ...",
    choices: [
      { id: "a", label: "72", score: 0 },
      { id: "b", label: "80", score: 0 },
      { id: "c", label: "96", score: 0 },
      { id: "d", label: "100", score: 5 },
      { id: "e", label: "120", score: 0 },
    ],
    explanation: "Penerapan Konsep Dasar Selisih Kuadrat $a^2 - b^2 = (a - b)(a + b)$:\nDengan menetapkan $a = 86$ dan $b = 14$:\n$$\\frac{86^2 - 14^2}{72} = \\frac{(86 - 14)(86 + 14)}{72}$$\n$$= \\frac{72 \\times 100}{72} = 100$$\nJawaban yang tepat adalah 100 (Opsi D).",
  },
  {
    id: "mini-tiu7-14",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Nilai dari $2\\frac{1}{2} \\times 1{,}6 - \\frac{3}{4} \\div 0{,}25$ adalah ...",
    choices: [
      { id: "a", label: "1", score: 5 },
      { id: "b", label: "1,5", score: 0 },
      { id: "c", label: "2", score: 0 },
      { id: "d", label: "2,5", score: 0 },
      { id: "e", label: "3", score: 0 },
    ],
    explanation: "Operasi Hitung Campuran Pecahan dan Desimal:\nSelesaikan masing-masing perkalian dan pembagian terlebih dahulu:\n1. Bagian perkalian:\n   $$2\\frac{1}{2} \\times 1{,}6 = 2{,}5 \\times 1{,}6 = 4$$\n2. Bagian pembagian:\n   $$\\frac{3}{4} \\div 0{,}25 = \\frac{3}{4} \\div \\frac{1}{4} = \\frac{3}{4} \\times 4 = 3$$\n3. Operasi pengurangan:\n   $$4 - 3 = 1$$\nJawaban yang tepat adalah 1 (Opsi A).",
  },
  {
    id: "mini-tiu7-15",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Sebuah kemeja kerja berlabel harga Rp200.000,00 mendapat diskon bertingkat sebesar $20\\% + 10\\%$. Berapakah harga yang harus dibayar pembeli di kasir?",
    choices: [
      { id: "a", label: "Rp130.000,00", score: 0 },
      { id: "b", label: "Rp136.000,00", score: 0 },
      { id: "c", label: "Rp138.000,00", score: 0 },
      { id: "d", label: "Rp140.000,00", score: 0 },
      { id: "e", label: "Rp144.000,00", score: 5 },
    ],
    explanation: "Perhitungan Diskon Bertingkat (Bukan Penjumlahan Langsung):\n- Tahap 1: Diskon pertama sebesar 20%\n  $$\\text{Harga setelah diskon 1} = (100\\% - 20\\%) \\times 200.000 = 80\\% \\times 200.000 = 160.000$$\n- Tahap 2: Diskon kedua sebesar 10% dihitung dari harga tahap 1\n  $$\\text{Harga akhir} = (100\\% - 10\\%) \\times 160.000 = 90\\% \\times 160.000 = 144.000$$\nJadi, harga yang harus dibayar adalah Rp144.000,00 (Opsi E).",
  },
  {
    id: "mini-tiu7-16",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Seorang pedagang menjual suatu perangkat elektronik dengan harga Rp540.000,00 dan memperoleh keuntungan sebesar $20\\%$ dari harga pembelian. Berapakah harga beli perangkat tersebut?",
    choices: [
      { id: "a", label: "Rp420.000,00", score: 0 },
      { id: "b", label: "Rp450.000,00", score: 5 },
      { id: "c", label: "Rp460.000,00", score: 0 },
      { id: "d", label: "Rp480.000,00", score: 0 },
      { id: "e", label: "Rp500.000,00", score: 0 },
    ],
    explanation: "Perhitungan Aritmetika Sosial Persentase Keuntungan:\nRumus harga penjualan dengan untung $20\\%$:\n$$\\text{Harga Jual} = \\text{Harga Beli} + (20\\% \\times \\text{Harga Beli}) = 120\\% \\times \\text{Harga Beli}$$\n$$540.000 = 1{,}2 \\times \\text{Harga Beli}$$\n$$\\text{Harga Beli} = \\frac{540.000}{1{,}2} = \\frac{5.400.000}{12} = 450.000$$\nMaka harga beli perangkat elektronik tersebut adalah Rp450.000,00 (Opsi B).",
  },
  {
    id: "mini-tiu7-17",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Nilai rata-rata tes integritas dari 15 pegawai pria adalah 76, sedangkan nilai rata-rata dari 25 pegawai wanita adalah 84. Berapakah nilai rata-rata keseluruhan dari 40 pegawai tersebut?",
    choices: [
      { id: "a", label: "79", score: 0 },
      { id: "b", label: "80", score: 0 },
      { id: "c", label: "81", score: 5 },
      { id: "d", label: "82", score: 0 },
      { id: "e", label: "83", score: 0 },
    ],
    explanation: "Perhitungan Rata-rata Gabungan:\n$$\\bar{x}_{\\text{gab}} = \\frac{n_1 \\cdot \\bar{x}_1 + n_2 \\cdot \\bar{x}_2}{n_1 + n_2}$$\n- Total nilai pria: $15 \\times 76 = 1.140$\n- Total nilai wanita: $25 \\times 84 = 2.100$\n- Jumlah total nilai: $1.140 + 2.100 = 3.240$\n- Jumlah seluruh pegawai: $15 + 25 = 40$\n$$\\bar{x}_{\\text{gab}} = \\frac{3.240}{40} = 81$$\nNilai rata-rata keseluruhan adalah 81 (Opsi C).",
  },
  {
    id: "mini-tiu7-18",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Alokasi anggaran suatu unit kerja dibagi untuk tiga pos: Operasional, Pelatihan, dan Publikasi dengan perbandingan $3 : 4 : 5$. Jika anggaran untuk pos Pelatihan adalah Rp36.000.000,00, maka selisih anggaran antara pos Publikasi dan Operasional adalah ...",
    choices: [
      { id: "a", label: "Rp9.000.000,00", score: 0 },
      { id: "b", label: "Rp12.000.000,00", score: 0 },
      { id: "c", label: "Rp15.000.000,00", score: 0 },
      { id: "d", label: "Rp18.000.000,00", score: 5 },
      { id: "e", label: "Rp24.000.000,00", score: 0 },
    ],
    explanation: "Perhitungan Perbandingan Rasio Bagian:\n- Rasio Operasional : Pelatihan : Publikasi = $3 : 4 : 5$.\n- Anggaran Pelatihan memiliki 4 bagian senilai Rp36.000.000,00.\n  $$\\text{Nilai } 1 \\text{ bagian} = \\frac{36.000.000}{4} = 9.000.000$$\n- Selisih antara Publikasi (5 bagian) dan Operasional (3 bagian):\n  $$\\text{Selisih bagian} = 5 - 3 = 2 \\text{ bagian}$$\n  $$\\text{Selisih anggaran} = 2 \\times 9.000.000 = 18.000.000$$\nSelisih anggarannya adalah Rp18.000.000,00 (Opsi D).",
  },
  {
    id: "mini-tiu7-19",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "Angka berikutnya dari barisan bilangan $4, 7, 12, 19, 28, \\dots$ adalah ...",
    choices: [
      { id: "a", label: "39", score: 5 },
      { id: "b", label: "40", score: 0 },
      { id: "c", label: "41", score: 0 },
      { id: "d", label: "42", score: 0 },
      { id: "e", label: "43", score: 0 },
    ],
    explanation: "Analisis Deret Aritmetika Bertingkat Dua:\nLihat pola selisih antarsuku yang berdekatan:\n- $4 \\xrightarrow{+3} 7$\n- $7 \\xrightarrow{+5} 12$\n- $12 \\xrightarrow{+7} 19$\n- $19 \\xrightarrow{+9} 28$\nSelisih penambahan membentuk barisan bilangan ganjil ($+3, +5, +7, +9, \\dots$), sehingga penambahan berikutnya adalah $+11$:\n$$28 + 11 = 39$$\nJawaban yang tepat adalah 39 (Opsi A).",
  },
  {
    id: "mini-tiu7-20",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "Angka berikutnya dari deret $3, 6, 4, 8, 6, 12, 10, \\dots$ adalah ...",
    choices: [
      { id: "a", label: "14", score: 0 },
      { id: "b", label: "16", score: 0 },
      { id: "c", label: "18", score: 0 },
      { id: "d", label: "19", score: 0 },
      { id: "e", label: "20", score: 5 },
    ],
    explanation: "Analisis Pola Operasi Bergantian (Selang-Seling):\nPerhatikan relasi antarsuku yang berurutan:\n- $3 \\times 2 = 6$\n- $6 - 2 = 4$\n- $4 \\times 2 = 8$\n- $8 - 2 = 6$\n- $6 \\times 2 = 12$\n- $12 - 2 = 10$\nPola yang berulang adalah $(\\times 2)$ kemudian $(- 2)$. Langkah selanjutnya adalah dikalikan 2:\n$$10 \\times 2 = 20$$\nJawaban yang tepat adalah 20 (Opsi E).",
  },
  {
    id: "mini-tiu7-21",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "Angka yang tepat untuk melengkapi deret $5, 18, 9, 15, 13, 12, 17, \\dots$ adalah ...",
    choices: [
      { id: "a", label: "8", score: 0 },
      { id: "b", label: "9", score: 5 },
      { id: "c", label: "10", score: 0 },
      { id: "d", label: "21", score: 0 },
      { id: "e", label: "22", score: 0 },
    ],
    explanation: "Analisis Deret Dua Larik (Dua Pola Melompat Satu Suku):\n- Larik 1 (suku bernomor ganjil: suku 1, 3, 5, 7):\n  $5 \\xrightarrow{+4} 9 \\xrightarrow{+4} 13 \\xrightarrow{+4} 17$ (bertambah 4)\n- Larik 2 (suku bernomor genap: suku 2, 4, 6, 8):\n  $18 \\xrightarrow{-3} 15 \\xrightarrow{-3} 12 \\xrightarrow{-3} X$ (berkurang 3)\nSuku yang dicari berada pada urutan ke-8 (bagian dari Larik 2):\n$$X = 12 - 3 = 9$$\nJawaban yang tepat adalah 9 (Opsi B).",
  },
  {
    id: "mini-tiu7-22",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "Huruf berikutnya dari barisan huruf B, D, G, K, P, ... adalah ...",
    choices: [
      { id: "a", label: "T", score: 0 },
      { id: "b", label: "U", score: 0 },
      { id: "c", label: "V", score: 5 },
      { id: "d", label: "W", score: 0 },
      { id: "e", label: "X", score: 0 },
    ],
    explanation: "Konversi Posisi Huruf ke Urutan Alfabet:\n- B = 2\n- D = 4 ($2 + 2$)\n- G = 7 ($4 + 3$)\n- K = 11 ($7 + 4$)\n- P = 16 ($11 + 5$)\nPola lompatan huruf bertambah 1 secara berurutan: $+2, +3, +4, +5, \\dots$\nMaka lompatan berikutnya adalah $+6$:\n$$16 + 6 = 22$$\nHuruf pada urutan ke-22 dalam alfabet adalah V. Jawaban yang tepat adalah V (Opsi C).",
  },
  {
    id: "mini-tiu7-23",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Sebuah proyek pemeliharaan gedung direncanakan selesai dalam waktu 30 hari oleh 12 orang pekerja. Setelah dikerjakan selama 10 hari, pekerjaan terhenti selama 5 hari karena kendala cuaca. Berapakah tambahan pekerja yang dibutuhkan agar proyek dapat selesai tepat waktu sesuai jadwal semula?",
    choices: [
      { id: "a", label: "4 orang", score: 5 },
      { id: "b", label: "5 orang", score: 0 },
      { id: "c", label: "6 orang", score: 0 },
      { id: "d", label: "8 orang", score: 0 },
      { id: "e", label: "10 orang", score: 0 },
    ],
    explanation: "Perhitungan Perbandingan Berbalik Nilai Pekerja dan Waktu:\n- Sisa waktu rencana normal: $30 - 10 = 20$ hari dengan 12 pekerja.\n- Beban kerja yang tersisa:\n  $$\\text{Beban} = 20 \\times 12 = 240 \\text{ orang-hari}$$\n- Waktu riil yang tersisa setelah libur 5 hari:\n  $$\\text{Waktu sisa} = 20 - 5 = 15 \\text{ hari}$$\n- Jumlah pekerja yang dibutuhkan agar selesai dalam 15 hari:\n  $$\\text{Pekerja total} = \\frac{240}{15} = 16 \\text{ orang}$$\n- Tambahan pekerja yang harus didatangkan:\n  $$\\text{Tambahan} = 16 - 12 = 4 \\text{ orang}$$\nJawaban yang tepat adalah 4 orang (Opsi A).",
  },
  {
    id: "mini-tiu7-24",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Jarak antara kota P dan kota Q adalah 180 km. Ari berangkat dari kota P menuju kota Q pada pukul 08.00 dengan kecepatan rata-rata 40 km/jam. Pada saat yang bersamaan, Bagas berangkat dari kota Q menuju kota P melalui rute yang sama dengan kecepatan rata-rata 50 km/jam. Pada pukul berapa mereka akan berpapasan di jalan?",
    choices: [
      { id: "a", label: "09.30", score: 0 },
      { id: "b", label: "09.45", score: 0 },
      { id: "c", label: "09.50", score: 0 },
      { id: "d", label: "10.00", score: 5 },
      { id: "e", label: "10.15", score: 0 },
    ],
    explanation: "Perhitungan Waktu Berpapasan (Arah Berlawanan Waktu Bersamaan):\n- Jarak total ($s$) = 180 km.\n- Kecepatan relatif total ($v_1 + v_2$) = $40 + 50 = 90$ km/jam.\n- Waktu tempuh hingga berpapasan:\n  $$t = \\frac{s}{v_1 + v_2} = \\frac{180}{90} = 2 \\text{ jam}$$\n- Waktu mereka berpapasan:\n  $$08.00 + 2 \\text{ jam} = 10.00$$\nJawaban yang tepat adalah 10.00 (Opsi D).",
  },
  {
    id: "mini-tiu7-25",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Sebuah bak penampungan air dapat diisi penuh oleh pipa saluran A saja dalam waktu 6 jam, atau oleh pipa saluran B saja dalam waktu 3 jam. Jika kedua pipa saluran tersebut dibuka secara bersamaan, berapa jam waktu yang dibutuhkan untuk mengisi bak penampungan tersebut hingga penuh?",
    choices: [
      { id: "a", label: "1,5 jam", score: 0 },
      { id: "b", label: "2 jam", score: 5 },
      { id: "c", label: "2,5 jam", score: 0 },
      { id: "d", label: "4 jam", score: 0 },
      { id: "e", label: "4,5 jam", score: 0 },
    ],
    explanation: "Perhitungan Debit Pengisian Bersama:\n- Laju pengisian pipa A dalam 1 jam = $\\frac{1}{6}$ bagian.\n- Laju pengisian pipa B dalam 1 jam = $\\frac{1}{3}$ bagian.\n- Laju pengisian gabungan kedua pipa dalam 1 jam:\n  $$\\frac{1}{t_{\\text{gab}}} = \\frac{1}{6} + \\frac{1}{3} = \\frac{1}{6} + \\frac{2}{6} = \\frac{3}{6} = \\frac{1}{2}$$\n- Waktu yang dibutuhkan untuk memenuhi bak:\n  $$t_{\\text{gab}} = 2 \\text{ jam}$$\nJawaban yang tepat adalah 2 jam (Opsi B).",
  },
  {
    id: "mini-tiu7-26",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Panjang sebuah lahan persegi panjang bertambah sebesar $25\\%$, sedangkan lebarnya berkurang sebesar $20\\%$. Persentase perubahan luas lahan persegi panjang tersebut dibandingkan dengan luas semula adalah ...",
    choices: [
      { id: "a", label: "Bertambah 5%", score: 0 },
      { id: "b", label: "Berkurang 5%", score: 0 },
      { id: "c", label: "Bertambah 2%", score: 0 },
      { id: "d", label: "Berkurang 2%", score: 0 },
      { id: "e", label: "Tetap (tidak berubah)", score: 5 },
    ],
    explanation: "Perhitungan Persentase Perubahan Luas Bangun Datar:\n- Misalkan panjang awal $= p$ dan lebar awal $= l$. Luas awal $L_1 = p \\times l$.\n- Panjang baru ($p_2$) = $p + 25\\% p = 1{,}25p = \\frac{5}{4}p$.\n- Lebar baru ($l_2$) = $l - 20\\% l = 0{,}80l = \\frac{4}{5}l$.\n- Luas baru ($L_2$):\n  $$L_2 = p_2 \\times l_2 = \\left(\\frac{5}{4}p\\right) \\times \\left(\\frac{4}{5}l\\right) = \\frac{20}{20}(p \\times l) = 1 \\times L_1 = L_1$$\nKarena $L_2 = L_1$, maka luas lahan tersebut tidak mengalami perubahan (tetap / 0% perubahan). Jawaban yang tepat adalah Opsi E.",
  },
  {
    id: "mini-tiu7-27",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Diketahui persamaan linear satu variabel $4x - 5 = 2x + 7$.\n$$P = x$$\n$$Q = 4$$\nManakah hubungan yang benar antara kuantitas $P$ dan $Q$?",
    choices: [
      { id: "a", label: "P > Q", score: 5 },
      { id: "b", label: "P < Q", score: 0 },
      { id: "c", label: "P = Q", score: 0 },
      { id: "d", label: "2P = 3Q", score: 0 },
      { id: "e", label: "Hubungan P dan Q tidak dapat ditentukan", score: 0 },
    ],
    explanation: "Penyelesaian Persamaan Linear Satu Variabel:\n$$4x - 5 = 2x + 7$$\n$$4x - 2x = 7 + 5$$\n$$2x = 12 \\implies x = 6$$\nDiperoleh nilai kuantitas:\n$$P = 6$$\n$$Q = 4$$\nKarena $6 > 4$, maka hubungan yang benar adalah $P > Q$ (Opsi A).",
  },
  {
    id: "mini-tiu7-28",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Pak Anton dapat menyelesaikan pengecatan pagar sebuah rumah dinas dalam waktu 12 hari. Pak Budi dapat menyelesaikan pengecatan pagar yang sama dalam waktu 8 hari.\n$$P = \\text{Waktu yang dibutuhkan Pak Anton untuk menyelesaikan } \\frac{1}{3} \\text{ bagian pagar}$$\n$$Q = \\text{Waktu yang dibutuhkan Pak Budi untuk menyelesaikan } \\frac{3}{4} \\text{ bagian pagar}$$\nManakah hubungan yang benar antara kuantitas $P$ dan $Q$?",
    choices: [
      { id: "a", label: "P > Q", score: 0 },
      { id: "b", label: "P < Q", score: 5 },
      { id: "c", label: "P = Q", score: 0 },
      { id: "d", label: "P + Q = 11", score: 0 },
      { id: "e", label: "Hubungan P dan Q tidak dapat ditentukan", score: 0 },
    ],
    explanation: "Perhitungan Nilai Masing-Masing Kuantitas:\n- Kuantitas $P$ (Waktu Pak Anton):\n  $$P = \\frac{1}{3} \\times 12 \\text{ hari} = 4 \\text{ hari}$$\n- Kuantitas $Q$ (Waktu Pak Budi):\n  $$Q = \\frac{3}{4} \\times 8 \\text{ hari} = 6 \\text{ hari}$$\nKarena $4 < 6$, maka $P < Q$ (Opsi B).",
  },
  {
    id: "mini-tiu7-29",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Diketahui dua nilai pecahan:\n$$P = \\frac{3}{8} \\times 64$$\n$$Q = 0{,}75 \\times 32$$\nManakah hubungan yang benar antara kuantitas $P$ dan $Q$?",
    choices: [
      { id: "a", label: "P > Q", score: 0 },
      { id: "b", label: "P < Q", score: 0 },
      { id: "c", label: "P = Q", score: 5 },
      { id: "d", label: "P - Q = 2", score: 0 },
      { id: "e", label: "Hubungan P dan Q tidak dapat ditentukan", score: 0 },
    ],
    explanation: "Perhitungan Perbandingan Dua Kuantitas:\n- Hitung nilai $P$:\n  $$P = \\frac{3}{8} \\times 64 = 3 \\times 8 = 24$$\n- Hitung nilai $Q$:\n  $$Q = 0{,}75 \\times 32 = \\frac{3}{4} \\times 32 = 3 \\times 8 = 24$$\nKarena $24 = 24$, maka hubungan yang benar adalah $P = Q$ (Opsi C).",
  },
  {
    id: "mini-tiu7-30",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Diketahui $a, b,$ dan $c$ adalah bilangan bulat positif yang memenuhi persamaan $a + b + c = 30$.\n$$P = a \\times b$$\n$$Q = 100$$\nManakah hubungan yang benar antara kuantitas $P$ dan $Q$?",
    choices: [
      { id: "a", label: "P > Q", score: 0 },
      { id: "b", label: "P < Q", score: 0 },
      { id: "c", label: "P = Q", score: 0 },
      { id: "d", label: "P + Q = 200", score: 0 },
      { id: "e", label: "Hubungan P dan Q tidak dapat ditentukan", score: 5 },
    ],
    explanation: "Analisis Nilai Variabel Bebas pada Kuantitas P dan Q:\nDiketahui $a, b, c$ bilangan bulat positif dengan $a + b + c = 30$.\n- Kasus 1: Jika $a = 10, b = 10, c = 10$, maka $P = 10 \\times 10 = 100 \\implies P = Q$.\n- Kasus 2: Jika $a = 1, b = 1, c = 28$, maka $P = 1 \\times 1 = 1 \\implies P < Q$.\n- Kasus 3: Jika $a = 14, b = 14, c = 2$, maka $P = 14 \\times 14 = 196 \\implies P > Q$.\nKarena nilai $P$ dapat bernilai lebih kecil, sama dengan, maupun lebih besar dari $Q$ tergantung pemilihan nilai $(a, b)$, maka hubungan antara kuantitas $P$ dan $Q$ tidak dapat ditentukan dari informasi yang diberikan. Jawaban yang tepat adalah Opsi E.",
  },
  {
    id: "mini-tiu7-31",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: `[svg]<div style="font-size:15px;font-weight:600;color:#1e293b;margin-bottom:12px;">Perhatikan pola susunan bilangan dalam tabel $3 \\times 3$ berikut:</div><div style="display:flex;justify-content:center;margin:16px 0;"><table style="border-collapse:collapse;border:2px solid #334155;background:#ffffff;box-shadow:0 1px 3px rgba(0,0,0,0.08);"><tbody style="text-align:center;font-weight:600;font-size:18px;color:#0f172a;"><tr><td style="border:1.5px solid #64748b;padding:12px 22px;min-width:54px;">4</td><td style="border:1.5px solid #64748b;padding:12px 22px;min-width:54px;">36</td><td style="border:1.5px solid #64748b;padding:12px 22px;min-width:54px;">49</td></tr><tr><td style="border:1.5px solid #64748b;padding:12px 22px;min-width:54px;color:#2563eb;background:#eff6ff;font-size:20px;font-weight:bold;">X</td><td style="border:1.5px solid #64748b;padding:12px 22px;min-width:54px;">81</td><td style="border:1.5px solid #64748b;padding:12px 22px;min-width:54px;">1</td></tr><tr><td style="border:1.5px solid #64748b;padding:12px 22px;min-width:54px;">64</td><td style="border:1.5px solid #64748b;padding:12px 22px;min-width:54px;">9</td><td style="border:1.5px solid #64748b;padding:12px 22px;min-width:54px;">16</td></tr></tbody></table></div><div style="font-size:15px;color:#334155;margin-top:12px;">Nilai <strong>X</strong> yang tepat untuk melengkapi pola tabel di atas adalah ...</div>`,
    choices: [
      { id: "a", label: "25", score: 5 },
      { id: "b", label: "32", score: 0 },
      { id: "c", label: "45", score: 0 },
      { id: "d", label: "50", score: 0 },
      { id: "e", label: "100", score: 0 },
    ],
    explanation: "Analisis Pola Bilangan Kuadrat dalam Tabel:\nSemua bilangan di dalam tabel $3 \\times 3$ tersebut merupakan bilangan kuadrat sempurna dari bilangan bulat $1$ sampai $9$:\n- $1^2 = 1$\n- $2^2 = 4$\n- $3^2 = 9$\n- $4^2 = 16$\n- $5^2 = 25$\n- $6^2 = 36$\n- $7^2 = 49$\n- $8^2 = 64$\n- $9^2 = 81$\n\nBerdasarkan pola per kolom ditinjau dari nilai akar kuadratnya:\n- Kolom 3: $\\sqrt{1}=1$, $\\sqrt{16}=4$, $\\sqrt{49}=7$ (pola melompat $+3$: $1, 4, 7$)\n- Kolom 2: $\\sqrt{9}=3$, $\\sqrt{36}=6$, $\\sqrt{81}=9$ (pola melompat $+3$: $3, 6, 9$)\n- Kolom 1: $\\sqrt{4}=2$, $\\sqrt{X}$, $\\sqrt{64}=8$ (pola melompat $+3$: $2, 5, 8$)\nMaka akar kuadrat dari $X$ haruslah $5$, sehingga $X = 5^2 = 25$.\nJawaban yang tepat adalah 25 (Opsi A).",
  },
  {
    id: "mini-tiu7-32",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: `[svg]<div style="font-size:15px;font-weight:600;color:#1e293b;margin-bottom:12px;">Perhatikan pola penjumlahan antar-baris pada tabel $3 \\times 3$ berikut:</div><div style="display:flex;justify-content:center;margin:16px 0;"><table style="border-collapse:collapse;border:2px solid #334155;background:#ffffff;box-shadow:0 1px 3px rgba(0,0,0,0.08);"><tbody style="text-align:center;font-weight:600;font-size:18px;color:#0f172a;"><tr><td style="border:1.5px solid #64748b;padding:12px 22px;min-width:54px;">1</td><td style="border:1.5px solid #64748b;padding:12px 22px;min-width:54px;">3</td><td style="border:1.5px solid #64748b;padding:12px 22px;min-width:54px;">5</td></tr><tr><td style="border:1.5px solid #64748b;padding:12px 22px;min-width:54px;">3</td><td style="border:1.5px solid #64748b;padding:12px 22px;min-width:54px;">2</td><td style="border:1.5px solid #64748b;padding:12px 22px;min-width:54px;">8</td></tr><tr><td style="border:1.5px solid #64748b;padding:12px 22px;min-width:54px;">4</td><td style="border:1.5px solid #64748b;padding:12px 22px;min-width:54px;">5</td><td style="border:1.5px solid #64748b;padding:12px 22px;min-width:54px;color:#2563eb;background:#eff6ff;font-size:20px;font-weight:bold;">X</td></tr></tbody></table></div><div style="font-size:15px;color:#334155;margin-top:12px;">Nilai <strong>X</strong> yang tepat untuk melengkapi pola tabel di atas adalah ...</div>`,
    choices: [
      { id: "a", label: "10", score: 0 },
      { id: "b", label: "11", score: 0 },
      { id: "c", label: "12", score: 0 },
      { id: "d", label: "13", score: 5 },
      { id: "e", label: "15", score: 0 },
    ],
    explanation: "Analisis Pola Operasi Penjumlahan Vertikal (Baris 1 + Baris 2 = Baris 3):\nPerhatikan pola pada setiap kolom tabel:\n- Kolom 1: $1 + 3 = 4$\n- Kolom 2: $3 + 2 = 5$\n- Kolom 3: $5 + 8 = X$\n\nBerdasarkan aturan baris pertama ditambah baris kedua menghasilkan baris ketiga:\n$$X = 5 + 8 = 13$$\nJawaban yang tepat adalah 13 (Opsi D).",
  },
  {
    id: "mini-tiu7-33",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: `[svg]<div style="font-size:15px;font-weight:600;color:#1e293b;margin-bottom:12px;">Perhatikan pola relasi aritmetika antar-kolom pada tabel $3 \\times 4$ berikut:</div><div style="display:flex;justify-content:center;margin:16px 0;"><table style="border-collapse:collapse;border:2px solid #334155;background:#ffffff;box-shadow:0 1px 3px rgba(0,0,0,0.08);"><tbody style="text-align:center;font-weight:600;font-size:18px;color:#0f172a;"><tr><td style="border:1.5px solid #64748b;padding:12px 20px;min-width:50px;">10</td><td style="border:1.5px solid #64748b;padding:12px 20px;min-width:50px;">5</td><td style="border:1.5px solid #64748b;padding:12px 20px;min-width:50px;">3</td><td style="border:1.5px solid #64748b;padding:12px 20px;min-width:50px;background:#f1f5f9;">15</td></tr><tr><td style="border:1.5px solid #64748b;padding:12px 20px;min-width:50px;">8</td><td style="border:1.5px solid #64748b;padding:12px 20px;min-width:50px;">2</td><td style="border:1.5px solid #64748b;padding:12px 20px;min-width:50px;">4</td><td style="border:1.5px solid #64748b;padding:12px 20px;min-width:50px;background:#f1f5f9;">24</td></tr><tr><td style="border:1.5px solid #64748b;padding:12px 20px;min-width:50px;">6</td><td style="border:1.5px solid #64748b;padding:12px 20px;min-width:50px;">3</td><td style="border:1.5px solid #64748b;padding:12px 20px;min-width:50px;">5</td><td style="border:1.5px solid #64748b;padding:12px 20px;min-width:50px;color:#2563eb;background:#eff6ff;font-size:20px;font-weight:bold;">X</td></tr></tbody></table></div><div style="font-size:15px;color:#334155;margin-top:12px;">Nilai <strong>X</strong> yang tepat untuk melengkapi pola tabel di atas adalah ...</div>`,
    choices: [
      { id: "a", label: "11", score: 0 },
      { id: "b", label: "13", score: 0 },
      { id: "c", label: "15", score: 5 },
      { id: "d", label: "18", score: 0 },
      { id: "e", label: "20", score: 0 },
    ],
    explanation: "Analisis Pola Operasi Horizontal Antar-Kolom:\nPerhatikan operasi aritmetika dari Kolom 1 ($K_1$), Kolom 2 ($K_2$), dan Kolom 3 ($K_3$) untuk memperoleh Kolom 4 ($K_4$) pada setiap baris:\n$$(K_1 - K_2) \\times K_3 = K_4$$\n- Baris 1: $(10 - 5) \\times 3 = 5 \\times 3 = 15$\n- Baris 2: $(8 - 2) \\times 4 = 6 \\times 4 = 24$\n- Baris 3: $(6 - 3) \\times 5 = 3 \\times 5 = 15$\n\nMaka nilai $X$ adalah:\n$$X = 15$$\nJawaban yang tepat adalah 15 (Opsi C).",
  },
  {
    id: "mini-tiu7-34",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: `[svg]<div style="font-size:15px;font-weight:600;color:#1e293b;margin-bottom:12px;">Perhatikan pola kombinasi aritmetika pada tabel $3 \\times 4$ berikut:</div><div style="display:flex;justify-content:center;margin:16px 0;"><table style="border-collapse:collapse;border:2px solid #334155;background:#ffffff;box-shadow:0 1px 3px rgba(0,0,0,0.08);"><tbody style="text-align:center;font-weight:600;font-size:18px;color:#0f172a;"><tr><td style="border:1.5px solid #64748b;padding:12px 20px;min-width:50px;">13</td><td style="border:1.5px solid #64748b;padding:12px 20px;min-width:50px;">3</td><td style="border:1.5px solid #64748b;padding:12px 20px;min-width:50px;">3</td><td style="border:1.5px solid #64748b;padding:12px 20px;min-width:50px;background:#f1f5f9;">36</td></tr><tr><td style="border:1.5px solid #64748b;padding:12px 20px;min-width:50px;">8</td><td style="border:1.5px solid #64748b;padding:12px 20px;min-width:50px;">3</td><td style="border:1.5px solid #64748b;padding:12px 20px;min-width:50px;">5</td><td style="border:1.5px solid #64748b;padding:12px 20px;min-width:50px;background:#f1f5f9;">19</td></tr><tr><td style="border:1.5px solid #64748b;padding:12px 20px;min-width:50px;">7</td><td style="border:1.5px solid #64748b;padding:12px 20px;min-width:50px;">6</td><td style="border:1.5px solid #64748b;padding:12px 20px;min-width:50px;">10</td><td style="border:1.5px solid #64748b;padding:12px 20px;min-width:50px;color:#2563eb;background:#eff6ff;font-size:20px;font-weight:bold;">X</td></tr></tbody></table></div><div style="font-size:15px;color:#334155;margin-top:12px;">Nilai <strong>X</strong> yang tepat untuk melengkapi pola tabel di atas adalah ...</div>`,
    choices: [
      { id: "a", label: "24", score: 0 },
      { id: "b", label: "28", score: 0 },
      { id: "c", label: "30", score: 0 },
      { id: "d", label: "32", score: 5 },
      { id: "e", label: "36", score: 0 },
    ],
    explanation: "Analisis Pola Operasi Horizontal Kombinasi Perkalian dan Pengurangan:\nPerhatikan hubungan aritmetika antar-kolom pada setiap baris:\n$$(K_1 \\times K_2) - K_3 = K_4$$\n- Baris 1: $(13 \\times 3) - 3 = 39 - 3 = 36$\n- Baris 2: $(8 \\times 3) - 5 = 24 - 5 = 19$\n- Baris 3: $(7 \\times 6) - 10 = 42 - 10 = 32$\n\nMaka nilai $X$ adalah:\n$$X = 32$$\nJawaban yang tepat adalah 32 (Opsi D).",
  },
  {
    id: "mini-tiu7-35",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: `[svg]<div style="font-size:15px;font-weight:600;color:#1e293b;margin-bottom:12px;">Perhatikan pola deret operasi bertingkat pada setiap baris tabel $4 \\times 4$ berikut:</div><div style="display:flex;justify-content:center;margin:16px 0;"><table style="border-collapse:collapse;border:2px solid #334155;background:#ffffff;box-shadow:0 1px 3px rgba(0,0,0,0.08);"><tbody style="text-align:center;font-weight:600;font-size:17px;color:#0f172a;"><tr><td style="border:1.5px solid #64748b;padding:10px 16px;min-width:48px;">48</td><td style="border:1.5px solid #64748b;padding:10px 16px;min-width:48px;">63</td><td style="border:1.5px solid #64748b;padding:10px 16px;min-width:48px;">126</td><td style="border:1.5px solid #64748b;padding:10px 16px;min-width:48px;">89</td></tr><tr><td style="border:1.5px solid #64748b;padding:10px 16px;min-width:48px;">-26</td><td style="border:1.5px solid #64748b;padding:10px 16px;min-width:48px;">-11</td><td style="border:1.5px solid #64748b;padding:10px 16px;min-width:48px;">-22</td><td style="border:1.5px solid #64748b;padding:10px 16px;min-width:48px;">-59</td></tr><tr><td style="border:1.5px solid #64748b;padding:10px 16px;min-width:48px;color:#2563eb;background:#eff6ff;font-size:19px;font-weight:bold;">X</td><td style="border:1.5px solid #64748b;padding:10px 16px;min-width:48px;">74</td><td style="border:1.5px solid #64748b;padding:10px 16px;min-width:48px;">148</td><td style="border:1.5px solid #64748b;padding:10px 16px;min-width:48px;">111</td></tr><tr><td style="border:1.5px solid #64748b;padding:10px 16px;min-width:48px;">31</td><td style="border:1.5px solid #64748b;padding:10px 16px;min-width:48px;">46</td><td style="border:1.5px solid #64748b;padding:10px 16px;min-width:48px;">92</td><td style="border:1.5px solid #64748b;padding:10px 16px;min-width:48px;">55</td></tr></tbody></table></div><div style="font-size:15px;color:#334155;margin-top:12px;">Nilai <strong>X</strong> yang tepat untuk mengisi posisi baris ketiga kolom pertama adalah ...</div>`,
    choices: [
      { id: "a", label: "47", score: 0 },
      { id: "b", label: "51", score: 0 },
      { id: "c", label: "53", score: 0 },
      { id: "d", label: "56", score: 0 },
      { id: "e", label: "59", score: 5 },
    ],
    explanation: "Analisis Pola Deret Bertingkat Sepanjang Baris:\nPerhatikan aturan operasi perubahan antar-kolom berurutan pada setiap baris:\n- Langkah 1 ($K_1 \\rightarrow K_2$): Ditambah $15$ ($+15$)\n- Langkah 2 ($K_2 \\rightarrow K_3$): Dikalikan $2$ ($\\times 2$)\n- Langkah 3 ($K_3 \\rightarrow K_4$): Dikurang $37$ ($-37$)\n\nPengujian konsistensi pola pada baris lain:\n- Baris 1: $48 \\xrightarrow{+15} 63 \\xrightarrow{\\times 2} 126 \\xrightarrow{-37} 89$ (Terbukti benar)\n- Baris 2: $-26 \\xrightarrow{+15} -11 \\xrightarrow{\\times 2} -22 \\xrightarrow{-37} -59$ (Terbukti benar)\n- Baris 4: $31 \\xrightarrow{+15} 46 \\xrightarrow{\\times 2} 92 \\xrightarrow{-37} 55$ (Terbukti benar)\n\nPenerapan aturan pada Baris 3:\n$$X \\xrightarrow{+15} 74 \\xrightarrow{\\times 2} 148 \\xrightarrow{-37} 111$$\nMaka nilai $X$:\n$$X + 15 = 74 \\implies X = 74 - 15 = 59$$\nJawaban yang tepat adalah 59 (Opsi E).",
  },
];
