import type { Question } from "./types";

export const MINI_TIU_8_QUESTIONS: Question[] = [
  {
    id: "mini-tiu8-01",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "Jujur : curang = ... : ...",
    choices: [
      { id: "a", label: "curiga : percaya", score: 0 },
      { id: "b", label: "ceroboh : cermat", score: 0 },
      { id: "c", label: "hemat : boros", score: 5 },
      { id: "d", label: "pesimistis : optimistis", score: 0 },
      { id: "e", label: "malas : rajin", score: 0 },
    ],
    explanation: "Pembahasan: Jujur dan curang merupakan antonim dengan arah makna positif menuju negatif. Hemat dan boros memiliki hubungan serta arah yang sama. Opsi lainnya juga berupa antonim, tetapi bergerak dari makna negatif menuju positif. Jawaban C.",
  },
  {
    id: "mini-tiu8-02",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "Saringan : partikel = kriteria : ...",
    choices: [
      { id: "a", label: "kandidat", score: 5 },
      { id: "b", label: "kelulusan", score: 0 },
      { id: "c", label: "wawancara", score: 0 },
      { id: "d", label: "keputusan", score: 0 },
      { id: "e", label: "panitia", score: 0 },
    ],
    explanation: "Pembahasan: Saringan menyeleksi partikel berdasarkan karakteristik tertentu. Dengan pola yang sama, kriteria digunakan untuk menyeleksi kandidat. Jawaban A.",
  },
  {
    id: "mini-tiu8-03",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "Premis : inferensi : kesimpulan = data : analisis : ...",
    choices: [
      { id: "a", label: "variabel", score: 0 },
      { id: "b", label: "hipotesis", score: 0 },
      { id: "c", label: "metode", score: 0 },
      { id: "d", label: "temuan", score: 5 },
      { id: "e", label: "observasi", score: 0 },
    ],
    explanation: "Pembahasan: Premis diproses melalui inferensi untuk menghasilkan kesimpulan. Dengan pola yang sama, data diproses melalui analisis untuk menghasilkan temuan (input -> proses -> keluaran). Jawaban D.",
  },
  {
    id: "mini-tiu8-04",
    category: "TIU",
    topic: "Logika Analitis",
    prompt: "Jika arsip telah didigitalisasi, arsip tersebut akan mudah dicari. Hasil pemeriksaan menunjukkan bahwa satu arsip tidak mudah dicari. Kesimpulan yang tepat adalah ...",
    choices: [
      { id: "a", label: "arsip itu telah didigitalisasi", score: 0 },
      { id: "b", label: "arsip itu belum didigitalisasi", score: 5 },
      { id: "c", label: "arsip itu pasti hilang", score: 0 },
      { id: "d", label: "semua arsip sulit dicari", score: 0 },
      { id: "e", label: "tidak dapat ditarik kesimpulan", score: 0 },
    ],
    explanation: "Pembahasan: Misalkan P = arsip telah didigitalisasi dan Q = arsip mudah dicari. Premis memberi P -> Q dan ~Q, sehingga melalui modus tollens berlaku ~P (arsip itu belum didigitalisasi). Jawaban B.",
  },
  {
    id: "mini-tiu8-05",
    category: "TIU",
    topic: "Logika Analitis",
    prompt: "Beberapa peneliti juga bekerja sebagai dosen. Tidak satu pun dosen buta aksara. Berdasarkan informasi tersebut, kesimpulan yang pasti benar adalah ...",
    choices: [
      { id: "a", label: "semua peneliti adalah dosen", score: 0 },
      { id: "b", label: "semua peneliti tidak buta aksara", score: 0 },
      { id: "c", label: "beberapa peneliti tidak buta aksara", score: 5 },
      { id: "d", label: "beberapa orang buta aksara adalah peneliti", score: 0 },
      { id: "e", label: "tidak ada peneliti yang menjadi dosen", score: 0 },
    ],
    explanation: "Pembahasan: Ada setidaknya satu peneliti yang juga dosen. Karena tidak ada dosen yang buta aksara, peneliti yang merangkap dosen tersebut pasti tidak buta aksara. Jadi, beberapa peneliti tidak buta aksara. Jawaban C.",
  },
  {
    id: "mini-tiu8-06",
    category: "TIU",
    topic: "Logika Analitis",
    prompt: "Pada sebuah sistem verifikasi berlaku aturan: jika A dan B benar, maka C benar. Jika C benar, maka D benar. Hasil pemeriksaan menunjukkan bahwa A benar, tetapi D salah. Pernyataan yang pasti benar adalah ...",
    choices: [
      { id: "a", label: "B benar", score: 0 },
      { id: "b", label: "C benar", score: 0 },
      { id: "c", label: "A salah", score: 0 },
      { id: "d", label: "B salah", score: 5 },
      { id: "e", label: "D benar", score: 0 },
    ],
    explanation: "Pembahasan: D salah menyebabkan C salah melalui modus tollens pada C -> D. Karena A benar dan (A dan B) -> C, maka konjungsi (A dan B) harus bernilai salah. Mengingat A bernilai benar, maka B pasti salah. Jawaban D.",
  },
  {
    id: "mini-tiu8-07",
    category: "TIU",
    topic: "Logika Analitis",
    prompt: "Tujuh peserta, yaitu Dika, Maya, Sari, Nia, Tono, Vina, dan Raka, mengikuti wawancara secara bergiliran. Dika mendapat giliran pertama. Sari tepat setelah Maya. Nia mendapat giliran setelah Sari, tetapi sebelum Tono. Vina tepat sebelum Raka, sedangkan Raka mendapat giliran terakhir. Siapa yang mendapat giliran keempat?",
    choices: [
      { id: "a", label: "Maya", score: 0 },
      { id: "b", label: "Sari", score: 0 },
      { id: "c", label: "Nia", score: 5 },
      { id: "d", label: "Tono", score: 0 },
      { id: "e", label: "Vina", score: 0 },
    ],
    explanation: "Pembahasan: Dika di posisi 1, Raka di posisi 7, dan Vina di posisi 6 (tepat sebelum Raka). Empat posisi di tengah (2, 3, 4, 5) harus diisi berturut-turut oleh Maya, Sari, Nia, dan Tono. Jadi urutannya: 1-Dika, 2-Maya, 3-Sari, 4-Nia, 5-Tono, 6-Vina, 7-Raka. Giliran keempat ditempati oleh Nia. Jawaban C.",
  },
  {
    id: "mini-tiu8-08",
    category: "TIU",
    topic: "Logika Analitis",
    prompt: "Dalam sesi foto resmi, enam delegasi A, B, C, D, E, dan F duduk berjajar. A dan B harus berdampingan karena berasal dari tim yang sama. C dan D juga harus berdampingan, sedangkan E harus duduk di kursi paling kanan. Berapa banyak susunan yang memenuhi ketentuan tersebut?",
    choices: [
      { id: "a", label: "12", score: 0 },
      { id: "b", label: "18", score: 0 },
      { id: "c", label: "24", score: 5 },
      { id: "d", label: "36", score: 0 },
      { id: "e", label: "48", score: 0 },
    ],
    explanation: "Pembahasan: Tetapkan E di kursi ke-6. Pada lima kursi tersisa (1-5), anggap (A, B) sebagai blok 1, (C, D) sebagai blok 2, dan F sebagai satu unsur tersendiri. Ketiga kelompok dapat disusun dalam 3! = 6 cara. Urutan internal dalam blok (A, B) ada 2 cara dan blok (C, D) ada 2 cara. Total susunan = 3! x 2 x 2 = 6 x 4 = 24. Jawaban C.",
  },
  {
    id: "mini-tiu8-09",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Nilai dari 3/4 + 0,6 - 25% x 1,4 adalah ...",
    choices: [
      { id: "a", label: "0,90", score: 0 },
      { id: "b", label: "1,00", score: 5 },
      { id: "c", label: "1,10", score: 0 },
      { id: "d", label: "1,25", score: 0 },
      { id: "e", label: "1,35", score: 0 },
    ],
    explanation: "Pembahasan: 3/4 = 0,75 dan 25% x 1,4 = 0,25 x 1,4 = 0,35. Maka nilainya: 0,75 + 0,60 - 0,35 = 1,00. Jawaban B.",
  },
  {
    id: "mini-tiu8-10",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Nilai dari 37,5% x 2 2/3 + 0,125 : 1/2 + (3:2)/5 adalah ...",
    choices: [
      { id: "a", label: "1,25", score: 0 },
      { id: "b", label: "1,35", score: 0 },
      { id: "c", label: "1,50", score: 0 },
      { id: "d", label: "1,55", score: 5 },
      { id: "e", label: "1,75", score: 0 },
    ],
    explanation: "Pembahasan: 37,5% = 3/8 dan 2 2/3 = 8/3, sehingga perkaliannya: 3/8 x 8/3 = 1. Kemudian 0,125 : 1/2 = 1/8 x 2 = 1/4 = 0,25. Selanjutnya (3:2)/5 = 1,5 / 5 = 0,30. Total = 1 + 0,25 + 0,30 = 1,55. Jawaban D.",
  },
  {
    id: "mini-tiu8-11",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Diketahui P = 497 x 503 dan Q = 500^2. Hubungan P dan Q yang benar adalah ...",
    choices: [
      { id: "a", label: "P > Q", score: 0 },
      { id: "b", label: "P < Q", score: 5 },
      { id: "c", label: "P = Q", score: 0 },
      { id: "d", label: "P = Q + 9", score: 0 },
      { id: "e", label: "hubungan tidak dapat ditentukan", score: 0 },
    ],
    explanation: "Pembahasan: P = (500 - 3)(500 + 3) = 500^2 - 3^2 = 500^2 - 9 = Q - 9. Karena P bernilai 9 lebih kecil dari Q, maka hubungan yang benar adalah P < Q. Jawaban B.",
  },
  {
    id: "mini-tiu8-12",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Pasangan perkalian yang memiliki nilai sama adalah ...",
    choices: [
      { id: "a", label: "125 x 56 dan 115 x 75", score: 0 },
      { id: "b", label: "128 x 45 dan 96 x 60", score: 5 },
      { id: "c", label: "144 x 35 dan 125 x 40", score: 0 },
      { id: "d", label: "175 x 32 dan 160 x 36", score: 0 },
      { id: "e", label: "225 x 24 dan 215 x 25", score: 0 },
    ],
    explanation: "Pembahasan: 128 x 45 = 5.760 dan 96 x 60 = 5.760. Dari 128 menjadi 96 faktor pertama dikali 3/4, dan dari 45 menjadi 60 faktor kedua dikali 4/3. Karena (3/4) x (4/3) = 1, kedua pasangan memiliki nilai perkalian yang sama. Jawaban B.",
  },
  {
    id: "mini-tiu8-13",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "Angka berikutnya pada deret 2, 6, 15, 31, 56, ... adalah ...",
    choices: [
      { id: "a", label: "81", score: 0 },
      { id: "b", label: "87", score: 0 },
      { id: "c", label: "90", score: 0 },
      { id: "d", label: "92", score: 5 },
      { id: "e", label: "96", score: 0 },
    ],
    explanation: "Pembahasan: Selisih antarsuku berturut-turut adalah 4, 9, 16, dan 25 yang merupakan pola kuadrat (2^2, 3^2, 4^2, 5^2). Selisih berikutnya adalah 6^2 = 36. Maka suku berikutnya: 56 + 36 = 92. Jawaban D.",
  },
  {
    id: "mini-tiu8-14",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "Angka berikutnya pada deret 3, 20, 6, 18, 12, 16, 24, 14, ... adalah ...",
    choices: [
      { id: "a", label: "12", score: 0 },
      { id: "b", label: "26", score: 0 },
      { id: "c", label: "28", score: 0 },
      { id: "d", label: "36", score: 0 },
      { id: "e", label: "48", score: 5 },
    ],
    explanation: "Pembahasan: Deret memiliki dua larik berselang-seling:\n- Larik ganjil: 3, 6, 12, 24, ... (pola dikali 2, suku berikutnya = 24 x 2 = 48)\n- Larik genap: 20, 18, 16, 14, ... (pola dikurangi 2)\nSuku kesembilan berada pada larik ganjil, yaitu 48. Jawaban E.",
  },
  {
    id: "mini-tiu8-15",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "Nilai suku ke-13 pada tabel berikut adalah ...\n\n| Suku ke-n | Nilai |\n| :---: | :---: |\n| 2 | 8 |\n| 4 | 24 |\n| 7 | 63 |\n| 10 | 120 |\n| 13 | ? |",
    choices: [
      { id: "a", label: "169", score: 0 },
      { id: "b", label: "182", score: 0 },
      { id: "c", label: "195", score: 5 },
      { id: "d", label: "208", score: 0 },
      { id: "e", label: "225", score: 0 },
    ],
    explanation: "Pembahasan: Pasangan pada tabel memenuhi rumus U_n = n x (n + 2):\nU2 = 2 x 4 = 8\nU4 = 4 x 6 = 24\nU7 = 7 x 9 = 63\nU10 = 10 x 12 = 120\nMaka untuk n = 13: U13 = 13 x (13 + 2) = 13 x 15 = 195. Jawaban C.",
  },
  {
    id: "mini-tiu8-16",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "Perhatikan matriks angka berikut:\n\n| 4 | 7 | 5 | 23 |\n| 6 | 5 | 8 | 22 |\n| 9 | 4 | 7 | ? |\n\nNilai pengganti tanda tanya adalah ...",
    choices: [
      { id: "a", label: "25", score: 0 },
      { id: "b", label: "27", score: 0 },
      { id: "c", label: "29", score: 5 },
      { id: "d", label: "31", score: 0 },
      { id: "e", label: "36", score: 0 },
    ],
    explanation: "Pembahasan: Pola operasi pada setiap baris adalah: (Kolom 1 x Kolom 2) - Kolom 3 = Kolom 4.\nBaris 1: (4 x 7) - 5 = 28 - 5 = 23\nBaris 2: (6 x 5) - 8 = 30 - 8 = 22\nBaris 3: (9 x 4) - 7 = 36 - 7 = 29. Jawaban C.",
  },
  {
    id: "mini-tiu8-17",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "Perhatikan matriks angka berikut:\n\n| 2 | 3 | 5 |\n| 7 | 11 | 13 |\n| 17 | ? | 23 |\n\nNilai pengganti tanda tanya adalah ...",
    choices: [
      { id: "a", label: "18", score: 0 },
      { id: "b", label: "19", score: 5 },
      { id: "c", label: "20", score: 0 },
      { id: "d", label: "21", score: 0 },
      { id: "e", label: "25", score: 0 },
    ],
    explanation: "Pembahasan: Matriks memuat urutan sembilan bilangan prima pertama yang dibaca dari kiri ke kanan: 2, 3, 5, 7, 11, 13, 17, 19, 23. Jadi tanda tanya diisi bilangan prima 19. Jawaban B.",
  },
  {
    id: "mini-tiu8-18",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "Nilai suku ke-45 pada tabel berikut adalah ...\n\n| Suku ke-n | Nilai |\n| :---: | :---: |\n| 8 | 29 |\n| 13 | 49 |\n| 21 | 81 |\n| 45 | ? |",
    choices: [
      { id: "a", label: "169", score: 0 },
      { id: "b", label: "173", score: 0 },
      { id: "c", label: "177", score: 5 },
      { id: "d", label: "181", score: 0 },
      { id: "e", label: "209", score: 0 },
    ],
    explanation: "Pembahasan: Beda per satu indeks = (49 - 29) / (13 - 8) = 20 / 5 = 4. Menghitung langsung dari suku ke-8: U45 = U8 + (45 - 8) x 4 = 29 + (37 x 4) = 29 + 148 = 177. Jawaban C.",
  },
  {
    id: "mini-tiu8-19",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Sebuah tas memperoleh diskon 20% dari harga awal, lalu dikenai pajak 10% yang dihitung dari harga setelah diskon. Jika pembeli membayar Rp440.000, harga awal tas adalah ...",
    choices: [
      { id: "a", label: "Rp480.000", score: 0 },
      { id: "b", label: "Rp484.000", score: 0 },
      { id: "c", label: "Rp490.000", score: 0 },
      { id: "d", label: "Rp500.000", score: 5 },
      { id: "e", label: "Rp550.000", score: 0 },
    ],
    explanation: "Pembahasan: Harga akhir = (1 - 0,20) x (1 + 0,10) x Harga Awal = 0,8 x 1,1 x Harga Awal = 0,88 x Harga Awal. Maka Harga Awal = Rp440.000 / 0,88 = Rp500.000. Jawaban D.",
  },
  {
    id: "mini-tiu8-20",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Sebanyak 15 pekerja dapat menyelesaikan suatu proyek dalam 24 hari kerja. Proyek tersebut kemudian dikerjakan oleh 20 pekerja dengan kemampuan yang sama. Mereka mulai bekerja pada hari Senin dan libur setiap hari Minggu. Pada hari apa proyek selesai?",
    choices: [
      { id: "a", label: "Rabu", score: 0 },
      { id: "b", label: "Kamis", score: 0 },
      { id: "c", label: "Jumat", score: 0 },
      { id: "d", label: "Sabtu", score: 5 },
      { id: "e", label: "Senin", score: 0 },
    ],
    explanation: "Pembahasan: Beban kerja proyek = 15 x 24 = 360 hari-orang. Dengan 20 pekerja, proyek memerlukan 360 / 20 = 18 hari kerja. Karena bekerja Senin sampai Sabtu (6 hari kerja per minggu) dan libur hari Minggu, 18 hari kerja tepat berlangsung selama 3 minggu penuh dan selesai pada hari Sabtu minggu ketiga. Jawaban D.",
  },
  {
    id: "mini-tiu8-21",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Bus P berangkat dari Kota X pukul 07.15 menuju Kota Y dengan kecepatan 60 km/jam. Bus Q berangkat dari Kota Y pukul 07.45 menuju Kota X dengan kecepatan 75 km/jam. Jika jarak kedua kota 300 km, pukul berapa kedua bus berpapasan?",
    choices: [
      { id: "a", label: "09.15", score: 0 },
      { id: "b", label: "09.30", score: 0 },
      { id: "c", label: "09.45", score: 5 },
      { id: "d", label: "10.00", score: 0 },
      { id: "e", label: "10.15", score: 0 },
    ],
    explanation: "Pembahasan: Pada pukul 07.45 (setelah 30 menit / 0,5 jam), Bus P telah menempuh jarak 60 x 0,5 = 30 km. Sisa jarak kedua bus pada pukul 07.45 adalah 300 - 30 = 270 km. Kecepatan saling mendekat = 60 + 75 = 135 km/jam. Waktu tempuh hingga berpapasan = 270 / 135 = 2 jam setelah pukul 07.45, yaitu pukul 09.45. Jawaban C.",
  },
  {
    id: "mini-tiu8-22",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Adi berumur 4 tahun lebih tua daripada Budi. Berapa umur Adi saat ini?\n\n(1) Jumlah umur Adi dan Budi adalah 32 tahun.\n(2) Umur Budi merupakan kelipatan 3.",
    choices: [
      { id: "a", label: "Pernyataan (1) saja cukup, tetapi pernyataan (2) saja tidak cukup.", score: 5 },
      { id: "b", label: "Pernyataan (2) saja cukup, tetapi pernyataan (1) saja tidak cukup.", score: 0 },
      { id: "c", label: "Kedua pernyataan bersama-sama cukup, tetapi masing-masing pernyataan saja tidak cukup.", score: 0 },
      { id: "d", label: "Masing-masing pernyataan secara terpisah sudah cukup.", score: 0 },
      { id: "e", label: "Bahkan kedua pernyataan bersama-sama masih tidak cukup.", score: 0 },
    ],
    explanation: "Pembahasan: Dari soal diketahui A = B + 4. Pernyataan (1) memberi A + B = 32 -> (B + 4) + B = 32 -> 2B = 28 -> B = 14, sehingga umur Adi = 18 tahun (cukup). Pernyataan (2) hanya membatasi umur Budi sebagai kelipatan 3 dan menyisakan banyak kemungkinan (tidak cukup). Jadi pernyataan (1) saja cukup, tetapi pernyataan (2) saja tidak cukup. Jawaban A.",
  },
  {
    id: "mini-tiu8-23",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Pada nota pembelian, harga satu buku dinyatakan b rupiah dan harga satu pensil p rupiah. Berapakah harga satu buku?\n\n(1) 3b + 2p = 64.000.\n(2) 2b + 3p = 61.000.",
    choices: [
      { id: "a", label: "Pernyataan (1) saja cukup, tetapi pernyataan (2) saja tidak cukup.", score: 0 },
      { id: "b", label: "Pernyataan (2) saja cukup, tetapi pernyataan (1) saja tidak cukup.", score: 0 },
      { id: "c", label: "Kedua pernyataan bersama-sama cukup, tetapi masing-masing pernyataan saja tidak cukup.", score: 5 },
      { id: "d", label: "Masing-masing pernyataan secara terpisah sudah cukup.", score: 0 },
      { id: "e", label: "Bahkan kedua pernyataan bersama-sama masih tidak cukup.", score: 0 },
    ],
    explanation: "Pembahasan: Masing-masing pernyataan hanya memberi satu persamaan dengan dua variabel sehingga belum cukup secara mandiri. Kedua persamaan saling bebas dan membentuk sistem SPLDV: jika dijumlahkan atau dieliminasi, diperoleh nilai unik b = Rp14.000. Jadi kedua pernyataan bersama-sama cukup, tetapi masing-masing pernyataan saja tidak cukup. Jawaban C.",
  },
  {
    id: "mini-tiu8-24",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Bus A berangkat dari terminal pukul 07.00 dengan kecepatan tetap 60 km/jam. Bus B berangkat pukul 08.00 dari terminal dan rute yang sama. Pukul berapa Bus B menyusul Bus A?\n\n(1) Kecepatan Bus B 90 km/jam.\n(2) Kota tujuan berjarak 300 km dari terminal.",
    choices: [
      { id: "a", label: "Pernyataan (1) saja cukup, tetapi pernyataan (2) saja tidak cukup.", score: 5 },
      { id: "b", label: "Pernyataan (2) saja cukup, tetapi pernyataan (1) saja tidak cukup.", score: 0 },
      { id: "c", label: "Kedua pernyataan bersama-sama cukup, tetapi masing-masing pernyataan saja tidak cukup.", score: 0 },
      { id: "d", label: "Masing-masing pernyataan secara terpisah sudah cukup.", score: 0 },
      { id: "e", label: "Bahkan kedua pernyataan bersama-sama masih tidak cukup.", score: 0 },
    ],
    explanation: "Pembahasan: Saat pukul 08.00, Bus A telah menempuh 60 km (head start). Pernyataan (1) memberikan kecepatan Bus B = 90 km/jam sehingga kecepatan relatif menyusul = 90 - 60 = 30 km/jam. Waktu menyusul = 60 / 30 = 2 jam, yaitu pukul 10.00 (cukup). Pernyataan (2) tidak memberikan kecepatan Bus B (tidak cukup). Jadi pernyataan (1) saja cukup, tetapi pernyataan (2) saja tidak cukup. Jawaban A.",
  },
  {
    id: "mini-tiu8-25",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Sebanyak 170 paket bantuan dibagikan kepada Desa A, Desa B, dan Desa C. Berapa paket yang diterima Desa C?\n\n(1) Perbandingan paket untuk Desa A dan Desa B adalah 3:4.\n(2) Perbandingan paket untuk Desa B dan Desa C adalah 2:5.",
    choices: [
      { id: "a", label: "Pernyataan (1) saja cukup, tetapi pernyataan (2) saja tidak cukup.", score: 0 },
      { id: "b", label: "Pernyataan (2) saja cukup, tetapi pernyataan (1) saja tidak cukup.", score: 0 },
      { id: "c", label: "Kedua pernyataan bersama-sama cukup, tetapi masing-masing pernyataan saja tidak cukup.", score: 5 },
      { id: "d", label: "Masing-masing pernyataan secara terpisah sudah cukup.", score: 0 },
      { id: "e", label: "Bahkan kedua pernyataan bersama-sama masih tidak cukup.", score: 0 },
    ],
    explanation: "Pembahasan: Masing-masing pernyataan hanya menghubungkan dua desa sehingga belum cukup menentukan bagian Desa C. Jika digabungkan, rasio A : B = 3 : 4 dan B : C = 2 : 5 = 4 : 10, sehingga A : B : C = 3 : 4 : 10 (total 17 bagian). Total 170 paket berarti 1 bagian = 10 paket, sehingga Desa C menerima 10 x 10 = 100 paket. Jadi kedua pernyataan bersama-sama cukup, tetapi masing-masing pernyataan saja tidak cukup. Jawaban C.",
  },
  {
    id: "mini-tiu8-26",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Adi dapat menyelesaikan suatu pekerjaan dalam 7 jam, sedangkan Budi dapat menyelesaikannya dalam 8 jam. Jika mereka bekerja bersama, waktu yang diperlukan adalah ...",
    choices: [
      { id: "a", label: "3 jam 32 menit", score: 0 },
      { id: "b", label: "3 jam 40 menit", score: 0 },
      { id: "c", label: "3 jam 44 menit", score: 5 },
      { id: "d", label: "3 jam 48 menit", score: 0 },
      { id: "e", label: "4 jam 12 menit", score: 0 },
    ],
    explanation: "Pembahasan: Laju gabungan Adi dan Budi = 1/7 + 1/8 = 15/56 pekerjaan/jam. Waktu yang diperlukan = 56/15 jam = 3 11/15 jam = 3 jam + (11/15 x 60 menit) = 3 jam 44 menit. Jawaban C.",
  },
  {
    id: "mini-tiu8-27",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Sebuah dana dibagi untuk kegiatan A, B, dan C dengan perbandingan 3:4:10. Jika jumlah dana A dan B adalah Rp56 juta, dana untuk kegiatan C adalah ...",
    choices: [
      { id: "a", label: "Rp64 juta", score: 0 },
      { id: "b", label: "Rp72 juta", score: 0 },
      { id: "c", label: "Rp80 juta", score: 5 },
      { id: "d", label: "Rp88 juta", score: 0 },
      { id: "e", label: "Rp96 juta", score: 0 },
    ],
    explanation: "Pembahasan: Perbandingan A : B : C = 3 : 4 : 10. Jumlah bagian A dan B = 3 + 4 = 7 bagian = Rp56 juta. Maka 1 bagian = Rp8 juta. Dana untuk kegiatan C = 10 x Rp8 juta = Rp80 juta. Jawaban C.",
  },
  {
    id: "mini-tiu8-28",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Rina menabung Rp7.500.000 dengan bunga tunggal 8% per tahun. Jika tabungan disimpan selama 1 tahun 6 bulan tanpa biaya administrasi, jumlah tabungan Rina menjadi ...",
    choices: [
      { id: "a", label: "Rp8.100.000", score: 0 },
      { id: "b", label: "Rp8.250.000", score: 0 },
      { id: "c", label: "Rp8.400.000", score: 5 },
      { id: "d", label: "Rp8.550.000", score: 0 },
      { id: "e", label: "Rp8.700.000", score: 0 },
    ],
    explanation: "Pembahasan: Durasi tabungan = 1,5 tahun. Bunga tunggal = Rp7.500.000 x 8% x 1,5 = Rp900.000. Jumlah akhir tabungan = Rp7.500.000 + Rp900.000 = Rp8.400.000. Jawaban C.",
  },
  {
    id: "mini-tiu8-29",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Usia Andi saat ini tiga kali usia Beni. Selisih usia mereka lima tahun lalu adalah 12 tahun. Usia Andi saat ini adalah ...",
    choices: [
      { id: "a", label: "15 tahun", score: 0 },
      { id: "b", label: "16 tahun", score: 0 },
      { id: "c", label: "18 tahun", score: 5 },
      { id: "d", label: "20 tahun", score: 0 },
      { id: "e", label: "21 tahun", score: 0 },
    ],
    explanation: "Pembahasan: Selisih usia tidak berubah oleh waktu, sehingga saat ini selisih usia mereka tetap 12 tahun. Misalkan usia Beni saat ini = x, maka usia Andi = 3x. Selisih: 3x - x = 12 -> 2x = 12 -> x = 6. Jadi usia Andi saat ini = 3 x 6 = 18 tahun. Jawaban C.",
  },
  {
    id: "mini-tiu8-30",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Sebuah toko menjual 40% persediaan buku tulis pada pagi hari. Pada sore hari, toko tersebut menjual 25% dari sisa persediaan. Jika setelah itu masih tersisa 90 buku tulis, persediaan awalnya adalah ...",
    choices: [
      { id: "a", label: "160 buku", score: 0 },
      { id: "b", label: "180 buku", score: 0 },
      { id: "c", label: "200 buku", score: 5 },
      { id: "d", label: "220 buku", score: 0 },
      { id: "e", label: "240 buku", score: 0 },
    ],
    explanation: "Pembahasan: Setelah penjualan pagi, sisa persediaan = 60%. Penjualan sore menyisakan 75% dari sisa tersebut. Persediaan akhir = 60% x 75% = 45% dari persediaan awal. Karena 45% bernilai 90 buku, persediaan awal = 90 / 0,45 = 200 buku. Jawaban C.",
  },
  {
    id: "mini-tiu8-31",
    category: "TIU",
    topic: "Figural Analogi",
    prompt: "Pilihlah bentuk yang paling tepat untuk melengkapi analogi gambar berikut:\n\n![Analogi Gambar](/tryout/mini-tiu/soal-31.png)",
    choices: [
      { id: "a", label: "[img]/tryout/mini-tiu/soal-31-a.png", score: 0 },
      { id: "b", label: "[img]/tryout/mini-tiu/soal-31-b.png", score: 5 },
      { id: "c", label: "[img]/tryout/mini-tiu/soal-31-c.png", score: 0 },
      { id: "d", label: "[img]/tryout/mini-tiu/soal-31-d.png", score: 0 },
      { id: "e", label: "[img]/tryout/mini-tiu/soal-31-e.png", score: 0 },
    ],
    explanation:
      "Pembahasan: Analogi gambar mengikuti pola inversi (pembalikan warna) dan perubahan letak elemen:\n1. Hubungan Gambar 1 ke Gambar 2:\n• Bidang utama segi lima bersudut terpotong yang semula berwarna hitam pekat berubah menjadi putih (outline/garis tepi).\n• Elemen di dalam bidang (belah ketupat putih dan tanda plus putih) berpindah ke luar bidang dan mengalami inversi warna menjadi hitam pekat.\n\n2. Menerapkan pola yang sama untuk Gambar 3 ke Gambar 4:\n• Bidang utama elips yang semula berwarna putih (outline/garis tepi) harus berinversi menjadi berwarna hitam pekat (mengeliminasi pilihan A dan C).\n• Elemen di dalam elips (gambar hati hitam dan tanda silang hitam) harus berpindah ke luar elips serta berinversi menjadi berwarna putih dengan garis tepi hitam (outline).\n\nBentuk yang tepat dengan elips hitam pekat serta hati dan silang putih di luar elips adalah Opsi B. Jawaban B.",
  },
  {
    id: "mini-tiu8-32",
    category: "TIU",
    topic: "Figural Ketaksamaan",
    prompt: "Pilihlah salah satu gambar di bawah ini yang berbeda (tidak mengikuti pola) dari keempat gambar lainnya:",
    choices: [
      { id: "a", label: "[img]/tryout/mini-tiu/soal-32-a.png", score: 0 },
      { id: "b", label: "[img]/tryout/mini-tiu/soal-32-b.png", score: 0 },
      { id: "c", label: "[img]/tryout/mini-tiu/soal-32-c.png", score: 0 },
      { id: "d", label: "[img]/tryout/mini-tiu/soal-32-d.png", score: 0 },
      { id: "e", label: "[img]/tryout/mini-tiu/soal-32-e.png", score: 5 },
    ],
    explanation:
      "Pembahasan: Soal ini merupakan tipe figural ketaksamaan (mencari gambar yang berbeda sendiri atau bukan hasil rotasi objek yang sama):\n\nPerhatikan hubungan arah panah, posisi titik hitam, dan kemiringan garis arsir:\n1. Pada Gambar C: Panah menghadap ke atas, titik hitam terletak di sisi belakang-kiri panah (kiri-bawah), dan garis arsir miring dari kiri-bawah ke kanan-atas (/).\n2. Gambar A merupakan hasil rotasi Gambar C sebesar 90° searah jarum jam (panah ke kanan, titik di kiri-atas).\n3. Gambar D merupakan hasil rotasi Gambar C sebesar 180° (panah ke bawah, titik di kanan-atas).\n4. Gambar B merupakan hasil rotasi Gambar C sebesar 270° searah jarum jam (atau 90° berlawanan arah jarum jam) (panah ke kiri, titik di kanan-bawah).\n\nKeempat gambar (A, B, C, dan D) identik dan dapat saling dibentuk hanya dengan rotasi (perputaran bidang).\n\nSementara itu, pada Gambar E, arah panah menghadap ke atas tetapi titik hitam berada di kanan-bawah dan garis arsirnya miring terbalik (\\). Gambar E merupakan hasil pencerminan/refleksi (mirror image), bukan hasil rotasi, sehingga Gambar E berbeda sendiri dari kelompok gambar lainnya.\n\nJawaban E.",
  },
  {
    id: "mini-tiu8-33",
    category: "TIU",
    topic: "Serial Gambar",
    prompt:
      "Pilihlah gambar yang tepat untuk menggantikan tanda tanya (?) pada barisan gambar berikut:\n\n![Serial Gambar](/tryout/mini-tiu/soal-33.png)",
    choices: [
      { id: "a", label: "[img]/tryout/mini-tiu/soal-33-a.png", score: 0 },
      { id: "b", label: "[img]/tryout/mini-tiu/soal-33-b.png", score: 5 },
      { id: "c", label: "[img]/tryout/mini-tiu/soal-33-c.png", score: 0 },
      { id: "d", label: "[img]/tryout/mini-tiu/soal-33-d.png", score: 0 },
      { id: "e", label: "[img]/tryout/mini-tiu/soal-33-e.png", score: 0 },
    ],
    explanation:
      "Pembahasan: Pola barisan serial gambar ini adalah rotasi bangun sebesar 45° searah jarum jam secara konsisten pada setiap langkah:\n\n1. Amati arah mata panah lengkung:\n• Kotak 1: Mata panah menghadap ke bawah/kiri-bawah (arah pukul 7-8).\n• Kotak 2 (?): Diputar 45° searah jarum jam sehingga mata panah menghadap ke kiri mendatar (arah pukul 9).\n• Kotak 3: Diputar 45° searah jarum jam sehingga mata panah menghadap ke atas-kiri (arah pukul 10-11).\n• Kotak 4: Diputar 45° searah jarum jam sehingga mata panah menghadap ke atas-kanan (arah pukul 12-1).\n• Kotak 5: Diputar 45° searah jarum jam sehingga mata panah menghadap ke kanan mendatar (arah pukul 2-3).\n\n2. Amati orientasi juring lingkaran hitam:\n• Kotak 1 memiliki batas garis lurus tegak di bagian atas dan mendatar di kanan.\n• Kotak 2 (?) harus mengalami rotasi 45° searah jarum jam, sehingga bidang juring bergeser ke kanan-bawah dengan batas miring 45°.\n\nGambar yang tepat untuk mengisi posisi tanda tanya pada Kotak 2 adalah Opsi B. Jawaban B.",
  },
  {
    id: "mini-tiu8-34",
    category: "TIU",
    topic: "Figural Matriks 9 Kotak",
    prompt:
      "Pilihlah gambar yang tepat untuk menggantikan tanda tanya (?) pada matriks 3×3 berikut:\n\n![Matriks Figural 3x3](/tryout/mini-tiu/soal-34.png)",
    choices: [
      { id: "a", label: "[img]/tryout/mini-tiu/soal-34-a.png", score: 0 },
      { id: "b", label: "[img]/tryout/mini-tiu/soal-34-b.png", score: 0 },
      { id: "c", label: "[img]/tryout/mini-tiu/soal-34-c.png", score: 5 },
      { id: "d", label: "[img]/tryout/mini-tiu/soal-34-d.png", score: 0 },
      { id: "e", label: "[img]/tryout/mini-tiu/soal-34-e.png", score: 0 },
    ],
    explanation:
      "Pembahasan: Analisis pola baris pada matriks 3×3 menunjukkan aturan pergantian elemen dan inversi warna berikut:\n\n1. Pola Hubungan Antarkolom (Per Baris):\n• Kolom 1 memuat elemen pertama (A) yang berwarna hitam pekat (solid black).\n• Kolom 2 memuat elemen A yang berubah warna menjadi putih (outline), ditambah kemunculan elemen baru (B) yang berwarna hitam pekat.\n• Kolom 3 memuat elemen A yang dihilangkan sepenuhnya, sedangkan elemen baru (B) berubah warna (berinversi) menjadi putih (outline).\n\n2. Pembuktian pada Baris 1 & Baris 3:\n• Baris 1: Panah kanan hitam (Kolom 1) -> Panah kanan putih + panah kiri hitam (Kolom 2) -> Panah kiri putih (Kolom 3).\n• Baris 3: Kepiting hitam (Kolom 1) -> Kepiting putih + garpu/pisau silang hitam (Kolom 2) -> Garpu/pisau silang putih (Kolom 3).\n\n3. Penerapan pada Baris 2:\n• Kolom 1 memuat tangan bertepuk hitam.\n• Kolom 2 memuat tangan bertepuk putih + dua topeng teater (senyum dan sedih) berwarna hitam pekat.\n• Kolom 3 (?) harus menghilangkan tangan bertepuk, dan kedua topeng teater harus berubah (berinversi) warna menjadi putih (garis tepi/outline).\n\nGambar yang menampilkan kedua topeng teater (senyum dan sedih) berwarna putih (outline) adalah Opsi C. Jawaban C.",
  },
  {
    id: "mini-tiu8-35",
    category: "TIU",
    topic: "Figural Matriks 9 Kotak",
    prompt:
      "Pilihlah huruf yang paling tepat untuk menggantikan tanda tanya (?) pada pola matriks berikut:\n\n![Pola Matriks Huruf](/tryout/mini-tiu/soal-35.png)",
    choices: [
      { id: "a", label: "[img]/tryout/mini-tiu/soal-35-a.png", score: 5 },
      { id: "b", label: "[img]/tryout/mini-tiu/soal-35-b.png", score: 0 },
      { id: "c", label: "[img]/tryout/mini-tiu/soal-35-c.png", score: 0 },
      { id: "d", label: "[img]/tryout/mini-tiu/soal-35-d.png", score: 0 },
      { id: "e", label: "[img]/tryout/mini-tiu/soal-35-e.png", score: 0 },
    ],
    explanation:
      "Pembahasan: Pola pembentukan huruf pada matriks ditentukan oleh jumlah ruas garis lurus (garis penyusun huruf) pada setiap baris:\n\n1. Baris 1:\n• Huruf L tersusun dari 2 ruas garis lurus (1 tegak, 1 mendatar).\n• Huruf N tersusun dari 3 ruas garis lurus (2 tegak, 1 miring).\n• Huruf W tersusun dari 4 ruas garis lurus (4 garis miring).\n-> Pola jumlah garis: 2, 3, 4.\n\n2. Baris 2:\n• Huruf T tersusun dari 2 ruas garis lurus (1 mendatar, 1 tegak).\n• Huruf H tersusun dari 3 ruas garis lurus (2 tegak, 1 mendatar).\n• Huruf E tersusun dari 4 ruas garis lurus (1 tegak, 3 mendatar).\n-> Pola jumlah garis: 2, 3, 4.\n\n3. Baris 3:\n• Huruf X tersusun dari 2 ruas garis lurus (2 garis miring bersilangan).\n• Huruf F tersusun dari 3 ruas garis lurus (1 tegak, 2 mendatar).\n• Tanda tanya (?) harus diisi oleh huruf yang tersusun dari 4 ruas garis lurus.\n\nAnalisis pilihan jawaban berdasarkan jumlah ruas garis:\n• A. M : tersusun dari 4 ruas garis lurus (2 tegak, 2 miring) -> BENAR (4 garis).\n• B. K : tersusun dari 3 ruas garis lurus (1 tegak, 2 miring) -> Salah.\n• C. A : tersusun dari 3 ruas garis lurus (2 miring, 1 mendatar) -> Salah.\n• D. I : tersusun dari 1 ruas garis lurus (1 tegak) -> Salah.\n• E. Z : tersusun dari 3 ruas garis lurus (2 mendatar, 1 miring) -> Salah.\n\nHuruf yang memenuhi pola 4 ruas garis lurus adalah M (Pilihan A).\n\nJawaban A.",
  },
];

