import type { Question } from "./types";

export const MINI_TIU_4_QUESTIONS: Question[] = [
  {
    id: "mini-tiu4-01",
    category: "TIU",
    topic: "Analogi Kata",
    prompt: "IMUNISASI : ANTIBODI = ... : ...",
    choices: [
      { id: "a", label: "Vaksinasi : Penyakit", score: 0 },
      { id: "b", label: "Stimulus : Respons", score: 0 },
      { id: "c", label: "Latihan : Keterampilan", score: 5 },
      { id: "d", label: "Obat : Pasien", score: 0 },
      { id: "e", label: "Belajar : Ujian", score: 0 },
    ],
    explanation: "Hubungan kausal fungsional terencana: Proses imunisasi dilakukan secara sistematis untuk membentuk ketahanan berupa antibodi, sebagaimana proses latihan dilakukan secara terencana untuk membentuk kapasitas berupa keterampilan.",
  },
  {
    id: "mini-tiu4-02",
    category: "TIU",
    topic: "Analogi Kata",
    prompt: "INFLASI : DAYA BELI = HIPOTERMIA : ...",
    choices: [
      { id: "a", label: "Suhu Tubuh", score: 0 },
      { id: "b", label: "Kesadaran", score: 5 },
      { id: "c", label: "Metabolisme", score: 0 },
      { id: "d", label: "Denyut Nadi", score: 0 },
      { id: "e", label: "Pembuluh Darah", score: 0 },
    ],
    explanation: "Hubungan anomali sistemik yang menurunkan fungsi vital: Lonjakan inflasi yang tidak terkendali melumpuhkan daya beli, sebagaimana kondisi hipotermia akut melumpuhkan tingkat kesadaran.",
  },
  {
    id: "mini-tiu4-03",
    category: "TIU",
    topic: "Analogi Kata",
    prompt: "DIREKTORAT : KEMENTERIAN = FAKULTAS : ...",
    choices: [
      { id: "a", label: "Dekanat", score: 0 },
      { id: "b", label: "Jurusan", score: 0 },
      { id: "c", label: "Rektorat", score: 0 },
      { id: "d", label: "Universitas", score: 5 },
      { id: "e", label: "Sivitas", score: 0 },
    ],
    explanation: "Relasi hierarkis struktural: Direktorat merupakan unit eselon pelaksana teknis di bawah naungan kementerian, sedangkan fakultas merupakan unit pelaksana akademik di bawah naungan universitas.",
  },
  {
    id: "mini-tiu4-04",
    category: "TIU",
    topic: "Analogi Kata",
    prompt: "... : REGULASI = KENDARAAN : ...",
    choices: [
      { id: "a", label: "Hukum – Mobil", score: 0 },
      { id: "b", label: "Organisasi – Kemudi", score: 5 },
      { id: "c", label: "Kebijakan – Rem", score: 0 },
      { id: "d", label: "Birokrasi – Bahan Bakar", score: 0 },
      { id: "e", label: "Pelanggaran – Kecelakaan", score: 0 },
    ],
    explanation: "Hubungan analogi ganda instrumen pengendali: Jalannya sebuah organisasi diarahkan dan dikendalikan oleh instrumen regulasi, sebagaimana pergerakan kendaraan diarahkan jalannya oleh kemudi.",
  },
  {
    id: "mini-tiu4-05",
    category: "TIU",
    topic: "Silogisme",
    prompt: "Semua analis data yang tersertifikasi mampu mengoperasikan bahasa pemrograman Python. Tidak ada tenaga administrasi umum yang mampu mengoperasikan bahasa pemrograman Python. Sebagian staf bagian kepegawaian adalah analis data yang tersertifikasi.\n\nSimpulan yang paling tepat adalah ...",
    choices: [
      { id: "a", label: "Semua staf bagian kepegawaian bukan tenaga administrasi umum.", score: 0 },
      { id: "b", label: "Sebagian staf bagian kepegawaian bukan tenaga administrasi umum.", score: 5 },
      { id: "c", label: "Semua orang yang mampu mengoperasikan bahasa pemrograman Python adalah staf bagian kepegawaian.", score: 0 },
      { id: "d", label: "Sebagian tenaga administrasi umum adalah analis data yang tersertifikasi.", score: 0 },
      { id: "e", label: "Tidak ada staf bagian kepegawaian yang merupakan analis data yang tersertifikasi.", score: 0 },
    ],
    explanation: "Premis 1: Analis Tersertifikasi (A) → Mampu Python (P).\nPremis 2: Tenaga Administrasi Umum (T) → Tidak Mampu Python (~P). Kontraposisi: P → ~T. Maka A → ~T (Tidak ada analis tersertifikasi yang merupakan tenaga administrasi umum).\nPremis 3: Sebagian staf kepegawaian (K) adalah analis tersertifikasi (A).\nSimpulan: Sebagian staf bagian kepegawaian (K) bukan tenaga administrasi umum (~T).",
  },
  {
    id: "mini-tiu4-06",
    category: "TIU",
    topic: "Silogisme",
    prompt: "Jika seorang penyidik ingin memimpin operasi khusus, ia harus memiliki sertifikasi investigasi madya dan integritas tanpa catatan pelanggaran. Jika penyidik memiliki integritas tanpa catatan pelanggaran, maka ia diprioritaskan mendapat promosi kenaikan pangkat. Hendra adalah penyidik yang memimpin operasi khusus.\n\nSimpulan yang sah adalah ...",
    choices: [
      { id: "a", label: "Hendra belum tentu memiliki sertifikasi investigasi madya.", score: 0 },
      { id: "b", label: "Hendra memiliki sertifikasi investigasi madya dan diprioritaskan mendapat promosi kenaikan pangkat.", score: 5 },
      { id: "c", label: "Hendra diprioritaskan mendapat promosi kenaikan pangkat meskipun tidak memiliki sertifikasi investigasi madya.", score: 0 },
      { id: "d", label: "Semua penyidik yang memiliki sertifikasi investigasi madya pasti memimpin operasi khusus.", score: 0 },
      { id: "e", label: "Hendra tidak memimpin operasi khusus jika tidak diprioritaskan mendapat promosi kenaikan pangkat.", score: 0 },
    ],
    explanation: "Premis 1: Pimpin Operasi Khusus (M) → Sertifikasi Madya (S) ∧ Integritas Tanpa Catatan (I).\nPremis 2: Integritas Tanpa Catatan (I) → Prioritas Promosi (P).\nFakta: Hendra memimpin operasi khusus (M).\nDari Premis 1: Hendra memiliki S dan I.\nKarena Hendra memiliki I, dari Premis 2 diperoleh Hendra mendapat prioritas promosi (P).\nSimpulan sah: Hendra memiliki sertifikasi investigasi madya (S) dan diprioritaskan mendapat promosi kenaikan pangkat (P).",
  },
  {
    id: "mini-tiu4-07",
    category: "TIU",
    topic: "Silogisme",
    prompt: "Tidak ada arsip rahasia negara yang boleh dipublikasikan ke media sosial. Sebagian dokumen perencanaan pemindahan instansi merupakan arsip rahasia negara. Semua dokumen yang diunggah staf humas dipublikasikan ke media sosial.\n\nSimpulan yang benar adalah ...",
    choices: [
      { id: "a", label: "Semua dokumen perencanaan pemindahan instansi diunggah oleh staf humas.", score: 0 },
      { id: "b", label: "Sebagian dokumen perencanaan pemindahan instansi tidak diunggah oleh staf humas.", score: 5 },
      { id: "c", label: "Staf humas tidak pernah mengunggah dokumen arsip rahasia negara kecuali diizinkan pimpinan.", score: 0 },
      { id: "d", label: "Sebagian arsip rahasia negara boleh diunggah jika staf humas memverifikasinya.", score: 0 },
      { id: "e", label: "Semua dokumen yang tidak diunggah staf humas adalah arsip rahasia negara.", score: 0 },
    ],
    explanation: "Arsip rahasia negara → Tidak diunggah ke medsos (~M).\nSebagian dokumen perencanaan (D) adalah arsip rahasia.\nSemua unggahan humas (H) → Medsos (M). Kontraposisi: ~M → ~H (Tidak diunggah humas).\nKarena sebagian dokumen perencanaan pemindahan instansi berstatus ~M, maka dokumen tersebut dipastikan ~H (tidak diunggah oleh staf humas).",
  },
  {
    id: "mini-tiu4-08",
    category: "TIU",
    topic: "Silogisme",
    prompt: "Setiap calon auditor wajib lulus uji sertifikasi forensik atau menyelesaikan magang investigasi khusus. Jika calon auditor menyelesaikan magang investigasi khusus, ia harus memiliki pengalaman audit minimal dua tahun. Restu adalah calon auditor yang belum memiliki pengalaman audit selama dua tahun.\n\nSimpulan yang sah adalah ...",
    choices: [
      { id: "a", label: "Restu tidak dapat diangkat menjadi auditor.", score: 0 },
      { id: "b", label: "Restu wajib lulus uji sertifikasi forensik.", score: 5 },
      { id: "c", label: "Restu telah menyelesaikan magang investigasi khusus melalui jalur penugasan lain.", score: 0 },
      { id: "d", label: "Restu harus menunggu dua tahun untuk lulus uji sertifikasi forensik.", score: 0 },
      { id: "e", label: "Restu dibebaskan dari kewajiban sertifikasi forensik.", score: 0 },
    ],
    explanation: "Disjungsi: Wajib Uji Forensik (F) ∨ Magang Investigasi (M).\nImplikasi: M → Pengalaman ≥ 2 tahun (P).\nFakta: Restu belum 2 tahun (~P). Berdasarkan Modus Tollens: ~P → ~M.\nBerdasarkan silogisme disjungtif: (F ∨ M) ∧ ~M → F (Restu wajib lulus uji sertifikasi forensik).",
  },
  {
    id: "mini-tiu4-09",
    category: "TIU",
    topic: "Penalaran Analitis",
    prompt: "Delapan orang pegawai (Arya, Bagas, Citra, Dodi, Elsa, Fani, Gilang, dan Haris) menempati meja kerja yang berderet lurus dengan urutan nomor 1 hingga 8 dari kiri ke kanan:\n1. Citra duduk di meja nomor 4.\n2. Dodi duduk tepat di sebelah kiri Citra.\n3. Elsa duduk tepat di antara Bagas dan Haris (ketiganya menempati tiga meja yang berdampingan secara berurutan).\n4. Arya tidak boleh duduk di ujung barisan (bukan meja nomor 1 dan bukan meja nomor 8).\n5. Gilang duduk di sebelah kanan Fani.\n\nJika Bagas, Elsa, dan Haris menempati meja bernomor 5, 6, dan 7, maka pernyataan berikut yang PASTI BENAR adalah ...",
    choices: [
      { id: "a", label: "Bagas duduk di meja nomor 5.", score: 0 },
      { id: "b", label: "Gilang duduk di meja nomor 8.", score: 5 },
      { id: "c", label: "Fani duduk di meja nomor 2.", score: 0 },
      { id: "d", label: "Arya duduk tepat di sebelah Haris.", score: 0 },
      { id: "e", label: "Elsa duduk di meja nomor 7.", score: 0 },
    ],
    explanation: "Citra di nomor 4 (C = 4). Dodi tepat di kiri Citra, maka Dodi di nomor 3 (D = 3).\nJika Bagas, Elsa, dan Haris menempati meja nomor 5, 6, dan 7, maka meja nomor 8 kosong.\nMeja yang belum terisi adalah nomor 1, 2, dan 8 untuk tiga orang: Arya, Fani, dan Gilang.\nArya tidak boleh duduk di ujung (bukan nomor 1 dan bukan nomor 8), sehingga Arya wajib duduk di meja nomor 2.\nSisa meja 1 dan 8 untuk Fani dan Gilang. Karena Gilang duduk di sebelah kanan Fani, maka Fani harus di meja nomor 1 dan Gilang pasti duduk di meja nomor 8.",
  },
  {
    id: "mini-tiu4-10",
    category: "TIU",
    topic: "Penalaran Analitis",
    prompt: "Delapan orang pegawai (Arya, Bagas, Citra, Dodi, Elsa, Fani, Gilang, dan Haris) menempati meja kerja yang berderet lurus dengan urutan nomor 1 hingga 8 dari kiri ke kanan:\n1. Citra duduk di meja nomor 4.\n2. Dodi duduk tepat di sebelah kiri Citra.\n3. Elsa duduk tepat di antara Bagas dan Haris (ketiganya menempati tiga meja yang berdampingan secara berurutan).\n4. Arya tidak boleh duduk di ujung barisan (bukan meja nomor 1 dan bukan meja nomor 8).\n5. Gilang duduk di sebelah kanan Fani.\n\nJika Haris duduk di meja nomor 8 dan Gilang duduk di sebelah kanan Arya, maka pegawai yang duduk di meja nomor 2 adalah ...",
    choices: [
      { id: "a", label: "Fani", score: 0 },
      { id: "b", label: "Arya", score: 5 },
      { id: "c", label: "Gilang", score: 0 },
      { id: "d", label: "Bagas", score: 0 },
      { id: "e", label: "Dodi", score: 0 },
    ],
    explanation: "Jika Haris di nomor 8, maka paket tiga meja wajib menempati meja 6, 7, dan 8 dengan formasi: Bagas (6), Elsa (7), dan Haris (8).\nMeja yang tersisa adalah nomor 1, 2, dan 5 untuk Arya, Fani, dan Gilang.\nArya tidak boleh di meja nomor 1. Jika Arya di nomor 5, Gilang tidak mungkin berada di sebelah kanan Arya (karena meja 6, 7, 8 sudah terisi penuh).\nOleh karena itu, Arya wajib duduk di meja nomor 2, Gilang di meja nomor 5, dan Fani di meja nomor 1.",
  },
  {
    id: "mini-tiu4-11",
    category: "TIU",
    topic: "Penalaran Analitis",
    prompt: "Lima orang peserta seleksi (K, L, M, N, dan O) dijadwalkan mengikuti sesi wawancara dari hari Senin hingga Jumat (satu orang per hari):\n1. M dijadwalkan sebelum O.\n2. K diwawancarai tepat satu hari setelah L.\n3. N tidak boleh diwawancarai pada hari Senin maupun Jumat.\n4. M diwawancarai pada hari Rabu.\n\nUrutan jadwal wawancara yang benar dari hari Senin sampai Jumat adalah ...",
    choices: [
      { id: "a", label: "L, K, M, N, O", score: 5 },
      { id: "b", label: "K, L, M, O, N", score: 0 },
      { id: "c", label: "L, M, K, N, O", score: 0 },
      { id: "d", label: "N, L, K, M, O", score: 0 },
      { id: "e", label: "L, K, M, O, N", score: 0 },
    ],
    explanation: "Urutan hari: Senin, Selasa, Rabu, Kamis, Jumat.\nRabu diisi M.\nSyarat M sebelum O mewajibkan O di hari Kamis atau Jumat.\nBlok L lalu K berurutan (LK) hanya dapat menempati Senin–Selasa.\nSisa hari Kamis dan Jumat untuk N dan O. Karena N tidak boleh di hari Jumat, maka N = Kamis dan O = Jumat.\nUrutan pasti: Senin (L), Selasa (K), Rabu (M), Kamis (N), Jumat (O).",
  },
  {
    id: "mini-tiu4-12",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Nilai dari $\\frac{87^2 - 13^2}{74 \\times 25} = \\dots$",
    choices: [
      { id: "a", label: "2", score: 0 },
      { id: "b", label: "4", score: 5 },
      { id: "c", label: "6", score: 0 },
      { id: "d", label: "8", score: 0 },
      { id: "e", label: "10", score: 0 },
    ],
    explanation: "Faktorisasi selisih kuadrat $a^2 - b^2 = (a - b)(a + b)$:\n$$87^2 - 13^2 = (87 - 13)(87 + 13) = 74 \\times 100$$\n$$\\frac{74 \\times 100}{74 \\times 25} = \\frac{100}{25} = 4$$",
  },
  {
    id: "mini-tiu4-13",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Nilai dari $62{,}5\\% \\times 512 + 0{,}375 \\times 256 - \\frac{5}{8} \\times 112 = \\dots$",
    choices: [
      { id: "a", label: "326", score: 0 },
      { id: "b", label: "336", score: 0 },
      { id: "c", label: "346", score: 5 },
      { id: "d", label: "356", score: 0 },
      { id: "e", label: "366", score: 0 },
    ],
    explanation: "Konversi pecahan istimewa: $62{,}5\\% = \\frac{5}{8}$ dan $0{,}375 = \\frac{3}{8}$.\nKombinasikan dengan sifat distributif:\n$$\\frac{5}{8}(512 - 112) + \\frac{3}{8}(256) = \\frac{5}{8}(400) + 3 \\times 32 = 250 + 96 = 346$$",
  },
  {
    id: "mini-tiu4-14",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Nilai dari $\\left(83\\frac{1}{3}\\% \\times 0{,}72\\right) + \\left(\\frac{5}{6} \\times 1{,}68\\right) - (37{,}5\\% \\times 1{,}6) = \\dots$",
    choices: [
      { id: "a", label: "1,2", score: 0 },
      { id: "b", label: "1,4", score: 5 },
      { id: "c", label: "1,6", score: 0 },
      { id: "d", label: "1,8", score: 0 },
      { id: "e", label: "2,2", score: 0 },
    ],
    explanation: "Ubah pecahan persen ke bentuk pecahan biasa: $83\\frac{1}{3}\\% = \\frac{5}{6}$ dan $37{,}5\\% = \\frac{3}{8}$.\nGunakan sifat distributif pada suku pertama dan kedua:\n$$\\frac{5}{6} \\times 0{,}72 + \\frac{5}{6} \\times 1{,}68 = \\frac{5}{6}(0{,}72 + 1{,}68) = \\frac{5}{6}(2{,}40) = 5 \\times 0{,}40 = 2{,}0$$\nHitung suku ketiga: $\\frac{3}{8} \\times 1{,}6 = 3 \\times 0{,}2 = 0{,}6$.\nHasil akhir: $2{,}0 - 0{,}6 = 1{,}4$.",
  },
  {
    id: "mini-tiu4-15",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Nilai dari $\\frac{0{,}875 \\times 44\\% + 0{,}875 \\times 36\\%}{\\frac{7}{10} \\times 0{,}25} = \\dots$",
    choices: [
      { id: "a", label: "2", score: 0 },
      { id: "b", label: "3", score: 0 },
      { id: "c", label: "4", score: 5 },
      { id: "d", label: "5", score: 0 },
      { id: "e", label: "8", score: 0 },
    ],
    explanation: "Pembilang: Faktorkan $0{,}875$ keluar:\n$$0{,}875 \\times (44\\% + 36\\%) = 0{,}875 \\times 80\\% = \\frac{7}{8} \\times \\frac{4}{5} = \\frac{7}{10}$$\nPenyebut: $\\frac{7}{10} \\times 0{,}25 = \\frac{7}{10} \\times \\frac{1}{4}$.\nSederhanakan pecahan bertingkat dengan langsung mencoret faktor $\\frac{7}{10}$:\n$$\\frac{\\frac{7}{10}}{\\frac{7}{10} \\times \\frac{1}{4}} = \\frac{1}{\\frac{1}{4}} = 4$$",
  },
  {
    id: "mini-tiu4-16",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "$4, 7, 8, 14, 16, 28, 32, 56, \\dots, \\dots$",
    choices: [
      { id: "a", label: "48, 84", score: 0 },
      { id: "b", label: "64, 84", score: 0 },
      { id: "c", label: "64, 112", score: 5 },
      { id: "d", label: "48, 112", score: 0 },
      { id: "e", label: "64, 128", score: 0 },
    ],
    explanation: "Larik selang-seling dua tingkat:\n- Posisi ganjil: $4, 8, 16, 32, \\dots$ (dikali 2) → suku berikutnya $= 64$.\n- Posisi genap: $7, 14, 28, 56, \\dots$ (dikali 2) → suku berikutnya $= 112$.",
  },
  {
    id: "mini-tiu4-17",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "$3, 5, 20, 6, 10, 17, 12, 20, 14, \\dots, \\dots$",
    choices: [
      { id: "a", label: "24, 40", score: 5 },
      { id: "b", label: "24, 11", score: 0 },
      { id: "c", label: "18, 40", score: 0 },
      { id: "d", label: "18, 25", score: 0 },
      { id: "e", label: "24, 35", score: 0 },
    ],
    explanation: "Larik melompat tiga urutan:\n- Larik 1 (suku 1, 4, 7, 10): $3, 6, 12, \\dots \\implies 24$ (dikali 2).\n- Larik 2 (suku 2, 5, 8, 11): $5, 10, 20, \\dots \\implies 40$ (dikali 2).\n- Larik 3 (suku 3, 6, 9): $20, 17, 14$ (dikurang 3).\nMaka dua suku berikutnya adalah 24 dan 40.",
  },
  {
    id: "mini-tiu4-18",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "$5, 8, 14, 23, 35, 50, \\dots, \\dots$",
    choices: [
      { id: "a", label: "65, 83", score: 0 },
      { id: "b", label: "68, 89", score: 5 },
      { id: "c", label: "68, 88", score: 0 },
      { id: "d", label: "70, 92", score: 0 },
      { id: "e", label: "72, 95", score: 0 },
    ],
    explanation: "Pola bertingkat dua dengan beda kelipatan 3:\n- Tingkat 1: $+3, +6, +9, +12, +15, \\dots$\n- Suku selanjutnya: $50 + 18 = 68$, lalu $68 + 21 = 89$.",
  },
  {
    id: "mini-tiu4-19",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "$2, 6, 4, 12, 10, 30, 28, 84, \\dots, \\dots$",
    choices: [
      { id: "a", label: "82, 246", score: 5 },
      { id: "b", label: "82, 164", score: 0 },
      { id: "c", label: "86, 258", score: 0 },
      { id: "d", label: "80, 240", score: 0 },
      { id: "e", label: "82, 250", score: 0 },
    ],
    explanation: "Operasi bergantian teratur: $\\times 3$, kemudian $-2$:\n$$28 \\times 3 = 84 \\implies 84 - 2 = 82 \\implies 82 \\times 3 = 246$$",
  },
  {
    id: "mini-tiu4-20",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Jika $-3 \\le a \\le 2$ dan $1 \\le b \\le 4$, dengan $x = a^2 - b$ serta $y = 3$, maka hubungan yang tepat adalah ...",
    choices: [
      { id: "a", label: "x > y", score: 0 },
      { id: "b", label: "x < y", score: 0 },
      { id: "c", label: "x = y", score: 0 },
      { id: "d", label: "2x = 3y", score: 0 },
      { id: "e", label: "Hubungan x dan y tidak dapat ditentukan", score: 5 },
    ],
    explanation: "Jika $-3 \\le a \\le 2$, nilai $a^2$ memiliki nilai minimum 0 (saat $a=0$) dan maksimum 9 (saat $a=-3$), sehingga $0 \\le a^2 \\le 9$.\nJika $1 \\le b \\le 4$, maka $-4 \\le -b \\le -1$.\nNilai $x = a^2 - b$ berada pada rentang $[0 - 4, 9 - 1] = [-4, 8]$.\nKarena nilai $x$ bisa kurang dari 3, sama dengan 3, maupun lebih dari 3, hubungan $x$ dan $y$ tidak dapat ditentukan.",
  },
  {
    id: "mini-tiu4-21",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Diketahui $x = \\frac{7}{12} - \\frac{1}{4} + 0{,}5$ dan $y = \\left(0{,}75 \\times \\frac{8}{9}\\right) + 0{,}15$.\n\nHubungan antara $x$ dan $y$ adalah ...",
    choices: [
      { id: "a", label: "x > y", score: 5 },
      { id: "b", label: "x < y", score: 0 },
      { id: "c", label: "x = y", score: 0 },
      { id: "d", label: "x = 2y", score: 0 },
      { id: "e", label: "Hubungan x dan y tidak dapat ditentukan", score: 0 },
    ],
    explanation: "Hitung $x$: $\\frac{7}{12} - \\frac{3}{12} + \\frac{6}{12} = \\frac{10}{12} = \\frac{5}{6} = \\frac{50}{60}$.\nHitung $y$: $(\\frac{3}{4} \\times \\frac{8}{9}) + \\frac{15}{100} = \\frac{2}{3} + \\frac{3}{20} = \\frac{40}{60} + \\frac{9}{60} = \\frac{49}{60}$.\nBandingkan pembilang: $\\frac{50}{60} > \\frac{49}{60}$, sehingga $x > y$.",
  },
  {
    id: "mini-tiu4-22",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Diketahui $x$ adalah $35\\%$ dari 480, sedangkan $y$ adalah $48\\%$ dari 350.\n\nHubungan antara $x$ dan $y$ adalah ...",
    choices: [
      { id: "a", label: "x > y", score: 0 },
      { id: "b", label: "x < y", score: 0 },
      { id: "c", label: "x = y", score: 5 },
      { id: "d", label: "x = 2y", score: 0 },
      { id: "e", label: "Hubungan x dan y tidak dapat ditentukan", score: 0 },
    ],
    explanation: "Sifat komutatif persentase ($a\\% \\times b = b\\% \\times a$):\n$$x = 35\\% \\times 480 = \\frac{35 \\times 480}{100} = 168$$\n$$y = 48\\% \\times 350 = \\frac{48 \\times 350}{100} = \\frac{480 \\times 35}{100} = 168$$\nTerbukti mutlak $x = y$.",
  },
  {
    id: "mini-tiu4-23",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Diketahui $x = \\frac{0{,}45 + 0{,}15}{1{,}6 \\times 0{,}75}$ dan $y = \\frac{2}{5} + \\left(0{,}35 \\div \\frac{7}{4}\\right)$.\n\nHubungan antara $x$ dan $y$ adalah ...",
    choices: [
      { id: "a", label: "x > y", score: 0 },
      { id: "b", label: "x < y", score: 5 },
      { id: "c", label: "x = y", score: 0 },
      { id: "d", label: "2x = 3y", score: 0 },
      { id: "e", label: "Hubungan x dan y tidak dapat ditentukan", score: 0 },
    ],
    explanation: "Hitung $x$: $$x = \\frac{0{,}60}{1{,}6 \\times \\frac{3}{4}} = \\frac{0{,}60}{1{,}20} = 0{,}50$$\nHitung $y$: $$y = 0{,}40 + \\left(\\frac{35}{100} \\times \\frac{4}{7}\\right) = 0{,}40 + \\frac{5 \\times 4}{100} = 0{,}40 + 0{,}20 = 0{,}60$$\nKarena $0{,}50 < 0{,}60$, maka disimpulkan $x < y$.",
  },
  {
    id: "mini-tiu4-24",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Notasi faktorial didefinisikan sebagai perkalian bilangan bulat positif berurutan: $n! = n \\times (n - 1) \\times (n - 2) \\times \\dots \\times 1$ untuk setiap bilangan bulat $n \\ge 1$, dengan $0! = 1$.\n\nJika $x = \\frac{6! \\times 4!}{5! \\times 3!}$ dan $y = 2^4 + 3^2 - 1$, maka hubungan antara $x$ dan $y$ adalah ...",
    choices: [
      { id: "a", label: "x > y", score: 0 },
      { id: "b", label: "x < y", score: 0 },
      { id: "c", label: "x = y", score: 5 },
      { id: "d", label: "x = y - 2", score: 0 },
      { id: "e", label: "Hubungan x dan y tidak dapat ditentukan", score: 0 },
    ],
    explanation: "Uraikan faktorial:\n$$x = \\frac{6!}{5!} \\times \\frac{4!}{3!} = 6 \\times 4 = 24$$\nHitung nilai $y$:\n$$y = 2^4 + 3^2 - 1 = 16 + 9 - 1 = 24$$\nTerbukti $x = y$.",
  },
  {
    id: "mini-tiu4-25",
    category: "TIU",
    topic: "Soal Cerita",
    prompt: "Arga mengendarai kendaraan dinas dari Kota P menuju Kota Q dengan kecepatan rata-rata 60 km/jam pada pukul 07.30 WIB. Tiga puluh menit kemudian, Bima berangkat menyusul dari titik yang sama melalui jalur yang sama dengan kecepatan rata-rata 80 km/jam. Pada pukul berapakah Bima akan tepat menyusul Arga?",
    choices: [
      { id: "a", label: "09.00 WIB", score: 0 },
      { id: "b", label: "09.15 WIB", score: 0 },
      { id: "c", label: "09.30 WIB", score: 5 },
      { id: "d", label: "09.45 WIB", score: 0 },
      { id: "e", label: "10.00 WIB", score: 0 },
    ],
    explanation: "Selisih waktu $= 30\\text{ menit} = 0{,}5\\text{ jam}$.\nSelisih jarak $= 60 \\times 0{,}5 = 30\\text{ km}$.\nWaktu susul:\n$$t = \\frac{\\Delta s}{v_2 - v_1} = \\frac{30}{80 - 60} = 1{,}5\\text{ jam} = 1\\text{ jam } 30\\text{ menit}$$\nWaktu menyusul $= 08.00 + 1.30 = 09.30\\text{ WIB}$.",
  },
  {
    id: "mini-tiu4-26",
    category: "TIU",
    topic: "Soal Cerita",
    prompt: "Jarak antara Kota A dan Kota B adalah 290 km. Mobil X berangkat dari Kota A menuju Kota B pada pukul 08.15 dengan kecepatan rata-rata 60 km/jam. Tepat pada pukul 08.45, Mobil Y berangkat dari Kota B menuju Kota A melalui rute yang sama dengan kecepatan rata-rata 70 km/jam. Pada jarak berapa kilometer dari Kota A kedua mobil tersebut akan berpapasan?",
    choices: [
      { id: "a", label: "120 km", score: 0 },
      { id: "b", label: "130 km", score: 0 },
      { id: "c", label: "140 km", score: 0 },
      { id: "d", label: "150 km", score: 5 },
      { id: "e", label: "160 km", score: 0 },
    ],
    explanation: "Jarak tempuh Mobil X selama 30 menit awal $= 60 \\times 0{,}5 = 30\\text{ km}$.\nSisa jarak per pukul 08.45 $= 290 - 30 = 260\\text{ km}$.\nWaktu berpapasan sejak 08.45:\n$$t = \\frac{260}{60 + 70} = \\frac{260}{130} = 2\\text{ jam}$$\nJarak temu dari Kota A $= 30\\text{ km} + (60 \\times 2) = 150\\text{ km}$.",
  },
  {
    id: "mini-tiu4-27",
    category: "TIU",
    topic: "Soal Cerita",
    prompt: "Sebuah pekerjaan instalasi jaringan dapat diselesaikan oleh 5 orang teknisi ahli dalam waktu 12 hari, atau oleh 6 orang asisten teknisi dalam waktu 20 hari. Jika pekerjaan tersebut dikerjakan secara bersama-sama oleh 3 orang teknisi ahli dan 4 orang asisten teknisi sejak awal, dalam berapa harikah instalasi tersebut akan selesai seluruhnya?",
    choices: [
      { id: "a", label: "8 hari", score: 0 },
      { id: "b", label: "10 hari", score: 0 },
      { id: "c", label: "12 hari", score: 5 },
      { id: "d", label: "14 hari", score: 0 },
      { id: "e", label: "15 hari", score: 0 },
    ],
    explanation: "Kapasitas per orang per hari:\n- 1 Teknisi Ahli $= \\frac{1}{5 \\times 12} = \\frac{1}{60}\\text{ bagian/hari}$.\n- 1 Asisten Teknisi $= \\frac{1}{6 \\times 20} = \\frac{1}{120}\\text{ bagian/hari}$.\n\nLaju kerja gabungan (3 teknisi ahli + 4 asisten):\n$$\\text{Laju} = 3\\left(\\frac{1}{60}\\right) + 4\\left(\\frac{1}{120}\\right) = \\frac{6}{120} + \\frac{4}{120} = \\frac{10}{120} = \\frac{1}{12}\\text{ bagian/hari}$$\nWaktu yang dibutuhkan $= \\frac{1}{1/12} = 12\\text{ hari}$.",
  },
  {
    id: "mini-tiu4-28",
    category: "TIU",
    topic: "Soal Cerita",
    prompt: "Fajar dapat menyelesaikan penataan dokumen secara mandiri dalam waktu 6 hari, Gina dalam 10 hari, dan Hadi dalam 15 hari. Awalnya, Fajar dan Gina bekerja sama selama 2 hari, kemudian Gina berhenti dan digantikan oleh Hadi hingga seluruh pekerjaan selesai. Total waktu yang diperlukan untuk menyelesaikan seluruh pekerjaan tersebut adalah ...",
    choices: [
      { id: "a", label: "3 hari", score: 0 },
      { id: "b", label: "4 hari", score: 5 },
      { id: "c", label: "5 hari", score: 0 },
      { id: "d", label: "6 hari", score: 0 },
      { id: "e", label: "7 hari", score: 0 },
    ],
    explanation: "Laju per hari: Fajar $= \\frac{1}{6}$, Gina $= \\frac{1}{10}$, Hadi $= \\frac{1}{15}$.\nDua hari awal oleh Fajar dan Gina: $2 \\times \\left(\\frac{1}{6} + \\frac{1}{10}\\right) = 2 \\times \\frac{8}{30} = \\frac{8}{15}\\text{ bagian}$.\nSisa pekerjaan $= 1 - \\frac{8}{15} = \\frac{7}{15}\\text{ bagian}$.\nLaju Fajar dan Hadi $= \\frac{1}{6} + \\frac{1}{15} = \\frac{7}{30}\\text{ bagian/hari}$.\nWaktu sisa $= \\frac{7/15}{7/30} = 2\\text{ hari}$.\nTotal waktu yang dihabiskan $= 2\\text{ hari} + 2\\text{ hari} = 4\\text{ hari}$.",
  },
  {
    id: "mini-tiu4-29",
    category: "TIU",
    topic: "Soal Cerita",
    prompt: "Sebuah instansi membeli perlengkapan kantor yang memperoleh promo diskon bertingkat sebesar $20\\% + 15\\%$ (diskon $20\\%$ kemudian dikenakan potongan tambahan $15\\%$ dari harga setelah diskon pertama). Jika nominal akhir yang dibayarkan oleh bendahara setelah kedua diskon tersebut adalah Rp6.800.000,00, berapakah harga perlengkapan kantor sebelum diskon?",
    choices: [
      { id: "a", label: "Rp9.200.000,00", score: 0 },
      { id: "b", label: "Rp9.500.000,00", score: 0 },
      { id: "c", label: "Rp10.000.000,00", score: 5 },
      { id: "d", label: "Rp10.500.000,00", score: 0 },
      { id: "e", label: "Rp11.000.000,00", score: 0 },
    ],
    explanation: "Faktor pembayaran diskon bertingkat:\n$$(100\\% - 20\\%) \\times (100\\% - 15\\%) = 0{,}80 \\times 0{,}85 = 0{,}68$$\nHarga awal $= \\frac{\\text{Rp}6.800.000}{0{,}68} = \\text{Rp}10.000.000,00$.",
  },
  {
    id: "mini-tiu4-30",
    category: "TIU",
    topic: "Soal Cerita",
    prompt: "Dari 80 orang aparatur yang mengikuti pelatihan, 48 orang menguasai analisis data kuantitatif, 42 orang menguasai perancangan kebijakan publik, dan 14 orang tidak menguasai kedua keahlian tersebut. Jika seorang peserta dipilih secara acak, berapakah peluang terpilihnya aparatur yang HANYA menguasai salah satu bidang keahlian tersebut?",
    choices: [
      { id: "a", label: "9/40", score: 0 },
      { id: "b", label: "12/40", score: 0 },
      { id: "c", label: "21/40", score: 5 },
      { id: "d", label: "24/40", score: 0 },
      { id: "e", label: "33/40", score: 0 },
    ],
    explanation: "Total yang menguasai minimal satu bidang $= 80 - 14 = 66\\text{ orang}$.\nPeserta yang menguasai kedua bidang (irisan) $= (48 + 42) - 66 = 90 - 66 = 24\\text{ orang}$.\nPeserta yang HANYA menguasai salah satu bidang $= 66 - 24 = 42\\text{ orang}$.\nPeluang $= \\frac{42}{80} = \\frac{21}{40}$.",
  },
  {
    id: "mini-tiu4-31",
    category: "TIU",
    topic: "Kemampuan Figural",
    prompt: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 370 100\" style=\"width:100%;max-width:480px;display:block\"><rect x=\"2\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><polygon points=\"41,16 16,68 66,68\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><circle cx=\"41\" cy=\"30\" r=\"4.5\" fill=\"black\"/><polygon points=\"26,56 29,60 26,64 23,60\" fill=\"white\" stroke=\"black\" stroke-width=\"1\"/><polygon points=\"56,56 59,60 56,64 53,60\" fill=\"white\" stroke=\"black\" stroke-width=\"1\"/><text x=\"41\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(1)</text><text x=\"90\" y=\"48\" text-anchor=\"middle\" font-size=\"18\" font-family=\"serif\">=</text><rect x=\"98\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><polygon points=\"137,68 112,16 162,16\" fill=\"#d1d5db\" stroke=\"black\" stroke-width=\"1.5\"/><circle cx=\"137\" cy=\"54\" r=\"4.5\" fill=\"white\" stroke=\"black\" stroke-width=\"1\"/><polygon points=\"122,24 125,28 122,32 119,28\" fill=\"black\"/><polygon points=\"152,24 155,28 152,32 149,28\" fill=\"black\"/><text x=\"137\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(2)</text><text x=\"186\" y=\"48\" text-anchor=\"middle\" font-size=\"18\" font-family=\"serif\">=</text><rect x=\"194\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><rect x=\"210\" y=\"20\" width=\"46\" height=\"46\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><polygon points=\"221,25 226,30 221,35 216,30\" fill=\"black\"/><circle cx=\"245\" cy=\"30\" r=\"4.5\" fill=\"white\" stroke=\"black\" stroke-width=\"1\"/><circle cx=\"221\" cy=\"56\" r=\"4.5\" fill=\"white\" stroke=\"black\" stroke-width=\"1\"/><circle cx=\"245\" cy=\"56\" r=\"4.5\" fill=\"white\" stroke=\"black\" stroke-width=\"1\"/><text x=\"233\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(3)</text><rect x=\"290\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><text x=\"329\" y=\"52\" text-anchor=\"middle\" font-size=\"40\" font-family=\"sans-serif\" font-weight=\"bold\">?</text><text x=\"329\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(4)</text></svg>",
    choices: [
      {
        id: "a",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><rect x=\"20\" y=\"20\" width=\"48\" height=\"48\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><polygon points=\"32,26 37,32 32,38 27,32\" fill=\"black\"/><circle cx=\"56\" cy=\"32\" r=\"4.5\" fill=\"white\" stroke=\"black\" stroke-width=\"1\"/><circle cx=\"32\" cy=\"56\" r=\"4.5\" fill=\"white\" stroke=\"black\" stroke-width=\"1\"/><circle cx=\"56\" cy=\"56\" r=\"4.5\" fill=\"white\" stroke=\"black\" stroke-width=\"1\"/></svg>",
        score: 0,
      },
      {
        id: "b",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><rect x=\"20\" y=\"20\" width=\"48\" height=\"48\" fill=\"#d1d5db\" stroke=\"black\" stroke-width=\"1.5\"/><circle cx=\"32\" cy=\"32\" r=\"4.5\" fill=\"black\"/><circle cx=\"56\" cy=\"32\" r=\"4.5\" fill=\"black\"/><circle cx=\"32\" cy=\"56\" r=\"4.5\" fill=\"black\"/><polygon points=\"56,50 61,56 56,62 51,56\" fill=\"white\" stroke=\"black\" stroke-width=\"1\"/></svg>",
        score: 5,
      },
      {
        id: "c",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><rect x=\"20\" y=\"20\" width=\"48\" height=\"48\" fill=\"#d1d5db\" stroke=\"black\" stroke-width=\"1.5\"/><circle cx=\"32\" cy=\"32\" r=\"4.5\" fill=\"white\" stroke=\"black\" stroke-width=\"1\"/><circle cx=\"56\" cy=\"32\" r=\"4.5\" fill=\"white\" stroke=\"black\" stroke-width=\"1\"/><circle cx=\"32\" cy=\"56\" r=\"4.5\" fill=\"white\" stroke=\"black\" stroke-width=\"1\"/><polygon points=\"56,50 61,56 56,62 51,56\" fill=\"black\"/></svg>",
        score: 0,
      },
      {
        id: "d",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><rect x=\"20\" y=\"20\" width=\"48\" height=\"48\" fill=\"#1f2937\" stroke=\"black\" stroke-width=\"1.5\"/><polygon points=\"44,38 49,44 44,50 39,44\" fill=\"white\" stroke=\"black\" stroke-width=\"1\"/><circle cx=\"10\" cy=\"44\" r=\"4.5\" fill=\"black\"/><circle cx=\"78\" cy=\"44\" r=\"4.5\" fill=\"black\"/><circle cx=\"44\" cy=\"78\" r=\"4.5\" fill=\"black\"/></svg>",
        score: 0,
      },
      {
        id: "e",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><rect x=\"20\" y=\"20\" width=\"48\" height=\"48\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><polygon points=\"32,50 37,56 32,62 27,56\" fill=\"white\" stroke=\"black\" stroke-width=\"1\"/><circle cx=\"56\" cy=\"32\" r=\"4.5\" fill=\"black\"/><circle cx=\"32\" cy=\"32\" r=\"4.5\" fill=\"white\" stroke=\"black\" stroke-width=\"1\"/><circle cx=\"56\" cy=\"56\" r=\"4.5\" fill=\"white\" stroke=\"black\" stroke-width=\"1\"/></svg>",
        score: 0,
      },
    ],
    explanation: "Dekonstruksi Elemen Visual:\n- Bingkai: Berubah warna menjadi abu-abu.\n- Posisi: Mengalami inversi simetris $180^\\circ$ (kiri atas berpindah ke kanan bawah).\n- Warna elemen dalam: Mengalami pembalikan polaritas warna (hitam menjadi putih, putih menjadi hitam). Belah ketupat hitam di kiri atas berubah menjadi putih di sudut kanan bawah, dan tiga bulatan putih berubah menjadi hitam (Opsi B).",
  },
  {
    id: "mini-tiu4-32",
    category: "TIU",
    topic: "Kemampuan Figural",
    prompt: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 370 100\" style=\"width:100%;max-width:480px;display:block\"><rect x=\"2\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"41\" y1=\"46\" x2=\"41\" y2=\"20\" stroke=\"black\" stroke-width=\"2.5\"/><polygon points=\"41,14 36,22 46,22\" fill=\"black\"/><line x1=\"21\" y1=\"60\" x2=\"61\" y2=\"60\" stroke=\"black\" stroke-width=\"2\"/><line x1=\"21\" y1=\"68\" x2=\"61\" y2=\"68\" stroke=\"black\" stroke-width=\"2\"/><text x=\"41\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(1)</text><text x=\"90\" y=\"48\" text-anchor=\"middle\" font-size=\"18\" font-family=\"serif\">=</text><rect x=\"98\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"125\" y1=\"23\" x2=\"145\" y2=\"43\" stroke=\"black\" stroke-width=\"2.5\"/><polygon points=\"151,49 139,46 148,37\" fill=\"black\"/><line x1=\"125\" y1=\"56\" x2=\"125\" y2=\"74\" stroke=\"black\" stroke-width=\"2\"/><line x1=\"137\" y1=\"56\" x2=\"137\" y2=\"74\" stroke=\"black\" stroke-width=\"2\"/><line x1=\"149\" y1=\"56\" x2=\"149\" y2=\"74\" stroke=\"black\" stroke-width=\"2\"/><text x=\"137\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(2)</text><text x=\"186\" y=\"48\" text-anchor=\"middle\" font-size=\"18\" font-family=\"serif\">=</text><rect x=\"194\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"251\" y1=\"36\" x2=\"223\" y2=\"36\" stroke=\"black\" stroke-width=\"2.5\"/><polygon points=\"217,36 225,31 225,41\" fill=\"black\"/><line x1=\"213\" y1=\"64\" x2=\"253\" y2=\"64\" stroke=\"black\" stroke-width=\"2\"/><text x=\"233\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(3)</text><rect x=\"290\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><text x=\"329\" y=\"52\" text-anchor=\"middle\" font-size=\"40\" font-family=\"sans-serif\" font-weight=\"bold\">?</text><text x=\"329\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(4)</text></svg>",
    choices: [
      {
        id: "a",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"33\" y1=\"50\" x2=\"53\" y2=\"30\" stroke=\"black\" stroke-width=\"2.5\"/><polygon points=\"59,24 47,27 56,36\" fill=\"black\"/><line x1=\"38\" y1=\"60\" x2=\"38\" y2=\"78\" stroke=\"black\" stroke-width=\"2\"/><line x1=\"50\" y1=\"60\" x2=\"50\" y2=\"78\" stroke=\"black\" stroke-width=\"2\"/></svg>",
        score: 5,
      },
      {
        id: "b",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"44\" y1=\"46\" x2=\"44\" y2=\"20\" stroke=\"black\" stroke-width=\"2.5\"/><polygon points=\"44,14 39,22 49,22\" fill=\"black\"/><line x1=\"44\" y1=\"60\" x2=\"44\" y2=\"78\" stroke=\"black\" stroke-width=\"2\"/></svg>",
        score: 0,
      },
      {
        id: "c",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"33\" y1=\"28\" x2=\"53\" y2=\"48\" stroke=\"black\" stroke-width=\"2.5\"/><polygon points=\"59,54 47,51 56,42\" fill=\"black\"/><line x1=\"24\" y1=\"64\" x2=\"64\" y2=\"64\" stroke=\"black\" stroke-width=\"2\"/><line x1=\"24\" y1=\"72\" x2=\"64\" y2=\"72\" stroke=\"black\" stroke-width=\"2\"/></svg>",
        score: 0,
      },
      {
        id: "d",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"44\" y1=\"20\" x2=\"44\" y2=\"46\" stroke=\"black\" stroke-width=\"2.5\"/><polygon points=\"44,52 39,44 49,44\" fill=\"black\"/><line x1=\"24\" y1=\"60\" x2=\"64\" y2=\"60\" stroke=\"black\" stroke-width=\"2\"/><line x1=\"24\" y1=\"68\" x2=\"64\" y2=\"68\" stroke=\"black\" stroke-width=\"2\"/><line x1=\"24\" y1=\"76\" x2=\"64\" y2=\"76\" stroke=\"black\" stroke-width=\"2\"/></svg>",
        score: 0,
      },
      {
        id: "e",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"53\" y1=\"50\" x2=\"33\" y2=\"30\" stroke=\"black\" stroke-width=\"2.5\"/><polygon points=\"27,24 39,27 30,36\" fill=\"black\"/><line x1=\"24\" y1=\"70\" x2=\"40\" y2=\"54\" stroke=\"black\" stroke-width=\"2\"/><line x1=\"32\" y1=\"78\" x2=\"48\" y2=\"62\" stroke=\"black\" stroke-width=\"2\"/></svg>",
        score: 0,
      },
    ],
    explanation: "Dekonstruksi Elemen Visual:\n- Jarum panah: Berotasi searah jarum jam sejauh $135^\\circ$. Dari arah jam 9 berputar $+135^\\circ$ menuju arah jam 1.30.\n- Segmen garis: Berotasi $90^\\circ$ dari horizontal menjadi vertikal, dan jumlahnya bertambah 1 garis (dari 1 menjadi 2 garis vertikal sejajar pada Opsi A).",
  },
  {
    id: "mini-tiu4-33",
    category: "TIU",
    topic: "Kemampuan Figural",
    prompt: "Di antara lima konfigurasi figur geometris berikut, manakah yang TIDAK MENGIKUTI pola/kaidah pembentukan yang sama dengan empat konfigurasi lainnya?",
    choices: [
      {
        id: "a",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><polygon points=\"44,16 71,35 61,67 27,67 17,35\" fill=\"none\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"44\" y1=\"16\" x2=\"61\" y2=\"67\" stroke=\"#4b5563\" stroke-width=\"1\"/><line x1=\"44\" y1=\"16\" x2=\"27\" y2=\"67\" stroke=\"#4b5563\" stroke-width=\"1\"/><line x1=\"17\" y1=\"35\" x2=\"71\" y2=\"35\" stroke=\"#4b5563\" stroke-width=\"1\"/><circle cx=\"44\" cy=\"16\" r=\"3.5\" fill=\"black\"/><circle cx=\"71\" cy=\"35\" r=\"3.5\" fill=\"black\"/><circle cx=\"61\" cy=\"67\" r=\"3.5\" fill=\"black\"/><circle cx=\"27\" cy=\"67\" r=\"3.5\" fill=\"black\"/><circle cx=\"17\" cy=\"35\" r=\"3.5\" fill=\"black\"/></svg>",
        score: 0,
      },
      {
        id: "b",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><polygon points=\"58,18 72,44 58,70 30,70 16,44 30,18\" fill=\"none\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"30\" y1=\"18\" x2=\"58\" y2=\"70\" stroke=\"#4b5563\" stroke-width=\"1\"/><line x1=\"58\" y1=\"18\" x2=\"30\" y2=\"70\" stroke=\"#4b5563\" stroke-width=\"1\"/><line x1=\"16\" y1=\"44\" x2=\"72\" y2=\"44\" stroke=\"#4b5563\" stroke-width=\"1\"/><line x1=\"30\" y1=\"18\" x2=\"30\" y2=\"70\" stroke=\"#4b5563\" stroke-width=\"1\"/><circle cx=\"58\" cy=\"18\" r=\"3.5\" fill=\"black\"/><circle cx=\"72\" cy=\"44\" r=\"3.5\" fill=\"black\"/><circle cx=\"58\" cy=\"70\" r=\"3.5\" fill=\"black\"/><circle cx=\"30\" cy=\"70\" r=\"3.5\" fill=\"black\"/><circle cx=\"16\" cy=\"44\" r=\"3.5\" fill=\"black\"/><circle cx=\"30\" cy=\"18\" r=\"3.5\" fill=\"black\"/></svg>",
        score: 0,
      },
      {
        id: "c",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><polygon points=\"22,22 66,22 66,66 22,66\" fill=\"none\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"22\" y1=\"22\" x2=\"66\" y2=\"66\" stroke=\"#4b5563\" stroke-width=\"1\"/><line x1=\"66\" y1=\"22\" x2=\"22\" y2=\"66\" stroke=\"#4b5563\" stroke-width=\"1\"/><circle cx=\"22\" cy=\"22\" r=\"3.5\" fill=\"black\"/><circle cx=\"66\" cy=\"22\" r=\"3.5\" fill=\"black\"/><circle cx=\"66\" cy=\"66\" r=\"3.5\" fill=\"black\"/><circle cx=\"22\" cy=\"66\" r=\"3.5\" fill=\"black\"/></svg>",
        score: 0,
      },
      {
        id: "d",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><polygon points=\"44,16 68,26 72,52 56,70 32,70 16,52 20,26\" fill=\"none\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"44\" y1=\"16\" x2=\"56\" y2=\"70\" stroke=\"#4b5563\" stroke-width=\"1\"/><line x1=\"44\" y1=\"16\" x2=\"32\" y2=\"70\" stroke=\"#4b5563\" stroke-width=\"1\"/><line x1=\"20\" y1=\"26\" x2=\"68\" y2=\"26\" stroke=\"#4b5563\" stroke-width=\"1\"/><line x1=\"16\" y1=\"52\" x2=\"72\" y2=\"52\" stroke=\"#4b5563\" stroke-width=\"1\"/><line x1=\"20\" y1=\"26\" x2=\"56\" y2=\"70\" stroke=\"#4b5563\" stroke-width=\"1\"/><circle cx=\"44\" cy=\"16\" r=\"3.5\" fill=\"black\"/><circle cx=\"68\" cy=\"26\" r=\"3.5\" fill=\"black\"/><circle cx=\"72\" cy=\"52\" r=\"3.5\" fill=\"black\"/><circle cx=\"56\" cy=\"70\" r=\"3.5\" fill=\"black\"/><circle cx=\"32\" cy=\"70\" r=\"3.5\" fill=\"black\"/><circle cx=\"16\" cy=\"52\" r=\"3.5\" fill=\"black\"/><circle cx=\"20\" cy=\"26\" r=\"3.5\" fill=\"black\"/></svg>",
        score: 0,
      },
      {
        id: "e",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><polygon points=\"34,16 54,16 72,34 72,54 54,72 34,72 16,54 16,34\" fill=\"none\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"34\" y1=\"16\" x2=\"54\" y2=\"72\" stroke=\"#4b5563\" stroke-width=\"1\"/><line x1=\"54\" y1=\"16\" x2=\"34\" y2=\"72\" stroke=\"#4b5563\" stroke-width=\"1\"/><line x1=\"16\" y1=\"34\" x2=\"72\" y2=\"54\" stroke=\"#4b5563\" stroke-width=\"1\"/><line x1=\"16\" y1=\"54\" x2=\"72\" y2=\"34\" stroke=\"#4b5563\" stroke-width=\"1\"/><line x1=\"34\" y1=\"16\" x2=\"72\" y2=\"54\" stroke=\"#4b5563\" stroke-width=\"1\"/><line x1=\"16\" y1=\"34\" x2=\"54\" y2=\"72\" stroke=\"#4b5563\" stroke-width=\"1\"/><line x1=\"54\" y1=\"16\" x2=\"16\" y2=\"54\" stroke=\"#4b5563\" stroke-width=\"1\"/><circle cx=\"34\" cy=\"16\" r=\"3.5\" fill=\"black\"/><circle cx=\"54\" cy=\"16\" r=\"3.5\" fill=\"black\"/><circle cx=\"72\" cy=\"34\" r=\"3.5\" fill=\"black\"/><circle cx=\"72\" cy=\"54\" r=\"3.5\" fill=\"black\"/><circle cx=\"54\" cy=\"72\" r=\"3.5\" fill=\"black\"/><circle cx=\"34\" cy=\"72\" r=\"3.5\" fill=\"black\"/><circle cx=\"16\" cy=\"54\" r=\"3.5\" fill=\"black\"/><circle cx=\"16\" cy=\"34\" r=\"3.5\" fill=\"black\"/></svg>",
        score: 5,
      },
    ],
    explanation: "Dekonstruksi Elemen Visual:\nHubungan poligon bersisi $n$:\n- Jumlah bulatan sudut $= n$.\n- Jumlah garis diagonal internal $= n - 2$.\n- Uji pola: Segi lima ($5 - 2 = 3$), segi enam ($6 - 2 = 4$), segi empat ($4 - 2 = 2$), segi tujuh ($7 - 2 = 5$).\n- Opsi E menyimpang karena segi delapan ($n=8$) digambar memiliki 7 garis diagonal internal, bukan 6.",
  },
  {
    id: "mini-tiu4-34",
    category: "TIU",
    topic: "Kemampuan Figural",
    prompt: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 470 100\" style=\"width:100%;max-width:560px;display:block\"><rect x=\"6\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"6\" y1=\"30\" x2=\"84\" y2=\"30\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"6\" y1=\"56\" x2=\"84\" y2=\"56\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"32\" y1=\"4\" x2=\"32\" y2=\"82\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"58\" y1=\"4\" x2=\"58\" y2=\"82\" stroke=\"#9ca3af\" stroke-width=\"1\"/><rect x=\"58\" y=\"56\" width=\"26\" height=\"26\" fill=\"#9ca3af\"/><circle cx=\"19\" cy=\"17\" r=\"7\" fill=\"black\"/><polygon points=\"45,34 37,50 53,50\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><text x=\"45\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(1)</text><rect x=\"100\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"100\" y1=\"30\" x2=\"178\" y2=\"30\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"100\" y1=\"56\" x2=\"178\" y2=\"56\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"126\" y1=\"4\" x2=\"126\" y2=\"82\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"152\" y1=\"4\" x2=\"152\" y2=\"82\" stroke=\"#9ca3af\" stroke-width=\"1\"/><rect x=\"126\" y=\"56\" width=\"26\" height=\"26\" fill=\"#9ca3af\"/><circle cx=\"139\" cy=\"17\" r=\"7\" fill=\"black\"/><polygon points=\"147,43 131,35 131,51\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><text x=\"139\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(2)</text><rect x=\"194\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"194\" y1=\"30\" x2=\"272\" y2=\"30\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"194\" y1=\"56\" x2=\"272\" y2=\"56\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"220\" y1=\"4\" x2=\"220\" y2=\"82\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"246\" y1=\"4\" x2=\"246\" y2=\"82\" stroke=\"#9ca3af\" stroke-width=\"1\"/><rect x=\"194\" y=\"56\" width=\"26\" height=\"26\" fill=\"#9ca3af\"/><circle cx=\"259\" cy=\"17\" r=\"7\" fill=\"black\"/><polygon points=\"233,51 225,35 241,35\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><text x=\"233\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(3)</text><rect x=\"288\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"288\" y1=\"30\" x2=\"366\" y2=\"30\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"288\" y1=\"56\" x2=\"366\" y2=\"56\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"314\" y1=\"4\" x2=\"314\" y2=\"82\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"340\" y1=\"4\" x2=\"340\" y2=\"82\" stroke=\"#9ca3af\" stroke-width=\"1\"/><rect x=\"288\" y=\"30\" width=\"26\" height=\"26\" fill=\"#9ca3af\"/><circle cx=\"353\" cy=\"43\" r=\"7\" fill=\"black\"/><polygon points=\"319,43 335,35 335,51\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><text x=\"327\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(4)</text><rect x=\"382\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><text x=\"421\" y=\"52\" text-anchor=\"middle\" font-size=\"40\" font-family=\"sans-serif\" font-weight=\"bold\">?</text><text x=\"421\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(5)</text></svg>",
    choices: [
      {
        id: "a",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"2\" y1=\"30\" x2=\"86\" y2=\"30\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"2\" y1=\"58\" x2=\"86\" y2=\"58\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"30\" y1=\"2\" x2=\"30\" y2=\"86\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"58\" y1=\"2\" x2=\"58\" y2=\"86\" stroke=\"#9ca3af\" stroke-width=\"1\"/><rect x=\"2\" y=\"2\" width=\"28\" height=\"28\" fill=\"#9ca3af\"/><circle cx=\"72\" cy=\"72\" r=\"8\" fill=\"black\"/><polygon points=\"44,34 35,52 53,52\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/></svg>",
        score: 5,
      },
      {
        id: "b",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"2\" y1=\"30\" x2=\"86\" y2=\"30\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"2\" y1=\"58\" x2=\"86\" y2=\"58\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"30\" y1=\"2\" x2=\"30\" y2=\"86\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"58\" y1=\"2\" x2=\"58\" y2=\"86\" stroke=\"#9ca3af\" stroke-width=\"1\"/><rect x=\"30\" y=\"2\" width=\"28\" height=\"28\" fill=\"#9ca3af\"/><circle cx=\"44\" cy=\"72\" r=\"8\" fill=\"black\"/><polygon points=\"44,34 35,52 53,52\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/></svg>",
        score: 0,
      },
      {
        id: "c",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"2\" y1=\"30\" x2=\"86\" y2=\"30\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"2\" y1=\"58\" x2=\"86\" y2=\"58\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"30\" y1=\"2\" x2=\"30\" y2=\"86\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"58\" y1=\"2\" x2=\"58\" y2=\"86\" stroke=\"#9ca3af\" stroke-width=\"1\"/><rect x=\"30\" y=\"2\" width=\"28\" height=\"28\" fill=\"#9ca3af\"/><circle cx=\"72\" cy=\"72\" r=\"8\" fill=\"black\"/><polygon points=\"53,44 35,35 35,53\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/></svg>",
        score: 0,
      },
      {
        id: "d",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"2\" y1=\"30\" x2=\"86\" y2=\"30\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"2\" y1=\"58\" x2=\"86\" y2=\"58\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"30\" y1=\"2\" x2=\"30\" y2=\"86\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"58\" y1=\"2\" x2=\"58\" y2=\"86\" stroke=\"#9ca3af\" stroke-width=\"1\"/><rect x=\"2\" y=\"58\" width=\"28\" height=\"28\" fill=\"#9ca3af\"/><circle cx=\"44\" cy=\"44\" r=\"8\" fill=\"black\"/><polygon points=\"44,53 35,35 53,35\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/></svg>",
        score: 0,
      },
      {
        id: "e",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><line x1=\"2\" y1=\"30\" x2=\"86\" y2=\"30\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"2\" y1=\"58\" x2=\"86\" y2=\"58\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"30\" y1=\"2\" x2=\"30\" y2=\"86\" stroke=\"#9ca3af\" stroke-width=\"1\"/><line x1=\"58\" y1=\"2\" x2=\"58\" y2=\"86\" stroke=\"#9ca3af\" stroke-width=\"1\"/><rect x=\"58\" y=\"58\" width=\"28\" height=\"28\" fill=\"#9ca3af\"/><circle cx=\"16\" cy=\"16\" r=\"8\" fill=\"black\"/><polygon points=\"35,44 53,35 53,53\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/></svg>",
        score: 0,
      },
    ],
    explanation: "Dekonstruksi Elemen Visual:\n- Lingkaran hitam: Bergeser 1 sel searah jarum jam di lintasan tepi. Dari (baris 2, kolom 3) berpindah ke (baris 3, kolom 3).\n- Segitiga pusat: Berputar $90^\\circ$ searah jarum jam tiap langkah. Dari menghadap ke kiri pada Pola 4, kembali menghadap ke atas pada Pola 5.\n- Arsiran abu-abu: Bergeser 1 sel berlawanan jarum jam di lintasan tepi. Dari (baris 2, kolom 1) berpindah ke (baris 1, kolom 1).\nKonfigurasi yang memenuhi adalah Opsi A.",
  },
  {
    id: "mini-tiu4-35",
    category: "TIU",
    topic: "Kemampuan Figural",
    prompt: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 470 100\" style=\"width:100%;max-width:560px;display:block\"><rect x=\"6\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><circle cx=\"45\" cy=\"43\" r=\"28\" fill=\"none\" stroke=\"#e5e7eb\" stroke-dasharray=\"2,2\"/><line x1=\"45\" y1=\"43\" x2=\"45\" y2=\"19\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><line x1=\"45\" y1=\"43\" x2=\"55\" y2=\"26\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><circle cx=\"45\" cy=\"43\" r=\"3\" fill=\"black\"/><circle cx=\"28\" cy=\"54\" r=\"3\" fill=\"black\"/><text x=\"45\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(1)</text><rect x=\"100\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><circle cx=\"139\" cy=\"43\" r=\"28\" fill=\"none\" stroke=\"#e5e7eb\" stroke-dasharray=\"2,2\"/><line x1=\"139\" y1=\"43\" x2=\"139\" y2=\"19\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><line x1=\"139\" y1=\"43\" x2=\"157\" y2=\"33\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><circle cx=\"139\" cy=\"43\" r=\"3\" fill=\"black\"/><circle cx=\"147\" cy=\"24\" r=\"3\" fill=\"black\"/><circle cx=\"152\" cy=\"30\" r=\"3\" fill=\"black\"/><text x=\"139\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(2)</text><rect x=\"194\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><circle cx=\"233\" cy=\"43\" r=\"28\" fill=\"none\" stroke=\"#e5e7eb\" stroke-dasharray=\"2,2\"/><line x1=\"233\" y1=\"43\" x2=\"233\" y2=\"19\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><line x1=\"233\" y1=\"43\" x2=\"257\" y2=\"43\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><circle cx=\"233\" cy=\"43\" r=\"3\" fill=\"black\"/><circle cx=\"218\" cy=\"32\" r=\"3\" fill=\"black\"/><circle cx=\"218\" cy=\"56\" r=\"3\" fill=\"black\"/><circle cx=\"244\" cy=\"58\" r=\"3\" fill=\"black\"/><text x=\"233\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(3)</text><rect x=\"288\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><circle cx=\"327\" cy=\"43\" r=\"28\" fill=\"none\" stroke=\"#e5e7eb\" stroke-dasharray=\"2,2\"/><line x1=\"327\" y1=\"43\" x2=\"327\" y2=\"19\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><line x1=\"327\" y1=\"43\" x2=\"347\" y2=\"55\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><circle cx=\"327\" cy=\"43\" r=\"3\" fill=\"black\"/><circle cx=\"335\" cy=\"25\" r=\"3\" fill=\"black\"/><circle cx=\"343\" cy=\"33\" r=\"3\" fill=\"black\"/><circle cx=\"344\" cy=\"43\" r=\"3\" fill=\"black\"/><circle cx=\"338\" cy=\"52\" r=\"3\" fill=\"black\"/><text x=\"327\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(4)</text><rect x=\"382\" y=\"4\" width=\"78\" height=\"78\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><text x=\"421\" y=\"52\" text-anchor=\"middle\" font-size=\"40\" font-family=\"sans-serif\" font-weight=\"bold\">?</text><text x=\"421\" y=\"96\" text-anchor=\"middle\" font-size=\"10\" font-family=\"sans-serif\">(5)</text></svg>",
    choices: [
      {
        id: "a",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><circle cx=\"44\" cy=\"44\" r=\"32\" fill=\"none\" stroke=\"#e5e7eb\" stroke-dasharray=\"2,2\"/><line x1=\"44\" y1=\"44\" x2=\"44\" y2=\"16\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><line x1=\"44\" y1=\"44\" x2=\"55\" y2=\"63\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><circle cx=\"44\" cy=\"44\" r=\"3\" fill=\"black\"/><circle cx=\"53\" cy=\"24\" r=\"3\" fill=\"black\"/><circle cx=\"62\" cy=\"34\" r=\"3\" fill=\"black\"/><circle cx=\"64\" cy=\"46\" r=\"3\" fill=\"black\"/><circle cx=\"58\" cy=\"56\" r=\"3\" fill=\"black\"/><circle cx=\"48\" cy=\"58\" r=\"3\" fill=\"black\"/></svg>",
        score: 0,
      },
      {
        id: "b",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><circle cx=\"44\" cy=\"44\" r=\"32\" fill=\"none\" stroke=\"#e5e7eb\" stroke-dasharray=\"2,2\"/><line x1=\"44\" y1=\"44\" x2=\"44\" y2=\"16\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><line x1=\"44\" y1=\"44\" x2=\"55\" y2=\"63\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><circle cx=\"44\" cy=\"44\" r=\"3\" fill=\"black\"/><circle cx=\"30\" cy=\"24\" r=\"3\" fill=\"black\"/><circle cx=\"22\" cy=\"38\" r=\"3\" fill=\"black\"/><circle cx=\"22\" cy=\"54\" r=\"3\" fill=\"black\"/><circle cx=\"32\" cy=\"66\" r=\"3\" fill=\"black\"/><circle cx=\"42\" cy=\"72\" r=\"3\" fill=\"black\"/></svg>",
        score: 5,
      },
      {
        id: "c",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><circle cx=\"44\" cy=\"44\" r=\"32\" fill=\"none\" stroke=\"#e5e7eb\" stroke-dasharray=\"2,2\"/><line x1=\"44\" y1=\"44\" x2=\"44\" y2=\"16\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><line x1=\"44\" y1=\"44\" x2=\"44\" y2=\"68\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><circle cx=\"44\" cy=\"44\" r=\"3\" fill=\"black\"/><circle cx=\"30\" cy=\"24\" r=\"3\" fill=\"black\"/><circle cx=\"22\" cy=\"38\" r=\"3\" fill=\"black\"/><circle cx=\"22\" cy=\"54\" r=\"3\" fill=\"black\"/><circle cx=\"30\" cy=\"66\" r=\"3\" fill=\"black\"/><circle cx=\"16\" cy=\"44\" r=\"3\" fill=\"black\"/></svg>",
        score: 0,
      },
      {
        id: "d",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><circle cx=\"44\" cy=\"44\" r=\"32\" fill=\"none\" stroke=\"#e5e7eb\" stroke-dasharray=\"2,2\"/><line x1=\"44\" y1=\"44\" x2=\"44\" y2=\"16\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><line x1=\"44\" y1=\"44\" x2=\"60\" y2=\"60\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><circle cx=\"44\" cy=\"44\" r=\"3\" fill=\"black\"/><circle cx=\"30\" cy=\"24\" r=\"3\" fill=\"black\"/><circle cx=\"22\" cy=\"38\" r=\"3\" fill=\"black\"/><circle cx=\"22\" cy=\"54\" r=\"3\" fill=\"black\"/><circle cx=\"32\" cy=\"66\" r=\"3\" fill=\"black\"/></svg>",
        score: 0,
      },
      {
        id: "e",
        label: "[svg]<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 88 88\" style=\"width:56px;height:56px;display:block\"><rect x=\"2\" y=\"2\" width=\"84\" height=\"84\" fill=\"white\" stroke=\"black\" stroke-width=\"1.5\"/><circle cx=\"44\" cy=\"44\" r=\"32\" fill=\"none\" stroke=\"#e5e7eb\" stroke-dasharray=\"2,2\"/><line x1=\"44\" y1=\"44\" x2=\"44\" y2=\"16\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><line x1=\"44\" y1=\"44\" x2=\"55\" y2=\"63\" stroke=\"black\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><circle cx=\"44\" cy=\"44\" r=\"3\" fill=\"black\"/><circle cx=\"53\" cy=\"22\" r=\"3\" fill=\"black\"/><circle cx=\"62\" cy=\"30\" r=\"3\" fill=\"black\"/><circle cx=\"66\" cy=\"40\" r=\"3\" fill=\"black\"/><circle cx=\"64\" cy=\"50\" r=\"3\" fill=\"black\"/><circle cx=\"56\" cy=\"58\" r=\"3\" fill=\"black\"/><circle cx=\"48\" cy=\"60\" r=\"3\" fill=\"black\"/></svg>",
        score: 0,
      },
    ],
    explanation: "Dekonstruksi Elemen Visual:\n- Besar sudut: Bertambah $+30^\\circ$ konstan ($30^\\circ, 60^\\circ, 90^\\circ, 120^\\circ \\to 150^\\circ$).\n- Jumlah titik: Bertambah satu per satu ($1, 2, 3, 4 \\to 5$ titik).\n- Posisi titik: Berselang-seling teratur (Luar → Dalam → Luar → Dalam → Luar sudut).\n- Pola ke-5 memiliki sudut $150^\\circ$ dengan 5 titik hitam di area luar sudut (Opsi B).",
  },
];
