import type { Question } from "./types";

export const MINI_TIU_7_QUESTIONS: Question[] = [
  {
    id: "mini-tiu7-01",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "VAKSINASI : KEKEBALAN = ASURANSI : ...",
    choices: [
      { id: "a", label: "Perlindungan", score: 5 },
      { id: "b", label: "Premi", score: 0 },
      { id: "c", label: "Klaim", score: 0 },
      { id: "d", label: "Polis", score: 0 },
      { id: "e", label: "Kompensasi", score: 0 },
    ],
    explanation: "Hubungan tindakan preventif terencana dan tujuannya: Vaksinasi dilakukan secara terencana untuk memperoleh kekebalan tubuh terhadap penyakit, sebagaimana asuransi diikuti secara terencana untuk memperoleh perlindungan terhadap risiko kerugian finansial. Jawaban yang tepat adalah Opsi A.",
  },
  {
    id: "mini-tiu7-02",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "HIGROMETER : KELEMBAPAN = BAROMETER : ...",
    choices: [
      { id: "a", label: "Ketinggian", score: 0 },
      { id: "b", label: "Suhu Udara", score: 0 },
      { id: "c", label: "Tekanan Udara", score: 5 },
      { id: "d", label: "Kecepatan Angin", score: 0 },
      { id: "e", label: "Curah Hujan", score: 0 },
    ],
    explanation: "Hubungan alat ukur dan besaran fisik yang diukur: Higrometer adalah instrumen untuk mengukur tingkat kelembapan udara, sedangkan barometer adalah instrumen khusus untuk mengukur tekanan udara atmosfer. Jawaban yang tepat adalah Opsi C.",
  },
  {
    id: "mini-tiu7-03",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "KAPOLRES : KABUPATEN = KAPOLDA : ...",
    choices: [
      { id: "a", label: "Kecamatan", score: 0 },
      { id: "b", label: "Kotamadya", score: 0 },
      { id: "c", label: "Karesidenan", score: 0 },
      { id: "d", label: "Provinsi", score: 5 },
      { id: "e", label: "Nasional", score: 0 },
    ],
    explanation: "Hubungan pimpinan komando kewilayahan dan tingkat wilayah yurisdiksinya: Kapolres memimpin kesatuan kepolisian resor di tingkat kabupaten/kota, sedangkan Kapolda memimpin kesatuan kepolisian daerah di tingkat provinsi. Jawaban yang tepat adalah Opsi D.",
  },
  {
    id: "mini-tiu7-04",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "... : PERSIDANGAN = WASIT : ...",
    choices: [
      { id: "a", label: "Pengacara – Kejuaraan", score: 0 },
      { id: "b", label: "Hakim – Pertandingan", score: 5 },
      { id: "c", label: "Jaksa – Lapangan", score: 0 },
      { id: "d", label: "Terdakwa – Penonton", score: 0 },
      { id: "e", label: "Panitera – Peluit", score: 0 },
    ],
    explanation: "Hubungan analogi ganda penegak aturan dan arena tugasnya: Hakim memimpin dan memutuskan perkara secara adil dalam jalannya persidangan, sebagaimana wasit memimpin dan menegakkan aturan main secara adil dalam jalannya pertandingan. Jawaban yang tepat adalah Opsi B.",
  },
  {
    id: "mini-tiu7-05",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "Semua pranata komputer ahli pertama menguasai arsitektur basis data. Sebagian staf biro perencanaan adalah pranata komputer ahli pertama. Tidak ada staf biro perencanaan yang berstatus pegawai lepas.\n\nSimpulan yang paling tepat adalah ...",
    choices: [
      { id: "a", label: "Sebagian staf biro perencanaan menguasai arsitektur basis data.", score: 5 },
      { id: "b", label: "Semua staf biro perencanaan menguasai arsitektur basis data.", score: 0 },
      { id: "c", label: "Semua orang yang menguasai arsitektur basis data adalah staf biro perencanaan.", score: 0 },
      { id: "d", label: "Sebagian orang yang menguasai arsitektur basis data berstatus pegawai lepas.", score: 0 },
      { id: "e", label: "Tidak ada pranata komputer ahli pertama yang bukan staf biro perencanaan.", score: 0 },
    ],
    explanation: "Analisis Silogisme Kategorik:\n- Premis 1: Pranata Komputer Ahli Pertama (P) → Menguasai Basis Data (B).\n- Premis 2: Sebagian Staf Biro Perencanaan (S) adalah Pranata Komputer Ahli Pertama (P).\nSimpulan langsung: Karena sebagian S adalah P, dan seluruh P adalah B, maka dipastikan sebagian staf biro perencanaan (S) menguasai arsitektur basis data (B). Jawaban yang tepat adalah Opsi A.",
  },
  {
    id: "mini-tiu7-06",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "Jika sebuah instansi menerapkan digitalisasi arsip, maka waktu pelayanan publik menjadi lebih cepat. Jika waktu pelayanan publik menjadi lebih cepat, maka indeks kepuasan masyarakat meningkat. Instansi B tidak mengalami peningkatan indeks kepuasan masyarakat.\n\nSimpulan yang sah adalah ...",
    choices: [
      { id: "a", label: "Instansi B tetap menerapkan digitalisasi arsip namun pelayanannya lambat.", score: 0 },
      { id: "b", label: "Instansi B tidak menerapkan digitalisasi arsip.", score: 5 },
      { id: "c", label: "Instansi B mempercepat pelayanan publik tanpa digitalisasi arsip.", score: 0 },
      { id: "d", label: "Digitalisasi arsip tidak memengaruhi indeks kepuasan masyarakat di Instansi B.", score: 0 },
      { id: "e", label: "Sebagian pelayanan di Instansi B telah dilakukan secara digital.", score: 0 },
    ],
    explanation: "Analisis Silogisme Hipotetis & Modus Tollens:\n- Premis 1: Digitalisasi Arsip ($D$) → Waktu Lebih Cepat ($W$).\n- Premis 2: Waktu Lebih Cepat ($W$) → Indeks Kepuasan Naik ($I$).\nSilogisme berantai menghasilkan: $D \\implies I$.\n- Fakta: Instansi B tidak mengalami peningkatan indeks kepuasan masyarakat ($\\sim I$).\nBerdasarkan aturan penarikan kesimpulan Modus Tollens:\n$$(D \\implies I) \\land \\sim I \\implies \\sim D$$\nMaka simpulan yang sah: Instansi B tidak menerapkan digitalisasi arsip. Jawaban yang tepat adalah Opsi B.",
  },
  {
    id: "mini-tiu7-07",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "Setiap pejabat fungsional perencana wajib lulus uji kompetensi keahlian atau memiliki portofolio proyek strategis minimal 3 kali. Jika pejabat memiliki portofolio proyek strategis minimal 3 kali, ia harus sudah bekerja di biro perencanaan lebih dari 4 tahun. Bagus adalah pejabat fungsional perencana yang baru bekerja di biro perencanaan selama 2 tahun.\n\nSimpulan yang sah adalah ...",
    choices: [
      { id: "a", label: "Bagus tidak dapat diangkat sebagai pejabat fungsional perencana.", score: 0 },
      { id: "b", label: "Bagus telah memiliki portofolio proyek strategis minimal 3 kali.", score: 0 },
      { id: "c", label: "Bagus dibebaskan dari kewajiban uji kompetensi keahlian.", score: 0 },
      { id: "d", label: "Bagus harus menunggu 2 tahun lagi untuk mengikuti uji kompetensi.", score: 0 },
      { id: "e", label: "Bagus wajib lulus uji kompetensi keahlian.", score: 5 },
    ],
    explanation: "Analisis Silogisme Disjungtif & Modus Tollens:\n- Aturan: Lulus Uji Kompetensi ($U$) $\\lor$ Portofolio Proyek $\\ge 3$ ($P$).\n- Implikasi: $P \\implies$ Masa Kerja $> 4$ tahun ($M$).\n- Fakta: Masa kerja Bagus baru 2 tahun (artinya $\\sim M$).\nMelalui Modus Tollens: $\\sim M \\implies \\sim P$ (Bagus dipastikan belum memiliki portofolio proyek minimal 3 kali).\nMelalui Silogisme Disjungtif: $(U \\lor P) \\land \\sim P \\implies U$.\nMaka Bagus wajib lulus uji kompetensi keahlian. Jawaban yang tepat adalah Opsi E.",
  },
  {
    id: "mini-tiu7-08",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "Semua kendaraan operasional dinas berbahan bakar ramah lingkungan. Sebagian kendaraan operasional dinas digunakan untuk inspeksi lapangan. Semua kendaraan yang digunakan untuk inspeksi lapangan dilengkapi perangkat navigasi GPS.\n\nSimpulan yang benar adalah ...",
    choices: [
      { id: "a", label: "Semua kendaraan berbahan bakar ramah lingkungan digunakan untuk inspeksi lapangan.", score: 0 },
      { id: "b", label: "Semua kendaraan yang dilengkapi GPS bukan merupakan kendaraan dinas.", score: 0 },
      { id: "c", label: "Sebagian kendaraan berbahan bakar ramah lingkungan dilengkapi perangkat navigasi GPS.", score: 5 },
      { id: "d", label: "Tidak ada kendaraan dinas yang dilengkapi GPS berbahan bakar ramah lingkungan.", score: 0 },
      { id: "e", label: "Kendaraan yang tidak digunakan untuk inspeksi lapangan pasti tidak ramah lingkungan.", score: 0 },
    ],
    explanation: "Analisis Logika Himpunan / Diagram Venn:\n- Seluruh himpunan Kendaraan Dinas ($D$) termasuk dalam himpunan Ramah Lingkungan ($R$).\n- Sebagian $D$ beririsan dengan Kendaraan Inspeksi ($I$).\n- Seluruh $I$ termasuk dalam himpunan Ber-GPS ($G$).\nKarena sebagian $D$ adalah $I$, dan setiap $I$ memiliki GPS ($G$), maka terdapat sebagian kendaraan dinas yang ber-GPS. Mengingat semua kendaraan dinas adalah ramah lingkungan ($R$), maka dipastikan sebagian kendaraan berbahan bakar ramah lingkungan dilengkapi perangkat navigasi GPS. Jawaban yang tepat adalah Opsi C.",
  },
  {
    id: "mini-tiu7-09",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "Tujuh orang peserta pelatihan kepemimpinan (Adit, Bima, Caca, Doni, Ega, Fandi, dan Galih) duduk berjajar di barisan depan aula pada kursi nomor 1 sampai 7 secara berurutan dari kiri ke kanan dengan ketentuan:\n1. Doni duduk di kursi nomor 4.\n2. Galih duduk di kursi nomor 7.\n3. Adit duduk tepat di sebelah kiri Caca (keduanya menempati dua kursi berdampingan secara berurutan).\n4. Bima duduk tepat di sebelah kanan Ega (keduanya menempati dua kursi berdampingan secara berurutan).\n5. Fandi duduk di sebelah kiri Doni, tetapi tidak boleh duduk di kursi nomor 1.\n\nBerdasarkan ketentuan tersebut, pegawai yang PASTI duduk di kursi nomor 3 adalah ...",
    choices: [
      { id: "a", label: "Adit", score: 0 },
      { id: "b", label: "Bima", score: 0 },
      { id: "c", label: "Caca", score: 0 },
      { id: "d", label: "Fandi", score: 5 },
      { id: "e", label: "Ega", score: 0 },
    ],
    explanation: "Penalaran Analitis Posisi Duduk Berjajar:\n- Kursi tersedia: 1, 2, 3, 4, 5, 6, 7.\n- Posisi pasti: Kursi 4 = Doni, Kursi 7 = Galih.\n- Kursi yang masih kosong: {1, 2, 3} di sebelah kiri Doni, serta {5, 6} di sebelah kanan Doni.\n- Terdapat dua pasangan orang yang wajib duduk berdampingan: blok (Adit, Caca) dan blok (Ega, Bima).\n- Kursi {5, 6} adalah satu blok 2 kursi berturutan, sehingga salah satu pasangan (AC atau EB) WAJIB menempati kursi {5, 6}.\n- Pasangan lainnya wajib menempati kursi di sebelah kiri Doni {1, 2, 3}.\n- Agar satu pasangan dapat duduk berdampingan di {1, 2, 3}, pasangan tersebut harus menempati kursi {1, 2} ATAU {2, 3}.\n- Fakta syarat 5: Fandi duduk di kiri Doni ({1, 2, 3}) namun BUKAN di kursi 1. Jika pasangan menempati {2, 3}, maka Fandi terpaksa di kursi 1 (melanggar syarat 5). Oleh karena itu, pasangan tersebut wajib menempati kursi {1, 2}, sehingga Fandi secara unik dan pasti duduk di kursi nomor 3. Jawaban yang tepat adalah Opsi D.",
  },
  {
    id: "mini-tiu7-10",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "Tujuh orang peserta pelatihan kepemimpinan (Adit, Bima, Caca, Doni, Ega, Fandi, dan Galih) duduk berjajar di barisan depan aula pada kursi nomor 1 sampai 7 secara berurutan dari kiri ke kanan dengan ketentuan:\n1. Doni duduk di kursi nomor 4.\n2. Galih duduk di kursi nomor 7.\n3. Adit duduk tepat di sebelah kiri Caca.\n4. Bima duduk tepat di sebelah kanan Ega.\n5. Fandi duduk di sebelah kiri Doni, tetapi tidak boleh duduk di kursi nomor 1.\n\nJika Adit duduk di kursi nomor 1, maka pernyataan berikut yang PASTI BENAR adalah ...",
    choices: [
      { id: "a", label: "Ega duduk di kursi nomor 5.", score: 5 },
      { id: "b", label: "Bima duduk di kursi nomor 5.", score: 0 },
      { id: "c", label: "Caca duduk di kursi nomor 3.", score: 0 },
      { id: "d", label: "Fandi duduk di kursi nomor 2.", score: 0 },
      { id: "e", label: "Ega duduk di kursi nomor 6.", score: 0 },
    ],
    explanation: "Analisis Berdasarkan Kondisi Tambahan:\n- Jika Adit di kursi 1, karena Adit tepat di sebelah kiri Caca, maka Caca pasti duduk di kursi nomor 2.\n- Berdasarkan analisis sebelumnya, Fandi duduk di kursi nomor 3.\n- Doni duduk di kursi nomor 4.\n- Dua kursi yang tersisa di sebelah kanan adalah nomor 5 dan 6. Pasangan kedua adalah (Ega, Bima), di mana Bima tepat di sebelah kanan Ega (urutan: Ega lalu Bima).\n- Maka Ega pasti duduk di kursi nomor 5 dan Bima duduk di kursi nomor 6.\n- Galih di kursi nomor 7.\nPernyataan yang pasti benar adalah Ega duduk di kursi nomor 5. Jawaban yang tepat adalah Opsi A.",
  },
  {
    id: "mini-tiu7-11",
    category: "TIU",
    topic: "Kemampuan Verbal",
    prompt: "Tujuh orang peserta pelatihan kepemimpinan (Adit, Bima, Caca, Doni, Ega, Fandi, dan Galih) duduk berjajar di barisan depan aula pada kursi nomor 1 sampai 7 secara berurutan dari kiri ke kanan dengan ketentuan:\n1. Doni duduk di kursi nomor 4.\n2. Galih duduk di kursi nomor 7.\n3. Adit duduk tepat di sebelah kiri Caca.\n4. Bima duduk tepat di sebelah kanan Ega.\n5. Fandi duduk di sebelah kiri Doni, tetapi tidak boleh duduk di kursi nomor 1.\n\nJika Bima duduk di kursi nomor 2, maka susunan posisi duduk dari kursi nomor 1 sampai 7 secara berurutan adalah ...",
    choices: [
      { id: "a", label: "Adit, Caca, Fandi, Doni, Ega, Bima, Galih", score: 0 },
      { id: "b", label: "Ega, Bima, Fandi, Doni, Adit, Caca, Galih", score: 5 },
      { id: "c", label: "Bima, Ega, Fandi, Doni, Adit, Caca, Galih", score: 0 },
      { id: "d", label: "Ega, Bima, Adit, Doni, Caca, Fandi, Galih", score: 0 },
      { id: "e", label: "Fandi, Bima, Ega, Doni, Adit, Caca, Galih", score: 0 },
    ],
    explanation: "Analisis Urutan Lengkap:\n- Jika Bima di kursi nomor 2, karena Bima tepat di sebelah kanan Ega, maka Ega wajib di kursi nomor 1 (formasi: Ega = 1, Bima = 2).\n- Fandi duduk di kursi nomor 3.\n- Doni duduk di kursi nomor 4.\n- Pasangan (Adit, Caca) dengan Adit tepat di kiri Caca menempati kursi nomor 5 dan 6 (Adit = 5, Caca = 6).\n- Galih duduk di kursi nomor 7.\nMaka susunan lengkap kursi 1 s.d. 7 adalah: Ega, Bima, Fandi, Doni, Adit, Caca, Galih. Jawaban yang tepat adalah Opsi B.",
  },
  {
    id: "mini-tiu7-12",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Jika diketahui sistem persamaan linear dua variabel $3x + 2y = 23$ dan $y = x + 4$, maka nilai dari $x \\times y$ adalah ...",
    choices: [
      { id: "a", label: "15", score: 0 },
      { id: "b", label: "18", score: 0 },
      { id: "c", label: "21", score: 5 },
      { id: "d", label: "24", score: 0 },
      { id: "e", label: "28", score: 0 },
    ],
    explanation: "Penyelesaian Sistem Persamaan Linear Substitusi Dasar:\nSubstitusikan nilai $y = x + 4$ ke dalam persamaan pertama:\n$$3x + 2(x + 4) = 23$$\n$$3x + 2x + 8 = 23$$\n$$5x + 8 = 23 \\implies 5x = 15 \\implies x = 3$$\nSubstitusikan nilai $x = 3$ untuk mencari $y$:\n$$y = 3 + 4 = 7$$\nMaka nilai hasil kali $x \\times y$ adalah:\n$$x \\times y = 3 \\times 7 = 21$$\nJawaban yang tepat adalah 21 (Opsi C).",
  },
  {
    id: "mini-tiu7-13",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Nilai dari $\\frac{86^2 - 14^2}{72}$ adalah ...",
    choices: [
      { id: "a", label: "72", score: 0 },
      { id: "b", label: "80", score: 0 },
      { id: "c", label: "96", score: 0 },
      { id: "d", label: "100", score: 5 },
      { id: "e", label: "120", score: 0 },
    ],
    explanation: "Penerapan Konsep Dasar Selisih Kuadrat $a^2 - b^2 = (a - b)(a + b)$:\nDengan menetapkan $a = 86$ dan $b = 14$:\n$$\\frac{86^2 - 14^2}{72} = \\frac{(86 - 14)(86 + 14)}{72}$$\n$$= \\frac{72 \\times 100}{72} = 100$$\nJawaban yang tepat adalah 100 (Opsi D).",
  },
  {
    id: "mini-tiu7-14",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Nilai dari $2\\frac{1}{2} \\times 1{,}6 - \\frac{3}{4} \\div 0{,}25$ adalah ...",
    choices: [
      { id: "a", label: "1", score: 5 },
      { id: "b", label: "1,5", score: 0 },
      { id: "c", label: "2", score: 0 },
      { id: "d", label: "2,5", score: 0 },
      { id: "e", label: "3", score: 0 },
    ],
    explanation: "Operasi Hitung Campuran Pecahan dan Desimal:\nSelesaikan masing-masing perkalian dan pembagian terlebih dahulu:\n1. Bagian perkalian:\n   $$2\\frac{1}{2} \\times 1{,}6 = 2{,}5 \\times 1{,}6 = 4$$\n2. Bagian pembagian:\n   $$\\frac{3}{4} \\div 0{,}25 = \\frac{3}{4} \\div \\frac{1}{4} = \\frac{3}{4} \\times 4 = 3$$\n3. Operasi pengurangan:\n   $$4 - 3 = 1$$\nJawaban yang tepat adalah 1 (Opsi A).",
  },
  {
    id: "mini-tiu7-15",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Sebuah kemeja kerja berlabel harga Rp200.000,00 mendapat diskon bertingkat sebesar $20\\% + 10\\%$. Berapakah harga yang harus dibayar pembeli di kasir?",
    choices: [
      { id: "a", label: "Rp130.000,00", score: 0 },
      { id: "b", label: "Rp136.000,00", score: 0 },
      { id: "c", label: "Rp138.000,00", score: 0 },
      { id: "d", label: "Rp140.000,00", score: 0 },
      { id: "e", label: "Rp144.000,00", score: 5 },
    ],
    explanation: "Perhitungan Diskon Bertingkat (Bukan Penjumlahan Langsung):\n- Tahap 1: Diskon pertama sebesar 20%\n  $$\\text{Harga setelah diskon 1} = (100\\% - 20\\%) \\times 200.000 = 80\\% \\times 200.000 = 160.000$$\n- Tahap 2: Diskon kedua sebesar 10% dihitung dari harga tahap 1\n  $$\\text{Harga akhir} = (100\\% - 10\\%) \\times 160.000 = 90\\% \\times 160.000 = 144.000$$\nJadi, harga yang harus dibayar adalah Rp144.000,00 (Opsi E).",
  },
  {
    id: "mini-tiu7-16",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Seorang pedagang menjual suatu perangkat elektronik dengan harga Rp540.000,00 dan memperoleh keuntungan sebesar $20\\%$ dari harga pembelian. Berapakah harga beli perangkat tersebut?",
    choices: [
      { id: "a", label: "Rp420.000,00", score: 0 },
      { id: "b", label: "Rp450.000,00", score: 5 },
      { id: "c", label: "Rp460.000,00", score: 0 },
      { id: "d", label: "Rp480.000,00", score: 0 },
      { id: "e", label: "Rp500.000,00", score: 0 },
    ],
    explanation: "Perhitungan Aritmetika Sosial Persentase Keuntungan:\nRumus harga penjualan dengan untung $20\\%$:\n$$\\text{Harga Jual} = \\text{Harga Beli} + (20\\% \\times \\text{Harga Beli}) = 120\\% \\times \\text{Harga Beli}$$\n$$540.000 = 1{,}2 \\times \\text{Harga Beli}$$\n$$\\text{Harga Beli} = \\frac{540.000}{1{,}2} = \\frac{5.400.000}{12} = 450.000$$\nMaka harga beli perangkat elektronik tersebut adalah Rp450.000,00 (Opsi B).",
  },
  {
    id: "mini-tiu7-17",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Nilai rata-rata tes integritas dari 15 pegawai pria adalah 76, sedangkan nilai rata-rata dari 25 pegawai wanita adalah 84. Berapakah nilai rata-rata keseluruhan dari 40 pegawai tersebut?",
    choices: [
      { id: "a", label: "79", score: 0 },
      { id: "b", label: "80", score: 0 },
      { id: "c", label: "81", score: 5 },
      { id: "d", label: "82", score: 0 },
      { id: "e", label: "83", score: 0 },
    ],
    explanation: "Perhitungan Rata-rata Gabungan:\n$$\\bar{x}_{\\text{gab}} = \\frac{n_1 \\cdot \\bar{x}_1 + n_2 \\cdot \\bar{x}_2}{n_1 + n_2}$$\n- Total nilai pria: $15 \\times 76 = 1.140$\n- Total nilai wanita: $25 \\times 84 = 2.100$\n- Jumlah total nilai: $1.140 + 2.100 = 3.240$\n- Jumlah seluruh pegawai: $15 + 25 = 40$\n$$\\bar{x}_{\\text{gab}} = \\frac{3.240}{40} = 81$$\nNilai rata-rata keseluruhan adalah 81 (Opsi C).",
  },
  {
    id: "mini-tiu7-18",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Alokasi anggaran suatu unit kerja dibagi untuk tiga pos: Operasional, Pelatihan, dan Publikasi dengan perbandingan $3 : 4 : 5$. Jika anggaran untuk pos Pelatihan adalah Rp36.000.000,00, maka selisih anggaran antara pos Publikasi dan Operasional adalah ...",
    choices: [
      { id: "a", label: "Rp9.000.000,00", score: 0 },
      { id: "b", label: "Rp12.000.000,00", score: 0 },
      { id: "c", label: "Rp15.000.000,00", score: 0 },
      { id: "d", label: "Rp18.000.000,00", score: 5 },
      { id: "e", label: "Rp24.000.000,00", score: 0 },
    ],
    explanation: "Perhitungan Perbandingan Rasio Bagian:\n- Rasio Operasional : Pelatihan : Publikasi = $3 : 4 : 5$.\n- Anggaran Pelatihan memiliki 4 bagian senilai Rp36.000.000,00.\n  $$\\text{Nilai } 1 \\text{ bagian} = \\frac{36.000.000}{4} = 9.000.000$$\n- Selisih antara Publikasi (5 bagian) dan Operasional (3 bagian):\n  $$\\text{Selisih bagian} = 5 - 3 = 2 \\text{ bagian}$$\n  $$\\text{Selisih anggaran} = 2 \\times 9.000.000 = 18.000.000$$\nSelisih anggarannya adalah Rp18.000.000,00 (Opsi D).",
  },
  {
    id: "mini-tiu7-19",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "Angka berikutnya dari barisan bilangan $4, 7, 12, 19, 28, \\dots$ adalah ...",
    choices: [
      { id: "a", label: "39", score: 5 },
      { id: "b", label: "40", score: 0 },
      { id: "c", label: "41", score: 0 },
      { id: "d", label: "42", score: 0 },
      { id: "e", label: "43", score: 0 },
    ],
    explanation: "Analisis Deret Aritmetika Bertingkat Dua:\nLihat pola selisih antarsuku yang berdekatan:\n- $4 \\xrightarrow{+3} 7$\n- $7 \\xrightarrow{+5} 12$\n- $12 \\xrightarrow{+7} 19$\n- $19 \\xrightarrow{+9} 28$\nSelisih penambahan membentuk barisan bilangan ganjil ($+3, +5, +7, +9, \\dots$), sehingga penambahan berikutnya adalah $+11$:\n$$28 + 11 = 39$$\nJawaban yang tepat adalah 39 (Opsi A).",
  },
  {
    id: "mini-tiu7-20",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "Angka berikutnya dari deret $3, 6, 4, 8, 6, 12, 10, \\dots$ adalah ...",
    choices: [
      { id: "a", label: "14", score: 0 },
      { id: "b", label: "16", score: 0 },
      { id: "c", label: "18", score: 0 },
      { id: "d", label: "19", score: 0 },
      { id: "e", label: "20", score: 5 },
    ],
    explanation: "Analisis Pola Operasi Bergantian (Selang-Seling):\nPerhatikan relasi antarsuku yang berurutan:\n- $3 \\times 2 = 6$\n- $6 - 2 = 4$\n- $4 \\times 2 = 8$\n- $8 - 2 = 6$\n- $6 \\times 2 = 12$\n- $12 - 2 = 10$\nPola yang berulang adalah $(\\times 2)$ kemudian $(- 2)$. Langkah selanjutnya adalah dikalikan 2:\n$$10 \\times 2 = 20$$\nJawaban yang tepat adalah 20 (Opsi E).",
  },
  {
    id: "mini-tiu7-21",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "Angka yang tepat untuk melengkapi deret $5, 18, 9, 15, 13, 12, 17, \\dots$ adalah ...",
    choices: [
      { id: "a", label: "8", score: 0 },
      { id: "b", label: "9", score: 5 },
      { id: "c", label: "10", score: 0 },
      { id: "d", label: "21", score: 0 },
      { id: "e", label: "22", score: 0 },
    ],
    explanation: "Analisis Deret Dua Larik (Dua Pola Melompat Satu Suku):\n- Larik 1 (suku bernomor ganjil: suku 1, 3, 5, 7):\n  $5 \\xrightarrow{+4} 9 \\xrightarrow{+4} 13 \\xrightarrow{+4} 17$ (bertambah 4)\n- Larik 2 (suku bernomor genap: suku 2, 4, 6, 8):\n  $18 \\xrightarrow{-3} 15 \\xrightarrow{-3} 12 \\xrightarrow{-3} X$ (berkurang 3)\nSuku yang dicari berada pada urutan ke-8 (bagian dari Larik 2):\n$$X = 12 - 3 = 9$$\nJawaban yang tepat adalah 9 (Opsi B).",
  },
  {
    id: "mini-tiu7-22",
    category: "TIU",
    topic: "Deret & Pola",
    prompt: "Huruf berikutnya dari barisan huruf B, D, G, K, P, ... adalah ...",
    choices: [
      { id: "a", label: "T", score: 0 },
      { id: "b", label: "U", score: 0 },
      { id: "c", label: "V", score: 5 },
      { id: "d", label: "W", score: 0 },
      { id: "e", label: "X", score: 0 },
    ],
    explanation: "Konversi Posisi Huruf ke Urutan Alfabet:\n- B = 2\n- D = 4 ($2 + 2$)\n- G = 7 ($4 + 3$)\n- K = 11 ($7 + 4$)\n- P = 16 ($11 + 5$)\nPola lompatan huruf bertambah 1 secara berurutan: $+2, +3, +4, +5, \\dots$\nMaka lompatan berikutnya adalah $+6$:\n$$16 + 6 = 22$$\nHuruf pada urutan ke-22 dalam alfabet adalah V. Jawaban yang tepat adalah V (Opsi C).",
  },
  {
    id: "mini-tiu7-23",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Sebuah proyek pemeliharaan gedung direncanakan selesai dalam waktu 30 hari oleh 12 orang pekerja. Setelah dikerjakan selama 10 hari, pekerjaan terhenti selama 5 hari karena kendala cuaca. Berapakah tambahan pekerja yang dibutuhkan agar proyek dapat selesai tepat waktu sesuai jadwal semula?",
    choices: [
      { id: "a", label: "4 orang", score: 5 },
      { id: "b", label: "5 orang", score: 0 },
      { id: "c", label: "6 orang", score: 0 },
      { id: "d", label: "8 orang", score: 0 },
      { id: "e", label: "10 orang", score: 0 },
    ],
    explanation: "Perhitungan Perbandingan Berbalik Nilai Pekerja dan Waktu:\n- Sisa waktu rencana normal: $30 - 10 = 20$ hari dengan 12 pekerja.\n- Beban kerja yang tersisa:\n  $$\\text{Beban} = 20 \\times 12 = 240 \\text{ orang-hari}$$\n- Waktu riil yang tersisa setelah libur 5 hari:\n  $$\\text{Waktu sisa} = 20 - 5 = 15 \\text{ hari}$$\n- Jumlah pekerja yang dibutuhkan agar selesai dalam 15 hari:\n  $$\\text{Pekerja total} = \\frac{240}{15} = 16 \\text{ orang}$$\n- Tambahan pekerja yang harus didatangkan:\n  $$\\text{Tambahan} = 16 - 12 = 4 \\text{ orang}$$\nJawaban yang tepat adalah 4 orang (Opsi A).",
  },
  {
    id: "mini-tiu7-24",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Jarak antara kota P dan kota Q adalah 180 km. Ari berangkat dari kota P menuju kota Q pada pukul 08.00 dengan kecepatan rata-rata 40 km/jam. Pada saat yang bersamaan, Bagas berangkat dari kota Q menuju kota P melalui rute yang sama dengan kecepatan rata-rata 50 km/jam. Pada pukul berapa mereka akan berpapasan di jalan?",
    choices: [
      { id: "a", label: "09.30", score: 0 },
      { id: "b", label: "09.45", score: 0 },
      { id: "c", label: "09.50", score: 0 },
      { id: "d", label: "10.00", score: 5 },
      { id: "e", label: "10.15", score: 0 },
    ],
    explanation: "Perhitungan Waktu Berpapasan (Arah Berlawanan Waktu Bersamaan):\n- Jarak total ($s$) = 180 km.\n- Kecepatan relatif total ($v_1 + v_2$) = $40 + 50 = 90$ km/jam.\n- Waktu tempuh hingga berpapasan:\n  $$t = \\frac{s}{v_1 + v_2} = \\frac{180}{90} = 2 \\text{ jam}$$\n- Waktu mereka berpapasan:\n  $$08.00 + 2 \\text{ jam} = 10.00$$\nJawaban yang tepat adalah 10.00 (Opsi D).",
  },
  {
    id: "mini-tiu7-25",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Sebuah bak penampungan air dapat diisi penuh oleh pipa saluran A saja dalam waktu 6 jam, atau oleh pipa saluran B saja dalam waktu 3 jam. Jika kedua pipa saluran tersebut dibuka secara bersamaan, berapa jam waktu yang dibutuhkan untuk mengisi bak penampungan tersebut hingga penuh?",
    choices: [
      { id: "a", label: "1,5 jam", score: 0 },
      { id: "b", label: "2 jam", score: 5 },
      { id: "c", label: "2,5 jam", score: 0 },
      { id: "d", label: "4 jam", score: 0 },
      { id: "e", label: "4,5 jam", score: 0 },
    ],
    explanation: "Perhitungan Debit Pengisian Bersama:\n- Laju pengisian pipa A dalam 1 jam = $\\frac{1}{6}$ bagian.\n- Laju pengisian pipa B dalam 1 jam = $\\frac{1}{3}$ bagian.\n- Laju pengisian gabungan kedua pipa dalam 1 jam:\n  $$\\frac{1}{t_{\\text{gab}}} = \\frac{1}{6} + \\frac{1}{3} = \\frac{1}{6} + \\frac{2}{6} = \\frac{3}{6} = \\frac{1}{2}$$\n- Waktu yang dibutuhkan untuk memenuhi bak:\n  $$t_{\\text{gab}} = 2 \\text{ jam}$$\nJawaban yang tepat adalah 2 jam (Opsi B).",
  },
  {
    id: "mini-tiu7-26",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Panjang sebuah lahan persegi panjang bertambah sebesar $25\\%$, sedangkan lebarnya berkurang sebesar $20\\%$. Persentase perubahan luas lahan persegi panjang tersebut dibandingkan dengan luas semula adalah ...",
    choices: [
      { id: "a", label: "Bertambah 5%", score: 0 },
      { id: "b", label: "Berkurang 5%", score: 0 },
      { id: "c", label: "Bertambah 2%", score: 0 },
      { id: "d", label: "Berkurang 2%", score: 0 },
      { id: "e", label: "Tetap (tidak berubah)", score: 5 },
    ],
    explanation: "Perhitungan Persentase Perubahan Luas Bangun Datar:\n- Misalkan panjang awal $= p$ dan lebar awal $= l$. Luas awal $L_1 = p \\times l$.\n- Panjang baru ($p_2$) = $p + 25\\% p = 1{,}25p = \\frac{5}{4}p$.\n- Lebar baru ($l_2$) = $l - 20\\% l = 0{,}80l = \\frac{4}{5}l$.\n- Luas baru ($L_2$):\n  $$L_2 = p_2 \\times l_2 = \\left(\\frac{5}{4}p\\right) \\times \\left(\\frac{4}{5}l\\right) = \\frac{20}{20}(p \\times l) = 1 \\times L_1 = L_1$$\nKarena $L_2 = L_1$, maka luas lahan tersebut tidak mengalami perubahan (tetap / 0% perubahan). Jawaban yang tepat adalah Opsi E.",
  },
  {
    id: "mini-tiu7-27",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Diketahui persamaan linear satu variabel $4x - 5 = 2x + 7$.\n$$P = x$$\n$$Q = 4$$\nManakah hubungan yang benar antara kuantitas $P$ dan $Q$?",
    choices: [
      { id: "a", label: "P > Q", score: 5 },
      { id: "b", label: "P < Q", score: 0 },
      { id: "c", label: "P = Q", score: 0 },
      { id: "d", label: "2P = 3Q", score: 0 },
      { id: "e", label: "Hubungan P dan Q tidak dapat ditentukan", score: 0 },
    ],
    explanation: "Penyelesaian Persamaan Linear Satu Variabel:\n$$4x - 5 = 2x + 7$$\n$$4x - 2x = 7 + 5$$\n$$2x = 12 \\implies x = 6$$\nDiperoleh nilai kuantitas:\n$$P = 6$$\n$$Q = 4$$\nKarena $6 > 4$, maka hubungan yang benar adalah $P > Q$ (Opsi A).",
  },
  {
    id: "mini-tiu7-28",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Pak Anton dapat menyelesaikan pengecatan pagar sebuah rumah dinas dalam waktu 12 hari. Pak Budi dapat menyelesaikan pengecatan pagar yang sama dalam waktu 8 hari.\n$$P = \\text{Waktu yang dibutuhkan Pak Anton untuk menyelesaikan } \\frac{1}{3} \\text{ bagian pagar}$$\n$$Q = \\text{Waktu yang dibutuhkan Pak Budi untuk menyelesaikan } \\frac{3}{4} \\text{ bagian pagar}$$\nManakah hubungan yang benar antara kuantitas $P$ dan $Q$?",
    choices: [
      { id: "a", label: "P > Q", score: 0 },
      { id: "b", label: "P < Q", score: 5 },
      { id: "c", label: "P = Q", score: 0 },
      { id: "d", label: "P + Q = 11", score: 0 },
      { id: "e", label: "Hubungan P dan Q tidak dapat ditentukan", score: 0 },
    ],
    explanation: "Perhitungan Nilai Masing-Masing Kuantitas:\n- Kuantitas $P$ (Waktu Pak Anton):\n  $$P = \\frac{1}{3} \\times 12 \\text{ hari} = 4 \\text{ hari}$$\n- Kuantitas $Q$ (Waktu Pak Budi):\n  $$Q = \\frac{3}{4} \\times 8 \\text{ hari} = 6 \\text{ hari}$$\nKarena $4 < 6$, maka $P < Q$ (Opsi B).",
  },
  {
    id: "mini-tiu7-29",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Diketahui dua nilai pecahan:\n$$P = \\frac{3}{8} \\times 64$$\n$$Q = 0{,}75 \\times 32$$\nManakah hubungan yang benar antara kuantitas $P$ dan $Q$?",
    choices: [
      { id: "a", label: "P > Q", score: 0 },
      { id: "b", label: "P < Q", score: 0 },
      { id: "c", label: "P = Q", score: 5 },
      { id: "d", label: "P - Q = 2", score: 0 },
      { id: "e", label: "Hubungan P dan Q tidak dapat ditentukan", score: 0 },
    ],
    explanation: "Perhitungan Perbandingan Dua Kuantitas:\n- Hitung nilai $P$:\n  $$P = \\frac{3}{8} \\times 64 = 3 \\times 8 = 24$$\n- Hitung nilai $Q$:\n  $$Q = 0{,}75 \\times 32 = \\frac{3}{4} \\times 32 = 3 \\times 8 = 24$$\nKarena $24 = 24$, maka hubungan yang benar adalah $P = Q$ (Opsi C).",
  },
  {
    id: "mini-tiu7-30",
    category: "TIU",
    topic: "Kemampuan Numerik",
    prompt: "Diketahui $a, b,$ dan $c$ adalah bilangan bulat positif yang memenuhi persamaan $a + b + c = 30$.\n$$P = a \\times b$$\n$$Q = 100$$\nManakah hubungan yang benar antara kuantitas $P$ dan $Q$?",
    choices: [
      { id: "a", label: "P > Q", score: 0 },
      { id: "b", label: "P < Q", score: 0 },
      { id: "c", label: "P = Q", score: 0 },
      { id: "d", label: "P + Q = 200", score: 0 },
      { id: "e", label: "Hubungan P dan Q tidak dapat ditentukan", score: 5 },
    ],
    explanation: "Analisis Nilai Variabel Bebas pada Kuantitas P dan Q:\nDiketahui $a, b, c$ bilangan bulat positif dengan $a + b + c = 30$.\n- Kasus 1: Jika $a = 10, b = 10, c = 10$, maka $P = 10 \\times 10 = 100 \\implies P = Q$.\n- Kasus 2: Jika $a = 1, b = 1, c = 28$, maka $P = 1 \\times 1 = 1 \\implies P < Q$.\n- Kasus 3: Jika $a = 14, b = 14, c = 2$, maka $P = 14 \\times 14 = 196 \\implies P > Q$.\nKarena nilai $P$ dapat bernilai lebih kecil, sama dengan, maupun lebih besar dari $Q$ tergantung pemilihan nilai $(a, b)$, maka hubungan antara kuantitas $P$ dan $Q$ tidak dapat ditentukan dari informasi yang diberikan. Jawaban yang tepat adalah Opsi E.",
  },
  {
    id: "mini-tiu7-31",
    category: "TIU",
    topic: "Figural",
    prompt: `[svg]<div style="margin-bottom:12px;font-size:15px;font-weight:600;color:#1e293b;">Perhatikan analogi perubahan bentuk gambar berikut:</div><div style="display:flex;align-items:center;justify-content:center;gap:12px;margin:12px 0;"><div style="border:1.5px solid #334155;padding:6px;background:white;display:flex;align-items:center;gap:6px;"><span style="font-weight:bold;font-size:12px;">A</span><svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" viewBox="0 0 60 60"><circle cx="30" cy="30" r="24" fill="none" stroke="black" stroke-width="2"/><polygon points="30,12 42,38 18,38" fill="black"/></svg></div><span style="font-weight:bold;font-size:18px;">:</span><div style="border:1.5px solid #334155;padding:6px;background:white;display:flex;align-items:center;gap:6px;"><span style="font-weight:bold;font-size:12px;">B</span><svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" viewBox="0 0 60 60"><rect x="8" y="8" width="44" height="44" fill="none" stroke="black" stroke-width="2"/><polygon points="48,30 22,42 22,18" fill="none" stroke="black" stroke-width="2"/></svg></div><span style="font-weight:bold;font-size:18px;">=</span><div style="border:1.5px solid #334155;padding:6px;background:white;display:flex;align-items:center;gap:6px;"><span style="font-weight:bold;font-size:12px;">C</span><svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" viewBox="0 0 60 60"><rect x="8" y="8" width="44" height="44" fill="none" stroke="black" stroke-width="2"/><line x1="30" y1="12" x2="30" y2="48" stroke="black" stroke-width="3"/><polygon points="30,12 24,24 36,24" fill="black"/></svg></div><span style="font-weight:bold;font-size:18px;">:</span><div style="border:2px dashed #64748b;padding:6px;background:#f1f5f9;width:72px;height:72px;display:flex;align-items:center;justify-content:center;font-weight:bold;font-size:24px;color:#2563eb;">?</div></div><div style="margin-top:10px;font-size:14px;color:#334155;">Gambar yang tepat untuk menggantikan tanda tanya (?) adalah ...</div>`,
    choices: [
      {
        id: "a",
        label: `[svg]<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60" style="width:60px;height:60px;display:block"><polygon points="30,8 52,24 44,50 16,50 8,24" fill="none" stroke="black" stroke-width="2"/><line x1="12" y1="30" x2="48" y2="30" stroke="black" stroke-width="2"/><polygon points="48,30 36,24 36,36" fill="none" stroke="black" stroke-width="1.5"/></svg>`,
        score: 5,
      },
      {
        id: "b",
        label: `[svg]<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60" style="width:60px;height:60px;display:block"><rect x="8" y="8" width="44" height="44" fill="none" stroke="black" stroke-width="2"/><line x1="12" y1="30" x2="48" y2="30" stroke="black" stroke-width="2"/><polygon points="48,30 36,24 36,36" fill="black"/></svg>`,
        score: 0,
      },
      {
        id: "c",
        label: `[svg]<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60" style="width:60px;height:60px;display:block"><circle cx="30" cy="30" r="24" fill="none" stroke="black" stroke-width="2"/><line x1="30" y1="12" x2="30" y2="48" stroke="black" stroke-width="2"/><polygon points="30,48 24,36 36,36" fill="none" stroke="black" stroke-width="1.5"/></svg>`,
        score: 0,
      },
      {
        id: "d",
        label: `[svg]<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60" style="width:60px;height:60px;display:block"><polygon points="30,8 52,24 44,50 16,50 8,24" fill="none" stroke="black" stroke-width="2"/><line x1="30" y1="12" x2="30" y2="48" stroke="black" stroke-width="3"/><polygon points="30,48 24,36 36,36" fill="black"/></svg>`,
        score: 0,
      },
      {
        id: "e",
        label: `[svg]<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60" style="width:60px;height:60px;display:block"><polygon points="30,6 54,18 54,42 30,54 6,42 6,18" fill="none" stroke="black" stroke-width="2"/><line x1="12" y1="30" x2="48" y2="30" stroke="black" stroke-width="2"/><polygon points="12,30 24,24 24,36" fill="none" stroke="black" stroke-width="1.5"/></svg>`,
        score: 0,
      },
    ],
    explanation: "Analisis Pola Transformasi Figural Analogi (A : B = C : D):\n1. Bingkai luar: Dari lingkaran (kurva tak bersudut) menjadi persegi (segi-4, bertambah jumlah sisi). Maka dari persegi (segi-4 pada C) harus bertambah 1 sisi menjadi segi-5 (pentagon beraturan).\n2. Elemen dalam: Mengalami rotasi $90^\\circ$ searah jarum jam (panah mengarah ke atas berotasi menjadi mengarah ke kanan).\n3. Inversi isian (arsir): Elemen hitam pekat berubah menjadi putih bergaris luar (inversi arsir).\nKombinasi pentagon berbingkai garis + panah rotasi mengarah ke kanan berwarna putih bergaris secara sempurna dipenuhi oleh Opsi A.",
  },
  {
    id: "mini-tiu7-32",
    category: "TIU",
    topic: "Figural",
    prompt: `[svg]<div style="margin-bottom:12px;font-size:15px;font-weight:600;color:#1e293b;">Perhatikan kelanjutan pola serial pergerakan elemen berikut:</div><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 450 90" style="width:100%;max-width:520px;display:block;margin:auto;"><g><rect x="4" y="4" width="76" height="76" fill="white" stroke="#334155" stroke-width="1.5" rx="3"/><circle cx="42" cy="42" r="30" fill="none" stroke="black" stroke-width="1.5"/><circle cx="42" cy="18" r="4" fill="black"/><line x1="42" y1="42" x2="42" y2="24" stroke="black" stroke-width="2"/><text x="42" y="86" text-anchor="middle" font-size="10" font-family="sans-serif" font-weight="bold">(1)</text></g><g><rect x="94" y="4" width="76" height="76" fill="white" stroke="#334155" stroke-width="1.5" rx="3"/><circle cx="132" cy="42" r="30" fill="none" stroke="black" stroke-width="1.5"/><circle cx="153" cy="21" r="4" fill="black"/><line x1="132" y1="42" x2="153" y2="63" stroke="black" stroke-width="2"/><text x="132" y="86" text-anchor="middle" font-size="10" font-family="sans-serif" font-weight="bold">(2)</text></g><g><rect x="184" y="4" width="76" height="76" fill="white" stroke="#334155" stroke-width="1.5" rx="3"/><circle cx="222" cy="42" r="30" fill="none" stroke="black" stroke-width="1.5"/><circle cx="246" cy="42" r="4" fill="black"/><line x1="222" y1="42" x2="201" y2="63" stroke="black" stroke-width="2"/><text x="222" y="86" text-anchor="middle" font-size="10" font-family="sans-serif" font-weight="bold">(3)</text></g><g><rect x="274" y="4" width="76" height="76" fill="white" stroke="#334155" stroke-width="1.5" rx="3"/><circle cx="312" cy="42" r="30" fill="none" stroke="black" stroke-width="1.5"/><circle cx="333" cy="63" r="4" fill="black"/><line x1="312" y1="42" x2="288" y2="42" stroke="black" stroke-width="2"/><text x="312" y="86" text-anchor="middle" font-size="10" font-family="sans-serif" font-weight="bold">(4)</text></g><g><rect x="364" y="4" width="76" height="76" fill="white" stroke="#334155" stroke-width="1.5" rx="3"/><text x="402" y="52" text-anchor="middle" font-size="36" font-family="sans-serif" font-weight="bold" fill="#94a3b8">?</text><text x="402" y="86" text-anchor="middle" font-size="10" font-family="sans-serif" font-weight="bold">(5)</text></g></svg><div style="margin-top:10px;font-size:14px;color:#334155;">Gambar ke-5 yang logis untuk melanjutkan pola di atas adalah ...</div>`,
    choices: [
      {
        id: "a",
        label: `[svg]<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60" style="width:60px;height:60px;display:block"><circle cx="30" cy="30" r="26" fill="none" stroke="black" stroke-width="1.5"/><circle cx="30" cy="50" r="4" fill="black"/><line x1="30" y1="30" x2="30" y2="10" stroke="black" stroke-width="2"/></svg>`,
        score: 0,
      },
      {
        id: "b",
        label: `[svg]<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60" style="width:60px;height:60px;display:block"><circle cx="30" cy="30" r="26" fill="none" stroke="black" stroke-width="1.5"/><circle cx="16" cy="44" r="4" fill="black"/><line x1="30" y1="30" x2="44" y2="16" stroke="black" stroke-width="2"/></svg>`,
        score: 0,
      },
      {
        id: "c",
        label: `[svg]<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60" style="width:60px;height:60px;display:block"><circle cx="30" cy="30" r="26" fill="none" stroke="black" stroke-width="1.5"/><circle cx="10" cy="30" r="4" fill="black"/><line x1="30" y1="30" x2="44" y2="44" stroke="black" stroke-width="2"/></svg>`,
        score: 0,
      },
      {
        id: "d",
        label: `[svg]<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60" style="width:60px;height:60px;display:block"><circle cx="30" cy="30" r="26" fill="none" stroke="black" stroke-width="1.5"/><circle cx="30" cy="50" r="4" fill="black"/><line x1="30" y1="30" x2="44" y2="16" stroke="black" stroke-width="2"/></svg>`,
        score: 5,
      },
      {
        id: "e",
        label: `[svg]<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60" style="width:60px;height:60px;display:block"><circle cx="30" cy="30" r="26" fill="none" stroke="black" stroke-width="1.5"/><circle cx="30" cy="10" r="4" fill="black"/><line x1="30" y1="30" x2="16" y2="16" stroke="black" stroke-width="2"/></svg>`,
        score: 0,
      },
    ],
    explanation: "Analisis Serial Figural Dua Elemen Independen:\n1. Titik hitam di tepi lingkaran: Berputar searah jarum jam sejauh $45^\\circ$ setiap langkah:\n   - Posisi 1: Atas ($0^\\circ$)\n   - Posisi 2: Kanan-Atas ($45^\\circ$)\n   - Posisi 3: Kanan ($90^\\circ$)\n   - Posisi 4: Kanan-Bawah ($135^\\circ$)\n   - Posisi 5: Bawah tepat ($180^\\circ$, koordinat $x=30, y=50$).\n2. Jarum garis pusat: Berputar searah jarum jam dengan sudut bertambah bertahap:\n   - Dari langkah 1 ke 2: $+135^\\circ$ (dari jam 12 ke jam 4.30)\n   - Dari langkah 2 ke 3: $+90^\\circ$ (dari jam 4.30 ke jam 7.30)\n   - Dari langkah 3 ke 4: $+45^\\circ$ (dari jam 7.30 ke jam 9.00)\n   - Dari langkah 4 ke 5: Mengulang putaran $+135^\\circ$ dari jam 9.00 ($270^\\circ$) menghasilkan arah jam 1.30 ($45^\\circ$, mengarah ke kanan-atas).\nKombinasi titik hitam tepat di bawah ($x=30, y=50$) dan jarum mengarah ke kanan-atas ditunjukkan secara tepat oleh Opsi D.",
  },
  {
    id: "mini-tiu7-33",
    category: "TIU",
    topic: "Figural",
    prompt: `[svg]<div style="margin-bottom:12px;font-size:15px;font-weight:600;color:#1e293b;">Pilihlah satu gambar yang TIDAK SESUAI (berbeda kelompok / memiliki karakteristik ganjil) dibandingkan dengan empat gambar lainnya:</div><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 450 90" style="width:100%;max-width:520px;display:block;margin:auto;"><g><rect x="4" y="4" width="76" height="76" fill="white" stroke="#334155" stroke-width="1.5" rx="3"/><polygon points="42,16 68,64 16,64" fill="none" stroke="black" stroke-width="2"/><circle cx="42" cy="32" r="3.5" fill="black"/><circle cx="30" cy="54" r="3.5" fill="black"/><circle cx="54" cy="54" r="3.5" fill="black"/><text x="42" y="86" text-anchor="middle" font-size="10" font-family="sans-serif" font-weight="bold">A</text></g><g><rect x="94" y="4" width="76" height="76" fill="white" stroke="#334155" stroke-width="1.5" rx="3"/><rect x="112" y="20" width="40" height="40" fill="none" stroke="black" stroke-width="2"/><circle cx="122" cy="30" r="3.5" fill="black"/><circle cx="142" cy="30" r="3.5" fill="black"/><circle cx="122" cy="50" r="3.5" fill="black"/><circle cx="142" cy="50" r="3.5" fill="black"/><text x="132" y="86" text-anchor="middle" font-size="10" font-family="sans-serif" font-weight="bold">B</text></g><g><rect x="184" y="4" width="76" height="76" fill="white" stroke="#334155" stroke-width="1.5" rx="3"/><polygon points="222,14 246,32 237,62 207,62 198,32" fill="none" stroke="black" stroke-width="2"/><circle cx="222" cy="28" r="3.5" fill="black"/><circle cx="210" cy="44" r="3.5" fill="black"/><circle cx="234" cy="44" r="3.5" fill="black"/><circle cx="222" cy="54" r="3.5" fill="black"/><text x="222" y="86" text-anchor="middle" font-size="10" font-family="sans-serif" font-weight="bold">C</text></g><g><rect x="274" y="4" width="76" height="76" fill="white" stroke="#334155" stroke-width="1.5" rx="3"/><polygon points="312,14 336,28 336,54 312,68 288,54 288,28" fill="none" stroke="black" stroke-width="2"/><circle cx="300" cy="32" r="3" fill="black"/><circle cx="324" cy="32" r="3" fill="black"/><circle cx="296" cy="41" r="3" fill="black"/><circle cx="328" cy="41" r="3" fill="black"/><circle cx="300" cy="50" r="3.5" fill="black"/><circle cx="324" cy="50" r="3.5" fill="black"/><text x="312" y="86" text-anchor="middle" font-size="10" font-family="sans-serif" font-weight="bold">D</text></g><g><rect x="364" y="4" width="76" height="76" fill="white" stroke="#334155" stroke-width="1.5" rx="3"/><polygon points="402,14 420,20 428,36 422,54 410,64 394,64 382,54 376,36 384,20" fill="none" stroke="black" stroke-width="2"/><circle cx="402" cy="24" r="2.5" fill="black"/><circle cx="414" cy="30" r="2.5" fill="black"/><circle cx="390" cy="30" r="2.5" fill="black"/><circle cx="416" cy="44" r="2.5" fill="black"/><circle cx="388" cy="44" r="2.5" fill="black"/><circle cx="410" cy="56" r="2.5" fill="black"/><circle cx="394" cy="56" r="2.5" fill="black"/><text x="402" y="86" text-anchor="middle" font-size="10" font-family="sans-serif" font-weight="bold">E</text></g></svg>`,
    choices: [
      { id: "a", label: "Gambar A", score: 0 },
      { id: "b", label: "Gambar B", score: 0 },
      { id: "c", label: "Gambar C", score: 5 },
      { id: "d", label: "Gambar D", score: 0 },
      { id: "e", label: "Gambar E", score: 0 },
    ],
    explanation: "Analisis Ketidaksamaan Pola Figural (Odd One Out):\nPerhatikan relasi antara jumlah sisi poligon terluar dengan jumlah titik hitam di dalamnya:\n- Gambar A: Poligon luar segitiga (3 sisi), terdapat 3 titik hitam (Sama).\n- Gambar B: Poligon luar persegi (4 sisi), terdapat 4 titik hitam (Sama).\n- Gambar C: Poligon luar pentagon (5 sisi), namun hanya terdapat 4 titik hitam (TIDAK SAMA / Ganjil).\n- Gambar D: Poligon luar heksagon (6 sisi), terdapat 6 titik hitam (Sama).\n- Gambar E: Poligon luar heptagon (7 sisi), terdapat 7 titik hitam (Sama).\nSatu-satunya gambar yang menyimpang dari aturan kesetaraan jumlah sisi dan jumlah titik adalah Gambar C (Opsi C).",
  },
  {
    id: "mini-tiu7-34",
    category: "TIU",
    topic: "Figural",
    prompt: `[svg]<div style="margin-bottom:12px;font-size:15px;font-weight:600;color:#1e293b;">Perhatikan matriks gambar 9 kotak (3 × 3) berikut:</div><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 180 180" style="width:180px;height:180px;display:block;margin:auto;"><rect x="2" y="2" width="176" height="176" fill="#f8fafc" stroke="#334155" stroke-width="2" rx="4"/><line x1="60" y1="2" x2="60" y2="178" stroke="#cbd5e1" stroke-width="1.5"/><line x1="120" y1="2" x2="120" y2="178" stroke="#cbd5e1" stroke-width="1.5"/><line x1="2" y1="60" x2="178" y2="60" stroke="#cbd5e1" stroke-width="1.5"/><line x1="2" y1="120" x2="178" y2="120" stroke="#cbd5e1" stroke-width="1.5"/><line x1="10" y1="30" x2="50" y2="30" stroke="black" stroke-width="2"/><line x1="90" y1="10" x2="90" y2="50" stroke="black" stroke-width="2"/><g><line x1="130" y1="30" x2="170" y2="30" stroke="black" stroke-width="2"/><line x1="150" y1="10" x2="150" y2="50" stroke="black" stroke-width="2"/></g><line x1="10" y1="70" x2="50" y2="110" stroke="black" stroke-width="2"/><line x1="70" y1="110" x2="110" y2="70" stroke="black" stroke-width="2"/><g><line x1="130" y1="70" x2="170" y2="110" stroke="black" stroke-width="2"/><line x1="130" y1="110" x2="170" y2="70" stroke="black" stroke-width="2"/></g><circle cx="30" cy="150" r="18" fill="none" stroke="black" stroke-width="2"/><line x1="70" y1="150" x2="110" y2="150" stroke="black" stroke-width="2"/><text x="150" y="158" text-anchor="middle" font-size="28" font-family="sans-serif" font-weight="bold" fill="#2563eb">?</text></svg><div style="margin-top:10px;font-size:14px;color:#334155;">Gambar yang tepat untuk melengkapi kotak bertanda tanya (?) adalah ...</div>`,
    choices: [
      {
        id: "a",
        label: `[svg]<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60" style="width:60px;height:60px;display:block"><circle cx="30" cy="30" r="20" fill="black"/></svg>`,
        score: 0,
      },
      {
        id: "b",
        label: `[svg]<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60" style="width:60px;height:60px;display:block"><line x1="30" y1="10" x2="30" y2="50" stroke="black" stroke-width="2"/></svg>`,
        score: 0,
      },
      {
        id: "c",
        label: `[svg]<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60" style="width:60px;height:60px;display:block"><circle cx="30" cy="30" r="20" fill="none" stroke="black" stroke-width="2"/><line x1="30" y1="10" x2="30" y2="50" stroke="black" stroke-width="2"/></svg>`,
        score: 0,
      },
      {
        id: "d",
        label: `[svg]<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60" style="width:60px;height:60px;display:block"><circle cx="30" cy="30" r="20" fill="none" stroke="black" stroke-width="2"/><line x1="10" y1="30" x2="50" y2="30" stroke="black" stroke-width="2"/></svg>`,
        score: 5,
      },
      {
        id: "e",
        label: `[svg]<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60" style="width:60px;height:60px;display:block"><rect x="10" y="10" width="40" height="40" fill="none" stroke="black" stroke-width="2"/><line x1="10" y1="30" x2="50" y2="30" stroke="black" stroke-width="2"/></svg>`,
        score: 0,
      },
    ],
    explanation: "Analisis Logika Operasi Penggabungan Matriks Visual Baris:\nPerhatikan operasi dari kolom 1 dan kolom 2 pada setiap baris:\n- Baris 1: Garis horizontal (Kolom 1) + Garis vertikal (Kolom 2) = Tanda tambah (Kolom 3).\n- Baris 2: Garis diagonal kiri-kanan (Kolom 1) + Garis diagonal kanan-kiri (Kolom 2) = Tanda silang (Kolom 3).\n- Baris 3: Lingkaran hampa (Kolom 1) digabungkan dengan garis horizontal (Kolom 2) menghasilkan lingkaran hampa yang dibelah oleh garis horizontal di tengahnya.\nGambar yang tepat sesuai hasil penggabungan tersebut adalah Opsi D.",
  },
  {
    id: "mini-tiu7-35",
    category: "TIU",
    topic: "Figural",
    prompt: `[svg]<div style="margin-bottom:12px;font-size:15px;font-weight:600;color:#1e293b;">Perhatikan jaring-jaring kubus berikut:</div><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 180 135" style="width:180px;height:135px;display:block;margin:auto;"><rect x="45" y="0" width="45" height="45" fill="white" stroke="black" stroke-width="1.5"/><rect x="55" y="10" width="25" height="25" fill="black"/><rect x="0" y="45" width="45" height="45" fill="white" stroke="black" stroke-width="1.5"/><circle cx="22.5" cy="67.5" r="12" fill="none" stroke="black" stroke-width="2"/><rect x="45" y="45" width="45" height="45" fill="white" stroke="black" stroke-width="1.5"/><line x1="53" y1="53" x2="82" y2="82" stroke="black" stroke-width="2"/><line x1="53" y1="82" x2="82" y2="53" stroke="black" stroke-width="2"/><rect x="90" y="45" width="45" height="45" fill="white" stroke="black" stroke-width="1.5"/><polygon points="112.5,52 125,78 100,78" fill="black"/><rect x="135" y="45" width="45" height="45" fill="white" stroke="black" stroke-width="1.5"/><line x1="140" y1="85" x2="175" y2="50" stroke="black" stroke-width="2.5"/><rect x="45" y="90" width="45" height="45" fill="white" stroke="black" stroke-width="1.5"/><circle cx="67.5" cy="112.5" r="6" fill="black"/></svg><div style="margin-top:10px;font-size:14px;color:#334155;">Jika jaring-jaring di atas dilipat membentuk kubus pejal tiga dimensi, maka bentuk kubus yang benar dan terbentuk secara sah adalah ...</div>`,
    choices: [
      {
        id: "a",
        label: "Kubus dengan sisi depan 'Kotak Hitam' dan sisi belakang 'Titik Hitam' berada berdampingan di sisi yang sama",
        score: 0,
      },
      {
        id: "b",
        label: "Kubus dengan sisi 'Lingkaran Hampa' tepat bersebelahan langsung dengan sisi 'Garis Diagonal' serta saling menempel di rusuk yang sama",
        score: 0,
      },
      {
        id: "c",
        label: "Kubus dengan sisi depan 'Tanda Silang' bersebelahan langsung dengan sisi 'Segitiga Hitam' dan saling berhadapan tanpa rusuk temu",
        score: 0,
      },
      {
        id: "d",
        label: "Kubus dengan sisi atas 'Kotak Hitam' yang saling menutupi berlawanan arah tepat di hadapan sisi 'Tanda Silang'",
        score: 0,
      },
      {
        id: "e",
        label: "Kubus dengan sisi depan 'Tanda Silang', sisi atas 'Kotak Hitam', dan sisi kanan 'Segitiga Hitam'",
        score: 5,
      },
    ],
    explanation: "Analisis Jaring-Jaring Kubus 3 Dimensi:\n1. Tentukan pasangan sisi yang saling berhadapan (tidak akan pernah bersebelahan):\n   - Sisi Atas (Kotak Hitam) berhadapan dengan Sisi Bawah (Titik Hitam).\n   - Sisi Kiri (Lingkaran Hampa) berhadapan dengan Sisi Tengah-Kanan (Segitiga Hitam).\n   - Sisi Tengah-Kiri (Tanda Silang) berhadapan dengan Sisi Paling Kanan (Garis Diagonal).\n2. Menguji opsi pilihan:\n   - Opsi A salah: Kotak Hitam dan Titik Hitam saling berhadapan, tidak bisa berdampingan.\n   - Opsi B salah: Lingkaran Hampa berhadapan dengan Segitiga Hitam, bukan bersebelahan pada rusuk yang sama dengan Garis Diagonal secara langsung terlipat.\n   - Opsi C salah: Tanda Silang dan Segitiga Hitam bertetangga (bersebelahan), bukan saling berhadapan.\n   - Opsi D salah: Kotak Hitam berhadapan dengan Titik Hitam, bukan Tanda Silang.\n   - Opsi E benar: Tiga sisi yang saling bertetangga dan bertemu pada satu titik sudut adalah Sisi Tengah-Kiri (Tanda Silang sebagai sisi depan), Sisi Atas (Kotak Hitam sebagai sisi atas), dan Sisi Tengah-Kanan (Segitiga Hitam sebagai sisi kanan). Ketiganya tidak ada yang saling berhadapan dan orientasinya tepat saat dilipat ke dalam. Jawaban yang tepat adalah Opsi E.",
  },
];
