import type { Question } from "./types";

export const PILAR_NEGARA_1_DRILL_QUESTIONS: Question[] = [
  {
    id: "pilar-negara-1-01",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Seorang ASN ditugaskan memberikan sosialisasi program pemerintah kepada masyarakat di daerah yang memiliki struktur sosial dan kebiasaan budaya berbeda dengan daerah asalnya. Sebelum menyampaikan materi, ia mempelajari karakteristik masyarakat setempat agar cara penyampaiannya tidak menyinggung nilai budaya yang mereka pegang. Namun, ia tetap memastikan bahwa substansi program pemerintah disampaikan sesuai ketentuan. Sikap tersebut menunjukkan ....",
    choices: [
      { id: "a", label: "Penyesuaian terhadap budaya lokal dengan tetap menjaga kepentingan dan ketentuan nasional.", score: 5 },
      { id: "b", label: "Pengutamaan budaya lokal karena komunikasi dengan masyarakat harus mengikuti seluruh kebiasaan daerah.", score: 0 },
      { id: "c", label: "Penyeragaman komunikasi pemerintahan karena seluruh masyarakat harus menerima informasi dengan cara yang sama.", score: 0 },
      { id: "d", label: "Pembatasan nilai budaya lokal agar pelaksanaan program pemerintah dapat berjalan lebih cepat.", score: 0 },
      { id: "e", label: "Pemisahan pendekatan pelayanan berdasarkan daerah agar setiap masyarakat memperoleh aturan yang berbeda.", score: 0 },
    ],
    explanation: "Pembahasan: Sikap tersebut sesuai dengan semangat Bhinneka Tunggal Ika karena ASN menghargai karakteristik budaya masyarakat tanpa mengubah substansi aturan yang berlaku secara nasional. Keberagaman membutuhkan kemampuan menyesuaikan cara berkomunikasi, tetapi penyesuaian tersebut tidak berarti mengubah ketentuan yang harus dilaksanakan. Pilihan B terlalu mengutamakan budaya lokal, C mengarah pada penyeragaman, D membatasi keberagaman, sedangkan E dapat menimbulkan perbedaan perlakuan dalam pelayanan. Jadi, pilihan A paling tepat.",
  },
  {
    id: "pilar-negara-1-02",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Pemerintah daerah menerima laporan bahwa program bantuan pendidikan belum sepenuhnya menjangkau siswa dari keluarga kurang mampu. Setelah dilakukan evaluasi, ditemukan bahwa sebagian penerima bantuan sebelumnya ditentukan berdasarkan data lama sehingga terdapat keluarga yang kondisi ekonominya sudah berubah. Pada saat yang sama, terdapat siswa lain yang baru mengalami kesulitan ekonomi tetapi belum masuk dalam daftar penerima. Jika Anda menjadi bagian dari tim evaluasi, tindakan yang paling mencerminkan implementasi Pancasila adalah ....",
    choices: [
      { id: "a", label: "Mempertahankan daftar penerima yang ada agar proses penyaluran bantuan tidak terganggu dan tidak menimbulkan keberatan dari penerima sebelumnya.", score: 0 },
      { id: "b", label: "Melakukan verifikasi dan memperbarui data penerima berdasarkan kondisi nyata agar bantuan diberikan secara tepat sasaran dan adil.", score: 5 },
      { id: "c", label: "Membagi bantuan secara merata kepada seluruh siswa agar tidak ada pihak yang merasa memperoleh perlakuan berbeda.", score: 0 },
      { id: "d", label: "Mengutamakan siswa yang lebih dahulu terdaftar karena mereka telah melalui proses administrasi sesuai ketentuan sebelumnya.", score: 0 },
      { id: "e", label: "Menyerahkan penentuan penerima kepada pihak sekolah karena sekolah dianggap paling mengetahui kondisi seluruh siswanya.", score: 0 },
    ],
    explanation: "Pembahasan: Kasus tersebut merupakan penerapan sila kelima, Keadilan Sosial bagi Seluruh Rakyat Indonesia, karena persoalan utamanya berkaitan dengan pemerataan hak dan ketepatan pemberian bantuan berdasarkan kondisi yang sebenarnya. Keadilan tidak selalu berarti memberikan bantuan dengan jumlah yang sama kepada semua orang, tetapi memastikan bantuan diberikan kepada pihak yang memenuhi kriteria dan paling membutuhkan melalui mekanisme yang objektif. Pilihan A dan D mempertahankan data lama meskipun sudah tidak sesuai, C menyamakan perlakuan tanpa mempertimbangkan kebutuhan, sedangkan E dapat dilakukan sebagai bagian dari verifikasi tetapi tidak berarti seluruh keputusan dapat diserahkan tanpa mekanisme yang jelas. Jadi, pilihan B paling tepat karena mengutamakan ketepatan sasaran, objektivitas, dan keadilan dalam distribusi bantuan.",
  },
  {
    id: "pilar-negara-1-03",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Indonesia memiliki wilayah geografis yang sangat luas dengan kondisi masyarakat dan sumber daya alam yang berbeda-beda. Dalam penyusunan kebijakan nasional, pemerintah perlu mempertimbangkan karakteristik daerah tanpa mengurangi kesatuan sistem pemerintahan. Pendekatan yang paling mencerminkan prinsip NKRI adalah ....",
    choices: [
      { id: "a", label: "Menetapkan kebijakan yang sama secara mutlak di seluruh daerah agar tidak terdapat perbedaan dalam penyelenggaraan pemerintahan.", score: 0 },
      { id: "b", label: "Memberikan kebebasan penuh kepada daerah untuk menentukan kebijakan karena setiap daerah memiliki kebutuhan yang berbeda.", score: 0 },
      { id: "c", label: "Mengembangkan kebijakan yang mempertimbangkan karakteristik daerah tetapi tetap berlandaskan kepentingan nasional dan kerangka hukum yang sama.", score: 5 },
      { id: "d", label: "Mengutamakan daerah yang memiliki sumber daya strategis karena wilayah tersebut memberikan kontribusi lebih besar kepada negara.", score: 0 },
      { id: "e", label: "Menyerahkan sebagian besar urusan nasional kepada daerah agar pemerintah pusat dapat berkonsentrasi pada hubungan luar negeri.", score: 0 },
    ],
    explanation: "Pembahasan: Prinsip NKRI memungkinkan adanya pengaturan yang memperhatikan karakteristik setiap daerah tanpa menghilangkan kesatuan penyelenggaraan negara. Perbedaan kondisi daerah justru membutuhkan kebijakan yang adaptif, tetapi tetap berada dalam kerangka hukum dan kepentingan nasional. Pilihan A terlalu menyeragamkan, B dan E terlalu memberikan kewenangan luas kepada daerah, sedangkan D berpotensi menciptakan ketimpangan perlakuan. Jadi, pilihan C paling tepat.",
  },
  {
    id: "pilar-negara-1-04",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Sebuah organisasi kepemudaan mengadakan kegiatan yang diikuti oleh anggota dari berbagai suku dan agama. Saat menentukan jenis kegiatan, muncul usulan yang sangat dipengaruhi oleh tradisi kelompok tertentu. Sebagian anggota khawatir kegiatan tersebut hanya mencerminkan budaya kelompok tertentu sehingga anggota lainnya merasa kurang dilibatkan. Ketua organisasi kemudian mengajak seluruh anggota mencari bentuk kegiatan yang dapat memperkenalkan keberagaman budaya sekaligus tetap dapat diikuti oleh seluruh anggota. Sikap tersebut menunjukkan ....",
    choices: [
      { id: "a", label: "Upaya menghilangkan perbedaan budaya agar seluruh anggota memiliki identitas organisasi yang sama.", score: 0 },
      { id: "b", label: "Penerapan toleransi dengan memberikan kesempatan kepada kelompok mayoritas untuk menentukan bentuk kegiatan.", score: 0 },
      { id: "c", label: "Pengutamaan kepentingan organisasi dengan membatasi unsur budaya yang dianggap berpotensi menimbulkan perbedaan.", score: 0 },
      { id: "d", label: "Penerapan Bhinneka Tunggal Ika melalui penghargaan terhadap keberagaman tanpa menghilangkan rasa kebersamaan.", score: 5 },
      { id: "e", label: "Penerapan persatuan dengan meminta setiap kelompok meninggalkan tradisi masing-masing selama kegiatan organisasi.", score: 0 },
    ],
    explanation: "Pembahasan: Bhinneka Tunggal Ika bukan berarti menghapus perbedaan, melainkan membangun persatuan di tengah keberagaman. Dalam kasus tersebut, upaya memperkenalkan berbagai budaya sekaligus mencari bentuk kegiatan yang dapat diikuti bersama menunjukkan bahwa keberagaman dipandang sebagai bagian dari kehidupan organisasi, bukan sebagai sesuatu yang harus diseragamkan. Pilihan A dan E mengarah pada penghilangan identitas budaya, B memberikan ruang dominan kepada mayoritas, sedangkan C justru membatasi unsur keberagaman. Jadi, pilihan D paling tepat.",
  },
  {
    id: "pilar-negara-1-05",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam sebuah forum warga, muncul perbedaan pendapat mengenai penggunaan dana lingkungan. Sebagian warga mengusulkan dana digunakan untuk memperbaiki fasilitas olahraga, sedangkan warga lainnya menganggap perbaikan saluran air lebih mendesak. Ketua forum tidak langsung menentukan keputusan, tetapi memberikan kesempatan kepada setiap kelompok untuk menjelaskan alasan dan kemudian mengajak warga mencari keputusan yang dapat diterima bersama. Simbol Pancasila yang paling sesuai dengan sikap tersebut adalah ....",
    choices: [
      { id: "a", label: "Kepala banteng, karena menggambarkan kehidupan demokratis yang mengutamakan musyawarah dalam mengambil keputusan.", score: 5 },
      { id: "b", label: "Pohon beringin, karena menggambarkan berbagai kelompok masyarakat yang hidup bersama dalam satu lingkungan.", score: 0 },
      { id: "c", label: "Padi dan kapas, karena keputusan penggunaan dana harus diarahkan untuk meningkatkan kesejahteraan masyarakat.", score: 0 },
      { id: "d", label: "Rantai, karena setiap warga memiliki hubungan yang saling membutuhkan dalam kehidupan bermasyarakat.", score: 0 },
      { id: "e", label: "Bintang, karena setiap warga memiliki kebebasan untuk menyampaikan pandangan berdasarkan keyakinannya.", score: 0 },
    ],
    explanation: "Pembahasan: Simbol kepala banteng merupakan simbol sila keempat, yaitu Kerakyatan yang Dipimpin oleh Hikmat Kebijaksanaan dalam Permusyawaratan/Perwakilan. Banteng menggambarkan kehidupan bersama dan semangat berkumpul untuk membahas persoalan serta mengambil keputusan melalui musyawarah. Dalam kasus tersebut, ketua forum tidak memaksakan kehendak, melainkan memberikan ruang bagi warga untuk menyampaikan pendapat dan mencari keputusan bersama. Pohon beringin lebih menekankan persatuan, padi dan kapas keadilan sosial, rantai kemanusiaan, sedangkan bintang ketuhanan. Jadi, jawaban yang tepat adalah A.",
  },
  {
    id: "pilar-negara-1-06",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Sebuah daerah perbatasan memiliki kondisi geografis yang sulit dijangkau dan masyarakatnya menghadapi keterbatasan akses pendidikan, kesehatan, serta infrastruktur. Sebagian masyarakat mengusulkan agar pengelolaan wilayah tersebut lebih banyak dilakukan secara mandiri karena pemerintah pusat dianggap kurang memahami kondisi lokal. Dalam perspektif NKRI, kebijakan yang paling tepat adalah ....",
    choices: [
      { id: "a", label: "Memberikan kewenangan yang lebih luas kepada masyarakat perbatasan agar mereka dapat menentukan arah pembangunan tanpa banyak campur tangan pemerintah pusat.", score: 0 },
      { id: "b", label: "Meningkatkan kehadiran negara melalui pelayanan dan pembangunan yang sesuai kebutuhan daerah sekaligus memperkuat integrasi wilayah perbatasan dengan NKRI.", score: 5 },
      { id: "c", label: "Memprioritaskan pembangunan wilayah yang memiliki jumlah penduduk lebih besar karena sumber daya negara harus digunakan secara efisien.", score: 0 },
      { id: "d", label: "Menyerahkan pembangunan perbatasan kepada pemerintah daerah sepenuhnya karena kondisi wilayah lebih mudah dipahami oleh pemerintah setempat.", score: 0 },
      { id: "e", label: "Mengutamakan pembangunan pusat pemerintahan terlebih dahulu agar pengawasan wilayah perbatasan dapat dilakukan setelah fasilitas utama tersedia.", score: 0 },
    ],
    explanation: "Pembahasan: Wilayah perbatasan merupakan bagian integral dari NKRI sehingga kehadiran negara tidak hanya diwujudkan melalui aspek keamanan, tetapi juga melalui pembangunan dan pelayanan masyarakat. Penguatan wilayah perbatasan dapat menjaga integrasi nasional sekaligus meningkatkan kesejahteraan masyarakat. Pilihan A dan D terlalu menyerahkan tanggung jawab kepada daerah, C mengabaikan kebutuhan strategis wilayah perbatasan, sedangkan E tidak menjawab persoalan utama masyarakat. Jadi, pilihan B paling tepat karena menggabungkan pembangunan, pelayanan, dan penguatan integrasi wilayah.",
  },
  {
    id: "pilar-negara-1-07",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Sebuah instansi pemerintah membuka seleksi untuk mengisi jabatan tertentu. Dalam prosesnya, terdapat calon yang memiliki kompetensi sesuai persyaratan, tetapi salah satu pejabat mengusulkan agar calon tersebut tidak dipilih karena berasal dari daerah yang berbeda. Menurut pejabat tersebut, pegawai yang berasal dari daerah setempat akan lebih mudah menyesuaikan diri. Jika dikaitkan dengan UUD 1945, tindakan yang paling tepat adalah ....",
    choices: [
      { id: "a", label: "Mempertimbangkan asal daerah calon selama keputusan tersebut dapat membantu menjaga kekompakan lingkungan kerja.", score: 0 },
      { id: "b", label: "Memberikan kesempatan yang sama kepada calon berdasarkan persyaratan dan kompetensi tanpa membedakan latar belakang daerah.", score: 5 },
      { id: "c", label: "Mengutamakan calon dari daerah setempat karena pemerintah memiliki kewenangan menentukan pegawai sesuai kebutuhan organisasi.", score: 0 },
      { id: "d", label: "Menempatkan calon berdasarkan kesesuaian budaya daerah agar proses adaptasi dalam lingkungan kerja dapat berlangsung lebih cepat.", score: 0 },
      { id: "e", label: "Menyerahkan keputusan kepada pimpinan karena penentuan pegawai merupakan kewenangan pejabat yang bertanggung jawab.", score: 0 },
    ],
    explanation: "Pembahasan: Kasus tersebut berkaitan dengan prinsip persamaan kedudukan warga negara dalam hukum dan pemerintahan sebagaimana Pasal 27 ayat (1) UUD 1945. Dalam proses seleksi, seseorang tidak seharusnya dibedakan hanya berdasarkan asal daerah apabila persyaratan dan kompetensinya telah terpenuhi. Pilihan A, C, dan D memberikan ruang bagi pertimbangan identitas daerah sebagai dasar perlakuan berbeda, sedangkan E menyerahkan persoalan kepada kewenangan pimpinan tanpa mempertimbangkan prinsip kesetaraan. Jadi, pilihan B paling tepat karena menerapkan prinsip kesamaan kedudukan warga negara.",
  },
  {
    id: "pilar-negara-1-08",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Di sebuah lingkungan perumahan, warga berasal dari berbagai daerah dan memiliki kebiasaan yang berbeda dalam melaksanakan kegiatan sosial. Ketika akan mengadakan kerja bakti, sebagian warga mengusulkan waktu yang sesuai dengan kebiasaan kelompok mereka, sedangkan warga lainnya memiliki pertimbangan berbeda. Ketua RT kemudian mengajak warga mendiskusikan waktu yang memungkinkan sebanyak mungkin warga berpartisipasi. Prinsip Bhinneka Tunggal Ika yang tercermin dalam tindakan tersebut adalah ....",
    choices: [
      { id: "a", label: "Menyeragamkan kebiasaan masyarakat agar seluruh warga mengikuti pola yang telah ditetapkan bersama.", score: 0 },
      { id: "b", label: "Mengutamakan kebiasaan kelompok yang paling banyak jumlahnya karena dianggap mewakili masyarakat.", score: 0 },
      { id: "c", label: "Menghargai perbedaan kondisi warga dan mencari titik temu untuk kepentingan bersama.", score: 5 },
      { id: "d", label: "Membebaskan setiap kelompok melaksanakan kegiatan sendiri agar perbedaan kepentingan tidak menimbulkan konflik.", score: 0 },
      { id: "e", label: "Menentukan jadwal berdasarkan keputusan ketua RT karena persatuan membutuhkan satu keputusan yang harus diikuti seluruh warga.", score: 0 },
    ],
    explanation: "Pembahasan: Prinsip Bhinneka Tunggal Ika tercermin ketika masyarakat mampu mempertahankan kebersamaan meskipun memiliki kebiasaan dan kepentingan yang berbeda. Ketua RT tidak menyeragamkan kebiasaan ataupun sekadar mengikuti kelompok mayoritas, tetapi mencari titik temu agar kegiatan dapat dilaksanakan secara inklusif. Pilihan A dan B cenderung mengutamakan keseragaman atau mayoritas, D justru memisahkan kelompok, sedangkan E terlalu menekankan keputusan sepihak. Jadi, pilihan C paling tepat karena menunjukkan kemampuan mengelola keberagaman untuk mencapai kepentingan bersama.",
  },
  {
    id: "pilar-negara-1-09",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam suatu rapat lembaga pemerintahan, seorang pejabat menyampaikan bahwa kritik terhadap kebijakan pemerintah sebaiknya dibatasi karena kritik dapat menurunkan kepercayaan masyarakat kepada pemerintah. Pejabat tersebut mengusulkan agar informasi yang dianggap dapat menimbulkan persepsi negatif tidak disampaikan kepada publik. Jika dikaitkan dengan prinsip UUD 1945, sikap yang paling tepat adalah ....",
    choices: [
      { id: "a", label: "Membatasi seluruh kritik karena stabilitas pemerintahan harus ditempatkan di atas kepentingan penyampaian pendapat masyarakat.", score: 0 },
      { id: "b", label: "Membuka seluruh informasi tanpa pengecualian karena setiap pembatasan terhadap informasi bertentangan dengan prinsip demokrasi.", score: 0 },
      { id: "c", label: "Menghargai kebebasan berpendapat dan keterbukaan informasi dengan tetap memperhatikan pembatasan yang sah berdasarkan undang-undang.", score: 5 },
      { id: "d", label: "Menyerahkan pengaturan kritik kepada pimpinan instansi agar setiap lembaga dapat menentukan batas kebebasan sesuai kebutuhan.", score: 0 },
      { id: "e", label: "Membiarkan masyarakat menyampaikan pendapat tanpa batas karena pemerintah tidak memiliki kewenangan untuk mengatur kebebasan warga negara.", score: 0 },
    ],
    explanation: "Pembahasan: UUD 1945 menjamin kebebasan menyampaikan pendapat dan memperoleh informasi, tetapi pelaksanaan hak tersebut bukan berarti tanpa batas. Pasal 28J menegaskan bahwa dalam menjalankan hak dan kebebasannya, setiap orang wajib menghormati hak orang lain serta tunduk pada pembatasan yang ditetapkan dengan undang-undang untuk tujuan tertentu. Karena itu, pilihan A terlalu membatasi, B dan E mengabaikan adanya pembatasan konstitusional, sedangkan D menyerahkan persoalan yang seharusnya memiliki dasar hukum kepada pimpinan instansi. Jadi, pilihan C paling tepat.",
  },
  {
    id: "pilar-negara-1-10",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Pemerintah merencanakan pemanfaatan sumber daya alam strategis untuk meningkatkan penerimaan negara. Dalam pembahasannya, muncul usulan agar pengelolaan sepenuhnya diserahkan kepada perusahaan yang menawarkan keuntungan ekonomi terbesar. Sebagian pihak mengingatkan bahwa sumber daya tersebut berkaitan dengan kepentingan masyarakat luas dan harus dikelola dengan memperhatikan kepentingan nasional. Berdasarkan prinsip UUD 1945, kebijakan yang paling tepat adalah ....",
    choices: [
      { id: "a", label: "Menyerahkan pengelolaan kepada pihak yang memberikan keuntungan ekonomi terbesar karena penerimaan negara merupakan tujuan utama pengelolaan sumber daya.", score: 0 },
      { id: "b", label: "Menyerahkan pengelolaan kepada pemerintah daerah karena sumber daya tersebut berada di wilayah administrasi daerah tertentu.", score: 0 },
      { id: "c", label: "Mengelola sumber daya untuk sebesar-besar kemakmuran rakyat dengan tetap memperhatikan kepentingan nasional dan ketentuan hukum yang berlaku.", score: 5 },
      { id: "d", label: "Membagikan seluruh hasil sumber daya secara merata kepada setiap warga agar tidak terjadi perbedaan manfaat di masyarakat.", score: 0 },
      { id: "e", label: "Menghentikan pemanfaatan sumber daya alam agar tidak terjadi kemungkinan penyalahgunaan oleh pihak yang mengelolanya.", score: 0 },
    ],
    explanation: "Pembahasan: Kasus tersebut berkaitan dengan Pasal 33 ayat (3) UUD 1945, yang menegaskan bahwa bumi, air, dan kekayaan alam yang terkandung di dalamnya dikuasai oleh negara dan dipergunakan untuk sebesar-besar kemakmuran rakyat. Artinya, pertimbangan pengelolaan tidak cukup hanya berdasarkan keuntungan ekonomi terbesar, tetapi harus diarahkan pada kepentingan dan kemakmuran rakyat sesuai ketentuan hukum. Pilihan A terlalu berorientasi pada keuntungan, B mengabaikan dimensi kepentingan nasional, D menyamakan pembagian tanpa mempertimbangkan mekanisme pengelolaan, sedangkan E menghilangkan manfaat sumber daya secara keseluruhan. Jadi, pilihan C paling tepat.",
  },
];

export const PILAR_NEGARA_2_DRILL_QUESTIONS: Question[] = [
  {
    id: "pilar-negara-2-01",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Seorang pegawai menemukan bahwa seorang warga yang sedang mengurus dokumen pelayanan diperlakukan secara berbeda karena kondisi ekonominya. Petugas lain menganggap warga tersebut kurang memiliki kemampuan untuk menyampaikan keberatan sehingga tidak perlu diberikan penjelasan secara lengkap. Pegawai tersebut kemudian mengingatkan bahwa setiap masyarakat harus diperlakukan secara manusiawi, diberikan informasi yang layak, dan dihormati tanpa membedakan status sosialnya. Simbol Pancasila yang paling tepat menggambarkan sikap tersebut adalah ....",
    choices: [
      { id: "a", label: "Bintang, karena setiap manusia memiliki kewajiban menjalankan kehidupan berdasarkan nilai ketuhanan.", score: 0 },
      { id: "b", label: "Pohon beringin, karena setiap masyarakat harus ditempatkan sebagai bagian dari satu kesatuan bangsa.", score: 0 },
      { id: "c", label: "Kepala banteng, karena masyarakat memiliki hak untuk menyampaikan pendapat dalam kehidupan demokratis.", score: 0 },
      { id: "d", label: "Padi dan kapas, karena setiap masyarakat berhak memperoleh kesejahteraan dari negara.", score: 0 },
      { id: "e", label: "Rantai, karena menggambarkan hubungan antarmanusia yang saling menghargai dan memperlakukan secara beradab.", score: 5 },
    ],
    explanation: "Pembahasan: Simbol rantai merupakan simbol sila kedua, Kemanusiaan yang Adil dan Beradab. Rantai menggambarkan hubungan antarmanusia yang saling berkaitan serta perlunya memperlakukan setiap manusia dengan adil, bermartabat, dan beradab. Dalam kasus tersebut, tindakan membedakan pelayanan berdasarkan kondisi ekonomi bertentangan dengan penghormatan terhadap martabat manusia. Bintang berkaitan dengan ketuhanan, pohon beringin dengan persatuan, kepala banteng dengan musyawarah, dan padi kapas dengan keadilan sosial. Jadi, jawaban yang tepat adalah E.",
  },
  {
    id: "pilar-negara-2-02",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam sebuah rapat organisasi mahasiswa, terjadi perbedaan pendapat mengenai program kerja yang akan dilaksanakan. Sebagian peserta menginginkan kegiatan berskala besar, sedangkan kelompok lainnya mengusulkan kegiatan yang lebih sederhana karena mempertimbangkan keterbatasan anggaran. Perdebatan berlangsung cukup panjang dan masing-masing kelompok mempertahankan pendapatnya. Ketua rapat kemudian memberikan kesempatan kepada setiap kelompok untuk menyampaikan alasan sebelum dilakukan pembahasan bersama. Sikap tersebut merupakan implementasi terutama dari ....",
    choices: [
      { id: "a", label: "Sila pertama karena setiap peserta memiliki kebebasan untuk menyampaikan pandangan berdasarkan keyakinannya masing-masing.", score: 0 },
      { id: "b", label: "Sila kedua karena setiap peserta memperoleh perlakuan yang sama selama mengikuti proses pembahasan.", score: 0 },
      { id: "c", label: "Sila ketiga karena perbedaan pendapat harus diselesaikan dengan mengutamakan kepentingan organisasi.", score: 0 },
      { id: "d", label: "Sila keempat karena keputusan diupayakan melalui proses pembahasan dan pertimbangan bersama.", score: 5 },
      { id: "e", label: "Sila kelima karena keputusan harus menghasilkan pembagian manfaat yang sama bagi seluruh peserta.", score: 0 },
    ],
    explanation: "Pembahasan: Kasus tersebut paling tepat mencerminkan implementasi sila keempat Pancasila, yaitu Kerakyatan yang Dipimpin oleh Hikmat Kebijaksanaan dalam Permusyawaratan/Perwakilan. Hal utama yang ditonjolkan dalam kasus adalah adanya perbedaan pendapat yang kemudian diselesaikan melalui kesempatan menyampaikan pandangan dan pembahasan bersama sebelum mengambil keputusan. Pilihan A lebih berkaitan dengan kebebasan menjalankan keyakinan, pilihan B menekankan nilai kemanusiaan, pilihan C memang berkaitan dengan persatuan tetapi bukan inti mekanisme penyelesaian masalah dalam kasus, sedangkan pilihan E lebih menekankan aspek keadilan sosial. Jadi, jawaban yang tepat adalah D.",
  },
  {
    id: "pilar-negara-2-03",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam suatu kegiatan pelayanan publik, seorang petugas menghadapi masyarakat yang menggunakan bahasa daerah ketika menjelaskan permasalahannya. Petugas tersebut sebenarnya tidak memahami seluruh istilah yang digunakan. Beberapa rekan menyarankan agar masyarakat tersebut diminta menggunakan bahasa Indonesia secara langsung agar pelayanan lebih cepat. Namun, petugas memahami bahwa sebagian masyarakat mungkin memiliki keterbatasan dalam menggunakan bahasa Indonesia secara formal. Tindakan yang paling mencerminkan Bhinneka Tunggal Ika adalah ....",
    choices: [
      { id: "a", label: "Meminta masyarakat menggunakan bahasa Indonesia sepenuhnya karena pelayanan pemerintah harus menggunakan bahasa yang sama.", score: 0 },
      { id: "b", label: "Tetap memberikan pelayanan dengan mencari cara komunikasi yang dapat dipahami bersama tanpa merendahkan latar belakang bahasa masyarakat.", score: 5 },
      { id: "c", label: "Meminta masyarakat membawa anggota keluarga yang dapat menerjemahkan agar petugas tidak perlu menyesuaikan cara berkomunikasi.", score: 0 },
      { id: "d", label: "Mengutamakan masyarakat yang mampu menggunakan bahasa Indonesia dengan baik agar pelayanan dapat berlangsung lebih efisien.", score: 0 },
      { id: "e", label: "Menyerahkan masyarakat tersebut kepada petugas lain yang berasal dari daerah yang sama agar proses komunikasi lebih mudah.", score: 0 },
    ],
    explanation: "Pembahasan: Bhinneka Tunggal Ika menuntut kemampuan hidup bersama dalam keberagaman, termasuk keberagaman bahasa dan latar belakang masyarakat. Dalam pelayanan publik, penggunaan bahasa Indonesia tetap penting, tetapi petugas perlu mencari cara komunikasi yang efektif tanpa merendahkan masyarakat karena keterbatasan bahasa. Pilihan A terlalu kaku, C memindahkan tanggung jawab pelayanan, D berpotensi menciptakan perlakuan berbeda, sedangkan E dapat menjadi solusi teknis dalam kondisi tertentu tetapi tidak secara langsung menunjukkan sikap inklusif yang diperlukan. Jadi, pilihan B paling tepat karena pelayanan tetap diberikan dengan menghargai keberagaman masyarakat.",
  },
  {
    id: "pilar-negara-2-04",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam sebuah diskusi mengenai pembangunan nasional, seorang peserta menyampaikan bahwa pembangunan seharusnya lebih dahulu dipusatkan di wilayah yang sudah maju karena daerah tersebut memiliki potensi ekonomi yang lebih besar. Peserta lain mengingatkan bahwa ketimpangan antarwilayah dapat memengaruhi rasa keadilan dan keterikatan masyarakat terhadap negara. Kebijakan yang paling sesuai dengan prinsip menjaga keutuhan NKRI adalah ....",
    choices: [
      { id: "a", label: "Memusatkan pembangunan di wilayah dengan potensi ekonomi terbesar agar pertumbuhan nasional dapat dicapai dalam waktu lebih cepat.", score: 0 },
      { id: "b", label: "Mengembangkan seluruh wilayah dengan mempertimbangkan kebutuhan, potensi, dan kondisi masing-masing agar manfaat pembangunan dapat dirasakan secara lebih merata.", score: 5 },
      { id: "c", label: "Memberikan prioritas pembangunan kepada wilayah yang paling banyak memberikan kontribusi terhadap pendapatan negara.", score: 0 },
      { id: "d", label: "Menyerahkan penentuan prioritas pembangunan kepada masing-masing pemerintah daerah karena kebutuhan pembangunan bersifat lokal.", score: 0 },
      { id: "e", label: "Menyamakan jenis dan jumlah pembangunan di setiap daerah agar tidak muncul perbedaan perlakuan antarwilayah.", score: 0 },
    ],
    explanation: "Pembahasan: Keutuhan NKRI tidak hanya berkaitan dengan batas wilayah dan pemerintahan, tetapi juga dengan kemampuan negara membangun keterikatan masyarakat melalui kesejahteraan dan pemerataan pembangunan. Setiap daerah memiliki kondisi berbeda sehingga pembangunan tidak harus identik, tetapi perlu mempertimbangkan kebutuhan dan karakteristik masing-masing wilayah. Pilihan A dan C berpotensi memperlebar ketimpangan, D terlalu menyerahkan persoalan kepada daerah, sedangkan E menyamakan pembangunan tanpa mempertimbangkan perbedaan kondisi. Jadi, pilihan B paling tepat.",
  },
  {
    id: "pilar-negara-2-05",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Di media sosial, beredar sebuah unggahan yang membandingkan dua kelompok masyarakat berdasarkan suku dan menyatakan bahwa salah satu kelompok lebih unggul daripada kelompok lainnya. Unggahan tersebut kemudian memicu komentar yang saling merendahkan. Seorang pengguna media sosial ingin menerapkan nilai Bhinneka Tunggal Ika dalam menghadapi situasi tersebut. Tindakan yang paling tepat adalah ....",
    choices: [
      { id: "a", label: "Membalas unggahan tersebut dengan menunjukkan keunggulan kelompok lain agar terjadi keseimbangan dalam perdebatan.", score: 0 },
      { id: "b", label: "Membagikan unggahan tersebut agar masyarakat mengetahui adanya perbedaan pandangan antar kelompok.", score: 0 },
      { id: "c", label: "Menghindari seluruh pembicaraan mengenai suku agar perbedaan tidak lagi muncul dalam interaksi masyarakat.", score: 0 },
      { id: "d", label: "Mengingatkan pentingnya menghargai keberagaman serta menghindari penyebaran konten yang merendahkan kelompok tertentu.", score: 5 },
      { id: "e", label: "Membela kelompok yang dianggap dirugikan dengan menggunakan argumen yang sama kerasnya agar pihak lain memahami kesalahannya.", score: 0 },
    ],
    explanation: "Pembahasan: Bhinneka Tunggal Ika menghendaki keberagaman menjadi dasar untuk membangun persatuan, bukan alasan untuk merendahkan kelompok lain. Dalam situasi media sosial, tindakan yang tepat adalah tidak memperkuat konten yang berpotensi menimbulkan permusuhan serta mengingatkan pentingnya penghormatan terhadap keberagaman. Pilihan A dan E justru berpotensi memperpanjang konflik, B dapat memperluas penyebaran konten yang bermasalah, sedangkan C bukan solusi karena keberagaman tidak dapat dihilangkan hanya dengan menghindari pembicaraan. Jadi, pilihan D paling tepat.",
  },
  {
    id: "pilar-negara-2-06",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Pemerintah daerah menemukan bahwa sejumlah anak usia sekolah dari keluarga kurang mampu tidak dapat mengikuti pendidikan secara optimal karena keterbatasan biaya. Pemerintah kemudian menyusun program bantuan pendidikan dengan memprioritaskan siswa yang memenuhi kriteria berdasarkan kondisi ekonomi dan kebutuhan pendidikan. Kebijakan tersebut merupakan bentuk implementasi terutama dari ....",
    choices: [
      { id: "a", label: "Hak memperoleh pekerjaan dan penghidupan yang layak karena pendidikan merupakan bagian dari persiapan seseorang memasuki dunia kerja.", score: 0 },
      { id: "b", label: "Hak mendapatkan pendidikan sebagaimana dijamin konstitusi sekaligus tanggung jawab negara dalam memastikan akses pendidikan dapat dirasakan masyarakat.", score: 5 },
      { id: "c", label: "Hak memperoleh kedudukan yang sama dalam pemerintahan karena pendidikan menentukan kesempatan seseorang menjadi aparatur negara.", score: 0 },
      { id: "d", label: "Hak atas kebebasan berserikat karena sekolah merupakan tempat membangun organisasi dan hubungan sosial antarpelajar.", score: 0 },
      { id: "e", label: "Hak memperoleh perlindungan sosial karena seluruh bantuan pemerintah pada dasarnya merupakan bentuk perlindungan terhadap masyarakat.", score: 0 },
    ],
    explanation: "Pembahasan: Kasus tersebut merupakan implementasi Pasal 31 UUD 1945 mengenai hak setiap warga negara untuk mendapatkan pendidikan. Pemberian bantuan kepada siswa yang memenuhi kriteria merupakan salah satu bentuk upaya agar keterbatasan ekonomi tidak menjadi penghalang bagi warga negara untuk memperoleh pendidikan. Pilihan A, C, D, dan E memang berkaitan dengan hak warga negara dalam bidang tertentu, tetapi bukan dasar konstitusional yang paling langsung dengan persoalan pendidikan dalam kasus tersebut. Jadi, pilihan B paling tepat.",
  },
  {
    id: "pilar-negara-2-07",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam sebuah instansi pemerintah, pegawai berasal dari berbagai daerah dengan kebiasaan, bahasa daerah, dan latar belakang budaya yang berbeda. Dalam suatu kegiatan internal, seorang pegawai mengusulkan agar seluruh pegawai menggunakan kebiasaan budaya dari kelompok mayoritas supaya komunikasi menjadi lebih mudah. Pegawai lain berpendapat bahwa perbedaan budaya tidak perlu dihilangkan selama seluruh pegawai mampu bekerja sama. Sikap yang paling sesuai dengan prinsip Bhinneka Tunggal Ika adalah ....",
    choices: [
      { id: "a", label: "Mengutamakan kebiasaan kelompok mayoritas agar seluruh pegawai memiliki pola interaksi yang seragam.", score: 0 },
      { id: "b", label: "Membatasi penggunaan budaya daerah dalam lingkungan kerja agar perbedaan tidak memengaruhi hubungan antarpegawai.", score: 0 },
      { id: "c", label: "Menghargai keberagaman budaya setiap pegawai sambil membangun kesepakatan bersama dalam menjalankan tugas organisasi.", score: 5 },
      { id: "d", label: "Memberikan kebebasan kepada setiap kelompok untuk menjalankan kebiasaannya tanpa perlu menyesuaikan dengan lingkungan kerja.", score: 0 },
      { id: "e", label: "Menetapkan satu budaya yang dianggap paling sesuai untuk digunakan bersama agar tidak terjadi perbedaan dalam organisasi.", score: 0 },
    ],
    explanation: "Pembahasan: Bhinneka Tunggal Ika mengandung prinsip bahwa keberagaman tidak harus dihilangkan untuk membangun persatuan. Perbedaan budaya, kebiasaan, dan latar belakang tetap dapat dihargai selama terdapat kesediaan untuk membangun kesepakatan dan bekerja sama dalam kepentingan bersama. Pilihan A dan E cenderung menyeragamkan budaya, B membatasi ekspresi keberagaman, sedangkan D terlalu menekankan kebebasan kelompok tanpa memperhatikan kebutuhan membangun kesepahaman dalam organisasi. Jadi, pilihan C paling tepat karena menggabungkan penghargaan terhadap keberagaman dengan kepentingan persatuan.",
  },
  {
    id: "pilar-negara-2-08",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Pemerintah daerah memperoleh kewenangan untuk mengatur berbagai urusan yang menjadi kewenangannya. Dalam pelaksanaannya, pemerintah daerah menemukan bahwa suatu kebijakan yang akan diterapkan di daerah memiliki dampak terhadap kepentingan nasional. Sebagian pihak berpendapat bahwa karena daerah memiliki kewenangan otonomi, pemerintah pusat tidak seharusnya memberikan arahan terhadap kebijakan tersebut. Sikap yang paling tepat dalam kerangka NKRI adalah ....",
    choices: [
      { id: "a", label: "Pemerintah daerah memiliki kebebasan penuh menentukan kebijakan selama mendapat dukungan masyarakat setempat dan tidak bertentangan dengan kepentingan daerah.", score: 0 },
      { id: "b", label: "Pemerintah pusat dapat mengambil alih seluruh urusan daerah apabila terdapat perbedaan kebijakan agar penyelenggaraan pemerintahan tetap seragam.", score: 0 },
      { id: "c", label: "Pemerintah daerah menjalankan otonomi dalam kerangka negara kesatuan sehingga kebijakan daerah tetap harus selaras dengan kepentingan nasional dan peraturan yang berlaku.", score: 5 },
      { id: "d", label: "Pemerintah daerah seharusnya mengutamakan kebutuhan wilayahnya karena otonomi daerah diberikan untuk memperkuat kemandirian setiap daerah.", score: 0 },
      { id: "e", label: "Pemerintah pusat dan daerah dapat menjalankan kebijakan masing-masing selama tidak terjadi konflik terbuka dalam pelaksanaan pemerintahan.", score: 0 },
    ],
    explanation: "Pembahasan: NKRI menerapkan desentralisasi melalui otonomi daerah, tetapi otonomi tersebut tidak berarti daerah berdiri sendiri di luar kerangka negara kesatuan. Kebijakan daerah tetap harus berada dalam sistem hukum nasional dan memperhatikan kepentingan nasional. Pilihan A dan D terlalu menekankan kemandirian daerah, B justru menghilangkan prinsip otonomi, sedangkan E seolah membolehkan adanya kebijakan yang berjalan sendiri-sendiri. Jadi, pilihan C paling tepat karena menempatkan otonomi daerah dalam kerangka keutuhan NKRI.",
  },
  {
    id: "pilar-negara-2-09",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam suatu diskusi mengenai masa depan Indonesia, seorang peserta menyatakan bahwa perbedaan kepentingan antara pemerintah pusat dan daerah merupakan hal yang wajar dan tidak selalu menunjukkan ancaman terhadap NKRI. Namun, peserta tersebut juga menekankan bahwa perbedaan harus diselesaikan melalui mekanisme konstitusional agar tidak berkembang menjadi konflik yang mengancam keutuhan negara. Sikap tersebut menunjukkan pemahaman bahwa ....",
    choices: [
      { id: "a", label: "Setiap perbedaan kepentingan harus dihilangkan agar keutuhan NKRI dapat dipertahankan secara permanen.", score: 0 },
      { id: "b", label: "Kepentingan daerah harus selalu mengikuti kepentingan pusat agar tidak muncul perbedaan dalam penyelenggaraan negara.", score: 0 },
      { id: "c", label: "Keutuhan NKRI dapat dijaga dengan mengelola perbedaan melalui mekanisme hukum, demokrasi, dan institusi negara yang berlaku.", score: 5 },
      { id: "d", label: "Konflik pusat dan daerah merupakan bagian dari demokrasi sehingga penyelesaiannya dapat dilakukan tanpa menggunakan mekanisme hukum.", score: 0 },
      { id: "e", label: "Pemerintah daerah dapat mengambil keputusan sendiri apabila menganggap kebijakan pusat tidak sesuai dengan kebutuhan masyarakat setempat.", score: 0 },
    ],
    explanation: "Pembahasan: NKRI tidak berarti menghilangkan seluruh perbedaan kepentingan, karena dalam negara demokratis perbedaan merupakan bagian dari proses kehidupan bernegara. Yang penting adalah perbedaan tersebut dikelola melalui mekanisme konstitusional, hukum, demokrasi, dan kelembagaan yang tersedia sehingga tidak berkembang menjadi tindakan yang mengancam keutuhan negara. Pilihan A dan B terlalu menekankan keseragaman, D mengabaikan pentingnya mekanisme hukum, sedangkan E memberikan kewenangan sepihak kepada daerah. Jadi, pilihan C paling tepat karena menunjukkan cara menjaga keutuhan NKRI melalui mekanisme negara yang sah.",
  },
  {
    id: "pilar-negara-2-10",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam proses penyusunan sebuah peraturan daerah, terdapat ketentuan yang dianggap bertentangan dengan peraturan perundang-undangan yang lebih tinggi. Sebagian anggota berpendapat bahwa peraturan tersebut tetap dapat diberlakukan karena telah disepakati oleh mayoritas anggota lembaga daerah. Berdasarkan prinsip negara hukum dalam UUD 1945, tindakan yang paling tepat adalah ....",
    choices: [
      { id: "a", label: "Tetap memberlakukan peraturan tersebut karena keputusan mayoritas merupakan dasar utama dalam pemerintahan demokratis.", score: 0 },
      { id: "b", label: "Mempertahankan peraturan tersebut selama masyarakat daerah memberikan dukungan terhadap substansi yang telah ditetapkan.", score: 0 },
      { id: "c", label: "Mengkaji dan menyesuaikan peraturan tersebut agar selaras dengan peraturan perundang-undangan yang lebih tinggi.", score: 5 },
      { id: "d", label: "Menunda seluruh kegiatan pemerintahan daerah sampai pemerintah pusat memberikan persetujuan terhadap setiap kebijakan daerah.", score: 0 },
      { id: "e", label: "Mengabaikan keberatan hukum selama penerapan peraturan tersebut dapat memberikan manfaat bagi masyarakat daerah.", score: 0 },
    ],
    explanation: "Pembahasan: UUD 1945 menegaskan bahwa Indonesia adalah negara hukum. Artinya, penyelenggaraan pemerintahan dan pembentukan peraturan harus tunduk pada hukum serta tata urutan peraturan perundang-undangan yang berlaku. Dukungan mayoritas atau manfaat suatu kebijakan tidak dapat menjadi alasan untuk mempertahankan aturan yang bertentangan dengan ketentuan yang lebih tinggi. Pilihan A, B, dan E menempatkan dukungan atau manfaat di atas prinsip hukum, sedangkan D terlalu jauh karena tidak semua kebijakan daerah harus memperoleh persetujuan pemerintah pusat. Jadi, pilihan C paling tepat.",
  },
];

export const PILAR_NEGARA_3_DRILL_QUESTIONS: Question[] = [
  {
    id: "pilar-negara-3-01",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam sebuah organisasi, anggota memiliki pandangan yang berbeda mengenai program yang akan dilaksanakan. Meskipun terdapat beberapa pendapat yang bertentangan, seluruh anggota tetap diberi kesempatan untuk menyampaikan argumentasi. Ketua organisasi tidak menggunakan kedudukannya untuk memaksakan pendapat pribadi, tetapi mengarahkan proses pembahasan hingga diperoleh keputusan yang dapat dipertanggungjawabkan bersama. Jika dikaitkan dengan simbol Pancasila, nilai yang paling dominan dalam situasi tersebut ditunjukkan oleh ....",
    choices: [
      { id: "a", label: "Rantai, karena setiap anggota memiliki kedudukan sebagai manusia yang harus dihargai dalam organisasi.", score: 0 },
      { id: "b", label: "Pohon beringin, karena perbedaan pendapat tidak boleh menyebabkan anggota terpecah dari organisasi.", score: 0 },
      { id: "c", label: "Padi dan kapas, karena keputusan organisasi seharusnya memberikan manfaat bagi seluruh anggota.", score: 0 },
      { id: "d", label: "Kepala banteng, karena keputusan ditempuh melalui musyawarah dengan mempertimbangkan berbagai pendapat.", score: 5 },
      { id: "e", label: "Bintang, karena proses pengambilan keputusan harus dilandasi nilai moral dan keyakinan terhadap Tuhan.", score: 0 },
    ],
    explanation: "Pembahasan: Simbol kepala banteng menggambarkan sila keempat Pancasila yang menekankan kerakyatan, permusyawaratan, dan pengambilan keputusan dengan kebijaksanaan. Hal yang paling menonjol dalam kasus adalah adanya kesempatan bagi setiap anggota untuk menyampaikan pendapat dan keputusan tidak ditentukan secara sepihak oleh ketua. Rantai memang berkaitan dengan penghormatan terhadap manusia, pohon beringin dengan persatuan, padi dan kapas dengan keadilan sosial, sedangkan bintang dengan ketuhanan, tetapi keseluruhan proses dalam kasus secara langsung menunjukkan prinsip musyawarah. Jadi, jawaban yang tepat adalah D.",
  },
  {
    id: "pilar-negara-3-02",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam sebuah kegiatan sosial, masyarakat menggalang bantuan untuk warga yang rumahnya mengalami kerusakan akibat bencana. Bantuan diberikan berdasarkan tingkat kebutuhan dan kondisi masing-masing keluarga. Warga yang kehilangan tempat tinggal memperoleh bantuan lebih besar dibandingkan warga yang kerusakannya relatif ringan. Meskipun jumlah bantuan berbeda, seluruh warga tetap diperlakukan secara bermartabat dan transparan. Simbol Pancasila yang paling tepat menggambarkan nilai tersebut adalah ....",
    choices: [
      { id: "a", label: "Kepala banteng, karena bantuan ditentukan melalui kesepakatan masyarakat dalam forum bersama.", score: 0 },
      { id: "b", label: "Padi dan kapas, karena menggambarkan upaya mewujudkan kesejahteraan dan keadilan sosial bagi seluruh masyarakat.", score: 5 },
      { id: "c", label: "Pohon beringin, karena seluruh masyarakat berada dalam satu kesatuan meskipun memiliki kondisi yang berbeda.", score: 0 },
      { id: "d", label: "Rantai, karena warga menunjukkan kepedulian dan hubungan kemanusiaan terhadap korban bencana.", score: 0 },
      { id: "e", label: "Bintang, karena kegiatan bantuan dilakukan dengan menjunjung nilai ketuhanan dalam kehidupan bermasyarakat.", score: 0 },
    ],
    explanation: "Pembahasan: Simbol padi dan kapas merupakan simbol sila kelima, Keadilan Sosial bagi Seluruh Rakyat Indonesia. Padi dan kapas melambangkan kebutuhan dasar serta cita-cita kesejahteraan yang harus diwujudkan secara adil. Dalam kasus tersebut, bantuan diberikan berdasarkan tingkat kebutuhan sehingga keadilan tidak dimaknai sebagai pemberian yang sama persis kepada setiap orang, tetapi sesuai kondisi dan hak masing-masing. Rantai memang berkaitan dengan kepedulian kemanusiaan, tetapi inti kasus terletak pada distribusi bantuan secara adil. Jadi, jawaban yang tepat adalah B.",
  },
  {
    id: "pilar-negara-3-03",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam sebuah diskusi kelas, seorang siswa menyampaikan pendapat mengenai kebudayaan daerahnya. Siswa lain kemudian menanggapi dengan mengatakan bahwa budaya tersebut kurang modern dibandingkan budaya yang biasa mereka kenal. Guru tidak langsung menyalahkan siswa yang memberikan komentar, tetapi mengarahkan diskusi agar peserta memahami bahwa perkembangan zaman tidak menjadi alasan untuk merendahkan kebudayaan daerah tertentu. Tindakan guru tersebut merupakan bentuk ....",
    choices: [
      { id: "a", label: "Penyeragaman budaya agar siswa memiliki pandangan yang sama mengenai kebudayaan nasional.", score: 0 },
      { id: "b", label: "Penghormatan terhadap keberagaman budaya sebagai bagian dari identitas bangsa dalam bingkai persatuan.", score: 5 },
      { id: "c", label: "Pembatasan kebebasan berpendapat karena perbedaan budaya dapat menimbulkan konflik dalam lingkungan pendidikan.", score: 0 },
      { id: "d", label: "Pengutamaan budaya tradisional dengan mengesampingkan pengaruh budaya modern dalam kehidupan masyarakat.", score: 0 },
      { id: "e", label: "Pemisahan budaya berdasarkan daerah asal agar setiap kelompok dapat mempertahankan identitasnya masing-masing.", score: 0 },
    ],
    explanation: "Pembahasan: Bhinneka Tunggal Ika menempatkan keberagaman budaya sebagai bagian dari kehidupan bangsa yang harus dihargai dalam kerangka persatuan. Menghargai budaya daerah bukan berarti menolak perkembangan zaman, melainkan mencegah adanya sikap merendahkan budaya tertentu hanya karena berbeda dari kebiasaan kelompok lain. Pilihan A dan E cenderung menghasilkan pemisahan atau penyeragaman, C tidak tepat karena inti persoalannya bukan membatasi pendapat, sedangkan D terlalu mempertentangkan budaya tradisional dengan modern. Jadi, pilihan B paling sesuai dengan prinsip Bhinneka Tunggal Ika.",
  },
  {
    id: "pilar-negara-3-04",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam suatu lingkungan kerja, terjadi perselisihan antara dua kelompok pegawai akibat perbedaan cara pandang mengenai pelaksanaan suatu program. Perselisihan tersebut mulai memengaruhi komunikasi dan membuat beberapa pegawai hanya berinteraksi dengan kelompoknya sendiri. Kondisi ini kemudian diketahui oleh pimpinan. Jika ingin menerapkan nilai Pancasila dalam menyelesaikan permasalahan tersebut, langkah yang paling tepat adalah ....",
    choices: [
      { id: "a", label: "Meminta setiap kelompok menjalankan programnya masing-masing agar konflik tidak semakin berkembang selama target pekerjaan tetap tercapai.", score: 0 },
      { id: "b", label: "Menentukan kelompok yang pendapatnya paling sesuai dengan kepentingan organisasi kemudian meminta kelompok lainnya mengikuti keputusan tersebut.", score: 0 },
      { id: "c", label: "Memfasilitasi dialog antarkelompok untuk mencari titik temu dan mengarahkan seluruh pegawai kembali pada kepentingan bersama.", score: 5 },
      { id: "d", label: "Membatasi komunikasi antarpegawai yang sedang berselisih sampai masing-masing pihak dapat menyelesaikan persoalannya secara mandiri.", score: 0 },
      { id: "e", label: "Memberikan kewenangan kepada kelompok yang lebih senior untuk menentukan penyelesaian karena dianggap memiliki pengalaman yang lebih banyak.", score: 0 },
    ],
    explanation: "Pembahasan: Tindakan tersebut paling kuat mencerminkan sila ketiga, Persatuan Indonesia, karena inti persoalan adalah munculnya perpecahan akibat perbedaan kepentingan dan cara pandang. Persatuan bukan berarti menghilangkan perbedaan, tetapi mengelola perbedaan dengan menempatkan kepentingan bersama di atas kepentingan kelompok. Pilihan A dan D justru mempertahankan jarak antarkelompok, B berpotensi menciptakan dominasi satu pihak, sedangkan E memberikan keistimewaan berdasarkan senioritas. Jadi, pilihan C paling tepat karena dialog dan pencarian titik temu dapat memperkuat kembali persatuan tanpa mengabaikan adanya perbedaan.",
  },
  {
    id: "pilar-negara-3-05",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam suatu wilayah terjadi keadaan darurat yang menyebabkan pemerintah harus mengambil langkah cepat untuk melindungi masyarakat. Sejumlah kebijakan pembatasan aktivitas warga kemudian diterapkan. Sebagian masyarakat mempersoalkan kebijakan tersebut karena membatasi beberapa kebebasan yang biasanya dapat mereka lakukan. Agar kebijakan tersebut tetap sesuai dengan prinsip UUD 1945, pemerintah seharusnya ....",
    choices: [
      { id: "a", label: "Membatasi seluruh hak masyarakat selama keadaan darurat berlangsung karena keselamatan negara menjadi kepentingan tertinggi.", score: 0 },
      { id: "b", label: "Mengambil tindakan yang diperlukan berdasarkan kewenangan konstitusional, proporsional, memiliki dasar hukum, dan tetap menghormati hak warga.", score: 5 },
      { id: "c", label: "Membiarkan masyarakat menentukan sendiri bentuk pembatasan karena pemerintah tidak boleh membatasi kebebasan warga dalam keadaan apa pun.", score: 0 },
      { id: "d", label: "Menghentikan seluruh aktivitas pemerintahan sampai keadaan kembali normal agar tidak terjadi pelanggaran terhadap hak masyarakat.", score: 0 },
      { id: "e", label: "Menyerahkan seluruh keputusan kepada aparat keamanan karena keadaan darurat secara otomatis menjadi persoalan keamanan.", score: 0 },
    ],
    explanation: "Pembahasan: Keadaan darurat tidak menghapus prinsip negara hukum dan tidak menjadikan seluruh hak warga dapat dibatasi tanpa dasar. Pemerintah harus bertindak berdasarkan kewenangan yang sah, tujuan yang jelas, proporsionalitas, serta ketentuan peraturan perundang-undangan. Pilihan A terlalu luas karena menganggap seluruh hak dapat dibatasi, C mengabaikan kebutuhan pemerintah untuk melindungi masyarakat, sedangkan D dan E tidak menggambarkan mekanisme pemerintahan konstitusional secara tepat. Jadi, pilihan B paling tepat.",
  },
  {
    id: "pilar-negara-3-06",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Sebuah desa memiliki masyarakat dengan latar belakang budaya yang beragam. Ketika akan menyelenggarakan perayaan hari kemerdekaan, muncul usulan agar setiap kelompok budaya menampilkan kesenian daerahnya masing-masing. Sebagian warga khawatir kegiatan tersebut justru membuat masyarakat semakin terkotak-kotak. Panitia kemudian merancang acara yang menampilkan berbagai kesenian daerah dalam satu rangkaian kegiatan bersama. Sikap panitia tersebut menunjukkan bahwa ....",
    choices: [
      { id: "a", label: "Keberagaman budaya sebaiknya dibatasi agar masyarakat lebih mudah membangun identitas bersama.", score: 0 },
      { id: "b", label: "Identitas budaya daerah harus ditempatkan di atas identitas nasional agar setiap kelompok tetap memiliki ciri khas.", score: 0 },
      { id: "c", label: "Perbedaan budaya dapat menjadi bagian dari kekuatan persatuan apabila ditempatkan dalam kepentingan bersama.", score: 5 },
      { id: "d", label: "Persatuan hanya dapat dibangun apabila seluruh masyarakat menggunakan budaya yang sama dalam kegiatan nasional.", score: 0 },
      { id: "e", label: "Kegiatan kebudayaan sebaiknya dipisahkan berdasarkan kelompok agar tidak terjadi persaingan antarkelompok.", score: 0 },
    ],
    explanation: "Pembahasan: Bhinneka Tunggal Ika mengajarkan bahwa keberagaman dapat hidup berdampingan dalam satu identitas kebangsaan. Menampilkan berbagai kesenian daerah dalam satu kegiatan bersama menunjukkan bahwa identitas budaya tidak harus dihilangkan untuk membangun persatuan. Justru keberagaman dapat menjadi kekayaan bangsa apabila dikelola dalam semangat kebersamaan. Pilihan A dan D menekankan penyeragaman, B berpotensi menempatkan identitas kelompok di atas kepentingan nasional, sedangkan E memisahkan masyarakat berdasarkan kelompok. Jadi, pilihan C paling tepat.",
  },
  {
    id: "pilar-negara-3-07",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam sebuah kegiatan pembangunan desa, pemerintah setempat menerima usulan dari beberapa kelompok masyarakat. Setiap kelompok memiliki kebutuhan berbeda karena kondisi geografis dan sosial mereka tidak sama. Pemerintah kemudian mengadakan dialog dengan perwakilan berbagai kelompok untuk memahami kebutuhan tersebut sebelum menentukan program yang akan dilaksanakan. Prinsip Bhinneka Tunggal Ika yang paling sesuai dengan kondisi tersebut adalah ....",
    choices: [
      { id: "a", label: "Memberikan program yang sama kepada seluruh kelompok agar tidak terjadi perbedaan perlakuan.", score: 0 },
      { id: "b", label: "Mengutamakan kelompok dengan jumlah penduduk terbesar karena dianggap paling mewakili kepentingan masyarakat.", score: 0 },
      { id: "c", label: "Mengakui adanya perbedaan kebutuhan masyarakat dan mengelolanya dalam kerangka kepentingan bersama.", score: 5 },
      { id: "d", label: "Menyerahkan seluruh keputusan kepada kelompok masyarakat yang paling berpengalaman dalam pembangunan.", score: 0 },
      { id: "e", label: "Memisahkan program berdasarkan kelompok masyarakat agar setiap kelompok dapat menentukan kebutuhannya sendiri.", score: 0 },
    ],
    explanation: "Pembahasan: Prinsip Bhinneka Tunggal Ika tidak mengharuskan seluruh masyarakat memiliki kebutuhan dan perlakuan yang identik, tetapi mengajarkan bagaimana perbedaan tersebut dikelola dalam satu kesatuan kehidupan berbangsa. Dialog dengan berbagai kelompok menunjukkan adanya penghargaan terhadap keberagaman kebutuhan sekaligus usaha mencari kebijakan yang tetap berorientasi pada kepentingan bersama. Pilihan A menyamakan kondisi yang sebenarnya berbeda, B mengutamakan mayoritas, D memberikan dominasi kepada kelompok tertentu, sedangkan E berpotensi memisahkan kepentingan masyarakat. Jadi, pilihan C paling tepat.",
  },
  {
    id: "pilar-negara-3-08",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam sebuah forum publik, muncul pendapat bahwa setiap daerah sebaiknya memiliki kebijakan yang sepenuhnya berbeda dengan daerah lain karena kondisi sosial dan ekonominya tidak sama. Pendapat tersebut kemudian dikaitkan dengan konsep otonomi daerah. Jika ditinjau berdasarkan prinsip NKRI, pernyataan yang paling tepat adalah ....",
    choices: [
      { id: "a", label: "Otonomi daerah memungkinkan setiap daerah menentukan seluruh kebijakannya sendiri karena daerah memiliki karakteristik yang berbeda.", score: 0 },
      { id: "b", label: "Otonomi daerah merupakan bentuk pembagian negara menjadi wilayah-wilayah yang memiliki kewenangan politik yang sepenuhnya mandiri.", score: 0 },
      { id: "c", label: "Otonomi daerah memberikan ruang bagi daerah mengatur urusan tertentu sesuai kewenangannya, tetapi tetap berada dalam kerangka negara kesatuan.", score: 5 },
      { id: "d", label: "Otonomi daerah mengharuskan pemerintah pusat menyerahkan seluruh urusan pemerintahan kepada daerah agar pembangunan lebih cepat.", score: 0 },
      { id: "e", label: "Otonomi daerah terutama bertujuan memberikan kebebasan kepada daerah untuk menentukan hubungan politiknya dengan wilayah lain.", score: 0 },
    ],
    explanation: "Pembahasan: Konsep otonomi daerah dalam NKRI bukanlah pembentukan negara-negara kecil di dalam Indonesia. Daerah memperoleh kewenangan untuk mengatur urusan tertentu sesuai prinsip desentralisasi, tetapi tetap berada dalam kerangka konstitusi, hukum nasional, dan keutuhan NKRI. Pilihan A, B, D, dan E memberikan makna otonomi yang terlalu luas hingga mendekati kemandirian politik daerah. Jadi, pilihan C paling tepat.",
  },
  {
    id: "pilar-negara-3-09",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam suatu rapat, seorang pejabat daerah menyatakan bahwa kepentingan daerah harus selalu didahulukan apabila terdapat perbedaan dengan kebijakan pemerintah pusat. Menurutnya, kepala daerah memperoleh mandat langsung dari masyarakat sehingga keputusan daerah harus memiliki kedudukan yang lebih tinggi. Pernyataan tersebut perlu dikritisi karena ....",
    choices: [
      { id: "a", label: "Pemerintah daerah pada dasarnya hanya menjalankan kebijakan pemerintah pusat sehingga tidak memiliki ruang untuk menentukan kebijakan sendiri.", score: 0 },
      { id: "b", label: "Kepala daerah memiliki kedudukan yang sama dengan pemerintah pusat dalam menentukan seluruh kebijakan yang berlaku di wilayahnya.", score: 0 },
      { id: "c", label: "Kepentingan daerah dapat diperjuangkan melalui mekanisme pemerintahan yang tersedia, tetapi tetap harus ditempatkan dalam kerangka konstitusi dan kepentingan nasional.", score: 5 },
      { id: "d", label: "Setiap kebijakan daerah harus memperoleh persetujuan masyarakat terlebih dahulu sebelum dapat dilaksanakan oleh pemerintah daerah.", score: 0 },
      { id: "e", label: "Kepentingan nasional harus selalu mengesampingkan kepentingan daerah karena NKRI menuntut adanya keseragaman kebijakan.", score: 0 },
    ],
    explanation: "Pembahasan: Dalam NKRI, kepentingan daerah dan kepentingan nasional bukan sesuatu yang harus selalu dipertentangkan. Pemerintah daerah memiliki kewenangan dalam penyelenggaraan otonomi, tetapi kewenangan tersebut tetap dibatasi dan diarahkan oleh konstitusi serta sistem hukum nasional. Pilihan A dan E terlalu sentralistis, B memberikan kedudukan yang tidak tepat kepada pemerintah daerah, sedangkan D bukan prinsip umum yang berlaku untuk seluruh kebijakan. Jadi, pilihan C paling tepat karena menempatkan kepentingan daerah dan nasional secara proporsional dalam kerangka NKRI.",
  },
  {
    id: "pilar-negara-3-10",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam suatu proses pemilihan kepala daerah, seorang pejabat meminta bawahannya menggunakan fasilitas kantor untuk membantu kegiatan salah satu peserta pemilihan. Pejabat tersebut beralasan bahwa dukungan tersebut merupakan bentuk partisipasi politik dan tidak akan mengganggu pelayanan selama dilakukan di luar jam kerja. Jika dikaitkan dengan prinsip UUD 1945 dan penyelenggaraan pemerintahan, tindakan tersebut seharusnya ....",
    choices: [
      { id: "a", label: "Diperbolehkan selama fasilitas digunakan setelah jam kerja dan tidak mengurangi jumlah pelayanan kepada masyarakat.", score: 0 },
      { id: "b", label: "Diperbolehkan apabila sebagian besar pegawai menyetujui penggunaan fasilitas tersebut sebagai bentuk partisipasi politik.", score: 0 },
      { id: "c", label: "Dihindari karena fasilitas dan kewenangan pemerintahan harus digunakan untuk kepentingan kedinasan serta tidak boleh diarahkan untuk kepentingan politik tertentu.", score: 5 },
      { id: "d", label: "Diperbolehkan selama pejabat tersebut menggunakan fasilitas kantor atas nama pribadi dan bukan atas nama instansi.", score: 0 },
      { id: "e", label: "Diserahkan kepada masing-masing pegawai karena setiap warga negara memiliki kebebasan menentukan pilihan politiknya.", score: 0 },
    ],
    explanation: "Pembahasan: Fasilitas dan kewenangan pemerintahan harus digunakan secara netral demi kepentingan kedinasan serta tidak boleh difungsikan untuk kepentingan politik praktis tertentu. Hal ini selaras dengan prinsip tata kelola pemerintahan yang baik dan berasaskan kepastian hukum serta netralitas aparatur dalam UUD 1945. Pilihan C paling tepat.",
  },
];

export const PILAR_NEGARA_4_DRILL_QUESTIONS: Question[] = [
  {
    id: "pilar-negara-4-01",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam kehidupan masyarakat yang memiliki latar belakang agama berbeda, setiap warga diberikan kesempatan untuk menjalankan ibadah sesuai dengan keyakinannya. Pemerintah juga berkewajiban menciptakan kondisi yang memungkinkan masyarakat menjalankan kehidupan beragama secara aman dan saling menghormati. Berdasarkan ilustrasi tersebut, simbol Pancasila yang paling tepat untuk menggambarkan nilai yang diterapkan adalah ....",
    choices: [
      { id: "a", label: "Rantai, karena menggambarkan hubungan antarmanusia yang saling menghormati dalam kehidupan bermasyarakat.", score: 0 },
      { id: "b", label: "Kepala banteng, karena menggambarkan penyelesaian perbedaan melalui proses pembahasan dan pengambilan keputusan bersama.", score: 0 },
      { id: "c", label: "Pohon beringin, karena menggambarkan kehidupan masyarakat yang beragam tetapi tetap berada dalam satu kesatuan.", score: 0 },
      { id: "d", label: "Bintang, karena menggambarkan nilai Ketuhanan Yang Maha Esa sebagai landasan kehidupan berbangsa dan bernegara.", score: 5 },
      { id: "e", label: "Padi dan kapas, karena menggambarkan terpenuhinya kebutuhan masyarakat secara adil dan merata.", score: 0 },
    ],
    explanation: "Pembahasan: Simbol bintang merupakan simbol sila pertama, Ketuhanan Yang Maha Esa, yang mencerminkan pengakuan terhadap nilai ketuhanan dan penghormatan terhadap kehidupan beragama. Ilustrasi menekankan kebebasan menjalankan ibadah serta sikap saling menghormati antarumat beragama sehingga simbol yang paling sesuai adalah bintang. Rantai berkaitan dengan kemanusiaan, kepala banteng dengan musyawarah, pohon beringin dengan persatuan, sedangkan padi dan kapas dengan keadilan sosial. Jadi, jawaban yang tepat adalah D.",
  },
  {
    id: "pilar-negara-4-02",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam suatu seleksi kepanitiaan kegiatan nasional, peserta berasal dari berbagai daerah. Salah satu anggota panitia mengusulkan agar peserta yang berasal dari daerah tertentu diprioritaskan karena dianggap lebih mudah berkomunikasi dengan panitia. Anggota lain mengingatkan bahwa kemampuan peserta seharusnya dinilai berdasarkan persyaratan dan kompetensi yang telah ditentukan. Jika dikaitkan dengan Bhinneka Tunggal Ika, sikap yang paling tepat adalah ....",
    choices: [
      { id: "a", label: "Memberikan prioritas kepada kelompok yang memiliki kesamaan budaya dengan panitia agar koordinasi lebih mudah.", score: 0 },
      { id: "b", label: "Memberikan kesempatan yang sama kepada peserta berdasarkan persyaratan dan kemampuan tanpa membedakan asal daerah.", score: 5 },
      { id: "c", label: "Mengutamakan peserta dari daerah yang jumlah pendaftarnya paling banyak agar keterwakilan daerah mayoritas tetap terjamin.", score: 0 },
      { id: "d", label: "Membagi kuota berdasarkan daerah asal tanpa mempertimbangkan kompetensi agar seluruh wilayah memperoleh jumlah peserta yang sama.", score: 0 },
      { id: "e", label: "Menyerahkan penentuan peserta kepada panitia daerah karena mereka dianggap paling memahami karakter masyarakat setempat.", score: 0 },
    ],
    explanation: "Pembahasan: Bhinneka Tunggal Ika menuntut adanya penghargaan terhadap keberagaman tanpa menjadikan perbedaan asal daerah sebagai alasan untuk memberikan perlakuan yang tidak adil. Dalam proses seleksi, peserta seharusnya dinilai berdasarkan kriteria yang telah ditentukan sehingga keberagaman tetap dapat terwakili tanpa mengorbankan objektivitas. Pilihan A dan C memberikan keuntungan berdasarkan identitas kelompok, D menyamakan kuota tanpa mempertimbangkan kompetensi, sedangkan E berpotensi mengurangi objektivitas seleksi. Jadi, pilihan B paling tepat.",
  },
  {
    id: "pilar-negara-4-03",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam sebuah kantor, terdapat pegawai yang memiliki kebiasaan merayakan hari besar budaya daerahnya dengan mengenakan pakaian tradisional. Beberapa pegawai lainnya menganggap kebiasaan tersebut tidak perlu dilakukan karena lingkungan kantor seharusnya menggunakan pakaian yang seragam. Pimpinan kemudian menjelaskan bahwa penggunaan pakaian tradisional dapat diterima pada kegiatan tertentu selama sesuai dengan ketentuan berpakaian yang berlaku dan tidak mengganggu pelaksanaan tugas. Sikap pimpinan tersebut mencerminkan ....",
    choices: [
      { id: "a", label: "Penyeragaman budaya agar seluruh pegawai memiliki identitas yang sama ketika berada di lingkungan kantor.", score: 0 },
      { id: "b", label: "Penghormatan terhadap ekspresi budaya dengan tetap menempatkannya dalam kerangka aturan dan kepentingan bersama.", score: 5 },
      { id: "c", label: "Pemberian kebebasan tanpa batas kepada pegawai untuk menampilkan identitas budaya di lingkungan kerja.", score: 0 },
      { id: "d", label: "Pengutamaan budaya daerah karena identitas budaya merupakan bagian yang lebih penting daripada aturan organisasi.", score: 0 },
      { id: "e", label: "Pembatasan budaya daerah agar perbedaan identitas tidak memengaruhi hubungan profesional antarpegawai.", score: 0 },
    ],
    explanation: "Pembahasan: Sikap tersebut mencerminkan Bhinneka Tunggal Ika karena memberikan ruang bagi keberagaman budaya tanpa mengabaikan aturan dan kepentingan bersama. Penghormatan terhadap budaya tidak berarti setiap orang bebas bertindak tanpa batas, tetapi dilakukan secara proporsional dalam kerangka kehidupan bersama. Pilihan A dan E terlalu menekankan penyeragaman, C memberikan kebebasan tanpa batas, sedangkan D menempatkan budaya daerah di atas aturan organisasi. Jadi, pilihan B paling tepat karena menunjukkan keseimbangan antara penghargaan terhadap keberagaman dan kepatuhan terhadap aturan.",
  },
  {
    id: "pilar-negara-4-04",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Sebuah daerah dihuni oleh masyarakat dari berbagai suku dan budaya. Dalam kehidupan sehari-hari, masyarakat tetap menjalankan tradisi masing-masing, tetapi mereka bekerja sama ketika terdapat kegiatan yang menyangkut kepentingan seluruh lingkungan. Ketika terjadi perbedaan antarwarga, mereka berusaha menyelesaikannya tanpa mempertentangkan asal daerah maupun kelompok masing-masing. Simbol Pancasila yang paling sesuai dengan kondisi tersebut adalah ....",
    choices: [
      { id: "a", label: "Padi dan kapas, karena masyarakat berusaha menciptakan kehidupan yang sejahtera bagi seluruh warga.", score: 0 },
      { id: "b", label: "Rantai, karena masyarakat saling membantu dan menghargai martabat setiap orang.", score: 0 },
      { id: "c", label: "Pohon beringin, karena menggambarkan keberagaman masyarakat yang tetap berada dalam satu kesatuan.", score: 5 },
      { id: "d", label: "Kepala banteng, karena setiap persoalan masyarakat diselesaikan melalui pembahasan dan keputusan bersama.", score: 0 },
      { id: "e", label: "Bintang, karena masyarakat tetap menghormati keyakinan yang berbeda dalam kehidupan sosial.", score: 0 },
    ],
    explanation: "Pembahasan: Simbol pohon beringin merupakan simbol sila ketiga, Persatuan Indonesia. Pohon beringin memiliki makna sebagai tempat berteduh dan menggambarkan persatuan masyarakat yang memiliki latar belakang berbeda tetapi tetap berada dalam satu kesatuan. Kasus menekankan keberagaman suku dan budaya yang tidak menjadi penghalang untuk bekerja sama serta menjaga keutuhan lingkungan. Rantai, kepala banteng, bintang, dan padi kapas memiliki makna yang berbeda sebagaimana dijelaskan dalam masing-masing sila. Jadi, jawaban yang tepat adalah C.",
  },
  {
    id: "pilar-negara-4-05",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam sebuah kegiatan nasional, peserta berasal dari berbagai daerah dengan bahasa, adat istiadat, dan kebiasaan yang berbeda. Pada awal kegiatan, beberapa peserta cenderung berkumpul hanya dengan teman yang berasal dari daerah yang sama. Panitia kemudian membuat kegiatan kelompok yang anggotanya sengaja terdiri atas peserta dari berbagai daerah sehingga mereka dapat saling mengenal dan bekerja sama menyelesaikan tugas. Tujuan utama tindakan tersebut dalam perspektif Bhinneka Tunggal Ika adalah ....",
    choices: [
      { id: "a", label: "Mengurangi penggunaan budaya daerah agar peserta lebih mudah membentuk kebiasaan yang seragam.", score: 0 },
      { id: "b", label: "Menghilangkan kelompok berdasarkan daerah agar identitas lokal tidak lagi memengaruhi hubungan antar peserta.", score: 0 },
      { id: "c", label: "Mendorong interaksi lintas keberagaman sehingga perbedaan dapat menjadi dasar untuk membangun persatuan.", score: 5 },
      { id: "d", label: "Menentukan kelompok berdasarkan kemampuan peserta agar seluruh kegiatan dapat diselesaikan dengan lebih efisien.", score: 0 },
      { id: "e", label: "Memberikan kesempatan kepada peserta untuk mengenalkan budaya daerahnya tanpa perlu membangun hubungan dengan kelompok lain.", score: 0 },
    ],
    explanation: "Pembahasan: Pembentukan kelompok yang beranggotakan peserta dari berbagai daerah bertujuan memperluas interaksi dan membangun kerja sama lintas latar belakang. Hal tersebut sesuai dengan semangat Bhinneka Tunggal Ika yang tidak menghapus identitas daerah, tetapi mendorong masyarakat yang berbeda untuk tetap membangun persatuan sebagai satu bangsa. Pilihan A dan B mengarah pada penghilangan identitas, D lebih menekankan efisiensi kerja daripada keberagaman, sedangkan E tidak cukup mendorong interaksi lintas kelompok. Jadi, pilihan C paling tepat karena keberagaman ditempatkan sebagai bagian dari proses membangun persatuan.",
  },
  {
    id: "pilar-negara-4-06",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Suatu wilayah mengalami perkembangan ekonomi yang sangat cepat karena memiliki sumber daya alam strategis. Sebagian tokoh masyarakat kemudian mengusulkan agar sebagian besar hasil pengelolaan sumber daya tersebut digunakan hanya untuk pembangunan wilayah mereka dengan alasan masyarakat setempat menanggung dampak lingkungan dan sosial yang lebih besar. Pemerintah perlu merespons tuntutan tersebut dengan cara ....",
    choices: [
      { id: "a", label: "Menyetujui seluruh tuntutan daerah karena masyarakat setempat memiliki hak utama atas sumber daya yang berada di wilayahnya.", score: 0 },
      { id: "b", label: "Menolak seluruh tuntutan daerah karena pengelolaan sumber daya alam merupakan sepenuhnya kewenangan pemerintah pusat.", score: 0 },
      { id: "c", label: "Menyusun kebijakan yang memperhatikan kepentingan daerah penghasil sekaligus memastikan pengelolaan sumber daya tetap mendukung kepentingan nasional.", score: 5 },
      { id: "d", label: "Menyerahkan seluruh pengelolaan kepada pemerintah daerah agar masyarakat setempat dapat menentukan penggunaan hasil sumber daya tersebut.", score: 0 },
      { id: "e", label: "Membagi hasil secara sama rata kepada seluruh daerah tanpa mempertimbangkan kontribusi maupun dampak yang ditimbulkan.", score: 0 },
    ],
    explanation: "Pembahasan: Dalam negara kesatuan, pengelolaan sumber daya strategis harus mempertimbangkan kepentingan nasional sekaligus memperhatikan kebutuhan dan kondisi daerah penghasil. Pendekatan yang tepat bukan memberikan seluruh kewenangan kepada daerah atau mengabaikan kepentingan daerah, tetapi membangun pengaturan yang proporsional sesuai ketentuan hukum. Pilihan A dan D terlalu mengarah pada penguasaan daerah, B terlalu sentralistis, sedangkan E menyamaratakan tanpa mempertimbangkan kondisi masing-masing wilayah. Jadi, pilihan C paling tepat.",
  },
  {
    id: "pilar-negara-4-07",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam suatu rapat, pemerintah pusat dan pemerintah daerah sedang menyusun program pembangunan konektivitas antardaerah. Sebagian wilayah memiliki akses transportasi dan teknologi yang jauh lebih baik dibandingkan wilayah lainnya. Jika pembangunan hanya diarahkan pada wilayah yang sudah berkembang, terdapat risiko kesenjangan semakin besar. Dalam perspektif NKRI, strategi yang paling tepat adalah ....",
    choices: [
      { id: "a", label: "Memprioritaskan wilayah yang sudah berkembang karena pembangunan di wilayah tersebut memberikan hasil ekonomi yang lebih cepat.", score: 0 },
      { id: "b", label: "Menyamakan seluruh bentuk pembangunan di setiap wilayah tanpa mempertimbangkan kondisi geografis dan kebutuhan masyarakat.", score: 0 },
      { id: "c", label: "Mengembangkan konektivitas dengan mempertimbangkan ketimpangan, kondisi geografis, dan kebutuhan strategis setiap wilayah dalam rangka memperkuat keterhubungan nasional.", score: 5 },
      { id: "d", label: "Menyerahkan pembangunan konektivitas kepada daerah masing-masing agar pemerintah daerah dapat menentukan prioritas berdasarkan kebutuhan lokal.", score: 0 },
      { id: "e", label: "Mengutamakan pembangunan pusat-pusat ekonomi baru tanpa mempertimbangkan hubungan wilayah tersebut dengan daerah lainnya.", score: 0 },
    ],
    explanation: "Pembahasan: Konektivitas antardaerah memiliki peran penting dalam memperkuat integrasi nasional karena dapat mengurangi kesenjangan akses, memperlancar mobilitas masyarakat, dan menghubungkan berbagai wilayah Indonesia. Strategi pembangunan tidak harus seragam, tetapi harus mempertimbangkan karakteristik dan kebutuhan masing-masing wilayah dalam satu tujuan nasional. Pilihan A terlalu berorientasi pada hasil ekonomi jangka pendek, B mengabaikan perbedaan geografis, D terlalu menyerahkan persoalan kepada daerah, sedangkan E tidak menjamin keterhubungan antardaerah. Jadi, pilihan C paling tepat karena menghubungkan pembangunan daerah dengan kepentingan integrasi nasional.",
  },
  {
    id: "pilar-negara-4-08",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam sebuah pemerintah daerah, terdapat kebijakan yang dinilai dapat mempercepat pembangunan daerah karena memberikan perlakuan khusus kepada kelompok masyarakat tertentu. Namun, setelah dikaji, kebijakan tersebut menyebabkan sebagian warga yang berada dalam kondisi serupa tidak memperoleh kesempatan yang sama untuk mendapatkan pelayanan. Jika ditinjau dari prinsip konstitusional, tindakan yang paling tepat adalah ....",
    choices: [
      { id: "a", label: "Mempertahankan kebijakan tersebut karena pemerintah memiliki kewenangan menentukan prioritas sesuai kebutuhan pembangunan daerah.", score: 0 },
      { id: "b", label: "Menghapus seluruh bentuk kebijakan khusus karena setiap warga negara harus selalu mendapatkan perlakuan yang sama dalam semua keadaan.", score: 0 },
      { id: "c", label: "Mengevaluasi kebijakan berdasarkan prinsip kesetaraan dan memastikan setiap warga memperoleh perlakuan yang adil sesuai ketentuan hukum.", score: 5 },
      { id: "d", label: "Mengutamakan kelompok yang dianggap paling berpengaruh karena dukungan masyarakat diperlukan untuk menjaga keberlanjutan pemerintahan.", score: 0 },
      { id: "e", label: "Menyerahkan keputusan kepada pimpinan daerah karena kebijakan pemerintah merupakan bagian dari kewenangan eksekutif.", score: 0 },
    ],
    explanation: "Pembahasan: UUD 1945 menjamin prinsip persamaan kedudukan warga negara di dalam hukum dan pemerintahan serta perlindungan terhadap hak-hak konstitusional. Kebijakan pemerintah memang dapat mempertimbangkan kondisi dan kebutuhan tertentu, tetapi pelaksanaannya harus memiliki dasar hukum dan tidak boleh menghasilkan perlakuan yang sewenang-wenang. Pilihan A dan E terlalu menekankan kewenangan pemerintah, B terlalu mutlak karena perlakuan berbeda dapat dibenarkan apabila memiliki dasar objektif dan konstitusional, sedangkan D jelas tidak dapat dijadikan dasar penyelenggaraan pemerintahan. Jadi, pilihan C paling tepat.",
  },
  {
    id: "pilar-negara-4-09",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam pelayanan publik, sebuah kebijakan baru mengharuskan masyarakat memenuhi persyaratan tambahan yang tidak tercantum dalam peraturan sebelumnya. Petugas beralasan bahwa persyaratan tersebut dibuat untuk mempermudah proses verifikasi dan mengurangi kesalahan administrasi. Namun, persyaratan tambahan tersebut menyebabkan sebagian masyarakat yang sebenarnya memenuhi ketentuan menjadi tidak dapat memperoleh pelayanan. Tindakan yang paling sesuai dengan prinsip UUD 1945 adalah ....",
    choices: [
      { id: "a", label: "Tetap menerapkan persyaratan tambahan karena petugas memiliki tanggung jawab memastikan pelayanan berjalan tertib dan aman.", score: 0 },
      { id: "b", label: "Menghapus seluruh persyaratan administrasi agar masyarakat dapat memperoleh pelayanan tanpa hambatan.", score: 0 },
      { id: "c", label: "Meninjau kembali persyaratan tersebut agar pelayanan tetap tertib tetapi tidak memberikan perlakuan yang tidak memiliki dasar hukum kepada masyarakat.", score: 5 },
      { id: "d", label: "Memberikan pengecualian kepada masyarakat yang mengalami kesulitan agar seluruh persoalan dapat diselesaikan secara fleksibel.", score: 0 },
      { id: "e", label: "Menyerahkan penentuan persyaratan kepada masing-masing petugas karena kondisi masyarakat yang dilayani tidak selalu sama.", score: 0 },
    ],
    explanation: "Pembahasan: Kasus ini dapat dikaitkan dengan Pasal 28D ayat (1) UUD 1945 yang menjamin pengakuan, jaminan, perlindungan, dan kepastian hukum yang adil serta perlakuan yang sama di hadapan hukum. Persyaratan pelayanan harus memiliki dasar yang jelas dan tidak boleh dibuat secara sewenang-wenang oleh petugas. Pilihan A mempertahankan persyaratan tanpa menguji dasar hukumnya, B terlalu ekstrem karena pelayanan tetap membutuhkan persyaratan yang sah, D menciptakan pengecualian subjektif, sedangkan E membuka peluang ketidakseragaman dan ketidakpastian hukum. Jadi, pilihan C paling tepat.",
  },
  {
    id: "pilar-negara-4-10",
    category: "TWK",
    topic: "Pilar Negara",
    prompt: "Dalam sebuah lingkungan masyarakat, warga dari beberapa agama hidup berdampingan. Menjelang pelaksanaan kegiatan keagamaan, kelompok mayoritas meminta pemerintah setempat memberikan izin kegiatan tersebut dengan segera, sementara kelompok lain mengkhawatirkan munculnya gangguan apabila kegiatan dilaksanakan di lokasi tertentu. Pemerintah kemudian melakukan koordinasi untuk memastikan kegiatan dapat berlangsung dengan aman tanpa mengurangi hak masyarakat dalam menjalankan keyakinannya. Sikap pemerintah tersebut paling sesuai dengan ....",
    choices: [
      { id: "a", label: "Menempatkan kepentingan kelompok mayoritas sebagai pertimbangan utama karena jumlah masyarakat menjadi dasar dalam pengambilan keputusan.", score: 0 },
      { id: "b", label: "Membatasi seluruh kegiatan keagamaan untuk mencegah kemungkinan terjadinya perbedaan dan konflik di masyarakat.", score: 0 },
      { id: "c", label: "Menjamin kebebasan menjalankan agama sekaligus mengatur pelaksanaannya berdasarkan ketentuan hukum dan penghormatan terhadap hak masyarakat lainnya.", score: 5 },
      { id: "d", label: "Menyerahkan keputusan kepada tokoh agama mayoritas karena mereka dianggap paling memahami kebutuhan masyarakat setempat.", score: 0 },
      { id: "e", label: "Memberikan izin tanpa persyaratan apa pun karena kebebasan beragama tidak dapat dikenai pengaturan dalam keadaan apa pun.", score: 0 },
    ],
    explanation: "Pembahasan: Kasus tersebut berkaitan dengan Pasal 29 ayat (2) UUD 1945 yang menjamin kemerdekaan tiap-tiap penduduk untuk memeluk agamanya masing-masing dan beribadat menurut agama dan kepercayaannya. Pelaksanaan kebebasan tersebut tetap berlangsung dalam kehidupan bersama dan harus memperhatikan ketentuan hukum serta hak orang lain. Pilihan A mengutamakan mayoritas, B terlalu membatasi kebebasan beragama, D menyerahkan keputusan kepada kelompok tertentu, sedangkan E memahami kebebasan secara mutlak tanpa mempertimbangkan aturan yang berlaku. Jadi, pilihan C paling tepat.",
  },
];

export const PILAR_NEGARA_DRILL_QUESTIONS: Question[] = [
  ...PILAR_NEGARA_1_DRILL_QUESTIONS,
  ...PILAR_NEGARA_2_DRILL_QUESTIONS,
  ...PILAR_NEGARA_3_DRILL_QUESTIONS,
  ...PILAR_NEGARA_4_DRILL_QUESTIONS,
];
