import type { Question } from "./types";

const commonOptions =
[
  "Membatasi penggunaan teknologi tersebut agar risiko kesalahan dapat dikurangi tanpa mengubah proses kerja utama.",
  "Menyerahkan pengelolaan kepada satu pegawai yang dianggap paling memahami teknologi agar proses menjadi lebih sederhana.",
  "Memilih solusi yang paling populer digunakan orang lain agar penerapannya dianggap lebih mudah oleh seluruh anggota.",
  "Mempertahankan cara yang berjalan sekarang agar pegawai tidak perlu mengubah kebiasaan kerja yang sudah terbentuk."
]
;

const specificOptions =
[
  "Menetapkan penyimpanan bersama yang terstruktur, aturan penamaan file, dan pengendalian versi agar dokumen mudah ditemukan.",
  "Memeriksa alamat pengirim dan kanal resmi terlebih dahulu tanpa membuka tautan sampai keasliannya dapat dipastikan.",
  "Menggunakan kanal resmi dengan akses terbatas dan hanya membagikan data yang benar-benar diperlukan untuk pekerjaan.",
  "Menghapus aplikasi yang tidak diperlukan, memeriksa program yang berjalan, dan memastikan perangkat menggunakan sumber perangkat lunak tepercaya.",
  "Segera membatasi akses dokumen, melaporkan kejadian, dan memastikan pihak yang menerima informasi memahami pembatasannya.",
  "Menggunakan kata sandi berbeda untuk akun penting serta mengaktifkan autentikasi tambahan jika tersedia.",
  "Tidak membuka perangkat tersebut dan menyerahkannya kepada petugas TI atau pihak yang berwenang untuk diperiksa.",
  "Menggunakan riwayat perubahan dan hak akses yang sesuai agar setiap pembaruan dapat ditelusuri dengan jelas.",
  "Menghindari jaringan publik untuk akses sensitif atau menggunakan koneksi yang memiliki perlindungan keamanan memadai.",
  "Menggunakan penyimpanan organisasi dengan struktur akses yang jelas agar file tetap dapat dikelola ketika anggota berganti.",
  "Memastikan permintaan melalui kanal komunikasi yang telah dikenal sebelum melakukan transaksi atau tindakan penting.",
  "Tidak mengklik pop-up tersebut dan melakukan pemeriksaan menggunakan perangkat lunak keamanan yang tepercaya.",
  "Mencatat sumber, tanggal akses, dan konteks data agar informasi dapat diverifikasi ketika digunakan kembali.",
  "Memastikan kebijakan organisasi dan perlindungan data terpenuhi sebelum memasukkan dokumen internal ke layanan AI.",
  "Mematikan mikrofon dan memastikan lingkungan sekitar aman sebelum informasi internal dibahas lebih lanjut.",
  "Memeriksa daftar akun resmi dan membandingkan informasi melalui kanal organisasi sebelum mempercayai akun tersebut.",
  "Tidak membuka lampiran dan melaporkannya melalui mekanisme keamanan organisasi untuk pemeriksaan lebih lanjut.",
  "Memeriksa tanggal pembaruan dan sumber data sebelum menggunakan angka dalam laporan atau presentasi.",
  "Menghapus atau menutupi informasi pribadi pada materi publikasi serta melaporkan kebocoran kepada pihak terkait.",
  "Menetapkan kanal utama berdasarkan jenis informasi dan aturan penggunaan agar pesan penting tidak tersebar tanpa kendali.",
  "Menggunakan kanal resmi organisasi atau menunda pengiriman sampai metode yang aman dapat digunakan.",
  "Menilai setiap izin berdasarkan kebutuhan fungsi aplikasi dan menolak akses yang tidak relevan.",
  "Keluar dari akun setelah digunakan dan mengaktifkan mekanisme penguncian otomatis pada perangkat bersama.",
  "Membuat cadangan data pada media atau penyimpanan tepercaya sebelum perangkat mengalami kerusakan lebih lanjut.",
  "Memeriksa sumber dan konteks informasi sebelum meneruskan pesan kepada anggota lain.",
  "Menggunakan perangkat lunak resmi dan berlisensi agar keamanan, legalitas, dan dukungan sistem tetap terjaga.",
  "Menggunakan fitur kolaborasi dengan riwayat versi agar perubahan dapat dikerjakan pada dokumen yang sama.",
  "Tidak memberikan OTP kepada siapa pun dan melakukan verifikasi melalui kanal resmi layanan akun.",
  "Memetakan kebutuhan, alur kerja, keamanan, dan integrasi sebelum membandingkan aplikasi yang tersedia.",
  "Memastikan domain dan sertifikat situs sesuai dengan kanal resmi sebelum memasukkan informasi pribadi.",
  "Menghapus akses yang tidak diperlukan dan memindahkan dokumen ke penyimpanan organisasi yang memiliki perlindungan memadai.",
  "Menutup aplikasi sensitif dan menyiapkan tampilan khusus sebelum membagikan layar kepada peserta.",
  "Menetapkan pola penamaan, struktur folder, metadata, dan aturan pengarsipan yang konsisten.",
  "Menjadwalkan pembaruan pada waktu yang tepat dan menjaga sistem tetap memperoleh patch keamanan terbaru.",
  "Menghapus file sementara dan memastikan dokumen tidak tersimpan pada folder publik atau perangkat setelah digunakan.",
  "Mengumpulkan hanya data yang relevan, memiliki tujuan jelas, dan diperlukan untuk layanan yang diberikan.",
  "Memeriksa informasi melalui kanal resmi dan tidak mengikuti batas waktu atau tautan yang menekan pengguna.",
  "Menggunakan sistem pencatatan bersama agar perkembangan pekerjaan dapat dipantau sesuai hak akses yang ditetapkan.",
  "Memastikan lisensi dan kebijakan organisasi mengizinkan penggunaan pada perangkat pribadi sebelum memasangnya.",
  "Mematikan atau menonaktifkan perangkat kamera dan mikrofon setelah rapat sesuai prosedur keamanan.",
  "Memeriksa kualitas, duplikasi, format, dan kelengkapan data sebelum melakukan pengolahan lebih lanjut.",
  "Menggunakan pengelola kata sandi yang tepercaya dan tidak menyimpan kredensial dalam file teks terbuka.",
  "Menutupi informasi yang tidak diperlukan atau menggunakan data yang telah diminimalkan sebelum meminta pendapat.",
  "Menggunakan sistem pencatatan terpusat dengan nomor tiket dan status agar setiap keluhan dapat ditelusuri.",
  "Menggunakan perangkat organisasi sesuai kebutuhan kerja dan menghindari situs atau tautan yang berisiko.",
  "Membatasi akses berdasarkan anggota tim dan kebutuhan kerja serta menghindari tautan terbuka untuk dokumen sensitif.",
  "Membandingkan beberapa sumber, memeriksa kredibilitas, dan membaca konteks sebelum menggunakan hasil pencarian.",
  "Memeriksa kebijakan retensi dan kebutuhan audit sebelum menghapus file yang sudah lama.",
  "Memprioritaskan indikator utama dan menyederhanakan tampilan agar informasi penting mudah dipahami pengguna.",
  "Memastikan layanan memenuhi persyaratan keamanan dan kebijakan perlindungan data sebelum data diunggah."
]
;

type TeknologiInformasiSeed = {
  prompt: string;
  order: string;
  scores: number[];
};

const seeds: TeknologiInformasiSeed[] = [
  { prompt: "Sebuah unit pelayanan mulai menerapkan sistem penyimpanan digital untuk mempercepat pencarian dokumen. Namun, pegawai masih menyimpan file pada laptop masing-masing dengan nama yang berbeda, sementara dokumen yang sama sering memiliki beberapa versi. Ketika seorang pegawai berhalangan hadir, anggota tim lain kesulitan memastikan file mana yang paling baru dan dapat digunakan sebagai dasar pelayanan.\n\nBagaimana pengelolaan dokumen digital yang paling tepat diterapkan pada kondisi tersebut?", order: "0x123", scores: [4, 5, 3, 2, 1] },
  { prompt: "Anda menerima email yang mengatasnamakan administrator sistem dan menyatakan bahwa akun kantor akan dinonaktifkan apabila kata sandi tidak diperbarui dalam satu jam. Pesan tersebut menyertakan tautan menuju halaman login yang tampilannya menyerupai situs resmi, tetapi alamat pengirim memiliki tambahan karakter yang tidak biasa. Anda sedang membutuhkan akses sistem tersebut untuk menyelesaikan pekerjaan yang mendesak.\n\nLangkah apa yang paling tepat dilakukan sebelum merespons email tersebut?", order: "1230x", scores: [4, 3, 2, 1, 5] },
  { prompt: "Sebuah tim pelayanan menggunakan grup pesan instan untuk mempercepat koordinasi. Dalam suatu pekerjaan, seorang anggota mengusulkan agar seluruh data masyarakat dikirim ke grup karena beberapa pegawai perlu melakukan pemeriksaan secara bersamaan. Data tersebut memuat informasi yang tidak semuanya diperlukan oleh setiap anggota grup.\n\nPertimbangan apa yang paling penting sebelum membagikan data tersebut?", order: "23x01", scores: [3, 2, 5, 4, 1] },
  { prompt: "Komputer yang digunakan untuk pekerjaan administrasi semakin lambat dan membutuhkan waktu lama ketika membuka beberapa aplikasi. Setelah diperiksa, ternyata terdapat banyak aplikasi gratis yang pernah dipasang dari internet dan sebagian berjalan otomatis ketika komputer dinyalakan. Beberapa aplikasi juga sudah tidak digunakan lagi oleh pegawai.\n\nLangkah penanganan apa yang paling tepat dilakukan terhadap perangkat tersebut?", order: "x3012", scores: [5, 2, 1, 4, 3] },
  { prompt: "Dalam rapat daring lintas unit, seorang peserta membagikan tautan dokumen internal kepada pihak luar agar proses diskusi dapat berlangsung lebih cepat. Setelah tautan tersebar, diketahui bahwa dokumen tersebut berisi informasi yang belum boleh diketahui oleh pihak di luar organisasi. Sebagian peserta kemudian meminta agar dokumen tetap dapat diakses karena rapat masih berlangsung.\n\nApa tindakan yang paling tepat untuk menangani situasi tersebut?", order: "012x3", scores: [1, 3, 2, 5, 4] },
  { prompt: "Seorang rekan mengaku kesulitan mengingat banyak kata sandi sehingga menggunakan satu kata sandi untuk akun kantor, email pribadi, dan beberapa layanan daring. Ia juga jarang mengaktifkan autentikasi tambahan karena menganggap proses tersebut memperlambat ketika masuk ke akun. Kebiasaan tersebut sudah berlangsung cukup lama.\n\nPerubahan kebiasaan apa yang paling tepat disarankan kepada rekan tersebut?", order: "12x30", scores: [3, 4, 5, 1, 2] },
  { prompt: "Anda menemukan flash drive tanpa pemilik yang jelas di ruang rapat setelah kegiatan selesai. Perangkat tersebut memiliki label yang tampak berkaitan dengan salah satu unit kerja, tetapi tidak ada informasi yang memastikan siapa pemiliknya. Pada saat yang sama, Anda sedang membutuhkan perangkat penyimpanan untuk memindahkan beberapa file pekerjaan.\n\nApa tindakan yang paling aman terhadap flash drive tersebut?", order: "2301x", scores: [2, 1, 4, 3, 5] },
  { prompt: "Sebuah tim menggunakan spreadsheet bersama untuk memantau target pekerjaan setiap minggu. Beberapa anggota dapat mengubah isi file secara langsung, tetapi tidak ada aturan mengenai siapa yang boleh mengedit bagian tertentu dan perubahan tidak selalu dicatat. Akibatnya, terjadi perbedaan angka antara laporan sebelumnya dan data terbaru.\n\nPerbaikan apa yang paling tepat diterapkan pada pengelolaan spreadsheet tersebut?", order: "3x012", scores: [3, 5, 1, 2, 4] },
  { prompt: "Saat bekerja dari lokasi umum, seorang pegawai menggunakan jaringan Wi-Fi publik untuk mengakses sistem kantor karena koneksinya lebih cepat daripada jaringan seluler. Ia mengakses beberapa informasi pekerjaan yang tidak ditujukan untuk konsumsi publik. Pegawai tersebut beranggapan bahwa penggunaan kata sandi akun sudah cukup untuk melindungi akses.\n\nApa tindakan yang paling tepat untuk mengurangi risiko pada kondisi tersebut?", order: "012x3", scores: [4, 2, 3, 5, 1] },
  { prompt: "Dalam sebuah proyek, anggota tim menyimpan file pekerjaan menggunakan berbagai layanan penyimpanan awan dengan akun pribadi. Struktur folder dan aturan akses berbeda-beda sehingga anggota lain tidak selalu mengetahui lokasi file terbaru. Ketika salah satu anggota keluar dari proyek, beberapa dokumen menjadi sulit diakses.\n\nBagaimana pengelolaan file proyek yang paling tepat dilakukan?", order: "x1230", scores: [5, 1, 4, 3, 2] },
  { prompt: "Seorang pegawai menerima pesan yang mengaku berasal dari pimpinan dan meminta transfer dana untuk kebutuhan kantor yang harus diselesaikan segera. Nomor pengirim berbeda dengan nomor yang biasanya digunakan pimpinan, tetapi pesan tersebut menggunakan nama dan gaya bahasa yang tampak meyakinkan. Pegawai tersebut khawatir dianggap menghambat pekerjaan jika tidak segera bertindak.\n\nVerifikasi apa yang paling tepat dilakukan sebelum memenuhi permintaan tersebut?", order: "2301x", scores: [4, 3, 2, 1, 5] },
  { prompt: "Ketika sedang bekerja, komputer menampilkan pop-up berwarna mencolok yang menyatakan perangkat telah terkena virus. Pesan tersebut meminta pengguna mengunduh program tertentu melalui tautan yang tersedia agar perangkat segera dibersihkan. Pegawai belum mengetahui apakah peringatan tersebut berasal dari sistem keamanan resmi.\n\nRespons apa yang paling tepat terhadap peringatan tersebut?", order: "30x12", scores: [4, 3, 5, 2, 1] },
  { prompt: "Dalam menyusun laporan, seorang pegawai menemukan data statistik yang sesuai dengan kebutuhan analisis pada sebuah situs internet. Ia langsung menyalin angka tersebut ke laporan tanpa mencatat sumber, tanggal akses, atau konteks pengumpulan data. Ketika diminta menjelaskan dasar angka tersebut, ia kesulitan memastikan informasi masih relevan.\n\nApa perbaikan yang paling tepat dilakukan terhadap proses penggunaan data tersebut?", order: "0x123", scores: [3, 5, 2, 4, 1] },
  { prompt: "Sebuah unit kerja mulai memanfaatkan layanan kecerdasan buatan untuk membantu merangkum dokumen dan menyusun ide awal. Seorang pegawai mengusulkan agar seluruh dokumen internal langsung dimasukkan ke layanan AI publik karena sistem tersebut dianggap mampu menghasilkan jawaban yang lebih lengkap. Dokumen yang dimaksud memuat beberapa informasi yang hanya digunakan untuk kepentingan internal.\n\nApa pertimbangan utama sebelum menggunakan layanan AI tersebut?", order: "123x0", scores: [2, 1, 4, 5, 3] },
  { prompt: "Dalam rapat virtual, seorang peserta mengikuti pembahasan dari ruang yang cukup ramai. Mikrofon perangkatnya tetap terbuka ketika anggota lain membicarakan informasi internal dan percakapan tersebut berpotensi terdengar oleh orang di sekitarnya. Peserta tersebut baru menyadari kondisi itu setelah beberapa menit.\n\nTindakan apa yang paling tepat dilakukan untuk menjaga keamanan pembahasan?", order: "x2301", scores: [5, 1, 3, 2, 4] },
  { prompt: "Anda menemukan akun media sosial yang menggunakan nama, logo, dan foto yang menyerupai akun resmi organisasi. Akun tersebut mengunggah informasi mengenai layanan publik dan meminta pengikut mengisi formulir melalui tautan tertentu. Namun, akun itu tidak tercantum pada daftar kanal resmi yang biasa digunakan organisasi.\n\nLangkah apa yang paling tepat sebelum mempercayai informasi dari akun tersebut?", order: "301x2", scores: [3, 4, 1, 5, 2] },
  { prompt: "Sebuah email dari alamat yang tidak dikenal masuk ke kotak surat kantor dengan lampiran berformat tidak biasa. Pengirim mengatakan file tersebut sangat penting dan meminta penerima segera membukanya agar pekerjaan tidak terlambat. Anda tidak memiliki komunikasi sebelumnya dengan pengirim tersebut.\n\nApa tindakan yang paling tepat terhadap email dan lampiran tersebut?", order: "0x123", scores: [2, 5, 1, 4, 3] },
  { prompt: "Dalam menyiapkan presentasi, seorang pegawai mengambil angka dari dashboard kinerja yang pernah digunakan pada rapat bulan sebelumnya. Ia tidak memeriksa apakah dashboard tersebut telah diperbarui atau apakah periode data masih sesuai dengan topik rapat. Angka tersebut kemudian digunakan untuk menjelaskan kondisi terkini organisasi.\n\nKebiasaan kerja digital apa yang paling tepat untuk mencegah kesalahan tersebut?", order: "1230x", scores: [3, 1, 2, 4, 5] },
  { prompt: "Seorang pegawai membagikan tangkapan layar sistem internal ke media sosial untuk menunjukkan hasil pekerjaannya. Ia tidak menyadari bahwa gambar tersebut menampilkan sebagian identitas dan informasi pengguna pada sudut layar. Unggahan tersebut sudah sempat dilihat oleh beberapa orang sebelum kesalahan diketahui.\n\nApa tindakan paling tepat setelah mengetahui kejadian tersebut?", order: "x2301", scores: [5, 4, 2, 3, 1] },
  { prompt: "Sebuah tim memiliki banyak grup komunikasi digital karena setiap kegiatan dibuatkan grup baru. Informasi pekerjaan yang penting sering tersebar di beberapa grup, sementara anggota harus memeriksa banyak percakapan untuk menemukan keputusan terbaru. Kondisi tersebut mulai menyebabkan pekerjaan terlambat dan informasi tidak seragam.\n\nSolusi apa yang paling tepat untuk memperbaiki komunikasi digital tim?", order: "30x12", scores: [1, 4, 5, 3, 2] },
  { prompt: "Anda diminta mengirim dokumen berisi data sensitif kepada pihak eksternal untuk keperluan pekerjaan. Rekan menyarankan menggunakan email pribadi karena akun kantor sedang mengalami gangguan dan pekerjaan harus segera selesai. Dokumen tersebut tetap diperlukan oleh pihak eksternal pada hari yang sama.\n\nPilihan apa yang paling tepat dalam kondisi tersebut?", order: "01x23", scores: [4, 3, 5, 2, 1] },
  { prompt: "Sebuah aplikasi pengelola tugas meminta izin mengakses kamera, kontak, lokasi, mikrofon, dan penyimpanan perangkat. Padahal, fungsi utama aplikasi hanya mencatat tugas, tenggat waktu, dan status pekerjaan. Pegawai ingin segera menggunakan aplikasi tersebut karena dianggap praktis.\n\nApa langkah yang paling tepat sebelum memberikan izin aplikasi?", order: "x1230", scores: [5, 4, 3, 2, 1] },
  { prompt: "Pegawai sering menggunakan komputer bersama untuk menyelesaikan pekerjaan administrasi. Setelah selesai, ia membiarkan akun tetap masuk karena merasa proses login ulang akan menghabiskan waktu. Komputer tersebut juga digunakan oleh beberapa pegawai lain dalam satu hari kerja.\n\nKebiasaan apa yang paling tepat diterapkan pada penggunaan komputer bersama?", order: "2301x", scores: [3, 2, 4, 1, 5] },
  { prompt: "Sebuah dokumen penting hanya tersimpan pada satu komputer dan belum pernah dibuat salinan cadangan. Dalam beberapa hari terakhir, komputer tersebut mulai mengalami gangguan dan beberapa file tidak dapat dibuka dengan normal. Dokumen tersebut masih dibutuhkan untuk pekerjaan dan berpotensi diperlukan saat pemeriksaan.\n\nLangkah apa yang paling tepat untuk mencegah kehilangan data?", order: "301x2", scores: [2, 1, 4, 5, 3] },
  { prompt: "Dalam forum daring, seorang peserta menyebarkan informasi mengenai kebijakan pemerintah yang belum jelas sumbernya. Ia meminta anggota lain segera meneruskan pesan tersebut karena menurutnya informasi itu penting dan tidak boleh terlambat diketahui masyarakat. Beberapa anggota mulai membagikannya tanpa melakukan pemeriksaan.\n\nSikap digital apa yang paling tepat terhadap informasi tersebut?", order: "0x123", scores: [1, 5, 3, 2, 4] },
  { prompt: "Seorang pegawai mengunduh perangkat lunak berbayar dari situs tidak resmi karena ingin menghemat anggaran. Program tersebut memang dapat digunakan untuk menyelesaikan pekerjaan, tetapi sumbernya tidak jelas dan proses instalasinya meminta beberapa izin tambahan. Pegawai tersebut beranggapan bahwa selama aplikasi berjalan, penggunaannya tidak menjadi masalah.\n\nPertimbangan apa yang paling tepat terhadap penggunaan perangkat lunak tersebut?", order: "1230x", scores: [3, 4, 1, 2, 5] },
  { prompt: "Dalam proyek bersama, dua anggota mengedit dokumen yang sama pada salinan berbeda karena masing-masing bekerja dari lokasi berbeda. Ketika kedua versi digabungkan, beberapa perubahan saling menimpa dan sebagian informasi penting hilang. Tim membutuhkan cara kerja yang lebih terkoordinasi untuk pekerjaan berikutnya.\n\nSolusi teknologi apa yang paling tepat untuk mengurangi masalah tersebut?", order: "x2301", scores: [5, 2, 1, 4, 3] },
  { prompt: "Seorang pegawai menerima telepon dari seseorang yang mengaku sebagai petugas layanan akun organisasi. Orang tersebut mengatakan bahwa kode OTP diperlukan untuk memastikan identitas pegawai dan meminta kode tersebut segera disebutkan. Pegawai sedang terburu-buru menyelesaikan pekerjaan dan khawatir akunnya akan bermasalah.\n\nApa tindakan yang paling tepat dilakukan pegawai tersebut?", order: "301x2", scores: [3, 1, 2, 5, 4] },
  { prompt: "Sebuah unit kerja ingin mengganti aplikasi pengelolaan pekerjaan dengan sistem baru. Sebagian pegawai langsung memilih aplikasi yang sedang populer karena banyak organisasi lain menggunakannya. Namun, belum ada pemetaan mengenai kebutuhan, alur kerja, keamanan, dan kemampuan integrasi dengan sistem yang sudah tersedia.\n\nLangkah awal apa yang sebaiknya dilakukan sebelum menentukan aplikasi?", order: "01x23", scores: [4, 2, 5, 3, 1] },
  { prompt: "Ketika hendak mengakses situs layanan publik, seorang pegawai menemukan halaman yang tampak hampir sama dengan situs resmi. Perbedaannya hanya terlihat pada alamat domain dan beberapa detail kecil pada halaman login. Situs tersebut meminta data pribadi sebelum pengguna dapat melanjutkan proses layanan.\n\nApa langkah yang paling tepat sebelum memasukkan data pribadi?", order: "1x230", scores: [1, 5, 4, 3, 2] },
  { prompt: "Seorang pegawai mengirim dokumen pekerjaan melalui aplikasi pesan pribadi karena menganggap cara tersebut lebih cepat. Ia kemudian menyadari bahwa perangkat yang digunakan untuk menerima pesan juga dipakai bersama oleh anggota keluarganya dan pencadangan aplikasi tersimpan pada akun yang bukan khusus untuk pekerjaan.\n\nApa tindakan yang paling tepat untuk menjaga keamanan dokumen tersebut?", order: "x2301", scores: [5, 4, 3, 2, 1] },
  { prompt: "Dalam rapat online, seorang peserta diminta membagikan layar untuk menunjukkan proses kerja. Ia langsung melakukan screen sharing tanpa memeriksa aplikasi yang sedang terbuka dan tanpa menutup notifikasi. Beberapa saat kemudian, pesan pribadi muncul di layar dan dapat dilihat peserta rapat.\n\nKebiasaan apa yang sebaiknya diterapkan sebelum melakukan screen sharing?", order: "30x12", scores: [4, 3, 5, 2, 1] },
  { prompt: "Sebuah unit kerja memiliki arsip digital selama beberapa tahun, tetapi penamaan file dibuat berdasarkan kebiasaan masing-masing pegawai. Folder juga tidak memiliki struktur yang konsisten sehingga pencarian dokumen lama membutuhkan waktu cukup lama. Kondisi tersebut semakin menyulitkan ketika pegawai yang membuat arsip sudah pindah tugas.\n\nPerbaikan apa yang paling efektif untuk meningkatkan keteraturan arsip digital?", order: "012x3", scores: [3, 2, 4, 5, 1] },
  { prompt: "Seorang pegawai sering menunda pembaruan sistem operasi karena khawatir proses instalasi mengganggu pekerjaan. Akibatnya, perangkat menggunakan versi lama dan beberapa pembaruan keamanan belum diterapkan. Pegawai baru berencana melakukan pembaruan ketika perangkat benar-benar mengalami masalah.\n\nPendekatan apa yang paling tepat terhadap kebiasaan tersebut?", order: "1x230", scores: [2, 5, 1, 4, 3] },
  { prompt: "Dalam kegiatan pelayanan, seorang pegawai menggunakan komputer publik untuk membuka dokumen yang berisi informasi pribadi. Setelah dokumen selesai dicetak, file tersebut masih berada di folder unduhan perangkat. Pegawai tersebut hampir meninggalkan lokasi karena antrean pengguna berikutnya sudah mulai panjang.\n\nTindakan apa yang paling tepat untuk mencegah informasi tertinggal pada perangkat?", order: "2301x", scores: [1, 3, 2, 4, 5] },
  { prompt: "Sebuah unit kerja membuat formulir digital untuk mempercepat pengumpulan data masyarakat. Tim memasukkan banyak kolom karena beranggapan semakin banyak informasi yang dikumpulkan akan semakin bermanfaat. Setelah digunakan, masyarakat mengeluhkan proses pengisian terlalu panjang dan beberapa data ternyata tidak diperlukan.\n\nPrinsip apa yang paling tepat diterapkan dalam penyusunan formulir tersebut?", order: "3x012", scores: [3, 5, 4, 1, 2] },
  { prompt: "Seorang pegawai menerima pesan berantai yang menyatakan akun pemerintah akan ditutup jika pengguna tidak mengklik tautan tertentu dalam waktu singkat. Pesan tersebut menggunakan logo yang menyerupai instansi resmi dan meminta pengguna memasukkan informasi akun. Tidak ada pengumuman serupa pada kanal resmi organisasi.\n\nLangkah apa yang paling tepat untuk menilai kebenaran pesan tersebut?", order: "012x3", scores: [2, 1, 4, 5, 3] },
  { prompt: "Dalam proyek digital, pimpinan meminta laporan perkembangan pekerjaan secara berkala. Anggota tim masih menyimpan catatan pekerjaan pada perangkat pribadi sehingga informasi kemajuan hanya dapat diketahui ketika anggota tersebut mengirimkan laporan manual. Kondisi ini membuat pimpinan sulit melihat perubahan status secara cepat.\n\nPerbaikan apa yang paling tepat untuk meningkatkan transparansi pekerjaan?", order: "x1230", scores: [5, 3, 1, 2, 4] },
  { prompt: "Seorang pegawai menggunakan perangkat lunak berlisensi organisasi untuk mengolah dokumen pekerjaan. Ia kemudian ingin memasang perangkat lunak yang sama pada perangkat pribadi karena merasa pekerjaan akan lebih mudah dilakukan dari rumah. Pegawai tersebut belum mengetahui apakah lisensi organisasi mencakup penggunaan pada perangkat pribadi.\n\nApa pertimbangan yang seharusnya diperhatikan sebelum memasangnya?", order: "2301x", scores: [4, 2, 3, 1, 5] },
  { prompt: "Sebuah rapat hybrid menggunakan kamera dan mikrofon yang terhubung ke komputer kantor. Setelah rapat selesai, pegawai langsung meninggalkan ruangan dan membiarkan komputer serta perangkat konferensi tetap aktif. Ruangan tersebut kemudian digunakan oleh tim lain untuk kegiatan berbeda.\n\nKebiasaan apa yang paling tepat diterapkan setelah kegiatan selesai?", order: "30x12", scores: [1, 4, 5, 3, 2] },
  { prompt: "Tim menerima file data dalam jumlah besar dari beberapa sumber berbeda. Anggota tim langsung melakukan perhitungan tanpa memeriksa adanya data ganda, format yang berbeda, atau kolom yang kosong. Hasil awal terlihat cepat, tetapi ketika dibandingkan dengan sumber lain ditemukan beberapa perbedaan.\n\nApa langkah yang paling tepat dilakukan sebelum analisis data?", order: "012x3", scores: [4, 3, 2, 5, 1] },
  { prompt: "Seorang pegawai menyimpan daftar kata sandi akun kantor dalam file teks biasa di desktop agar mudah ditemukan. File tersebut tidak diberi perlindungan tambahan dan komputer digunakan untuk beberapa aktivitas pekerjaan lainnya. Pegawai merasa cara tersebut lebih praktis daripada mengingat banyak kata sandi.\n\nCara apa yang lebih tepat untuk mengelola kredensial tersebut?", order: "1230x", scores: [4, 3, 2, 1, 5] },
  { prompt: "Dalam grup kerja, seorang anggota mengirim foto dokumen yang memuat tanda tangan dan identitas masyarakat untuk meminta pendapat rekan. Ia sebenarnya hanya membutuhkan informasi mengenai satu bagian dokumen, tetapi seluruh halaman dikirim karena dianggap lebih cepat.\n\nBagaimana kebutuhan konsultasi tersebut sebaiknya dipenuhi?", order: "2x301", scores: [3, 5, 2, 4, 1] },
  { prompt: "Sebuah unit kerja menerima keluhan melalui email, pesan instan, formulir daring, dan kanal media sosial. Setiap petugas mencatat keluhan dengan cara berbeda sehingga beberapa laporan ditangani dua kali, sedangkan laporan lainnya tidak segera ditindaklanjuti. Pimpinan meminta proses tersebut diperbaiki tanpa mengurangi kemudahan masyarakat mengirim keluhan.\n\nSolusi digital apa yang paling tepat untuk memperbaiki proses tersebut?", order: "30x12", scores: [2, 1, 5, 4, 3] },
  { prompt: "Pegawai menggunakan komputer kantor untuk mengakses situs hiburan saat waktu istirahat. Beberapa situs menampilkan banyak iklan, tautan pengunduhan, dan pop-up yang tidak jelas sumbernya. Pegawai merasa aktivitas tersebut tidak berkaitan dengan pekerjaan sehingga menganggap tidak ada risiko terhadap perangkat organisasi.\n\nApa pertimbangan yang paling tepat dalam penggunaan perangkat organisasi tersebut?", order: "x0123", scores: [5, 1, 3, 2, 4] },
  { prompt: "Sebuah dokumen kerja bersama dapat diedit oleh siapa saja yang memiliki tautan. Tautan tersebut pernah diteruskan ke luar tim sehingga pihak yang tidak berkepentingan dapat melihat isi dokumen. Tim ingin tetap menggunakan kolaborasi daring tetapi membutuhkan pengendalian akses yang lebih baik.\n\nPengaturan akses apa yang paling tepat diterapkan?", order: "1230x", scores: [3, 4, 1, 2, 5] },
  { prompt: "Dalam kegiatan pencarian informasi, seorang pegawai biasanya menggunakan hasil pencarian pertama yang muncul karena ingin menyelesaikan pekerjaan dengan cepat. Ia jarang memeriksa siapa penerbit informasi, kapan informasi dibuat, atau apakah terdapat sumber lain yang memberikan data berbeda.\n\nKebiasaan apa yang paling tepat untuk meningkatkan kualitas pencarian informasi digital?", order: "23x01", scores: [2, 1, 5, 4, 3] },
  { prompt: "Ruang penyimpanan perangkat kerja hampir penuh sehingga seorang pegawai berencana menghapus file lama dalam jumlah besar. Sebagian file memang tidak pernah dibuka lagi, tetapi belum ada pemeriksaan mengenai aturan retensi dan kemungkinan kebutuhan dokumen tersebut untuk audit. Pegawai ingin segera menghapusnya agar pekerjaan dapat dilanjutkan.\n\nLangkah apa yang paling tepat dilakukan sebelum menghapus file tersebut?", order: "x3012", scores: [5, 3, 1, 2, 4] },
  { prompt: "Sebuah tim membuat dashboard kinerja dengan memasukkan banyak indikator karena ingin memberikan informasi selengkap mungkin. Pengguna justru kesulitan menemukan angka utama dan tidak mengetahui indikator mana yang perlu menjadi perhatian. Pimpinan meminta dashboard dibuat lebih mudah dipahami tanpa menghilangkan informasi penting.\n\nPrinsip apa yang paling tepat digunakan untuk memperbaiki dashboard tersebut?", order: "012x3", scores: [4, 2, 3, 5, 1] },
  { prompt: "Pegawai mengolah data masyarakat dan menemukan aplikasi pengolah data daring gratis yang menawarkan fitur lebih lengkap. Ia ingin mengunggah seluruh dataset agar proses pengolahan lebih cepat. Belum ada pemeriksaan mengenai lokasi penyimpanan, kebijakan privasi, atau ketentuan penggunaan data pada layanan tersebut.\n\nApa pertimbangan utama sebelum mengunggah data tersebut?", order: "1x230", scores: [1, 5, 4, 3, 2] },
];

const analysisByScore: Record<number, string> = {
  5: "Paling optimal karena menggabungkan keamanan, efisiensi, akurasi, dan tata kelola digital sesuai kebutuhan situasi.",
  4: "Sangat baik karena mengurangi risiko secara nyata, tetapi masih belum mencakup seluruh aspek pengelolaan yang diperlukan.",
  3: "Cukup tepat karena memiliki manfaat praktis, tetapi penerapannya masih menyisakan risiko atau keterbatasan tertentu.",
  2: "Kurang optimal karena hanya menyelesaikan sebagian masalah dan belum memberikan pengendalian yang memadai.",
  1: "Paling kurang tepat karena mengabaikan risiko digital atau terlalu mengandalkan cara yang tidak terkelola.",
};

export const TEKNOLOGI_INFORMASI_DRILL_QUESTIONS: Question[] = seeds.map((seed, index) => {
  const choices = [...seed.order].map((token, choiceIndex) => ({
    id: String.fromCharCode(97 + choiceIndex),
    label: token === "x" ? specificOptions[index] : commonOptions[Number(token)],
    score: seed.scores[choiceIndex],
  }));
  const best = choices.find((choice) => choice.score === 5);
  if (!best) throw new Error(`Soal TIK ${index + 1} tidak memiliki skor 5.`);
  const explanation = [
    `Jawaban terbaik: ${best.id.toUpperCase()}. ${best.label}`,
    ...choices.map((choice) => `${choice.id.toUpperCase()} (${choice.score}): ${analysisByScore[choice.score]}`),
  ].join("\n\n");
  return {
    id: `tkp-teknologi-informasi-${String(index + 1).padStart(3, "0")}`,
    category: "TKP",
    topic: "Teknologi Informasi",
    prompt: seed.prompt,
    choices,
    explanation,
  };
});
